### ISSUE TITLE
yolov3 http部署方式

### ISSUE THREAD

**Issue by ponycloud235** [PaddlePaddle/Serving#1009]
使用grpc方式部署成功了，使用http部署一直无法调用成功，我的问题：
   1. 使用官网的方式uci方式的入参和出参是如何定义的？
用的是yolov3的模型， python的代码如下

因项目需使用http方式，方便接入

`import sys
import numpy as np
from paddle_serving_client import Client
from paddle_serving_app.reader import *
import cv2
preprocess = Sequential([
    File2Image(), BGR2RGB(), Resize(
        (608, 608), interpolation=cv2.INTER_LINEAR), Div(255.0), Transpose(
            (2, 0, 1))
])

postprocess = RCNNPostprocess("label_list.txt", "output", [608, 608])
client = Client()

client.load_client_config("yolov3_client/serving_client_conf.prototxt")
client.connect(['127.0.0.1:9292'])

im = preprocess(sys.argv[1])
fetch_map = client.predict(
    feed={
        "image": im,
        "im_size": np.array(list(im.shape[1:])),
    },
    fetch=["save_infer_model/scale_0.tmp_0"],
    batch=False)
fetch_map["image"] = sys.argv[1]
postprocess(fetch_map)`

**Comment by TeslaZhao** [comment]
您好，uci webserver的示例可以参考:https://github.com/PaddlePaddle/Serving/blob/v0.4.0/python/examples/fit_a_line/test_server.py

```
get_data.sh
cat uci_housing_client/serving_client_conf.prototxt
```
feed_var {
  name: "x"
  alias_name: "x"
  is_lod_tensor: false
  feed_type: 1
  shape: 13
}
fetch_var {
  name: "fc_0.tmp_1"
  alias_name: "price"
  is_lod_tensor: false
  fetch_type: 1
  shape: 1
}

**Comment by ponycloud235** [comment]
> 您好，uci webserver的示例可以参考:https://github.com/PaddlePaddle/Serving/blob/v0.4.0/python/examples/fit_a_line/test_server.py
> 
> ```
> get_data.sh
> cat uci_housing_client/serving_client_conf.prototxt
> ```
> 
> feed_var {
> name: "x"
> alias_name: "x"
> is_lod_tensor: false
> feed_type: 1
> shape: 13
> }
> fetch_var {
> name: "fc_0.tmp_1"
> alias_name: "price"
> is_lod_tensor: false
> fetch_type: 1
> shape: 1
> }

您好，demo已经试跑成功； 但是图片服务始终无法调用成功，能否帮忙指导下,

服务端调用代码，及相关报错

`InvalidArgumentError: The input of Op(Conv) should be a 4-D or 5-D Tensor. But received: input's dimension is 3, input's shape is [3, 608, 608].
  [Hint: Expected in_dims.size() == 4 || in_dims.size() == 5 == true, but received in_dims.size() == 4 || in_dims.size() == 5:0 != true:1.] at (/paddle/paddle/fluid/operators/conv_op.cc:59)
  [operator < conv2d > error]`

`#coding=utf-8
from paddle_serving_server_gpu.web_service import WebService
from paddle_serving_app.reader import *
from PIL import Image
from io import BytesIO

import cv2
import numpy as np
import sys
import base64

pre2process = Sequential([
    File2Image(), BGR2RGB(), Resize(
        (608, 608), interpolation=cv2.INTER_LINEAR), Div(255.0), Transpose(
            (2, 0, 1))
])

class UciService(WebService):
    def preprocess(self, feed=[], fetch=[]):
        im = pre2process('./20191212163541_86515_input.jpg')
        is_batch = True
        feed = {
            'image': im,
            'im_size': np.array(list(im.shape[1:]))
        }
        print(feed)
        fetch = ['save_infer_model/scale_0.tmp_0']
        return feed, fetch, is_batch

#配置预测服务
uci_service = UciService(name = "uci")
uci_service.load_model_config("./yolov3_server")
uci_service.prepare_server(workdir="./workdir", port=9292, device="gpu", gpuid=0)
uci_service.run_rpc_service()
uci_service.run_web_service()
#获取flask服务
app_instance = uci_service.get_app_instance()
`

**Comment by ponycloud235** [comment]
使用的是yolo模型，grpc也调用成功了，因团队需要使用java开发应用，需使用http服务
