### ISSUE TITLE
Serving example中OCR 服务，报错

### ISSUE THREAD

**Issue by GreenValue** [PaddlePaddle/Serving#1015]
文档：https://github.com/PaddlePaddle/Serving/blob/develop/python/examples/ocr/README_CN.md
启动服务， port应该是9292，文档上是9293
`python -m paddle_serving_server_gpu.serve --model ocr_det_model --port 9292 --gpu_id 0`

执行命令
root@my_ubuntu:/paddle/Serving/python/examples/ocr# `python ocr_web_client.py`
```
<Response [404]>
Traceback (most recent call last):
  File "ocr_web_client.py", line 40, in <module>
    print(r.json())
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/python2.7.15/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python2.7.15/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python2.7.15/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting ',' delimiter: line 1 column 7 (char 6)
```

**Comment by GreenValue** [comment]
- 启动LocalPredictor版Web服务 for cpu user
- 客户端，虽然有结果，但乱码，为啥？
root@my_ubuntu:/paddle/Serving/python/examples/ocr# p`ython ocr_web_client.py`
```
<Response [200]>
{u'result': {u'res': [u'\u571f\u5730\u6574\u6cbb\u4e0e\u571f\u58e4\u4fee\u590d\u7814\u7a76\u4e2d\u5fc3', u'\u534e\u5357\u519c\u4e1a\u5927\u5b661\u7d20\u56fe']}}

```
- 服务端

`python ocr_debugger_server.py cpu`
```
W0203 07:31:28.735062  2753 analysis_predictor.cc:1059] Deprecated. Please use CreatePredictor instead.
I0203 07:31:28.735272  2753 analysis_predictor.cc:139] Profiler is deactivated, and no profiling report will be generated.
I0203 07:31:28.743610  2753 analysis_predictor.cc:524] ir_optim is turned off, no IR pass will be executed
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_graph_clean_pass]
--- Running analysis [ir_analysis_pass]
--- Running analysis [ir_params_sync_among_devices_pass]
--- Running analysis [adjust_cudnn_workspace_size_pass]
--- Running analysis [inference_op_replace_pass]
--- Running analysis [memory_optimize_pass]
I0203 07:31:28.765836  2753 memory_optimize_pass.cc:200] Cluster name : elementwise_add_3  size: 30720
I0203 07:31:28.765934  2753 memory_optimize_pass.cc:200] Cluster name : batch_norm_6.tmp_2  size: 40960
I0203 07:31:28.766043  2753 memory_optimize_pass.cc:200] Cluster name : image  size: 122880
I0203 07:31:28.766129  2753 memory_optimize_pass.cc:200] Cluster name : lstm_0.tmp_3  size: 192
I0203 07:31:28.766170  2753 memory_optimize_pass.cc:200] Cluster name : batch_norm_4.tmp_2  size: 204800
I0203 07:31:28.766274  2753 memory_optimize_pass.cc:200] Cluster name : hard_swish_15.tmp_0  size: 184320
I0203 07:31:28.766345  2753 memory_optimize_pass.cc:200] Cluster name : relu_2.tmp_0  size: 204800
--- Running analysis [ir_graph_to_program_pass]
I0203 07:31:28.786970  2753 analysis_predictor.cc:548] ======= optimize end =======
I0203 07:31:28.787032  2753 naive_executor.cc:107] ---  skip [feed], feed -> image
I0203 07:31:28.788170  2753 naive_executor.cc:107] ---  skip [hard_swish_15.tmp_0], fetch -> fetch
I0203 07:31:28.788177  2753 naive_executor.cc:107] ---  skip [relu_2.tmp_0], fetch -> fetch
ocr_debugger_server.py:52: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  data = np.fromstring(data, np.uint8)
```

**Comment by GreenValue** [comment]
1.  检测单服务启动后，结果OK
root@my_ubuntu:/paddle/Serving/python/examples/ocr# python ocr_web_client.py
```
<Response [200]>
{u'result': {u'dt_boxes': [[[292.0, 298.0], [332.0, 298.0], [345.0, 848.0], [305.0, 848.0]], [[345.0, 298.0], [377.0, 298.0], [382.0, 660.0], [350.0, 660.0]]]}}

```

2.  识别单服务启动后，结果异常

- 客户端

root@my_ubuntu:/paddle/Serving/python/examples/ocr# python rec_web_client.py
```
Traceback (most recent call last):
  File "rec_web_client.py", line 41, in <module>
    print(r.json())
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/python2.7.15/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python2.7.15/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python2.7.15/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

- 服务端
python rec_web_server.py gpu #for gpu user

```
[2021-02-03 07:43:44,499] ERROR in app: Exception on /ocr/prediction [POST]
Traceback (most recent call last):
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle_serving_server_gpu/web_service.py", line 223, in run
    return self.get_prediction(request)
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle_serving_server_gpu/web_service.py", line 193, in get_prediction
    feed=request.json["feed"], fetch=fetch, fetch_map=fetch_map)
  File "rec_web_server.py", line 67, in postprocess
    rec_res = self.ocr_reader.postprocess(fetch_map, with_score=True)
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle_serving_app/reader/ocr_reader.py", line 178, in postprocess
    rec_idx_lod = outputs["ctc_greedy_decoder_0.tmp_0.lod"]
TypeError: 'NoneType' object has no attribute '__getitem__'
I0203 07:43:44.554181  3291 socket.cpp:2370] Checking SocketId=0@127.0.0.1:12000
Aborted (core dumped)

```

**Comment by GreenValue** [comment]
参照[使用Paddle Serving部署OCR识别服务](https://aistudio.baidu.com/aistudio/projectdetail/605819)
运行OK。

**Comment by TeslaZhao** [comment]
{u'result': {u'res': [u'\u571f\u5730\u6574\u6cbb\u4e0e\u571f\u58e4\u4fee\u590d\u7814\u7a76\u4e2d\u5fc3', u'\u534e\u5357\u519c\u4e1a\u5927\u5b661\u7d20\u56fe']}}
客户端，虽然有结果，但乱码，为啥？

结果是unicode，转换之后为：
{u'result': {u'res': [u'土地整治与土壤修复研究中心', u'华南农业大学1素图']}}

您可以使用python3执行，在python3里我们做了兼容

**Comment by TeslaZhao** [comment]
> 1. 检测单服务启动后，结果OK
>    root@my_ubuntu:/paddle/Serving/python/examples/ocr# python ocr_web_client.py
> 
> ```
> <Response [200]>
> {u'result': {u'dt_boxes': [[[292.0, 298.0], [332.0, 298.0], [345.0, 848.0], [305.0, 848.0]], [[345.0, 298.0], [377.0, 298.0], [382.0, 660.0], [350.0, 660.0]]]}}
> ```
> 
> 1. 识别单服务启动后，结果异常
> 
> * 客户端
> 
> root@my_ubuntu:/paddle/Serving/python/examples/ocr# python rec_web_client.py
> 
> ```
> Traceback (most recent call last):
>   File "rec_web_client.py", line 41, in <module>
>     print(r.json())
>   File "/usr/local/python2.7.15/lib/python2.7/site-packages/requests/models.py", line 898, in json
>     return complexjson.loads(self.text, **kwargs)
>   File "/usr/local/python2.7.15/lib/python2.7/json/__init__.py", line 339, in loads
>     return _default_decoder.decode(s)
>   File "/usr/local/python2.7.15/lib/python2.7/json/decoder.py", line 364, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/local/python2.7.15/lib/python2.7/json/decoder.py", line 382, in raw_decode
>     raise ValueError("No JSON object could be decoded")
> ValueError: No JSON object could be decoded
> ```
> 
> * 服务端
>   python rec_web_server.py gpu #for gpu user
> 
> ```
> [2021-02-03 07:43:44,499] ERROR in app: Exception on /ocr/prediction [POST]
> Traceback (most recent call last):
>   File "/usr/local/python2.7.15/lib/python2.7/site-packages/flask/app.py", line 2447, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/usr/local/python2.7.15/lib/python2.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/usr/local/python2.7.15/lib/python2.7/site-packages/flask/app.py", line 1821, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/usr/local/python2.7.15/lib/python2.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/usr/local/python2.7.15/lib/python2.7/site-packages/flask/app.py", line 1936, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle_serving_server_gpu/web_service.py", line 223, in run
>     return self.get_prediction(request)
>   File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle_serving_server_gpu/web_service.py", line 193, in get_prediction
>     feed=request.json["feed"], fetch=fetch, fetch_map=fetch_map)
>   File "rec_web_server.py", line 67, in postprocess
>     rec_res = self.ocr_reader.postprocess(fetch_map, with_score=True)
>   File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle_serving_app/reader/ocr_reader.py", line 178, in postprocess
>     rec_idx_lod = outputs["ctc_greedy_decoder_0.tmp_0.lod"]
> TypeError: 'NoneType' object has no attribute '__getitem__'
> I0203 07:43:44.554181  3291 socket.cpp:2370] Checking SocketId=0@127.0.0.1:12000
> Aborted (core dumped)
> ```

您好，你使用的Serving版本是？paddle版本？

**Comment by GreenValue** [comment]
- docker环境， paddle 版本为1.8.5
nvidia-docker pull hub.baidubce.com/paddlepaddle/paddle:1.8.5-gpu-cuda10.0-cudnn7

- PaddleServing
git clone https://gitee.com/paddlepaddle/Serving.git

**Comment by TeslaZhao** [comment]
收到，我们复现一下

**Comment by TeslaZhao** [comment]
问题已经修复，在develop或v0.5.0分支合入 @GreenValue
