### ISSUE TITLE
如何在Paddle Serving使用c++ Client？

### ISSUE THREAD

**Issue by GreenValue** [PaddlePaddle/Serving#1017]
[如何在Paddle Serving使用Go Client](https://github.com/PaddlePaddle/Serving/blob/v0.4.0/doc/IMDB_GO_CLIENT_CN.md)
有Go，怎么没有C++的呀？

**Comment by TeslaZhao** [comment]
https://github.com/PaddlePaddle/Serving/blob/v0.4.0/doc/deprecated/CREATING.md

**Comment by GreenValue** [comment]
Paddle Serving提供的C++ SDK在sdk-cpp/目录中，入口为sdk-cpp/include/predictor_sdk.h中的`class PredictorApi类。
这个文件sdk-cpp/include/predictor_sdk.h 没找到。

**Comment by GreenValue** [comment]
sdk-cpp的git请明示一下。

**Comment by TeslaZhao** [comment]
使用哪个分支？
https://github.com/PaddlePaddle/Serving/blob/v0.4.0/core/sdk-cpp/include/predictor_sdk.h

**Comment by GreenValue** [comment]
好的。谢谢
