### ISSUE TITLE
请问有没有详细的工程设计文档？

### ISSUE THREAD

**Issue by jinmin527** [PaddlePaddle/Serving#1038]
想基于paddler serving做二次开发，但是在源码阅读过程中，缺乏可以参考的设计文档和代码注释，导致进展缓慢。能否贡献一下项目的设计文档、相关流程的解析（初始化流程、IO流程）以及各数据结构间的层次关系

**Comment by TeslaZhao** [comment]
您好，欢迎您使用Paddle Serving。在最新的v0.5.0版本中更新了[Paddle Serving设计文档](https://github.com/PaddlePaddle/Serving/blob/v0.5.0/doc/DESIGN_DOC_CN.md)，您可以阅读一下，根据您的需求做技术选型。对于代码和注释不够细致的问题，我们已经注意到了，由于修改的工作量较大，所以计划在此后每个版本迭代中修改文档，增加注释。设计的文档和用户手册也在逐步完善，希望可以帮到您。

**Comment by jinmin527** [comment]
谢谢啊！python源码还好阅读，C++源码阅读起来还是比较费劲，请问您们是否有C++实现的流程化的文档，或者类之间的层次关系。这样阅读起来至少有个主线。










在 2021-02-18 14:20:09，"TeslaZhao" <notifications@github.com> 写道：

您好，欢迎您使用Paddle Serving。在最新的v0.5.0版本中更新了Paddle Serving设计文档，您可以阅读一下，根据您的需求做好技术选型，再根据不同技术选型，查看响应的技术文档。对于代码和注释不够细致的问题，我们已经注意到了，修改的工作量比较大的，所以没有会在每个版本迭代中修改文档，增加注释。

**Comment by TeslaZhao** [comment]
您说的这个文档，我近期写一个

**Comment by jinmin527** [comment]
期待，希望可以尽早分享出来
