### ISSUE TITLE
模型转为serving时报错要enable_static，怎么解决

### ISSUE THREAD

**Issue by guojiahuiEmily** [PaddlePaddle/Serving#1060]
python -m paddle_serving_client.convert --dirname . --model_filename dygraph_model.pdmodel --params_filename dygraph_model.pdiparams --serving_server serving_server --serving_client serving_client
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main

AssertionError: In PaddlePaddle 2.x, we turn on dynamic graph mode by default, and 'load_inference_model()' is only supported in static graph mode. So if you want to use this api, please call 'paddle.enable_static()' before this api to enter static graph mode.

**Comment by TeslaZhao** [comment]
您使用的是v0.5.0版本或develop分支吗

**Comment by muyu1944** [comment]
@TeslaZhao pipeline是不是还不支持部署0.5.0版的serving转换的模型？
log里显示：failed to init op: (Unavailable) Load operator fail to open file serving_server/layer_norm_17.w_0, please check whether the model file is complete or damaged.

**Comment by HexToString** [comment]
您可以试试在转换代码中加入
paddle.enable_static()

另外，若代码中直接或间接用到了，save_inference_model这个函数，需要注意这个函数中的参数'params'。
当'params'没有值时，默认你的模型参数是离散的（多个模型参数问题）
当'params' = "params"，则你的模型参数是聚合的。
