### ISSUE TITLE
请问paddlehub里的模型怎么转为serving的模型

### ISSUE THREAD

**Issue by guojiahuiEmily** [PaddlePaddle/Serving#1061]
paddlehub的藏头诗模型，怎么转为可以serving的模型？

另外预测时，怎么调用，需要做什么处理才能输出汉字的结果

**Comment by TeslaZhao** [comment]
您好，Paddlehub的模型可以转成Serving模型。

模型转换：
若为paddle 2.0框架训练的模型，可参考：https://github.com/PaddlePaddle/Serving/blob/develop/doc/SAVE_CN.md
若为paddle 1.8框架及以下训练的模型，可参考：https://github.com/PaddlePaddle/Serving/blob/v0.4.0/doc/SAVE_CN.md

推理方法：
需要根据模型入参的结构传入参数，每个模型的入参结构都不一样。你可以参考lac示例： python/examples/lac

**Comment by guojiahuiEmily** [comment]
非常感谢。
但是那些文档里面并没有如何转换Paddlehub里的藏头诗及对诗模型。
Paddlehub对诗模型解压后是这样，没有model文件,model文件夹里都是python文件。
<img width="205" alt="截屏2021-02-23 下午1 14 10" src="https://user-images.githubusercontent.com/74049862/108804757-1c6a1780-75d9-11eb-8bf6-280e77c080d3.png">

**Comment by TeslaZhao** [comment]
您好，在此文档中有关于*.pdparams文件的转换方法，请参考：https://github.com/PaddlePaddle/Serving/blob/develop/doc/SAVE_CN.md
