### ISSUE TITLE
paddlex导出的模型，trans_model.py转换后部署到paddle serving，feed_var的im_size参数怎么赋值？

### ISSUE THREAD

**Issue by zwei-joe** [PaddlePaddle/Serving#1066]
paddlex导出的图像分类检测模型，用trans_model.py转换后部署到paddle serving。
转换后生成的serving_client_conf.prototxt 内容
=======================================
feed_var {
  name: "image"
  alias_name: "image"
  is_lod_tensor: false
  feed_type: 1
  shape: 3
}
feed_var {
  name: "im_size"
  alias_name: "im_size"
  is_lod_tensor: false
  feed_type: 2
  shape: 2
}
fetch_var {
  name: "save_infer_model/scale_0.tmp_0"
  alias_name: "save_infer_model/scale_0.tmp_0"
  is_lod_tensor: true
  fetch_type: 1
  shape: -1
}
================================
推理客户端代码：
feed_dict={}
feed_dict["image"]=im
#feed_dict["im_size"]=
fetch_map = client.predict(feed=feed_dict, fetch=["save_infer_model/scale_0.tmp_0"])
其中的im_size参数怎么赋值？

**Comment by TeslaZhao** [comment]
im_size是什么含义，图片数量？

**Comment by zwei-joe** [comment]
paddlex导出的模型文件：__model__和__params__，打开__model__文件里发现有ImgSizeim_size 内容。trans_model.py转换后feed_var就带有im_size输入参数。
im_size值应该为numpy.array 值
feed_dict["image"]=im //输入图片的尺寸为800，539  
feed_dict["im_size"]=numpy.array([800,539])  
但paddle serving还是会报错
----------------------
Error Message Summary:
----------------------
InvalidArgumentError: The number of input's channels should be equal to filter's channels * groups for Op(Conv). But received: the input's channels is 539, the input's shape is [1, 539, 800, 3]; the filter's channels is 3, the filter's shape is [32, 3, 3, 3]; the groups is 1, the data_format is NCHW. The error may come from wrong data_format setting.
  [Hint: Expected input_channels == filter_dims[1] * groups, but received input_channels:539 != filter_dims[1] * groups:3.] at (/paddle/paddle/fluid/operators/conv_op.cc:94)
  [operator < conv2d > error]
