### ISSUE TITLE
serving example中pipeline ocr里坐标不一致

### ISSUE THREAD

**Issue by zengqi0730** [PaddlePaddle/Serving#1071]
example/pipline/ocr 里Det Op输出的out_dict里获取的dt_boxes 与 Rec_Op收到的input_dicts里 dt_boxes不一致，前者是原图的坐标，后者貌似是整个剪切后的图片坐标。 那我client如何通过serving服务返回文字在图片中的坐标呢？

**Comment by TeslaZhao** [comment]
您好，如果Client要获得原图中坐标信息，您可以把Det Op输出的out_dict写成一个新的变量放入out_dict(Det::postprocess)中。在RecOp的postprocess中通过input_dicts拿到数据在输出即可

**Comment by zengqi0730** [comment]
> 您好，如果Client要获得原图中坐标信息，您可以把Det Op输出的out_dict写成一个新的变量放入out_dict(Det::postprocess)中。在RecOp的postprocess中通过input_dicts拿到数据在输出即可

可以了，谢谢指导！
返回res类型有限制，只能是dict或者numpy，而且dict的value必须是str，这个就很难受了。应该把res改进为json类型
