### ISSUE TITLE
Bert-As-Service例子运行报错

### ISSUE THREAD

**Issue by HJYgotoPLAY** [PaddlePaddle/Serving#1075]
首先按照官方教程在Docker内构建Paddle Serving

- 获取镜像：docker pull registry.baidubce.com/paddlepaddle/serving:latest-cuda10.0-cudnn7-devel
- 创建容器：nvidia-docker run -p 9292:9292 --name test -dit registry.baidubce.com/paddlepaddle/serving:latest-cuda10.0-cudnn7-devel
- 进入容器：nvidia-docker exec -it test bash
- 安装PaddleServing（环境py27，cuda10.0）：
1. pip install paddle-serving-client==0.5.0 
2. pip install paddle-serving-app==0.3.0 
3. pip install paddle-serving-server-gpu==0.5.0.post10
- 安装paddle：pip install https://paddle-wheel.bj.bcebos.com/2.0.0-gpu-cuda10-cudnn7-mkl/paddlepaddle_gpu-2.0.0.post100-cp27-cp27mu-linux_x86_64.whl

然后按照Bert-As-Service教程
#下载模型：
wget https://paddle-serving.bj.bcebos.com/paddle_hub_models/text/SemanticModel/bert_chinese_L-12_H-768_A-12.tar.gz
tar -xzf bert_chinese_L-12_H-768_A-12.tar.gz
mv bert_chinese_L-12_H-768_A-12_model bert_seq128_model
mv bert_chinese_L-12_H-768_A-12_client bert_seq128_client
#获取词典和样例数据：
sh get_data.sh 
#启动GPU预测服务
python bert_web_service_gpu.py bert_seq128_model/ 9292
 
执行预测：curl -H "Content-Type:application/json" -X POST -d '{"feed":[{"words": "hello"}], "fetch":["pooled_output"]}' http://127.0.0.1:9292/bert/prediction

结果报错：
![image](https://user-images.githubusercontent.com/24710595/109646990-c1fe2780-7b93-11eb-916b-bb95c220bd25.png)

**Comment by bjjwwang** [comment]
用最新的`registry.baidubce.com/paddlepaddle/serving:latest-cuda10.0-cudnn7-devel`
