### ISSUE TITLE
基于paddlehub训练的文本分类模型，使用paddle_serving_client RPC调用失败

### ISSUE THREAD

**Issue by baibaiw5** [PaddlePaddle/Serving#1077]
安装了以下包
paddlepaddle-gpu==1.8.5.post97
paddlehub==1.7.1 
paddle_serving_client==0.4.0 
paddle_serving_server==0.4.0
paddle_serving_app==0.3.0 

基于https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.8/demo/text_classification/text_cls.py训练了一个文本分类模型
使用paddlepaddle serving生成模型并启动RPC服务成功
python -m paddle_serving_client.convert --dirname ckpt_bert/best_model
python -m paddle_serving_server.serve --model serving_server --thread 2 --port 9292 --name test

但是调用RPC服务时失败。
import sys
from paddle_serving_client import Client
from paddle_serving_client.utils import benchmark_args
from paddle_serving_app.reader import ChineseBertReader
import numpy as np

max_seq_len=64
reader = ChineseBertReader({"max_seq_len": max_seq_len})
fetch = ["save_infer_model/scale_0.tmp_1"]
endpoint_list = ['127.0.0.1:9292']
client = Client()
client.load_client_config("text_classification/serving_client/serving_client_conf.prototxt")
client.connect(endpoint_list)

feed_batch = []
for line in ['abc','testid']:
    feed_dict = reader.process(line)
    for key in feed_dict.keys():
        feed_dict[key] = np.array(feed_dict[key]).reshape((max_seq_len, 1))
    feed_batch.append(feed_dict)
result = client.predict(feed=feed_batch, fetch=fetch, batch=True)
print(result)

错误日志为：
ERROR 2021-03-05 10:06:29,572 [_internal.py:113] 127.0.0.1 - - [05/Mar/2021 10:06:29] code 400, message Bad request syntax ('PRPC\x00\x00\x06L\x00\x00\x00Y')
INFO 2021-03-05 10:06:29,573 [_internal.py:113] 127.0.0.1 - - [05/Mar/2021 10:06:29] "PRPCLY" HTTPStatus.BAD_REQUEST -
ERROR 2021-03-05 10:07:05,628 [_internal.py:113] 127.0.0.1 - - [05/Mar/2021 10:07:05] code 400, message Bad request syntax ('PRPC\x00\x00\x06M\x00\x00\x00Z')
INFO 2021-03-05 10:07:05,629 [_internal.py:113] 127.0.0.1 - - [05/Mar/2021 10:07:05] "PRPCMZ" HTTPStatus.BAD_REQUEST -

基于http服务调用失败：
curl -H "Content-Type:application/json" -X POST -d '{"feed":[{"input_ids": [101,3844,6407,671,678,704,3152,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"position_ids":[0,1,2,3,4,5,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"segment_ids":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"input_mask":[1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],"seq_len":64}], "fetch":["save_infer_model/scale_0.tmp_1"]}' http://127.0.0.1:9292/test/prediction
返回错误：{"result":"Please make sure all of your inputs are numpy array"}

---------serving_client/serving_client_conf.prototxt
feed_var {
  name: "input_ids"
  alias_name: "input_ids"
  is_lod_tensor: false
  feed_type: 0
  shape: 64
  shape: 1
}
feed_var {
  name: "position_ids"
  alias_name: "position_ids"
  is_lod_tensor: false
  feed_type: 0
  shape: 64
  shape: 1
}
feed_var {
  name: "segment_ids"
  alias_name: "segment_ids"
  is_lod_tensor: false
  feed_type: 0
  shape: 64
  shape: 1
}
feed_var {
  name: "input_mask"
  alias_name: "input_mask"
  is_lod_tensor: false
  feed_type: 1
  shape: 64
  shape: 1
}
feed_var {
  name: "seq_len"
  alias_name: "seq_len"
  is_lod_tensor: false
  feed_type: 0
  shape: 1
}
fetch_var {
  name: "save_infer_model/scale_0.tmp_1"
  alias_name: "save_infer_model/scale_0.tmp_1"
  is_lod_tensor: true
  fetch_type: 1
  shape: -1
}
fetch_var {
  name: "save_infer_model/scale_1.tmp_1"
  alias_name: "save_infer_model/scale_1.tmp_1"
  is_lod_tensor: true
  fetch_type: 0
  shape: -1
}

---------------------------------------------------------------
切换到环境下部署
paddlepaddle==2.0.0
paddle_serving_client==0.5.0 
paddle_serving_server==0.5.0
paddle_serving_app==0.3.0 

上面的基于http服务调用的请求成功，能正确返回预测值。

上面到调用RPC服务的代码依然失败。
ERROR 2021-03-05 10:15:56,782 [_internal.py:113] 192.168.1.52 - - [05/Mar/2021 10:15:56] code 400, message Bad request syntax ('PRPC\x00\x00\x06M\x00\x00\x00Z')
INFO 2021-03-05 10:15:56,782 [_internal.py:113] 192.168.1.52 - - [05/Mar/2021 10:15:56] "PRPCMZ" HTTPStatus.BAD_REQUEST -

---------------------------------------------------------------
请问有PaddleHub的文本分类模型如何通过RPC调用PaddleServing的例子吗？
目前能找到的只有这个bert获取embedding的例子，用处不大
https://github.com/PaddlePaddle/Serving/blob/develop/python/examples/bert/bert_client.py

**Comment by TeslaZhao** [comment]
您好，我来回答您的问题：

1.您使用的v0.4.0 Serving版本，建议您升级到v0.5.0版本，安装步骤如下：
pip install paddle-serving-client==0.5.0 -U
pip install paddle-serving-server==0.5.0  -U
pip install paddlepaddle==2.0.0

2.根据您的启动参数
python -m paddle_serving_server.serve --model serving_server --thread 2 --port 9292 **_--name test_**
加上--name，是http服务，即9292是Http服务端口；不加 --name，开启RPC端口

**Comment by baibaiw5** [comment]
> 您好，我来回答您的问题：
> 
> 1.您使用的v0.4.0 Serving版本，建议您升级到v0.5.0版本，安装步骤如下：
> pip install paddle-serving-client==0.5.0 -U
> pip install paddle-serving-server==0.5.0 -U
> pip install paddlepaddle==2.0.0
> 
> 2.根据您的启动参数
> python -m paddle_serving_server.serve --model serving_server --thread 2 --port 9292 **_--name test_**
> 加上--name，是http服务，即9292是Http服务端口；不加 --name，开启RPC端口

谢谢，已解决
