### ISSUE TITLE
转换OCR rec模型后调用失败

### ISSUE THREAD

**Issue by xiahongjin** [PaddlePaddle/Serving#1078]
转换rec模型之后，启动rec_debugger_server调用后报以下错：

RuntimeError: (Unavailable) Load operator fail to open file D:\Serving-0.5.0\serving_rec_server/bn3c_branch2b_scale, please check whether the model file is complete or damaged.
  [Hint: Expected static_cast<bool>(fin) == true, but received static_cast<bool>(fin):0 != true:1.] (at D:\v2.0.0\paddle\paddle/fluid/operators/load_op.h:41)
  [operator < load > error]

det模型转换以后调用没问题，Windows10平台

**Comment by TeslaZhao** [comment]
您好，您使用Serving 版本，Paddle的版本信息能发一下吗？还有是否使用了[模型转换接口](https://github.com/PaddlePaddle/Serving/blob/develop/doc/SAVE_CN.md)

**Comment by xiahongjin** [comment]
paddle2.0版本，使用了模型转换接口中serving_io.inference_model_to_serving函数转换的，Serving0.5.0
转换语句：
python -m paddle_serving_client.convert --dirname ch_ppocr_mobile_v2.0_det_infer --model_filename inference.pdmodel --params_filename  inference.pdiparams --serving_server det_server --serving_client det_client

**Comment by TeslaZhao** [comment]
serving server, client, app的版本信息都发一下:

pip list | grep serving

**Comment by HexToString** [comment]
您这个问题看着像是代码中直接或间接用到了，save_inference_model这个函数，这个函数中的参数'params'输入错误。
当'params'没有值时，默认你的模型参数是离散的（多个模型参数问题）
当'params' = "__params__"，则你的模型参数是聚合的。
我猜测你的模型参数文件是后者，而没有指定params参数

**Comment by xiahongjin** [comment]
非常感谢，问题已经解决，谢谢您的回复

**Comment by HexToString** [comment]
可否发一下，您具体修改了哪个文件的哪个地方，能够给其他同学提供一个参考。
如果方便的话，多谢。
