### ISSUE TITLE
使用CPU教程运行失败

### ISSUE THREAD

**Issue by paopjian** [PaddlePaddle/Serving#1085]
命令:

docker pull registry.baidubce.com/paddlepaddle/serving:0.5.0-devel
docker run -p 9292:9292 --name test -dit registry.baidubce.com/paddlepaddle/serving:0.5.0-devel
docker exec -it test bash

报错:
Error response from daemon: Container 7ac0574a7f984b2fc6ce67ef2f07ec59772ff3aa3066182f0bac379d0712b2d1 is not running
查看日志:
/bin/sh: 1: source: not found

**Comment by TeslaZhao** [comment]
您好，docker没有run起来。单独运行下面语句，看一下报错信息。
docker run -p 9292:9292 --name test -dit registry.baidubce.com/paddlepaddle/serving:0.5.0-devel

**Comment by paopjian** [comment]
![image](https://user-images.githubusercontent.com/20377352/111119287-da8e1a80-8561-11eb-9dcf-23ca7220ba9c.png)

run时没有报错,但是无法启动.环境:ubuntu20.04

**Comment by TeslaZhao** [comment]
// 查询被停止serving的container_id
docker ps -a 

// 查询docker logs
docker logs container_id

**Comment by paopjian** [comment]
![image](https://user-images.githubusercontent.com/20377352/111121509-a536fc00-8564-11eb-81dc-e40407f09afa.png)

**Comment by bjjwwang** [comment]
不好意思 docker run缺少了最后的bash
会马上添加到首页
```
docker run -p 9292:9292 --name test -dit registry.baidubce.com/paddlepaddle/serving:0.5.0-devel bash
```
