### ISSUE TITLE
java教程服务端启动执行错误

### ISSUE THREAD

**Issue by paopjian** [PaddlePaddle/Serving#1091]
https://github.com/PaddlePaddle/Serving/blob/develop/java/README_CN.md
已完成
```
docker pull registry.baidubce.com/paddlepaddle/serving:0.5.0-java
docker run --rm -dit --name java_serving registry.baidubce.com/paddlepaddle/serving:0.5.0-java
docker exec -it java_serving bash
cd Serving/java
mvn compile
mvn install
cd examples
mvn compile
mvn install
pip install paddle-serving-client==0.5.0
pip install paddle-serving-server==0.5.0 # CPU
pip install paddle-serving-app==0.3.0
cd ../../python/examples/fit_a_line
sh get_data.sh
```
执行
python -m paddle_serving_server.serve --model uci_housing_model --thread 10 --port 9393 --use_multilang &
发生错误
![image](https://user-images.githubusercontent.com/20377352/111436256-acdbd980-86f9-11eb-955a-2e9838d2a9cb.png)

**Comment by HexToString** [comment]
看着像是gcc版本过低导致的问题。
查看一下你的gcc版本
