### ISSUE TITLE
raspberry 4b 树莓派4B docker下编译出错

### ISSUE THREAD

**Issue by 60999** [PaddlePaddle/Serving#1094]
因为下载的cpu镜像架构不同无法运行，所以使用文件 Dockerfile 构建镜像
参考：https://github.com/PaddlePaddle/Serving/blob/develop/doc/DOCKER_IMAGES_CN.md 
`
pi@raspberrypi:~/Serving/tools $ mkdir armv7
pi@raspberrypi:~/Serving/tools $ cp Dockerfile.devel ./armv7/ 
pi@raspberrypi:~/Serving/tools $ cd armv7/ 
`

修改Dockerfile.devel
ENV WITH_GPU=${WITH_GPU:-OFF}
ENV WITH_AVX=${WITH_AVX:-OFF}

`
pi@raspberrypi:~/Serving/tools $ sudo docker build -f Dockerfile.devel -t paddle-serving.armv7-pi4:latest .
`

`
Sending build context to Docker daemon  11.78kB
Step 1/71 : FROM hub.baidubce.com/ctr/cuda:9.0-cudnn7-devel-ubuntu16.04
 ---> 5978609a60c5
Step 2/71 : MAINTAINER PaddlePaddle Authors <paddle-dev@baidu.com>
 ---> Using cache
 ---> fa640de9e332
Step 3/71 : ARG WITH_GPU
 ---> Using cache
 ---> 7110618d9a45
Step 4/71 : ARG WITH_AVX
 ---> Using cache
 ---> 9cdb4b048a19
Step 5/71 : ENV WITH_GPU=${WITH_GPU:-ON}
 ---> [Warning] The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested
 ---> Running in c8fafac96d1f
Removing intermediate container c8fafac96d1f
 ---> 1d4ac76be9ef
Step 6/71 : ENV WITH_AVX=${WITH_AVX:-ON}
 ---> [Warning] The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested
 ---> Running in 1e9182cbb019
Removing intermediate container 1e9182cbb019
 ---> e2add42a6d84
Step 7/71 : ENV HOME /root
 ---> [Warning] The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested
 ---> Running in eeea6d370e01
Removing intermediate container eeea6d370e01
 ---> 7c42f998b26f
Step 8/71 : COPY tools/dockerfile/scripts/root/ /root/
COPY failed: file not found in build context or excluded by .dockerignore: stat tools/dockerfile/scripts/root/: file does not exist
`
请问如何继续构建docker镜像呢？

**Comment by 60999** [comment]
$ sudo docker build -f Dockerfile.devel -t paddle-serving.armv7-pi4:latest .
Sending build context to Docker daemon  11.78kB
Step 1/71 : FROM hub.baidubce.com/ctr/cuda:9.0-cudnn7-devel-ubuntu16.04
 ---> 5978609a60c5
Step 2/71 : MAINTAINER PaddlePaddle Authors <paddle-dev@baidu.com>
 ---> Using cache
 ---> fa640de9e332
Step 3/71 : ARG WITH_GPU
 ---> Using cache
 ---> 7110618d9a45
Step 4/71 : ARG WITH_AVX
 ---> Using cache
 ---> 9cdb4b048a19
Step 5/71 : ENV WITH_GPU=${WITH_GPU:-OFF}
 ---> Using cache
 ---> 4d89b1e0d906
Step 6/71 : ENV WITH_AVX=${WITH_AVX:-OFF}
 ---> Using cache
 ---> 80d809c6f6f8
Step 7/71 : ENV HOME /root
 ---> Using cache
 ---> 52da2cb367fd
Step 8/71 : COPY tools/dockerfile/scripts/root/ /root/
COPY failed: file not found in build context or excluded by .dockerignore: stat tools/dockerfile/scripts/root/: file does not exist

找不到文件？

**Comment by TeslaZhao** [comment]
你好，ARM环境与X86相比差别很大，需要在不同的硬件环境做适配。目前在飞腾ARM CPU环境跑通部署，预计下个版本(Serving v0.6.0，预计5月中旬发布)会尝试适配在树莓派.
