### ISSUE TITLE
jetson nano JetPack 4.5启动 paddle-serving Docker镜像失败

### ISSUE THREAD

**Issue by 60999** [PaddlePaddle/Serving#1095]
参考
https://github.com/PaddlePaddle/Serving/blob/develop/README_CN.md#%E5%AE%89%E8%A3%85

python3 summary_env.py
****************************************
Paddle version: None
Paddle With CUDA: None

OS: Ubuntu 18.04
Python version: 3.6.9

CUDA version: None
cuDNN version: None.None.None
Nvidia driver version: None

R32 (release), REVISION: 5.0, GCID: 25531747, BOARD: t210ref, EABI: aarch64, DATE: Fri Jan 15 22:55:35 UTC 2021

$ dpkg -l | grep TensorRT
ii  graphsurgeon-tf                            7.1.3-1+cuda10.2                                 arm64        GraphSurgeon for TensorRT package
ii  libnvinfer-bin                             7.1.3-1+cuda10.2                                 arm64        TensorRT binaries
ii  libnvinfer-dev                             7.1.3-1+cuda10.2                                 arm64        TensorRT development libraries and headers
ii  libnvinfer-doc                             7.1.3-1+cuda10.2                                 all          TensorRT documentation
ii  libnvinfer-plugin-dev                      7.1.3-1+cuda10.2                                 arm64        TensorRT plugin libraries
ii  libnvinfer-plugin7                         7.1.3-1+cuda10.2                                 arm64        TensorRT plugin libraries
ii  libnvinfer-samples                         7.1.3-1+cuda10.2                                 all          TensorRT samples
ii  libnvinfer7                                7.1.3-1+cuda10.2                                 arm64        TensorRT runtime libraries
ii  libnvonnxparsers-dev                       7.1.3-1+cuda10.2                                 arm64        TensorRT ONNX libraries
ii  libnvonnxparsers7                          7.1.3-1+cuda10.2                                 arm64        TensorRT ONNX libraries
ii  libnvparsers-dev                           7.1.3-1+cuda10.2                                 arm64        TensorRT parsers libraries
ii  libnvparsers7                              7.1.3-1+cuda10.2                                 arm64        TensorRT parsers libraries
ii  nvidia-container-csv-tensorrt              7.1.3.0-1+cuda10.2                               arm64        Jetpack TensorRT CSV file
ii  python-libnvinfer                          7.1.3-1+cuda10.2                                 arm64        Python bindings for TensorRT
ii  python-libnvinfer-dev                      7.1.3-1+cuda10.2                                 arm64        Python development package for TensorRT
ii  python3-libnvinfer                         7.1.3-1+cuda10.2                                 arm64        Python 3 bindings for TensorRT
ii  python3-libnvinfer-dev                     7.1.3-1+cuda10.2                                 arm64        Python 3 development package for TensorRT
ii  tensorrt                                   7.1.3.0-1+cuda10.2                               arm64        Meta package of TensorRT
ii  uff-converter-tf                           7.1.3-1+cuda10.2                                 arm64        UFF converter for TensorRT package

`# 启动 GPU Docker
sudo nvidia-docker pull registry.baidubce.com/paddlepaddle/serving:0.5.0-cuda10.2-cudnn8-devel
sudo nvidia-docker run -p 9292:9292 --name test -dit registry.baidubce.com/paddlepaddle/serving:0.5.0-cuda10.2-cudnn8-devel bash`

输出：
src: /usr/lib/aarch64-linux-gnu/libcublasLt.so, src_lnk: libcublasLt.so.10, dst: /var/lib/docker/overlay2/db61f16ed7640ec030f082603d17482379694357e008b0101493615a0b0e4d69/merged/usr/lib/aarch64-linux-gnu/libcublasLt.so, dst_lnk: libcublasLt.so.10
src: /usr/lib/aarch64-linux-gnu/libnvblas.so, src_lnk: libnvblas.so.10, dst: /var/lib/docker/overlay2/db61f16ed7640ec030f082603d17482379694357e008b0101493615a0b0e4d69/merged/usr/lib/aarch64-linux-gnu/libnvblas.so, dst_lnk: libnvblas.so.10
src: /usr/lib/aarch64-linux-gnu/libcublas.so, src_lnk: libcublas.so.10, dst: /var/lib/docker/overlay2/db61f16ed7640ec030f082603d17482379694357e008b0101493615a0b0e4d69/merged/usr/lib/aarch64-linux-gnu/libcublas.so, dst_lnk: libcublas.so.10
src: /usr/lib/aarch64-linux-gnu/libcublasLt.so.10, src_lnk: libcublasLt.so.10.2.2.89, dst: /var/lib/docker/overlay2/db61f16ed7640ec030f082603d17482379694357e008b0101493615a0b0e4d69/merged/usr/lib/aarch64-linux-gnu/libcublasLt.so.10, dst_lnk: libcublasLt.so.10.2.2.89
src: /usr/lib/aarch64-linux-gnu/libcublas.so.10, src_lnk: libcublas.so.10.2.2.89, dst: /var/lib/docker/overlay2/db61f16ed7640ec030f082603d17482379694357e008b0101493615a0b0e4d69/merged/usr/lib/aarch64-linux-gnu/libcublas.so.10, dst_lnk: libcublas.so.10.2.2.89
, stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=all --compute --utility --require=cuda>=10.2 brand=tesla,driver>=396,driver<397 brand=tesla,driver>=410,driver<411 brand=tesla,driver>=418,driver<419 brand=tesla,driver>=440,driver<441 --pid=8066 /var/lib/docker/overlay2/db61f16ed7640ec030f082603d17482379694357e008b0101493615a0b0e4d69/merged]
nvidia-container-cli: mount error: stat failed: /var/lib/docker/overlay2/db61f16ed7640ec030f082603d17482379694357e008b0101493615a0b0e4d69/merged/usr/local/cuda-10.2/compat/libcuda.so.440.118.02: no such file or directory: unknown.

启动也失败，编译也失败，请问能否提供一个镜像或者Dockerfile，谢谢!

**Comment by TeslaZhao** [comment]
你好，ARM环境与X86相比差别很大，需要在不同的硬件环境做适配。目前在飞腾ARM CPU环境跑通部署，预计下个版本(Serving v0.6.0，预计5月中旬发布)会尝试适配jetson.

**Comment by 60999** [comment]
看上面报错是找不到文件
docker适配性强,能否先出一个docker在jetson nano上的版本
