### ISSUE TITLE
jetson nano  docker下编译出错

### ISSUE THREAD

**Issue by 60999** [PaddlePaddle/Serving#1096]
$ docker build -f Dockerfile.cuda10.2-cudnn8.devel -t paddle-serving.armv8-nano:latest .
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.24/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile.cuda10.2-cudnn8.devel&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&shmsize=0&t=paddle-serving.armv8-nano%3Alatest&target=&ulimits=null&version=1: dial unix /var/run/docker.sock: connect: permission denied
fai@fai-desktop:~/Serving/tools/armv8$ sudo docker build -f Dockerfile.cuda10.2-cudnn8.devel -t paddle-serving.armv8-nano:latest .
Sending build context to Docker daemon  8.704kB
Step 1/62 : FROM hub.baidubce.com/ctr/cuda:10.2-cudnn8-devel-ubuntu16.04
10.2-cudnn8-devel-ubuntu16.04: Pulling from ctr/cuda
be8ec4e48d7f: Already exists 
33b8b485aff0: Already exists 
d887158cc58c: Already exists 
05895bb28c18: Already exists 
7cc9fc34ed5e: Already exists 
c001a8e57e73: Already exists 
993a4be22922: Already exists 
c4187999c3bc: Already exists 
6a0cbff9712e: Already exists 
ec7d68937b6b: Already exists 
Digest: sha256:3bdcf059a133ecf41d064239f821afdd7981570b697727ddc59ed378fad5c442
Status: Downloaded newer image for hub.baidubce.com/ctr/cuda:10.2-cudnn8-devel-ubuntu16.04
 ---> 49868fe0d389
Step 2/62 : MAINTAINER PaddlePaddle Authors <paddle-dev@baidu.com>
 ---> [Warning] The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
 ---> Running in 8749a9c6dfb5
Removing intermediate container 8749a9c6dfb5
 ---> daed91230b87
Step 3/62 : ARG WITH_GPU
 ---> [Warning] The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
 ---> Running in be2ad1defb14
Removing intermediate container be2ad1defb14
 ---> 4c6fa83de4db
Step 4/62 : ARG WITH_AVX
 ---> [Warning] The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
 ---> Running in 4239f079a906
Removing intermediate container 4239f079a906
 ---> 50fefa529989
Step 5/62 : ENV WITH_GPU=${WITH_GPU:-ON}
 ---> [Warning] The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
 ---> Running in a3c13d94b232
Removing intermediate container a3c13d94b232
 ---> e4dbfedf9776
Step 6/62 : ENV WITH_AVX=${WITH_AVX:-ON}
 ---> [Warning] The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
 ---> Running in f957e3d17d2c
Removing intermediate container f957e3d17d2c
 ---> 2dd4dcd6ae71
Step 7/62 : ENV HOME /root
 ---> [Warning] The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
 ---> Running in 9e0134bed03c
Removing intermediate container 9e0134bed03c
 ---> 426de4b55cfe
Step 8/62 : COPY tools/dockerfile/scripts/root/ /root/
COPY failed: file not found in build context or excluded by .dockerignore: stat tools/dockerfile/scripts/root/: file does not exist

看起来是架构不同，请问如何解决呢？

**Comment by TeslaZhao** [comment]
你好，ARM环境与X86相比差别很大，需要在不同的硬件环境做适配。目前在飞腾ARM CPU环境跑通部署，预计下个版本(Serving v0.6.0，预计5月中旬发布)会尝试适配jetson.

**Comment by 60999** [comment]
好的，谢谢

**Comment by ted8201** [comment]
请问jetson的适配完成了吗？release中说已经适配jetson但是并没有提供相关操作文档。
