### ISSUE TITLE
paddle_serving_client.Client()  创建实例失败

### ISSUE THREAD

**Issue by zouxiaoshi** [PaddlePaddle/Serving#1097]
在执行以下代码时报错
from paddle_serving_client import Client
**_client = Client()_**

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/miniconda3/lib/python3.8/site-packages/paddle_serving_client/__init__.py", line 139, in __init__
    from .serving_client import PredictorRes
ImportError: libcrypto.so.10: cannot open shared object file: No such file or directory

**Comment by zouxiaoshi** [comment]
我后来到 /root/miniconda3/lib/python3.8/site-packages/paddle_serving_client 里，其内容如下：
__init__.py  __pycache__  convert.py  io  lib  metric  pipeline  proto  serving_client.so  utils  version.py
在 lib 文件里 只能找到 libcrypto.a  libpython3.8.so  libssl.a 
全局搜索下也没有 find / -name libcrypto.so.10

paddle_serving_client 版本是最新版 0.5.0   Feb 24,2021 发布的。

**Comment by zouxiaoshi** [comment]
上面的是在服务器上的结果，
我自己搭的nvidia-docker 镜像  cuda10 cudnn7.6
装有paddlepaddle-gpu  paddle_serving_server-gpu.

后来我在本机上测试：
系统是macos catalina
python 环境 3.8 

Python 3.8.5 (default, Sep  4 2020, 02:22:02)
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from paddle_serving_client import Client
>>> client = Client()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/yuankaizou/opt/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle_serving_client/__init__.py", line 139, in __init__
    from .serving_client import PredictorRes
ImportError: dlopen(/Users/yuankaizou/opt/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle_serving_client/serving_client.so, 2): no suitable image found.  Did find:
	/Users/yuankaizou/opt/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle_serving_client/serving_client.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03
	/Users/yuankaizou/opt/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle_serving_client/serving_client.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03

**Comment by TeslaZhao** [comment]
您好，错误的原因是您的环境下找不到 libcrypto.so.10，解决方案请参考FAQ文档中的解决方案：https://github.com/PaddlePaddle/Serving/blob/develop/doc/FAQ.md
`
wget https://paddle-serving.bj.bcebos.com/others/centos_ssl.tar && \
    tar xf centos_ssl.tar && rm -rf centos_ssl.tar && \
    mv libcrypto.so.1.0.2k /usr/lib/libcrypto.so.1.0.2k && mv libssl.so.1.0.2k /usr/lib/libssl.so.1.0.2k && \
    ln -sf /usr/lib/libcrypto.so.1.0.2k /usr/lib/libcrypto.so.10 && \
    ln -sf /usr/lib/libssl.so.1.0.2k /usr/lib/libssl.so.10 && \
    ln -sf /usr/lib/libcrypto.so.10 /usr/lib/libcrypto.so && \
    ln -sf /usr/lib/libssl.so.10 /usr/lib/libssl.so
`

**Comment by zouxiaoshi** [comment]
> 您好，错误的原因是您的环境下找不到 libcrypto.so.10，解决方案请参考FAQ文档中的解决方案：https://github.com/PaddlePaddle/Serving/blob/develop/doc/FAQ.md
> `wget https://paddle-serving.bj.bcebos.com/others/centos_ssl.tar && \ tar xf centos_ssl.tar && rm -rf centos_ssl.tar && \ mv libcrypto.so.1.0.2k /usr/lib/libcrypto.so.1.0.2k && mv libssl.so.1.0.2k /usr/lib/libssl.so.1.0.2k && \ ln -sf /usr/lib/libcrypto.so.1.0.2k /usr/lib/libcrypto.so.10 && \ ln -sf /usr/lib/libssl.so.1.0.2k /usr/lib/libssl.so.10 && \ ln -sf /usr/lib/libcrypto.so.10 /usr/lib/libcrypto.so && \ ln -sf /usr/lib/libssl.so.10 /usr/lib/libssl.so`

1. 您好，有 ubuntu 版本的 libcrypto.so.10吗，不确定centos 的libcrypto.so.10 是否在ubuntu中也适用。
2. 在创建一个client （client = Client()）对象时还出现了如下错误：
from .serving_client import PredictorRes
ImportError: dlopen(/Users/yuankaizou/opt/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle_serving_client/serving_client.so, 2): no suitable image found. Did find:
/Users/yuankaizou/opt/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle_serving_client/serving_client.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03
/Users/yuankaizou/opt/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle_serving_client/serving_client.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03
有人说是 cv 版本问题导致 无法解析图像，请问 这里的  no suitable image found 是指 cv 版本吗，如果是的话，什么版本会适合。  paddle_serving_client 版本是 0.5.0

**Comment by TeslaZhao** [comment]
1. Ubuntu下可以使用libcrypto.so.10的，我们验证过的.
2. 使用libcrypto.so.10再启动client，看是否还有报错

**Comment by zouxiaoshi** [comment]
> * Ubuntu下可以使用libcrypto.so.10的，我们验证过的.
> * 使用libcrypto.so.10再启动client，看是否还有报错

非常感谢，it works!!
麻烦再问下， 在 macos 中，也可以用这个 centos_ssl.tar吗？
我在macos 中也出现了
from .serving_client import PredictorRes
ImportError: dlopen(/Users/yuankaizou/opt/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle_serving_client/serving_client.so, 2): no suitable image found. Did find:
/Users/yuankaizou/opt/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle_serving_client/serving_client.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03
/Users/yuankaizou/opt/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle_serving_client/serving_client.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03

**Comment by TeslaZhao** [comment]
您使用mac os原生还是docker环境？

**Comment by zouxiaoshi** [comment]
> 您使用mac os原生还是docker环境？

macos 通过conda 创建一个virtual env

**Comment by TeslaZhao** [comment]
抱歉，没有在 mac OS做过测试
