### ISSUE TITLE
训练时用save_persistables保存模型，如何进行serving模型转换？

### ISSUE THREAD

**Issue by bultiful** [PaddlePaddle/Serving#1098]
请问我用paddle训练时，是用save_persistables进行全部持久性变量保存，可以用paddle serving进行吗？我看训练好的模型都和用save_inference_model的不一样。

**Comment by bjjwwang** [comment]
需要使用save_inference_model的 
save_persistable会把vars事无巨细的保存下来唯独不保存模型结构。save_inference_model会保存相关的结构并做好裁剪。
具体参见[save文档](https://github.com/PaddlePaddle/Serving/blob/develop/doc/SAVE_CN.md)

**Comment by bultiful** [comment]
也就是说这种方式保存的持久化变量模型没法直接进行serving模型转换，得重新训练？



---原始邮件---
发件人: "Jiawei ***@***.***&gt;
发送时间: 2021年3月24日(周三) 中午12:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/Serving] 训练时用save_persistables保存模型，如何进行serving模型转换？ (#1098)




 
需要使用save_inference_model的
 save_persistable会把vars事无巨细的保存下来唯独不保存模型结构。save_inference_model会保存相关的结构并做好裁剪。
 具体参见https://github.com/PaddlePaddle/Serving/blob/develop/doc/SAVE_CN.md

**Comment by bjjwwang** [comment]
> 也就是说这种方式保存的持久化变量模型没法直接进行serving模型转换，得重新训练？
> […](#)
> ---原始邮件--- 发件人: "Jiawei ***@***.***&gt; 发送时间: 2021年3月24日(周三) 中午12:20 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [PaddlePaddle/Serving] 训练时用save_persistables保存模型，如何进行serving模型转换？ (#1098) 需要使用save_inference_model的 save_persistable会把vars事无巨细的保存下来唯独不保存模型结构。save_inference_model会保存相关的结构并做好裁剪。 具体参见https://github.com/PaddlePaddle/Serving/blob/develop/doc/SAVE_CN.md — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我觉得可能也不用 可以保存一个壳 然后把这些参数复制过去也可以的

**Comment by bjjwwang** [comment]
> 也就是说这种方式保存的持久化变量模型没法直接进行serving模型转换，得重新训练？
> […](#)
> ---原始邮件--- 发件人: "Jiawei ***@***.***&gt; 发送时间: 2021年3月24日(周三) 中午12:20 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [PaddlePaddle/Serving] 训练时用save_persistables保存模型，如何进行serving模型转换？ (#1098) 需要使用save_inference_model的 save_persistable会把vars事无巨细的保存下来唯独不保存模型结构。save_inference_model会保存相关的结构并做好裁剪。 具体参见https://github.com/PaddlePaddle/Serving/blob/develop/doc/SAVE_CN.md — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

不确定你的Paddle版本哈，
model描述文件应该是`__model__` or `***.pdmodel`
params文件 可能是一组文件（一个var对应一个文件）或者是一个文件`__params__` or `**.pdiparams`
现在save persistable的结果其实就是缺那个model描述文件。这个补上我理解也是可以用的。

**Comment by bultiful** [comment]
> > 也就是说这种方式保存的持久化变量模型没法直接进行serving模型转换，得重新训练？
> > […](#)
> > ---原始邮件--- 发件人: "Jiawei _**@**_._**> 发送时间: 2021年3月24日(周三) 中午12:20 收件人: _**@**_.**_>; 抄送: _**@**_._**_**@**_.**_>; 主题: Re: [PaddlePaddle/Serving] 训练时用save_persistables保存模型，如何进行serving模型转换？ (#1098) 需要使用save_inference_model的 save_persistable会把vars事无巨细的保存下来唯独不保存模型结构。save_inference_model会保存相关的结构并做好裁剪。 具体参见https://github.com/PaddlePaddle/Serving/blob/develop/doc/SAVE_CN.md — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 不确定你的Paddle版本哈，
> model描述文件应该是`__model__` or `***.pdmodel`
> params文件 可能是一组文件（一个var对应一个文件）或者是一个文件`__params__` or `**.pdiparams`
> 现在save persistable的结果其实就是缺那个model描述文件。这个补上我理解也是可以用的。

那这样的要就只能重新训练模型，以其他方式进行模型保存，我训练出来的参数文件就只有图中两种。看了很多方案，好像没有直接转换成paddle serving模型的方式。

<img width="429" alt="1" src="https://user-images.githubusercontent.com/38233022/112750599-05657d80-8ffc-11eb-8b12-fc09ea8f9aa2.png">
<img width="399" alt="2" src="https://user-images.githubusercontent.com/38233022/112750609-11e9d600-8ffc-11eb-96c1-efcb3c6bfe20.png">
