### ISSUE TITLE
Client 与 Server端通过BRPC调用是否支持常链接场景下的负载均衡？

### ISSUE THREAD

**Issue by LaraStuStu** [PaddlePaddle/Serving#11]
![image](https://user-images.githubusercontent.com/18028216/59431122-b2b2d580-8e16-11e9-97d3-c369848e7684.png)

关于推理服务部署的时候，Client端与Server端之间通过brpc调用，这个是否支持长连接场景下的负载均衡，如果支持，如何实现？

**Comment by wangguibao** [comment]
您说的长连接场景下的负载均衡，具体是指的什么case，能再详细一点吗？

Paddle Serving通过BRPC支持负载均衡，常见的算法如round-robin, locality-aware等，在client端可以配置。

但不确定您问的长连接场景下的负载均衡，是什么样的需求
