### ISSUE TITLE
使用Paddle Serving部署Ernie-tiny返回结果精度不理想

### ISSUE THREAD

**Issue by deep-rooteddz** [PaddlePaddle/Serving#1107]
在本地测试文本相似度匹配，准确度挺不错的；
但相同的模型部署之后，模型计算出的特征值和部署前稍有不同，准确度和原来差很多。

我使用的是以下命令导出模型：
`
python3 -m paddle_serving_client.convert --dirname . --model_filename model.pdmodel --params_filename model.pdiparams --serving_server serving_server --serving_client serving_client
`
导出文件：
![image](https://user-images.githubusercontent.com/76727820/112817921-8f255180-90b5-11eb-96e9-b0ebb8a82441.png)

模型导出后，对配置文件做了如下改动：
![image](https://user-images.githubusercontent.com/76727820/112816174-b5e28880-90b3-11eb-8a07-b3579d91d3ad.png)

通过uwsgi启动服务
`uwsgi --http :9292 --module nlp_service:app_instance`

最后通过模型输出特征进行二分类返回结果。

请问是哪里不正确或有遗漏呢，非常感谢！

**Comment by deep-rooteddz** [comment]
原因找到了，是最后的分类器没有使用模型classifier的参数进行初始化；
但新的问题是serving模型的fetch_var只返回特征值，不返回分类结果；
自己定义分类器的话想使用模型classifier的weight和bias只能再重新加载一遍模型吗？
有没有什么方法可以只加载一遍模型，但同时获得特征和分类结果呢？

**Comment by bjjwwang** [comment]
您的意思是说 fetch var 应该有两个是吗？
会不会是模型保存的时候 没有加上所需的vars呢

**Comment by deep-rooteddz** [comment]
@wangjiawei04 感谢提示，确实是模型保存的问题，现在已经改好了；

有另外个问题，由于我输入feed_var的数据要经过preprocess，才能用于预测，
feed_var本身是不需要送入推理网络的，但如果在preprocess中去掉这个feed_var的话，
在`paddle_serving_client`的`__init__.py的res = self.client_handle_.numpy_predict()`这行中，
会出现下面的问题：

![image](https://user-images.githubusercontent.com/76727820/113402823-45e84100-93d8-11eb-9593-7db7ef2e9a3b.png)

我现在的方案是在preprocess中用处理后的数据替换feed_var原本的内容，
结果可以正常返回，就是这样不太利于代码阅读，请问有什么解决方案吗？

我使用的版本是
paddlepaddle-gpu  2.0.0
serving develop分支

非常感谢！！

**Comment by deep-rooteddz** [comment]
已解决~
