### ISSUE TITLE
部署HTTP服务后图片的post格式是什么？

### ISSUE THREAD

**Issue by thugbobby** [PaddlePaddle/Serving#1109]
请问部署好HTTP服务后，我要进行POST的数据里有图片，那么图片的数据格式是base64还是其他什么呢？能不能给个示例呢？官方给的示例是post json的。麻烦解答谢谢。

`curl -H "Content-Type:application/json" -X POST -d '{"feed":[{"x": [0.0137, -0.1136, 0.2553, -0.0692, 0.0582, -0.0727, -0.1583, -0.0584, 0.6283, 0.4919, 0.1856, 0.0795, -0.0332]}], "fetch":["price"]}' http://127.0.0.1:9292/uci/prediction`
这个示例要怎么改才能上传图片？

**Comment by TeslaZhao** [comment]
您好，可以参考示例：https://github.com/PaddlePaddle/Serving/tree/develop/python/examples/ocr
