### ISSUE TITLE
win10环境 docker 安装 paddle serving，是否能使用T4 Cuda11 驱动？

### ISSUE THREAD

**Issue by meishitouzhele** [PaddlePaddle/Serving#1110]
win10环境 docker 安装 paddle serving，是否能使用T4 Cuda11  GPU 驱动？

**Comment by TeslaZhao** [comment]
您好，cuda11.0，cuda10.1，cuda10.2都是可以的

**Comment by meishitouzhele** [comment]
win10环境   是直接pip安装serving  还是用docker安装serving好一些？     如果用docker安装serving  docker安装哪个版本？

**Comment by TeslaZhao** [comment]
强烈推荐使用docker安装，原生win10环境支持的功能有限。推荐使用serving v0.5.0版本

**Comment by meishitouzhele** [comment]
![image](https://user-images.githubusercontent.com/11419081/163146095-e432ef71-8c5e-4d65-b473-58ff44d73c0a.png)
这里说必须使用：nvidia-docker，但是windows系统不支持nvidia-docker啊。是不是就是说win10上不能使用docker进行serving的GPU运算？
