### ISSUE TITLE
PaddlePaddleServing是否支持TLS connection between parameter servers and workers

### ISSUE THREAD

**Issue by YueWang1996** [PaddlePaddle/Serving#1116]
你好，根据https://github.com/PaddlePaddle/Serving/blob/develop/doc/DESIGN_DOC_CN.md 此文档可知 C++ Serving设计模型用better-rpc进行底层的通信，Python Pipeline Serving模型采用gRPC和gPRC gateway通信，而better-rpc和gRPC都支持TLS加密，那是否等同于说明PaddlePaddleServing是支持TLS加密连接的呢？如果PaddleServing有关于TLS连接的介绍文档，可否贴一下？谢谢！

**Comment by TeslaZhao** [comment]
您好，better-rpc和gRPC都支持TLS加密，目前示例没有。下周v0.6.0版本将封版提测，预计在下个版本的开发分支上增加TLS示例和文档。如果您有现成的示例也可以提供给我们，谢谢~~

**Comment by YueWang1996** [comment]
了解了，谢谢回复！期待你们的文档。
