### ISSUE TITLE
咨询一下，如何在paddleserving里面设置并发执行的模块？

### ISSUE THREAD

**Issue by allenxln** [PaddlePaddle/Serving#1121]
如题，没找到相关的并发处理的位置，感谢解答。

**Comment by meishitouzhele** [comment]
如何才能最大限度利用算力卡 达到80%以上利用率？

**Comment by TeslaZhao** [comment]
可以使用Pipeline Serving的模式，通过设置OP并发进程数量，实现多进程推理。其次，支持单机多卡推理，最大化利用算力。
https://github.com/PaddlePaddle/Serving/blob/develop/doc/PIPELINE_SERVING_CN.md

**Comment by meishitouzhele** [comment]
请问这个Pipeline Serving的模式  都支持什么环境  什么版本？

**Comment by TeslaZhao** [comment]
Linux或Docker环境
安装Serving v0.5.0版本
