### ISSUE TITLE
请问如何修改 batch size 参数和引擎实例数？

### ISSUE THREAD

**Issue by zh0ngtian** [PaddlePaddle/Serving#1122]
就类似于 Triton 的 dynamic batch 和 instance group

**Comment by TeslaZhao** [comment]
您好，batch_size是批量推理的数量，数据按批量格式组装好，predict接口中加上batch=True即可。

Triton的instance group是指线程数量吗？

**Comment by zh0ngtian** [comment]
telsa 你好
1. 我想说的是服务内自动组成batch，比如有两个请求从不同的客户端同时请求服务，服务侧会将他们组成batch=2的tensor送入推理引擎进行推理
2. 这个数量是指推理引擎的数量，就是可以执行forward的那个实例的个数
3. 在serving内部线程数这个概念可能是指rpc worker的线程数、负责拷贝数据的线程数或者引擎实例的线程数，我不清楚你说的线程数指的是哪个？

**Comment by TeslaZhao** [comment]
> telsa 你好
> 
> 1. 我想说的是服务内自动组成batch，比如有两个请求从不同的客户端同时请求服务，服务侧会将他们组成batch=2的tensor送入推理引擎进行推理
> 2. 这个数量是指推理引擎的数量，就是可以执行forward的那个实例的个数
> 3. 在serving内部线程数这个概念可能是指rpc worker的线程数、负责拷贝数据的线程数或者引擎实例的线程数，我不清楚你说的线程数指的是哪个？

Pipeline Serving 满足您的使用需求。
文档链接：https://github.com/PaddlePaddle/Serving/blob/develop/doc/PIPELINE_SERVING_CN.md
实例链接：https://github.com/PaddlePaddle/Serving/tree/develop/python/examples/pipeline

1. 支持N个请求合并推理，称之为Auto-Batching。配置使用batch_size + auto_batching_timeout
2. 推理引擎的数量由concurrency控制，在进程模式(is_thread_op: False)下concurrency表示每个模型并发进程数，即在每个进程内创建1个推理引擎，可以支持单机多卡推理。

**Comment by zh0ngtian** [comment]
谢谢你的回答，还有几个问题想继续请教下哈。
pipeline serving的模型推理应该是由pdserving执行的吧，如果是这样的话
(1) auto batch是不是由pipeline serving层完成batch拼凑再送入pdserving呢？
(2) pdserving是不是不支持单进程多个引擎实例呢？

**Comment by TeslaZhao** [comment]
pipeline serving的模型推理是paddle inference而非pdserving。
(1) pipeline组装数据后交给paddle inference推理。
(2) pipeline的进程模式是，每个进程下有一个推理引擎，线程模式是多个线程公用一个单引擎

**Comment by zh0ngtian** [comment]
明白了，谢谢！

**Comment by BraveLii** [comment]
> pipeline serving的模型推理是paddle inference而非pdserving。
> (1) pipeline组装数据后交给paddle inference推理。
> (2) pipeline的进程模式是，每个进程下有一个推理引擎，线程模式是多个线程公用一个单引擎


请问下单进程模式支持多个模型的推理么？从infer.cpp来看，TaskExecutor是单例。

**Comment by BraveLii** [comment]
> pipeline serving的模型推理是paddle inference而非pdserving。
> (1) pipeline组装数据后交给paddle inference推理。
> (2) pipeline的进程模式是，每个进程下有一个推理引擎，线程模式是多个线程公用一个单引擎

请问下线程模式怎么做到公用一个单引擎的呢？
我看到代码里，所有的engine初始化都会去设置TaskExecutor，而TaskExecutor是一个单例，这样不会出问题么？
