### ISSUE TITLE
paddle_serving java遇到的问题

### ISSUE THREAD

**Issue by chengxurensheng666** [PaddlePaddle/Serving#1125]
我根据java文档https://github.com/PaddlePaddle/Serving/tree/develop/java
放在win中idea打开，并且maven导入了
![image](https://user-images.githubusercontent.com/48110081/114295645-1d97cb00-9ad9-11eb-91c0-6ee0b9a8a425.png)
但是在执行的时候报错，错误提示是
![image](https://user-images.githubusercontent.com/48110081/114295669-3dc78a00-9ad9-11eb-9367-f98ee07765ac.png)

![image](https://user-images.githubusercontent.com/48110081/114295683-559f0e00-9ad9-11eb-8586-c357eb9e39f8.png)

**Comment by HexToString** [comment]
看着像是maven管理的io.grpc.Channel 这个jar包没下载下来，是运行时报的错对吧？
请检查一下你的maven管理的jar包是是否有这个包。

**Comment by chengxurensheng666** [comment]
我重新导入包后，之前那个错误消失了，但是出现了新的错误：
![image](https://user-images.githubusercontent.com/48110081/114332694-4a032400-9b79-11eb-9255-6612fd7acdd1.png)
![image](https://user-images.githubusercontent.com/48110081/114332779-7454e180-9b79-11eb-9b79-ce9ac4dbb06a.png)
![image](https://user-images.githubusercontent.com/48110081/114332806-833b9400-9b79-11eb-9144-90c0f1e2fd6f.png)
后台启动了服务端的
![image](https://user-images.githubusercontent.com/48110081/114332853-96e6fa80-9b79-11eb-8560-f429bd342e07.png)

**Comment by HexToString** [comment]
这个服务端的启动看着是正常了的，但是客户端没有连接到服务端。
1、如果开了代理的话，会出现这个问题。
2、另外请检查服务端和客户端的ip port是否对应？

**Comment by chengxurensheng666** [comment]
我仔细检查了，我关闭了客户机上的代理，检查了IP和端口，关闭服务端的防火墙，发现还是这样的情况
![image](https://user-images.githubusercontent.com/48110081/114336527-ce59a500-9b81-11eb-8798-87ecbd976811.png)
方便的话我可以加大佬你一个qq吗或者邮箱也行，这边业务比较急

**Comment by HexToString** [comment]
加我微信吧。sqzz8899

**Comment by TeslaZhao** [comment]
您好，在client机器上可以ping通Serving的ip/port吗?

**Comment by ycw4713** [comment]
自己下载源码编译打包
