### ISSUE TITLE
示例里基本上都是rpc服务的，有没有http服务的？

### ISSUE THREAD

**Issue by Lie-huo** [PaddlePaddle/Serving#1129]
使用paddleDetection训练了ppyolo，，请问怎么使用Serving部署成http服务呢？

**Comment by TeslaZhao** [comment]
您好，可以参考OCR中的det_debugger_server.py
https://github.com/PaddlePaddle/Serving/blob/develop/python/examples/ocr/det_debugger_server.py

**Comment by Lie-huo** [comment]
> 您好，可以参考OCR中的det_debugger_server.py
> https://github.com/PaddlePaddle/Serving/blob/develop/python/examples/ocr/det_debugger_server.py

才接触这块，对这方面不是很懂，自己写的有问多问题，所以想问一下可不可以出一个部署成http服务教程

**Comment by TeslaZhao** [comment]
您好，HTTP服务的教程参考下面链接，预计在v0.6.0版本会更新

https://github.com/PaddlePaddle/Serving/blob/v0.5.0/doc/NEW_WEB_SERVICE_CN.md
