### ISSUE TITLE
在Pipeline Serving模式下加载自己用Paddleocr训练的模型无法启动服务

### ISSUE THREAD

**Issue by huangch1024** [PaddlePaddle/Serving#1134]
已跑通paddle/examples/pieline/ocr官方样例的ocr pieline的部署。
然后在此基础上，将自己训练的的预测模型，通过paddle_serving_client.convert的模块完成转换。
预测模型文件如下
![image](https://user-images.githubusercontent.com/31469777/114691401-3824ab00-9d4a-11eb-9809-a81b2a193f37.png)
转换后的serving文件列表如下
![image](https://user-images.githubusercontent.com/31469777/114691553-61453b80-9d4a-11eb-9e37-2afaf8e3d439.png)
最后开启服务是显示是如下结果
![image](https://user-images.githubusercontent.com/31469777/114691662-7d48dd00-9d4a-11eb-954d-27e84139ae75.png)
请问是哪的问题

**Comment by bytes-lost** [comment]
在上述步骤基础上，执行`python pipeline_http_client.py`，始终未响应

**Comment by huangch1024** [comment]
paddle serving现在是不支持动态图的部署吗？感觉自己训练的模型跟例子区别就是动态图和静态图的区别
