### ISSUE TITLE
部署服务时出现，unrecognized arguments: --gpu_ids 0

### ISSUE THREAD

**Issue by Lie-huo** [PaddlePaddle/Serving#1135]
在ai studio上运行python/examples/detection/ppyolo_r50vd_dcn_1x_coco时，执行python -m paddle_serving_server.serve --model serving_server --port 9494 --gpu_ids 0出现serve: error: unrecognized arguments: --gpu_ids 0，这是什么问题

**Comment by HexToString** [comment]
你使用的是cpu版本的paddle_serving_server,如果想使用gpu，请安装pip install -U paddle_serving_server_gpu，启动的时候
python -m paddle_serving_server_gpu.serve --......

**Comment by xealml** [comment]
pip install paddle-serving-client==0.5.0
pip install paddle-serving-server==0.5.0 # CPU
pip install paddle-serving-app==0.3.0
pip install paddle-serving-server-gpu==0.5.0.post102 #GPU with CUDA10.2 + TensorRT7

paddle-serving-server==0.5.0 和 paddle-serving-server-gpu==0.5.0.post102 需要同时装吗？如果只装前者，会报一楼的问题，卸载前者，只安装后者，会报下面的问题
```
λ 400cf55ca71b /home/Serving/python/examples/ocr {develop} python -m paddle_serving_server.serve --model ocr_det_model --port 9293 --gpu_id 0
/usr/local/python2.7.15/bin/python: No module named paddle_serving_server
```
