### ISSUE TITLE
热更新

### ISSUE THREAD

**Issue by zouxiaoshi** [PaddlePaddle/Serving#1137]
模型文件结构如下：
|-serving_server
|-- __model__
|-- __params__
|-- serving_server_conf.protetxt
|-- serving_server_conf.stream.protetxt
通过如下方式启动模型：
python -m paddle_serving_server_gpu.serve --model serving_server --port 9393 --gpu_ids 0
看了 paddle_server_server monitor中的代码，热更新实际上是 
1. 替换模型文件 serving_server 2. 在serving_server中创建新的 fluid_time_stamp。
所以，核心还是通过time_stamp来判断是否应该更新模型。
我在serving_server文件夹下尝试创建新的fluid_time_stamp后，并没有发生更新行为，不知是为什么。

**Comment by TeslaZhao** [comment]
您好，模型热加载功能的核心是fluid_time_stamp来判断的，目前支持timestamp_ne, timestamp_gt判断。
要注意2个点：
1.model_toolkit.prototxt文件中，engin里的reloadable_type属性（一般在workdir目录下）
参考：https://github.com/PaddlePaddle/Serving/blob/bb6d004a2b7160bd8514b2e4185ab2ad6dcae64f/tools/cpp_examples/demo-serving/conf/model_toolkit.prototxt
2.不仅要创建fluid_time_stamp文件，还要在此文件中增加当前时间的时间戳(例如1618884444)

**Comment by zouxiaoshi** [comment]
> 您好，模型热加载功能的核心是fluid_time_stamp来判断的，目前支持timestamp_ne, timestamp_gt判断。
> 要注意2个点：
> 1.model_toolkit.prototxt文件中，engin里的reloadable_type属性（一般在workdir目录下）
> 参考：https://github.com/PaddlePaddle/Serving/blob/bb6d004a2b7160bd8514b2e4185ab2ad6dcae64f/tools/cpp_examples/demo-serving/conf/model_toolkit.prototxt
> 2.不仅要创建fluid_time_stamp文件，还要在此文件中增加当前时间的时间戳(例如1618884444)


非常感谢。
