### ISSUE TITLE
unrecognized arguments: --gpu_id 0

### ISSUE THREAD

**Issue by xealml** [PaddlePaddle/Serving#1140]
使用这两个文档启动发生失败，发生错误的在第二个文档的步骤
https://github.com/PaddlePaddle/Serving/blob/develop/README_CN.md
https://github.com/PaddlePaddle/Serving/tree/develop/python/examples/ocr

(ocr) [root@jj ocr]$ python3 -m paddle_serving_server.serve --model ocr_det_model --port 9293 --gpu_id 0
usage: serve [-h] [--thread THREAD] [--model MODEL] [--port PORT]
             [--name NAME] [--workdir WORKDIR] [--device DEVICE]
             [--mem_optim_off] [--ir_optim] [--use_mkl]
             [--max_body_size MAX_BODY_SIZE] [--use_encryption_model]
             [--use_multilang] [--product_name PRODUCT_NAME]
             [--container_id CONTAINER_ID]
serve: error: unrecognized arguments: --gpu_id 0

**Comment by HexToString** [comment]
我猜你安装的是按照官网的教程来安装的0.5.0的版本。
此时应该python3 -m paddle_serving_server_gpu.serve --model ocr_det_model --port 9293 --gpu_id 0

或者您需要查看0.5.0分支的说明，https://github.com/PaddlePaddle/Serving/tree/v0.5.0/python/examples/ocr

**Comment by xealml** [comment]
> 我猜你安装的是按照官网的教程来安装的0.5.0的版本。
> 此时应该python3 -m paddle_serving_server_gpu.serve --model ocr_det_model --port 9293 --gpu_id 0
> 
> 或者您需要查看0.5.0分支的说明，https://github.com/PaddlePaddle/Serving/tree/v0.5.0/python/examples/ocr
是的，已经从其他issue中得到支持，感谢回复
