### ISSUE TITLE
找不到 libnvinfer.so.7

### ISSUE THREAD

**Issue by zouxiaoshi** [PaddlePaddle/Serving#1141]
```bash
启动pd serving 时报错
python -m paddle_serving_server_gpu.serve \
--model serving_server \
-port 9393 --gpu_ids 0


mkdir: cannot create directory ‘workdir_0’: File exists
Going to Run Comand
/root/miniconda3/lib/python3.8/site-packages/paddle_serving_server_gpu/serving-gpu-102-0.5.0/serving -enable_model_toolkit -inferservice_path workdir_0 -inferservice_file infer_service.prototxt -max_concurrency 0 -num_threads 2 -port 9393 -reload_interval_s 10 -resource_path workdir_0 -resource_file resource.prototxt -workflow_path workdir_0 -workflow_file workflow.prototxt -bthread_concurrency 2 -gpuid 0 -max_body_size 536870912 
/root/miniconda3/lib/python3.8/site-packages/paddle_serving_server_gpu/serving-gpu-102-0.5.0/serving: error while loading shared libraries: libnvinfer.so.7: cannot open shared object file: No such file or directory
```

### 说明：
官方镜像体积太大了，后来自己了个镜像。
- BASE IMAGE： nvidia/cuda:10.0-cudnn7-devel-ubuntu16.04
- 其他package如下:
paddle-serving-app        0.2.0              
paddle-serving-client     0.5.0              
paddle-serving-server-gpu 0.5.0.post102      
paddlepaddle-gpu          2.0.1.post100 

通过 find / libnv*   找了下，容器里确实没有libnvinfer.so.7，
可以给个这个文件的下载链接吗

**Comment by TeslaZhao** [comment]
您好，如果您适用Serving的docker 镜像部署服务，cuda10.1及以上的镜像中安装默认安装对应的Tensor RT lib库。链接：https://github.com/PaddlePaddle/Serving/blob/develop/doc/DOCKER_IMAGES.md

如果您未使用docker镜像，请使用FAQ文档中说明："Cuda10.1及更高版本需要TensorRT。安装TensorRT相关文件的脚本参考 install_trt.sh"。 install_trt.sh链接：
https://github.com/PaddlePaddle/Serving/blob/develop/tools/dockerfile/build_scripts/install_trt.sh

**Comment by zouxiaoshi** [comment]
> 您好，如果您适用Serving的docker 镜像部署服务，cuda10.1及以上的镜像中安装默认安装对应的Tensor RT lib库。链接：https://github.com/PaddlePaddle/Serving/blob/develop/doc/DOCKER_IMAGES.md
> 
> 如果您未使用docker镜像，请使用FAQ文档中说明："Cuda10.1及更高版本需要TensorRT。安装TensorRT相关文件的脚本参考 install_trt.sh"。 install_trt.sh链接：
> https://github.com/PaddlePaddle/Serving/blob/develop/tools/dockerfile/build_scripts/install_trt.sh

非常感谢。 
当时没注意到
paddlepaddle-gpu 和 paddle-serving-server-gpu 版本兼容问题，
忘了paddlepaddle-gpu 2.0.1.post100 是没有编译tensorrt的。
