### ISSUE TITLE
panddle Serving 部署的api地址在哪设置呢？

### ISSUE THREAD

**Issue by huangch1024** [PaddlePaddle/Serving#1142]
paddle serving的api接口地址改在哪设置呢？我看见目前給出来的例子，都是默认的本地127的地址，也没有写在哪设置这个地址呢？

**Comment by zhangjun** [comment]
> paddle serving的api接口地址改在哪设置呢？我看见目前給出来的例子，都是默认的本地127的地址，也没有写在哪设置这个地址呢？

你好，服务部署设置ip地址似乎没有必要，除非有机器上多张网卡场景，使用默认地址启动，一般通过部署机器ip能直接访问。使用127.0.0.1作为默认地址比自行设定ip地址更合理些，能减少服务地址误设定的异常情况。

**Comment by HexToString** [comment]
我猜你想要的可能是这个地方？
https://github.com/PaddlePaddle/Serving/blob/develop/python/paddle_serving_server/web_service.py#L224
仅供参考
