### ISSUE TITLE
ppyolo test_client 结果不对

### ISSUE THREAD

**Issue by zouxiaoshi** [PaddlePaddle/Serving#1148]
执行[ppyo_r50vd_dcn_1x_coco](https://github.com/PaddlePaddle/Serving/tree/develop/python/examples/detection/ppyolo_r50vd_dcn_1x_coco) 里的示例，但是推理后的结果很差。
推理如果如下：

![000000570688 (1)](https://user-images.githubusercontent.com/44261675/115193836-41818f00-a11f-11eb-8067-1ac786bd9188.jpg)

版本信息如下：
paddle-serving-app        0.2.0              
paddle-serving-client     0.5.0              
paddle-serving-server-gpu 0.5.0.post10       
paddlepaddle-gpu          2.0.1.post100

**Comment by Nick198903** [comment]
参数调用不对
