### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by yangwenshuo** [PaddlePaddle/Serving#1149]
File "/usr/local/lib/python3.8/site-packages/paddle_serving_server_gpu/web_service.py", line 230, in run_rpc_service
    localIP = socket.gethostbyname(socket.gethostname())
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

启动命令是
python3 -m paddle_serving_server_gpu.serve --model uci_housing_model --thread 10 --port 9393 --gpu_id 0 --name uci

**Comment by HexToString** [comment]
https://blog.csdn.net/weixin_43507521/article/details/88871261
