### ISSUE TITLE
docker里面编译老是失败,baidu内网

### ISSUE THREAD

**Issue by yangwenshuo** [PaddlePaddle/Serving#1158]
fatal: unable to access 'https://github.com/google/snappy/': Unknown SSL protocol error in connection to github.com:443
fatal: unable to access 'https://github.com/gflags/gflags.git/': Unknown SSL protocol error in connection to github.com:443
Cloning into 'extern_snappy'...
Cloning into 'extern_gflags'...
fatal: unable to access 'https://github.com/open-source-parsers/jsoncpp/': Unknown SSL protocol error in connection to github.com:443
fatal: unable to access 'https://github.com/pybind/pybind11.git/': Unknown SSL protocol error in connection to github.com:443
Cloning into 'extern_pybind'...
fatal: unable to access 'https://github.com/google/protobuf.git/': Unknown SSL protocol error in connection to github.com:443

请问有什么好的解决办法么

**Comment by TeslaZhao** [comment]
您好，HI上私聊我

**Comment by TeslaZhao** [comment]
HI:zlSunshine0413
