### ISSUE TITLE
paddle sering更换新的proto文件编译失败

### ISSUE THREAD

**Issue by yangwenshuo** [PaddlePaddle/Serving#1162]
--grpc-gateway_out: no field "name" found in NormalMessageReq

[ 60%] Building CXX object core/cube/cube-api/CMakeFiles/cube-api.dir/src/meta.cpp.o
python/CMakeFiles/paddle_python.dir/build.make:67: recipe for target '.timestamp' failed
make[2]: *** [.timestamp] Error 1
CMakeFiles/Makefile2:1271: recipe for target 'python/CMakeFiles/paddle_python.dir/all' failed
make[1]: *** [python/CMakeFiles/paddle_python.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

错误信息如上图,NormalMessageReq是我们定义的请求格式,看错误信息是没有name这个字段,我应该去改哪里把 这个用name字段的地方去掉呢

**Comment by TeslaZhao** [comment]
name名称非常重要，不仅在python的proto文件Request中有使用，在gateway.proto中也有使用，并且在Service中也有使用，如下图所示。不建议修改。
```
option (google.api.http) = {
      post : "/{name=*}/{method=*}"
      body : "*"
    };
```
