### ISSUE TITLE
Cube和Serving的配置过于复杂

### ISSUE THREAD

**Issue by bjjwwang** [PaddlePaddle/Serving#117]
易用性问题反馈：
1. Cube和Serving启动的时候，配置文件复杂难以配合。
2. 缺乏一个Demo模型 （稀疏 + Dense），本地自动加载并能够提供预测服务。

**Comment by guru4elephant** [comment]
https://github.com/PaddlePaddle/Serving/tree/develop/python/examples/criteo_ctr_with_cube
