### ISSUE TITLE
ernie 1.0模型用bert测试报错

### ISSUE THREAD

**Issue by bluestinger** [PaddlePaddle/Serving#1178]
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0426 03:29:11.977586  7611 general_model.cpp:73] feed var num: 5fetch_var_num: 2
I0426 03:29:11.977638  7611 general_model.cpp:77] feed alias name: input_mask index: 0
I0426 03:29:11.977648  7611 general_model.cpp:80] feed[0] shape:
I0426 03:29:11.977654  7611 general_model.cpp:84] shape[0]: 512
I0426 03:29:11.977661  7611 general_model.cpp:84] shape[1]: 1
I0426 03:29:11.977667  7611 general_model.cpp:87] feed[0] feed type: 1
I0426 03:29:11.977675  7611 general_model.cpp:77] feed alias name: position_ids index: 1
I0426 03:29:11.977782  7611 general_model.cpp:80] feed[1] shape:
I0426 03:29:11.977788  7611 general_model.cpp:84] shape[0]: 512
I0426 03:29:11.977797  7611 general_model.cpp:84] shape[1]: 1
I0426 03:29:11.977802  7611 general_model.cpp:87] feed[1] feed type: 0
I0426 03:29:11.977810  7611 general_model.cpp:77] feed alias name: input_ids index: 2
I0426 03:29:11.977816  7611 general_model.cpp:80] feed[2] shape:
I0426 03:29:11.977841  7611 general_model.cpp:84] shape[0]: 512
I0426 03:29:11.977872  7611 general_model.cpp:84] shape[1]: 1
I0426 03:29:11.977880  7611 general_model.cpp:87] feed[2] feed type: 0
I0426 03:29:11.977898  7611 general_model.cpp:77] feed alias name: segment_ids index: 3
I0426 03:29:11.977905  7611 general_model.cpp:80] feed[3] shape:
I0426 03:29:11.977911  7611 general_model.cpp:84] shape[0]: 512
I0426 03:29:11.977917  7611 general_model.cpp:84] shape[1]: 1
I0426 03:29:11.977923  7611 general_model.cpp:87] feed[3] feed type: 0
I0426 03:29:11.977960  7611 general_model.cpp:77] feed alias name: segment_ids index: 4
I0426 03:29:11.977993  7611 general_model.cpp:80] feed[4] shape:
I0426 03:29:11.978008  7611 general_model.cpp:84] shape[0]: 1
I0426 03:29:11.978015  7611 general_model.cpp:87] feed[4] feed type: 0
I0426 03:29:11.978030  7611 general_model.cpp:95] fetch [0] alias name: pooled_output
I0426 03:29:11.978039  7611 general_model.cpp:95] fetch [1] alias name: sequence_output
I0426 03:29:11.978149  7611 general_model.cpp:55] Init commandline: dummy ernie_client.py --tryfromenv=profile_client,profile_server,max_body_size 
I0426 03:29:11.978436  7611 predictor_sdk.cpp:34] 
M
default??? d(?????????0:pooled
Defaultla"      baidu_std ?
general_model@baidu.paddle_serving.predictor.general_model.GeneralModelServiceWeightedRandomRender"
100*6
efault_tag_140065490880496list://127.0.0.1:9293
I0426 03:29:11.978503  7611 predictor_sdk.cpp:28] Succ register all components!
I0426 03:29:11.978541  7611 config_manager.cpp:217] Not found key in configue: cluster
I0426 03:29:11.978554  7611 config_manager.cpp:234] Not found key in configue: split_tag_name
I0426 03:29:11.978564  7611 config_manager.cpp:235] Not found key in configue: tag_candidates
I0426 03:29:11.978586  7611 config_manager.cpp:263] split info not set, skip...
I0426 03:29:11.978610  7611 abtest.cpp:55] Succ read weights list: 100, count: 1, normalized: 100
I0426 03:29:11.978628  7611 config_manager.cpp:202] Not found key in configue: connect_timeout_ms
I0426 03:29:11.978650  7611 config_manager.cpp:203] Not found key in configue: rpc_timeout_ms
I0426 03:29:11.978665  7611 config_manager.cpp:205] Not found key in configue: hedge_request_timeout_ms
I0426 03:29:11.978682  7611 config_manager.cpp:207] Not found key in configue: connect_retry_count
I0426 03:29:11.978706  7611 config_manager.cpp:209] Not found key in configue: hedge_fetch_retry_count
I0426 03:29:11.978716  7611 config_manager.cpp:211] Not found key in configue: max_connection_per_host
I0426 03:29:11.978725  7611 config_manager.cpp:212] Not found key in configue: connection_type
I0426 03:29:11.978734  7611 config_manager.cpp:219] Not found key in configue: load_balance_strategy
I0426 03:29:11.978744  7611 config_manager.cpp:221] Not found key in configue: cluster_filter_strategy
I0426 03:29:11.978751  7611 config_manager.cpp:226] Not found key in configue: protocol
I0426 03:29:11.978762  7611 config_manager.cpp:227] Not found key in configue: compress_type
I0426 03:29:11.978772  7611 config_manager.cpp:228] Not found key in configue: package_size
I0426 03:29:11.978781  7611 config_manager.cpp:230] Not found key in configue: max_channel_per_request
I0426 03:29:11.978788  7611 config_manager.cpp:234] Not found key in configue: split_tag_name
I0426 03:29:11.978804  7611 config_manager.cpp:235] Not found key in configue: tag_candidates
I0426 03:29:11.978816  7611 config_manager.cpp:263] split info not set, skip...
I0426 03:29:11.978823  7611 config_manager.cpp:186] Succ load one endpoint, name: general_model, count of variants: 1.
I0426 03:29:11.978838  7611 config_manager.cpp:85] Success reload endpoint config file, id: 1
I0426 03:29:11.982506  7611 naming_service_thread.cpp:209] brpc::policy::ListNamingService("127.0.0.1:9293"): added 1
I0426 03:29:11.982806  7611 stub_impl.hpp:376] Succ create parallel channel, count: 3
I0426 03:29:11.982821  7611 stub_impl.hpp:42] Create stub without tag, ep general_model
I0426 03:29:11.983860  7611 variant.cpp:69] Succ create default debug
I0426 03:29:11.983878  7611 endpoint.cpp:38] Succ create variant: 0, endpoint:general_model
I0426 03:29:11.983889  7611 predictor_sdk.cpp:69] Succ create endpoint instance with name: general_model
I0426 03:29:11.984738  7611 general_model.cpp:154] batch size: 1
I0426 03:29:11.984761  7611 stub_impl.hpp:149] Succ thread initialize stub impl!
I0426 03:29:11.984771  7611 endpoint.cpp:53] Succ thrd initialize all vars: 1
I0426 03:29:11.984781  7611 predictor_sdk.cpp:129] Succ thrd initialize endpoint:general_model
I0426 03:29:11.985100  7611 general_model.cpp:165] fetch general model predictor done.
I0426 03:29:11.985112  7611 general_model.cpp:166] float feed name size: 1
I0426 03:29:11.985123  7611 general_model.cpp:167] int feed name size: 3
I0426 03:29:11.985131  7611 general_model.cpp:168] max body size : 536870912
I0426 03:29:11.985143  7611 general_model.cpp:176] prepare batch 0
I0426 03:29:11.985162  7611 general_model.cpp:189] batch [0] int_feed_name and float_feed_name prepared
I0426 03:29:11.985174  7611 general_model.cpp:193] tensor_vec size 4 float shape 1
I0426 03:29:11.985191  7611 general_model.cpp:198] prepare float feed input_mask shape size 3
I0426 03:29:11.985209  7611 general_model.cpp:253] batch [0] float feed value prepared
I0426 03:29:11.985241  7611 general_model.cpp:270] prepare int feed input_ids shape size 3
I0426 03:29:11.985260  7611 general_model.cpp:270] prepare int feed position_ids shape size 3
Segmentation fault (core dumped)

**Comment by bluestinger** [comment]
怎么查看生成的core文件

**Comment by bluestinger** [comment]
serving_client_conf.prototxt中feed_var的name是怎么确定的？

**Comment by HexToString** [comment]
serving_client_conf.prototxt中feed_var的name是怎么确定的？

这个是由模型设置导出的

**Comment by HexToString** [comment]
怎么查看生成的core文件

使用gdb加载core文件

**Comment by bluestinger** [comment]
> serving_client_conf.prototxt中feed_var的name是怎么确定的？
> 
> 这个是由模型设置导出的

有例子吗？

**Comment by HexToString** [comment]
我的意思是，这个字段是由模型决定的。而不是自己设置的。

**Comment by bluestinger** [comment]
> 我的意思是，这个字段是由模型决定的。而不是自己设置的。

模型里怎么看呢？

**Comment by bluestinger** [comment]
我用
    src_ids = fluid.layers.data(name='1', shape=[-1, args.max_seq_len, 1], dtype='int64')
    sent_ids = fluid.layers.data(name='2', shape=[-1, args.max_seq_len, 1], dtype='int64')
    pos_ids = fluid.layers.data(name='3', shape=[-1, args.max_seq_len, 1], dtype='int64')
    task_ids = fluid.layers.data(name='4', shape=[-1, args.max_seq_len, 1], dtype='int64')
    input_mask = fluid.layers.data(name='5', shape=[-1, args.max_seq_len, 1], dtype='float32')
    seq_lens = fluid.layers.data(name='8', shape=[-1], dtype='int64’)
生成模型，但serving_client_conf.prototxt用feed_var=‘1’，’2’，’3’，’5’，，’8’赋值失败是什么原因呢？

**Comment by bluestinger** [comment]
head -1 data-c.txt | python3.6 ernie_client.py --model ernie_seq512_model_1/serving_client_conf.prototxt

WARNING: Logging before InitGoogleLogging() is written to STDERR
I0426 11:54:38.588513   515 naming_service_thread.cpp:209] brpc::policy::ListNamingService("127.0.0.1:9293"): added 1
dict_keys(['input_ids', 'position_ids', 'segment_ids', 'input_mask'])
[11]
Traceback (most recent call last):
  File "ernie_client.py", line 53, in <module>
    result = client.predict(feed=feed_dict, fetch=fetch, batch=False)
  File "/usr/local/lib/python3.6/site-packages/paddle_serving_client/__init__.py", line 292, in predict
    raise ValueError("Wrong feed name: {}.".format(key))
ValueError: Wrong feed name: 1.

**Comment by bluestinger** [comment]
python3.6 -m paddle_serving_server_gpu.serve --model ernie_seq512_model_1/ --port 9293 --gpu_ids 0 
mkdir: cannot create directory ‘workdir_0’: File exists
Going to Run Comand
/usr/local/lib/python3.6/site-packages/paddle_serving_server_gpu/serving-gpu-101-0.5.0/serving -enable_model_toolkit -inferservice_path workdir_0 -inferservice_file infer_service.prototxt -max_concurrency 0 -num_threads 2 -port 9293 -reload_interval_s 10 -resource_path workdir_0 -resource_file resource.prototxt -workflow_path workdir_0 -workflow_file workflow.prototxt -bthread_concurrency 2 -gpuid 0 -max_body_size 536870912 
I0100 00:00:00.000000   243 op_repository.h:68] RAW: Succ regist op: GeneralCopyOp
I0100 00:00:00.000000   243 op_repository.h:68] RAW: Succ regist op: GeneralDistKVInferOp
I0100 00:00:00.000000   243 op_repository.h:68] RAW: Succ regist op: GeneralDistKVQuantInferOp
I0100 00:00:00.000000   243 op_repository.h:68] RAW: Succ regist op: GeneralInferOp
I0100 00:00:00.000000   243 op_repository.h:68] RAW: Succ regist op: GeneralReaderOp
I0100 00:00:00.000000   243 op_repository.h:68] RAW: Succ regist op: GeneralResponseOp
I0100 00:00:00.000000   243 op_repository.h:68] RAW: Succ regist op: GeneralTextReaderOp
I0100 00:00:00.000000   243 op_repository.h:68] RAW: Succ regist op: GeneralTextResponseOp
I0100 00:00:00.000000   243 service_manager.h:79] RAW: Service[LoadGeneralModelService] insert successfully!
I0100 00:00:00.000000   243 load_general_model_service.pb.h:333] RAW: Success regist service[LoadGeneralModelService][PN5baidu14paddle_serving9predictor26load_general_model_service27LoadGeneralModelServiceImplE]
I0100 00:00:00.000000   243 service_manager.h:79] RAW: Service[GeneralModelService] insert successfully!
I0100 00:00:00.000000   243 general_model_service.pb.h:1507] RAW: Success regist service[GeneralModelService][PN5baidu14paddle_serving9predictor13general_model23GeneralModelServiceImplE]
I0100 00:00:00.000000   243 factory.h:155] RAW: Succ insert one factory, tag: FLUID_GPU_ANALYSIS, base type N5baidu14paddle_serving9predictor11InferEngineE
W0100 00:00:00.000000   243 fluid_gpu_engine.cpp:27] RAW: Succ regist factory: ::baidu::paddle_serving::predictor::FluidInferEngine<FluidGpuAnalysisCore>->::baidu::paddle_serving::predictor::InferEngine, tag: FLUID_GPU_ANALYSIS in macro!
I0100 00:00:00.000000   243 factory.h:155] RAW: Succ insert one factory, tag: FLUID_GPU_ANALYSIS_DIR, base type N5baidu14paddle_serving9predictor11InferEngineE
W0100 00:00:00.000000   243 fluid_gpu_engine.cpp:33] RAW: Succ regist factory: ::baidu::paddle_serving::predictor::FluidInferEngine< FluidGpuAnalysisDirCore>->::baidu::paddle_serving::predictor::InferEngine, tag: FLUID_GPU_ANALYSIS_DIR in macro!
I0100 00:00:00.000000   243 factory.h:155] RAW: Succ insert one factory, tag: FLUID_GPU_ANALYSIS_ENCRPT, base type N5baidu14paddle_serving9predictor11InferEngineE
W0100 00:00:00.000000   243 fluid_gpu_engine.cpp:38] RAW: Succ regist factory: ::baidu::paddle_serving::predictor::FluidInferEngine< FluidGpuAnalysisEncryptCore>->::baidu::paddle_serving::predictor::InferEngine, tag: FLUID_GPU_ANALYSIS_ENCRPT in macro!
I0100 00:00:00.000000   243 factory.h:155] RAW: Succ insert one factory, tag: FLUID_CPU_ANALYSIS, base type N5baidu14paddle_serving9predictor11InferEngineE
W0100 00:00:00.000000   243 fluid_cpu_engine.cpp:25] RAW: Succ regist factory: ::baidu::paddle_serving::predictor::FluidInferEngine<FluidCpuAnalysisCore>->::baidu::paddle_serving::predictor::InferEngine, tag: FLUID_CPU_ANALYSIS in macro!
I0100 00:00:00.000000   243 factory.h:155] RAW: Succ insert one factory, tag: FLUID_CPU_ANALYSIS_DIR, base type N5baidu14paddle_serving9predictor11InferEngineE
W0100 00:00:00.000000   243 fluid_cpu_engine.cpp:31] RAW: Succ regist factory: ::baidu::paddle_serving::predictor::FluidInferEngine< FluidCpuAnalysisDirCore>->::baidu::paddle_serving::predictor::InferEngine, tag: FLUID_CPU_ANALYSIS_DIR in macro!
I0100 00:00:00.000000   243 factory.h:155] RAW: Succ insert one factory, tag: FLUID_CPU_ANALYSIS_ENCRYPT, base type N5baidu14paddle_serving9predictor11InferEngineE
W0100 00:00:00.000000   243 fluid_cpu_engine.cpp:38] RAW: Succ regist factory: ::baidu::paddle_serving::predictor::FluidInferEngine< FluidCpuAnalysisEncryptCore>->::baidu::paddle_serving::predictor::InferEngine, tag: FLUID_CPU_ANALYSIS_ENCRYPT in macro!
I0426 11:46:58.310943   243 analysis_predictor.cc:139] Profiler is deactivated, and no profiling report will be generated.
I0426 11:46:58.325287   243 analysis_predictor.cc:524] ir_optim is turned off, no IR pass will be executed
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_graph_clean_pass]
--- Running analysis [ir_analysis_pass]
--- Running analysis [ir_params_sync_among_devices_pass]
I0426 11:46:59.269582   243 ir_params_sync_among_devices_pass.cc:45] Sync params from CPU to GPU
--- Running analysis [adjust_cudnn_workspace_size_pass]
--- Running analysis [inference_op_replace_pass]
--- Running analysis [memory_optimize_pass]
I0426 11:46:59.812711   243 memory_optimize_pass.cc:200] Cluster name : 8  size: 8
I0426 11:46:59.812749   243 memory_optimize_pass.cc:200] Cluster name : 5  size: 2048
I0426 11:46:59.812757   243 memory_optimize_pass.cc:200] Cluster name : 3  size: 4096
I0426 11:46:59.812763   243 memory_optimize_pass.cc:200] Cluster name : transpose_5.tmp_0  size: 1572864
I0426 11:46:59.812769   243 memory_optimize_pass.cc:200] Cluster name : layer_norm_2.tmp_2  size: 1572864
I0426 11:46:59.812777   243 memory_optimize_pass.cc:200] Cluster name : matmul_15.tmp_0  size: 12582912
I0426 11:46:59.812844   243 memory_optimize_pass.cc:200] Cluster name : stack_0.tmp_0  size: 12582912
I0426 11:46:59.812851   243 memory_optimize_pass.cc:200] Cluster name : softmax_6.tmp_0  size: 12582912
I0426 11:46:59.812857   243 memory_optimize_pass.cc:200] Cluster name : softmax_1.tmp_0  size: 12582912
I0426 11:46:59.812877   243 memory_optimize_pass.cc:200] Cluster name : transpose_26.tmp_0  size: 1572864
I0426 11:46:59.812896   243 memory_optimize_pass.cc:200] Cluster name : 2  size: 4096
I0426 11:46:59.812906   243 memory_optimize_pass.cc:200] Cluster name : 1  size: 4096
I0426 11:46:59.812911   243 memory_optimize_pass.cc:200] Cluster name : layer_norm_8.tmp_2  size: 1572864
--- Running analysis [ir_graph_to_program_pass]
I0426 11:46:59.863169   243 analysis_predictor.cc:548] ======= optimize end =======
I0426 11:46:59.863286   243 naive_executor.cc:107] ---  skip [feed], feed -> 8
I0426 11:46:59.863391   243 naive_executor.cc:107] ---  skip [feed], feed -> 5
I0426 11:46:59.863410   243 naive_executor.cc:107] ---  skip [feed], feed -> 3
I0426 11:46:59.863428   243 naive_executor.cc:107] ---  skip [feed], feed -> 2
I0426 11:46:59.863437   243 naive_executor.cc:107] ---  skip [feed], feed -> 1
I0426 11:46:59.866284   243 naive_executor.cc:107] ---  skip [softmax_1.tmp_0], fetch -> fetch
I0426 11:46:59.866307   243 naive_executor.cc:107] ---  skip [matmul_15.tmp_0], fetch -> fetch
W0426 11:46:59.866400   243 infer.h:469] Succ load common model[0x47399a60], path[ernie_seq512_model_1/].
W0426 11:46:59.866436   243 infer.h:215] Succ load model_data_pathernie_seq512_model_1/

**Comment by bluestinger** [comment]
> head -1 data-c.txt | python3.6 ernie_client.py --model ernie_seq512_model_1/serving_client_conf.prototxt
> 
> WARNING: Logging before InitGoogleLogging() is written to STDERR
> I0426 11:54:38.588513 515 naming_service_thread.cpp:209] brpc::policy::ListNamingService("127.0.0.1:9293"): added 1
> dict_keys(['input_ids', 'position_ids', 'segment_ids', 'input_mask'])
> [11]
> Traceback (most recent call last):
> File "ernie_client.py", line 53, in 
> result = client.predict(feed=feed_dict, fetch=fetch, batch=False)
> File "/usr/local/lib/python3.6/site-packages/paddle_serving_client/**init**.py", line 292, in predict
> raise ValueError("Wrong feed name: {}.".format(key))
> ValueError: Wrong feed name: 1.


import sys
from paddle_serving_client import Client
from paddle_serving_client.utils import benchmark_args
from paddle_serving_app.reader import ChineseBertReader
import numpy as np
args = benchmark_args()

reader = ChineseBertReader({"max_seq_len": 128*4})
fetch = ["pooled_output"]
endpoint_list = ['127.0.0.1:9293']
client = Client()
client.load_client_config(args.model)
client.connect(endpoint_list)

feed_dict = {}
for line in sys.stdin:
    #feed_dict = reader.process(line)
    #'''
    feed_dict_bert = reader.process(line)
    print(feed_dict_bert.keys())
    feed_dict['1'] = feed_dict_bert['input_ids']
    feed_dict['2'] = feed_dict_bert['segment_ids']
    feed_dict['3'] = feed_dict_bert['position_ids']
    feed_dict['5'] = feed_dict_bert['input_mask']
    feed_dict['8'] = [len([i for i in feed_dict_bert['input_ids'] if i > 0])]
    print(feed_dict['8'])
    #'''
    #feed_dict['8'] = [len([i for i in feed_dict['input_ids'] if i > 0])] 


    for key in feed_dict.keys():
        if key != '8':
            feed_dict[key] = np.array(feed_dict[key]).reshape((128*4, 1))
        else:
            feed_dict[key] = np.array(feed_dict[key]).reshape((1))
    #print(feed_dict)
    result = client.predict(feed=feed_dict, fetch=fetch, batch=False)


print(result)

**Comment by bluestinger** [comment]
layer名称的问题通过配serving_client_conf.prototxt解决了，现在
terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():  

  Compile Traceback (most recent call last):
    File "/home/shenchao/.local/lib/python3.6/site-packages/paddle/fluid/framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))

    File "/home/shenchao/.local/lib/python3.6/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)

    File "/home/shenchao/.local/lib/python3.6/site-packages/paddle/fluid/layers/nn.py", line 4806, in layer_norm
    "begin_norm_axis": begin_norm_axis})

    File "/home/shenchao/ERNIE/ERNIE/ernie/model/transformer_encoder.py", line 220, in pre_post_process_layer
    initializer=fluid.initializer.Constant(0.)))

    File "/home/shenchao/ERNIE/ERNIE/ernie/model/ernie_v1.py", line 155, in _build_model
    emb_out, 'nd', self._prepostprocess_dropout, name='pre_encoder')

    File "/home/shenchao/ERNIE/ERNIE/ernie/model/ernie_v1.py", line 126, in __init__
    self._build_model(src_ids, position_ids, sentence_ids, input_mask)

    File "ernie/ernie_encoder.py", line 77, in create_model
    config=ernie_config)

    File "ernie/ernie_encoder.py", line 140, in main
    args, pyreader_name='reader', ernie_config=ernie_config, is_infer=is_infer)

    File "ernie/ernie_encoder.py", line 217, in <module>
    main(args)


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: 'begin_norm_axis' must be less than the dimensions of X,But received 'begin_norm_axis' is [2],received the dimensions of X is [2].
  [Hint: Expected begin_norm_axis < x_dim.size(), but received begin_norm_axis:2 >= x_dim.size():2.] (at /paddle/paddle/fluid/operators/layer_norm_op.cc:49)
  [operator < layer_norm > error]

**Comment by HexToString** [comment]
我猜测您的serving_ver_conf.prototxt也许也需要适配？
