### ISSUE TITLE
Http方式部署thread参数不起作用

### ISSUE THREAD

**Issue by CH7auAI** [PaddlePaddle/Serving#1189]
使用以下命令部署模型是，输入的thread参数不起作用，cpu使用率不超过400%：

> python -m paddle_serving_server.serve --model my_model --thread 10 --port 9292 --name my_model

原因是文件：
https://github.com/PaddlePaddle/Serving/blob/develop/python/paddle_serving_server/serve.py
中第433行中processes=4，并没有更新为用户的输入参数；

**Comment by TeslaZhao** [comment]
您好，感谢您的issue，我们会在下个版本改进

**Comment by yafeisong** [comment]
> 您好，感谢您的issue，我们会在下个版本改进

部署http服务时，提示--name参数不能用，该怎么处理呢？
serve: error: unrecognized arguments: --name
