### ISSUE TITLE
docker serarch 报404

### ISSUE THREAD

**Issue by JunKuangKuang** [PaddlePaddle/Serving#1195]
我想要尝试拉取docker镜像的内容，但是在访问了对应的链接之后，却是提示我404找不到资源
```
[root@iz20d333q744p1z ~]# docker search registry.baidubce.com/paddlepaddle/serving
Error response from daemon: Unexpected status code 404
[root@iz20d333q744p1z ~]# docker search hub.baidubce.com/paddlepaddle/serving
Error response from daemon: Unexpected status code 404
```

**Comment by JunKuangKuang** [comment]
我的系统是centos7，
`Linux iz20d333q744p1z 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

我准备拉取指定的版本来运行我已经做好的模型，但是拉取docker镜像一直失败

**Comment by hysunflower** [comment]
> 我的系统是centos7，
> `Linux iz20d333q744p1z 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
> 
> 我准备拉取指定的版本来运行我已经做好的模型，但是拉取docker镜像一直失败

您好，尝试使用该文档所述的方法pull 镜像试试~  https://github.com/PaddlePaddle/Serving/blob/develop/README_CN.md
