### ISSUE TITLE
docker 容器无法启动

### ISSUE THREAD

**Issue by Amanda-Barbara** [PaddlePaddle/Serving#1196]
我用的是ubuntu20.04系统，按照https://github.com/PaddlePaddle/Serving/blob/develop/doc/RUN_IN_DOCKER_CN.md教程输入一下指令，
$ docker run --gpus all -p 9292:9292 --name test -dit registry.baidubce.com/paddlepaddle/serving:latest-cuda10.2-cudnn8-devel
f2ad919b0f20069c696073ea35f6fd743771c0b9bcb9ebd5adba2969482bb952
$ docker exec -it test bash
Error response from daemon: Container f2ad919b0f20069c696073ea35f6fd743771c0b9bcb9ebd5adba2969482bb952 is not running报出了容器没有运行，然后我使用docker的stop和start命令也还是报出容器没有运行，
想请教一下如何解决啊？

**Comment by HexToString** [comment]
请在您的docker run命令的最后加上 /bin/bash

**Comment by Amanda-Barbara** [comment]
@HexToString 可以了，多谢哈。
