### ISSUE TITLE
Pipeline Serving 的RPC服务同时启动一个web服务器和RPC服务器，请问这里的web是uwsgi还是其他的什么？

### ISSUE THREAD

**Issue by huangch1024** [PaddlePaddle/Serving#1200]

**Comment by huangch1024** [comment]
![image](https://user-images.githubusercontent.com/31469777/117257119-1b2d5480-ae7e-11eb-9f54-a233c6c252f6.png)

**Comment by TeslaZhao** [comment]
web服务是采用 gRPC-gateway实现的
