### ISSUE TITLE
请问可以部署ocr到阿里云函数计算吗 我这边提示错误不知道怎么解决

### ISSUE THREAD

**Issue by duolabmeng6** [PaddlePaddle/Serving#1201]
···
{
  "errorMessage": "Unable to import module 'index'",
  "errorType": "ImportError",
  "stackTrace": [
    "ImportError: /code/.fun/root/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /code/.fun/python/lib/python3.6/site-packages/paddle/fluid/core_avx.so)"
  ]
}
···

安装环境
···
fun install --runtime python3 --package-type pip install paddle-serving-client==0.5.0
fun install --runtime python3 --package-type pip install paddle-serving-server==0.5.0 # CPU
fun install --runtime python3 --package-type pip install paddle-serving-app==0.3.0 
fun install --runtime python3 --package-type pip install paddlepaddle==2.0.0
···

然后运行 ocr_debugger_server.py

就提示GLIBCXX_3.4.22

**Comment by duolabmeng6** [comment]
已经解决了 但是镜像文件1.7g

**Comment by TeslaZhao** [comment]
镜像里有安装paddle组件吗，还是只安装了Serving?

**Comment by duolabmeng6** [comment]
> 镜像里有安装paddle组件吗，还是只安装了Serving?

安装了因为没有gcc所以运行不了~
