### ISSUE TITLE
使用0.3.1跑plato模型出core报错。

### ISSUE THREAD

**Issue by lonelydancer** [PaddlePaddle/Serving#1202]
用paddle1.8.1训的model
paddle-serving版本是0.3.1

1.构造的数据的shape
这份数据在原生的python 预测端是可以正常进行。
![image](https://user-images.githubusercontent.com/548443/117394972-c0513700-af29-11eb-979d-dca56fb67c68.png)

报错信息
  File "/home/hupenglong/py37/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/hupenglong/py37/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/hupenglong/py37/lib/python3.7/site-packages/paddle/fluid/layers/tensor.py", line 375, in concat
    type='concat', inputs=inputs, outputs={'Out': [out]}, attrs=attrs)
  File "/home/hupenglong/Knover/models/unified_transformer.py", line 127, in _gen_input
    emb_out = layers.concat([aux_emb, emb_out], axis=1)
  File "/home/hupenglong/Knover/models/unified_transformer.py", line 179, in _generation_network
    token_ids, type_ids, pos_ids, generation_mask, aux_emb=aux_emb)
  File "/home/hupenglong/Knover/models/plato.py", line 198, in forward
    gather_idx=inputs.get("parent_idx", None),
  File "/home/hupenglong/Knover/models/model_base.py", line 92, in _build_programs
    outputs = self.forward(inputs, is_infer=True)
  File "/home/hupenglong/Knover/models/model_base.py", line 74, in __init__
    self._build_programs()
  File "/home/hupenglong/Knover/models/unified_transformer.py", line 94, in __init__
    super(UnifiedTransformer, self).__init__(args, place)
  File "/home/hupenglong/Knover/models/plato.py", line 50, in __init__
    super(Plato, self).__init__(args, place)
  File "/home/hupenglong/Knover/models/__init__.py", line 50, in create_model
    return MODEL_REGISTRY[args.model](args, place)
  File "save_inference_model.py", line 54, in save
    model = models.create_model(args, place)
  File "save_inference_model.py", line 63, in <module>
    save(args)

----------------------
Error Message Summary:
----------------------
Error: ShapeError: Dimension 2 in inputs' shapes must be equal. But recevied input[0]'s shape = [1, 1, 20, 1024], input[1]'s shape = [1, 20, 7, 1024].
  [Hint: Expected inputs_dims[0][j] == inputs_dims[i][j], but received inputs_dims[0][j]:20 != inputs_dims[i][j]:7.] at (/paddle/paddle/fluid/operators/concat_op.h:55)
  [operator < concat > error]
Aborted (core dumped)

有几个概念不太清楚：
1）传给client.predict中的feed的格式，如果是batch_size>1需要传list,每个list是一个字典；还是像我这样传与训练代码feed_dict一致就是合法的?
2）报错信息表示似乎给input shape多增加了一维信息
     model定义的shape应该是
     aux 20,1,1024,
     emb_out 20,7,1024
3)  我把数据变成batch_size=1,报错信息也类似。多增加了一个维度。
4) 怀疑是否跟对lod tensor支持不好有关呢？有几个feed变量是lod tensor
2. client端代码
https://github.com/lonelydancer/algorithm/blob/master/client.py
client的配置
https://github.com/lonelydancer/algorithm/blob/master/serving_client_conf.prototxt
3. 对应的plato feed_dict
https://github.com/PaddlePaddle/Knover/blob/plato-2/models/plato.py
_get_feed_dict中定义的

**Comment by bjjwwang** [comment]
嗯嗯 要不 升级成0.4.0版本 
0.4.0的predict(feed={}, fetch=[], batch=True)
其中 feed接口传入一个dict就可以，需要确保每个value都是numpy array，直接reshape成图1 里面的大小
然后batch记的设置成True，代表这次传入的feed是一整个batch，不需要前面再加一个1.

**Comment by lonelydancer** [comment]
请问0.4.0对输入有lod tensor的支持是怎样的呢？ 
换完之后报错~, b并且是中间计算环节了，并不是输入的类型,
训练代码定义的是int64
https://github.com/PaddlePaddle/Knover/blob/plato-2/models/generator.py

step_idx = layers.fill_constant(
shape=[1], dtype="int64", value=0, force_cpu=True)
pre_ids = layers.array_read(array=ids, i=step_idx)


![image](https://user-images.githubusercontent.com/548443/117530984-bf480480-b012-11eb-9924-8ebb718fc5a0.png)

**Comment by lonelydancer** [comment]
@bjjwwang 请帮忙看看呀。不知道是不是版本兼容的问题还是bug

**Comment by lonelydancer** [comment]
@bjjwwang 你好，我使用paddle2.1.0重新训练了model，并且paddle serving用了最新版，但是依然报错。
File "/home/Knover2/knover/models/unified_transformer.py", line 460, in infer
20599       return self.generator.inference(self, inputs, outputs)
20600     File "/home/Knover2/knover/modules/generator.py", line 217, in inference
20601       topk_indices = layers.lod_reset(topk_indices, pre_ids)
20602     File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line       6451, in lod_reset
20603       'Y': y}, outputs={'Out': out})
20604     File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", li      ne 43, in append_op
20605       return self.main_program.current_block().append_op(*args, **kwargs)
20606     File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/framework.py", line       3232, in append_op
20607       attrs=kwargs.get("attrs", None))
20608     File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/framework.py", line       2312, in __init__
20609       for frame in traceback.extract_stack():
InvalidArgumentError: Tensor holds the wrong type, it holds int64_t, but desires to be int.
 [Hint: Expected valid == true, but received valid:0 != true:1.] (at /paddle/paddle/fluid/framework/tensor_impl.h:33)
