### ISSUE TITLE
OCR的例子直接跑会报错，还有文档的一点小错误

### ISSUE THREAD

**Issue by erma0** [PaddlePaddle/Serving#1216]
环境：Win10 X64，paddle2.0.2
1. 运行`python ocr_debugger_server.py gpu`会报错，因为例子中判断参数为GPU后仍旧引入了CPU库。。。
```
Traceback (most recent call last):
  File "ocr_debugger_server.py", line 109, in <module>
    ocr_service.set_gpus("0")
AttributeError: 'OCRService' object has no attribute 'set_gpus'
```
`ocr_debugger_server.py `代码
```
if sys.argv[1] == 'gpu':
    from paddle_serving_server.web_service import WebService
elif sys.argv[1] == 'cpu':
    from paddle_serving_server.web_service import WebService
```
2. 程序支持paddle2.0，但提示某api即将弃用，且没有说api名字，建议更换api；另外Win10下提示touch命令出错，需要加上判断用其他命令，或者提前安装touch（`npm install touch-cli -g`）
```
This API will be deprecated later. Please do not use it
This API will be deprecated later. Please do not use it
子目录或文件 workdir 已经存在。
'touch' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'touch' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
```
3. OCR的readme中运行CPU和GPU版本用的都是同一个命令。。
>  https://github.com/PaddlePaddle/Serving/blob/develop/python/examples/ocr/README_CN.md
这个里面有两处“启动服务”中命令都是这个问题，并没有使用GPU

**Comment by TeslaZhao** [comment]
使用v0.6.1版本或develop版本已经修复该问题

pip install paddle-serving-client==0.6.1
pip install paddle-serving-server==0.6.1 # CPU
pip install paddle-serving-app==0.6.1
pip install paddle-serving-server-gpu==0.6.1.post102     # GPU with CUDA10.2 + TensorRT7
pip install paddle-serving-server-gpu==0.6.1.post101      # GPU with CUDA10.1 + TensorRT6
pip install paddle-serving-server-gpu==0.6.1.post11        # GPU with CUDA10.1 + TensorRT7
