### ISSUE TITLE
docker 镜像内无法检测到GPU

### ISSUE THREAD

**Issue by Jeffrey98-AI** [PaddlePaddle/Serving#1220]
提供的 registry.baidubce.com/paddlepaddle/serving:0.5.0-devel 这个镜像进去之后nvidia-smi ，bash: nvidia-smi: command not found，宿主机执行nvidia-smi是可以检测到的，另外试了其他的pytorch镜像也是没问题的

**Comment by TeslaZhao** [comment]
您好，您使用的机器(GPU)、CUDA、docker版本能发一下吗？
