### ISSUE TITLE
负载均衡

### ISSUE THREAD

**Issue by zouxiaoshi** [PaddlePaddle/Serving#1226]
您好：
通过如下命令启动RPC serivce 时， 是应用brpc 还是grpc？
```bash
python -m paddle_serving_server.serve --model uci_housing_model --thread 10 --port 9292 
```
如果是brpc，请问可否 用nginx进行负载。
刚接触brpc, 只知道可以在client端进行负载。
业务需要，像nginx那样集中式负载，所以想问问paddle serving有哪些负载模式。

大概场景是这样的：
好多台机器，每个机器若干服务，
对外只通过一个节点利用负载暴露服务

**Comment by TeslaZhao** [comment]
您好，运行命令对外暴露gRPC接口（python -m paddle_serving_server.serve --model uci_housing_model --thread 10 --port 9292 ）。RPC的负载均衡在Client上做，当然要做集中式负载如反向代理层或gateway也可以做到。Serving目前不提供集中式NG负载均衡，网上有很多教程通过Nginx实现gRPC服务的负载均衡（https://www.jianshu.com/p/611d586f58cd）。Serving V0.6版本机房发布基于K8S的安全网关，采用KONG做的，可以参考，下周会提交代码和文档。

**Comment by zouxiaoshi** [comment]
> 您好，运行命令对外暴露gRPC接口（python -m paddle_serving_server.serve --model uci_housing_model --thread 10 --port 9292 ）。RPC的负载均衡在Client上做，当然要做集中式负载如反向代理层或gateway也可以做到。Serving目前不提供集中式NG负载均衡，网上有很多教程通过Nginx实现gRPC服务的负载均衡（[https://www.jianshu.com/p/611d586f58cd）。Serving](https://www.jianshu.com/p/611d586f58cd%EF%BC%89%E3%80%82Serving) V0.6版本机房发布基于K8S的安全网关，采用KONG做的，可以参考，下周会提交代码和文档。

非常感谢。
