### ISSUE TITLE
官方的Docker 版本报错

### ISSUE THREAD

**Issue by ouyangshixiong** [PaddlePaddle/Serving#1251]
直接上图
![企业微信截图_76e6c33a-e32e-49f7-a56c-37df636540e6](https://user-images.githubusercontent.com/2086862/118741440-d55e8c00-b880-11eb-8a1c-b845e52016db.png)

**Comment by TeslaZhao** [comment]
docker run -p 9292:9292 --name test -dit registry.baidubce.com/paddlepaddle/serving:0.5.0-devel bash

少加一个bash
