### ISSUE TITLE
pipeline server 重写 process 通过grpc调用其他模型

### ISSUE THREAD

**Issue by zouxiaoshi** [PaddlePaddle/Serving#1273]
想通过重写process 函数，用grpc 调用其他模型，可否给个例子。

**Comment by TeslaZhao** [comment]
https://github.com/PaddlePaddle/Serving/blob/develop/python/pipeline/pipeline_client.py#L96

您好，Pipeline模式支持Rpc模式的，示例参考https://github.com/PaddlePaddle/Serving/tree/develop/python/examples/pipeline/imdb_model_ensemble
