### ISSUE TITLE
多模型共用TaskExecutor的疑问

### ISSUE THREAD

**Issue by BraveLii** [PaddlePaddle/Serving#1285]
ReloadableInferEngine::proc_initialize中使用TaskExecutor的是个单例，那么多个模型会一次去设置、启动同一个TaskExecutor；
在调用schedule()之后，TaskExecutor如何确定去调用哪个模型呢？

**Comment by HexToString** [comment]
你问的问题刚好就是我最近要改的地方。
感觉你是一个资深的开发者，预计一周之内，这个地方会改为可以满足多模型的设计，敬请期待。
如果你感兴趣的话，同时邀请你加入我们的核心开发者群。

**Comment by HexToString** [comment]
目前已经新增了支持多个模型的异步任务框架。详情见develop分支。
