### ISSUE TITLE
windows下docker运行serving的imagenet示例，docker里面HTTP调用成功，宿主机windowsHTTP调用连不上

### ISSUE THREAD

**Issue by pipishaw** [PaddlePaddle/Serving#1287]
windows下docker运行serving的imagenet示例，docker里面HTTP调用成功，宿主机windowsHTTP调用连不上
这种情况要怎么处理？

**Comment by bjjwwang** [comment]
是不是 没有对外暴露端口
Windows docker的启动命令有吗

**Comment by pipishaw** [comment]
暴漏了端口，用IP+端口不行，用localhost+端口可以访问。

有没有yolov3在windows下能跑的例子，windows跑RPC服务跑不起来，web服务的没看到示例。

**Comment by pipishaw** [comment]
pipeline下的列都卡在这不动了，客户端调用也没反应
λ a325bf88bcc2 /home/Serving/python/examples/pipeline/PaddleDetection/yolov3 {v0.6.0} python web_service.py
/usr/local/lib/python3.7/site-packages/paddle_serving_server/pipeline/pipeline_server.py:341: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  conf = yaml.load(f.read())
2021/06/30 12:34:14 start proxy service
