### ISSUE TITLE
部署ernie-tiny，server端报错维度不匹配

### ISSUE THREAD

**Issue by Karenlyw** [PaddlePaddle/Serving#1288]
使用paddlehub训练好模型后，得到静态图参数和模型，使用paddle_serving_client.convert 转化成inference model 并且得到config。config长这样：
feed_var {
  name: "input_ids"
  alias_name: "input_ids"
  is_lod_tensor: false
  feed_type: 0
  shape: 256
  shape: 1
}

feed_var {
  name: "position_ids"
  alias_name: "position_ids"
  is_lod_tensor: false
  feed_type: 0
  shape: 256
  shape: 1
}
feed_var {
  name: "segment_ids"
  alias_name: "segment_ids"
  is_lod_tensor: false
  feed_type: 0
  shape: 256
  shape: 1
}
feed_var {
  name: "input_mask"
  alias_name: "input_mask"
  is_lod_tensor: false
  feed_type: 1
  shape: 256
  shape: 1
}
fetch_var {
  name: "fc_0.tmp_2"
  alias_name: "fc_0.tmp_2"
  is_lod_tensor: true
  fetch_type: 1
  shape: -1
}

在client端使用reader预处理得到输入input_ids,segment_ids,positon_ids,input_mask
，定义的max_len是256，所以每个输入的维度都是1X256X1，然后传到feed的dict里，server端会报这个错：

InvalidArgumentError: The first dimension value of Input(Scale) must equal to be thesecond dimension value of the flattened 2D matrix of Input(X),But received the first dimension value of Input(Scale) is[1024], the second dimension value of the flattened 2D matrix of Input(Scale) is [262144].
  [Hint: Expected ctx->GetInputDim("Scale")[0] == right, but received ctx->GetInputDim("Scale")[0]:1024 != right:262144.] (at /paddle/paddle/fluid/operators/layer_norm_op.cc:72)
  [operator < layer_norm > error]

**Comment by TeslaZhao** [comment]
您好，您使用哪种Serving部署模式（python webservice, python pipeline, 还是命令行启动），以及使用的CPU/GPU 信息？从您的报错信息看是输入数据的维度有问题。

**Comment by Karenlyw** [comment]
您好，非常感谢回答，目前数据维度的问题已解决。有一个新的问题，如果client.predict被多进程调用，是应该使用同一个client还是每次调用都建一个新的client呢？涉不涉及client的回收之类的呢？另外运行程序会输出
E0702 03:33:28.017952 10012 factory.h:183] RAW: Insert duplicate with tag: WeightedRandomRender
I0702 03:33:28.017952 10012 abtest.h:67] RAW: Factory has been registed: WeightedRandomRender->EndpointRouterBase.
E0702 03:33:28.270856 10012 variable.cpp:177] Already exposed `general_model_baidu_paddle_serving_predictor_general_model_general_model_service_default_tag_139633810242080_infer_sync_ltc_latency' whose value is `0'
请问这个会有影响吗？不太懂是啥意思，提前感谢回答~

**Comment by Karenlyw** [comment]
> 您好，您使用哪种Serving部署模式（python webservice, python pipeline, 还是命令行启动），以及使用的CPU/GPU 信息？从您的报错信息看是输入数据的维度有问题。

您好，非常感谢回答，目前数据维度的问题已解决。有一个新的问题，如果client.predict被多进程调用，是应该使用同一个client还是每次调用都建一个新的client呢？涉不涉及client的回收之类的呢？另外运行程序会输出
E0702 03:33:28.017952 10012 factory.h:183] RAW: Insert duplicate with tag: WeightedRandomRender
I0702 03:33:28.017952 10012 abtest.h:67] RAW: Factory has been registed: WeightedRandomRender->EndpointRouterBase.
E0702 03:33:28.270856 10012 variable.cpp:177] Already exposed general_model_baidu_paddle_serving_predictor_general_model_general_model_service_default_tag_139633810242080_infer_sync_ltc_latency' whose value is 0'
请问这个会有影响吗？不太懂是啥意思，提前感谢回答~

**Comment by Karenlyw** [comment]
> 您好，您使用哪种Serving部署模式（python webservice, python pipeline, 还是命令行启动），以及使用的CPU/GPU 信息？从您的报错信息看是输入数据的维度有问题。

您好，非常感谢回答，目前数据维度的问题已解决。有一个新的问题，如果client.predict被多进程调用，是应该使用同一个client还是每次调用都建一个新的client呢？涉不涉及client的回收之类的呢？另外运行程序会输出
E0702 03:33:28.017952 10012 factory.h:183] RAW: Insert duplicate with tag: WeightedRandomRender
I0702 03:33:28.017952 10012 abtest.h:67] RAW: Factory has been registed: WeightedRandomRender->EndpointRouterBase.
E0702 03:33:28.270856 10012 variable.cpp:177] Already exposed general_model_baidu_paddle_serving_predictor_general_model_general_model_service_default_tag_139633810242080_infer_sync_ltc_latency' whose value is 0'
请问这个会有影响吗？不太懂是啥意思，提前感谢回答~

**Comment by TeslaZhao** [comment]
不要每次调用创建client，而是创建一个client数组并与进程绑定，即每个进程内使用唯一的client

**Comment by Karenlyw** [comment]
> 不要每次调用创建client，而是创建一个client数组并与进程绑定，即每个进程内使用唯一的client

好的，我试一下，非常感谢！

**Comment by Karenlyw** [comment]
> 不要每次调用创建client，而是创建一个client数组并与进程绑定，即每个进程内使用唯一的client

想追问下，如果每次调用都创建的话会有什么问题吗

**Comment by TeslaZhao** [comment]
慢
