### ISSUE TITLE
Pipeline Serving 的RPC服务启用GRPC多编程语言支持时，无法使用GPU

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/Serving#1295]
如题，使用 paddle serving的RPC多语言模式部署RPC服务，使用 java调用进行图像预测RPC接口，预测图像的时候不走GPU。

### 测试环境
CUDA 11.2
显卡：RTX 3090
python 3.6.0
paddle-serving-server-gpu==0.6.0.post102
paddle-serving-client==0.6.0
paddle-serving-app==0.6.0
paddlepaddle-gpu==2.1.0

### 测试命令
**服务端**
`python3 -m paddle_serving_server.serve --model yolov4_model --use_multilang --port 9393 --gpu_ids 0`

客户端代码使用
`Serving-0.6.0/java/examples/src/main/java/PaddleServingClientExample.java`

测试调用1次时间超过2s，而使用python直接预测时间小于0.1s
<img width="1105" alt="1" src="https://user-images.githubusercontent.com/26927826/125217795-21afd080-e2f4-11eb-8b5a-e16e901948f3.png">
同时使用nvidia-smi监控gpu占用，未发现对应的python进程
![2](https://user-images.githubusercontent.com/26927826/125217804-270d1b00-e2f4-11eb-8e31-71e814735ddb.png)

**Comment by HexToString** [comment]
分分钟给你修复。

**Comment by HexToString** [comment]
为了不影响您使用，请您在paddle_serving_server的安装路径下，找到server.py文件，直接修改def _prepare_engine函数，在其函数体第一行加上，self.device = device这句话即可。
感谢您对我们框架的支持。给您的使用带来不好的体验，抱歉。
此外，这个问题已经在develop分支修复，下次更新brpc也会有更好的一些性能提升，期待您的使用。

**Comment by ghost** [comment]
@HexToString 
这样修改之后确实是会变成GPU模式启动，但调用还是会出现错误。

Java端会报错client是空指针
<img width="1094" alt="1" src="https://user-images.githubusercontent.com/26927826/125242965-fd69e900-e31f-11eb-9e57-ce3da5a9a125.png">

服务端日志比较有意义：
首先是日志显示使用了GPU
![2](https://user-images.githubusercontent.com/26927826/125243103-3609c280-e320-11eb-80f3-a6ad899ac4fe.png)

其次是服务端会报**超时错误**
![3](https://user-images.githubusercontent.com/26927826/125243215-60f41680-e320-11eb-902b-51a8b638371e.png)

**Comment by ghost** [comment]
@HexToString 
您看这个问题能不能继续解决下？

**Comment by HexToString** [comment]
目测是超时时间设置的问题，第一次预测时间可能会比较慢，而且每台机器可能都不一样，建议
client.set_rpc_timeout_ms(100000)
没准能有惊喜？

**Comment by ghost** [comment]
@HexToString 
还是不行，感觉不像是超时问题，像是RPC的问题，没找到对应的endpoint

Java端设置超时时间
<img width="970" alt="1" src="https://user-images.githubusercontent.com/26927826/125270232-09fc3a80-e33c-11eb-8b8f-8ac6ea223e7b.png">

服务端可以看到超时时间已经设置为新的阈值，但还是会报超时错误
![Snipaste_2021-07-12_18-08-10](https://user-images.githubusercontent.com/26927826/125270386-33b56180-e33c-11eb-973b-03ff9bc08520.png)

**Comment by HexToString** [comment]
所以，您的问题是，使用CPU可以预测，但是使用GPU启动Server后预测不了？

**Comment by ghost** [comment]
我的目的是使用GPU启动Server，然后使用Java通过RPC调用Server预测
 【客户端（java）】-------RPC------【服务端（paddle serving）】
用java的paddle serving client 通过RPC方式调用paddle serving进行服务化封装的模型进行预测，而且预测的模型使用GPU资源。

最开始问题状况是
执行
`python3 -m paddle_serving_server.serve --model yolov4_model --use_multilang --port 9393 --gpu_ids 0`
启动服务端，然后java客户端可以调用，但是服务端的模型未使用GPU资源

然后根据
https://github.com/PaddlePaddle/Serving/issues/1295#issuecomment-877951896
https://github.com/PaddlePaddle/Serving/issues/1295#issuecomment-878118082
修改后，执行
`python3 -m paddle_serving_server.serve --model yolov4_model --use_multilang --port 9393 --gpu_ids 0`
启动服务端，服务端的模型已使用GPU资源，但是java客户端调用服务的时候会出错
结果就是还是不能使用paddle serving预测

**Comment by HexToString** [comment]
我仔细看了下，您需要改的大概是另外一个地方的rpc_timeout_ms
搜索paddle_serving_client的安装目录下的client.py文件，有两处都需要修改一下。
        self.rpc_timeout_ms = 20000，将这句改为1000000

**Comment by wanghyzyyt** [comment]
好，明天早上我试下。

**Comment by HexToString** [comment]
好的，按理说应该是这里的问题，如果还是不行的话，你试一下develop分支。
这个分支不需要你改任何代码即可预测。

**Comment by ghost** [comment]
@HexToString 
参考 https://github.com/PaddlePaddle/Serving/issues/1295#issuecomment-878186742
修改以后，java客户端可以成功调用paddle server端了，是个好消息。

但是仍存在2个问题：
1、paddle_serving_server.serve启动后，java端第一次调用时间很长（4-5分钟）
2、后续调用的时间会变短，但调用时间平均在1s左右
<img width="1006" alt="1" src="https://user-images.githubusercontent.com/26927826/125373229-5173dc80-e3b7-11eb-8a46-6eb3ddf75637.png">
从GPU使用上看，感觉像没有使用GPU，比较奇怪
![2](https://user-images.githubusercontent.com/26927826/125373648-1aea9180-e3b8-11eb-9d16-c3a817d4f9a1.png)


后面我又使用paddle hub serving进行了测试
<img width="956" alt="3" src="https://user-images.githubusercontent.com/26927826/125373683-2e95f800-e3b8-11eb-809c-1dce8758133f.png">
可以看到hub serving每次调用0.1s左右，而且hub的serving是http协议，paddle_serving是grpc，一般来说grpc应该效率更高才对

我也查看了paddle hub serving被调用时gpu使用情况
![4](https://user-images.githubusercontent.com/26927826/125373851-6b61ef00-e3b8-11eb-8c3c-b3aac1ca5f1c.png)
感觉paddle hub serving使用gpu了

**Comment by HexToString** [comment]
感谢您持续的反馈。
您的意见对我而言非常重要，推荐您加我微信，sqzz8899，我们更高效的沟通。

**Comment by HexToString** [comment]
相关问题已单独回复，两者特性不同。
下个版本我们会升级java等其他语言的性能，敬请期待。
