### ISSUE TITLE
v0.6.2按照文档部署pipeline测试的时候卡住了【CPU版】

### ISSUE THREAD

**Issue by learningpro** [PaddlePaddle/Serving#1298]
使用的版本是0.6.2分支，房价预测fit_a_line顺利通过，但是测试pipeline ocr的时候出现问题，启动web_service.py后停在了  start proxy service；启动pipeline_http_client.py 时候无任何输出，挂在了那儿不动了，无法完成测试
![image](https://user-images.githubusercontent.com/1081377/125383797-96553e80-e3ca-11eb-8a92-08d6c620b479.png)

host系统是Mac OS 11.4， docker版本是 docker desktop 3.3.3(64133)，使用的官方镜像 registry.baidubce.com/paddlepaddle/serving:0.6.2-devel，dockerfile中安装了各种相关的包
```
RUN cd /home && git clone -b v0.6.2 https://github.com/PaddlePaddle/Serving
RUN cd /home/Serving && pip3 install -r python/requirements.txt
RUN pip3 install paddle-serving-client==0.6.2 paddle-serving-server==0.6.2 paddle-serving-app==0.6.2
```

**Comment by TeslaZhao** [comment]
您好，您可以查看PipelineServingLogs/pipeline.log.wf 看看是否有错误信息
