### ISSUE TITLE
目标检测 如何实现http请求

### ISSUE THREAD

**Issue by lizhangling1** [PaddlePaddle/Serving#1299]
给予 PaddleDetection 进行的目标检测训练，部署serving，但只找到了通过RPC形式进行测试，请问怎么实现http形式？

尝试用curl:
 curl -H "Content-Type:application/json" -X POST -d '{"feed":[{"image":  "beizi608.jpeg”}], "fetch":["save_infer_model/scale_0.tmp_1"]}' http://127.0.0.1:9292/detection/prediction

抛出错误：
[172.17.0.2:9292][E1002]Fail to find method on `/detection/prediction'

**Comment by bjjwwang** [comment]
https://github.com/PaddlePaddle/Serving/tree/v0.6.0/python/examples/pipeline/PaddleDetection/faster_rcnn
