### ISSUE TITLE
ubuntu18.04 下按照INSTALL.md的说明进行执行报错。

### ISSUE THREAD

**Issue by 707503331** [PaddlePaddle/Serving#13]
**按照INSTALL.md中的说明，执行如下步骤，最后异步最终报错：**
$ git clone https://github.com/PaddlePaddle/serving.git
$ cd serving
$ mkdir build
$ cd build
$ cmake ..
$ make -j4
$ make install

**报错信息如下：**
............................................
[ 48%] Completed 'extern_opencv'
[ 48%] Built target extern_opencv
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by wangguibao** [comment]
这个可能要再找一下具体出错的位置，辛苦您再细细看一下编译日志，找到具体出错的地方，我们看一下。

**Comment by 707503331** [comment]
附件是我的命令窗口缓存的所有数据了，看看能找到线索吗？


------------------ 原始邮件 ------------------
发件人: "Wang Guibao"<notifications@github.com>;
发送时间: 2019年6月25日(星期二) 上午10:33
收件人: "PaddlePaddle/Serving"<Serving@noreply.github.com>;
抄送: "Kevin Bu"<707503331@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [PaddlePaddle/Serving] ubuntu18.04 下按照INSTALL.md的说明进行执行报错。 (#13)




这个可能要再找一下具体出错的位置，辛苦您再细细看一下编译日志，找到具体出错的地方，我们看一下。

**Comment by wangguibao** [comment]
是不是我没找到。。Issue页面上看不到附件

**Comment by luotao1** [comment]
@707503331 请不要用邮件回复，这样附件是看不到的。

**Comment by 707503331** [comment]
issue 上没有找到可添加附件的入口啊？能添加附件吗？




------------------ 原始邮件 ------------------
发件人: "Tao Luo"<notifications@github.com>;
发送时间: 2019年6月25日(星期二) 中午11:07
收件人: "PaddlePaddle/Serving"<Serving@noreply.github.com>;
抄送: "Kevin Bu"<707503331@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [PaddlePaddle/Serving] ubuntu18.04 下按照INSTALL.md的说明进行执行报错。 (#13)




@707503331 请不要用邮件回复，这样附件是看不到的。

**Comment by 707503331** [comment]
有qq吗？我直接发给你附件也行

**Comment by wangguibao** [comment]
可以把输出拷贝出来

**Comment by 707503331** [comment]
日志太长了，超出长度限制了。我选择性的截取有error的日志吧，稍等。

**Comment by 707503331** [comment]
/home/kevin/mytest/projects/paddle/Serving/build/Paddle/third_party/install/glog/include/glog/logging.h:717:32: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
 DEFINE_CHECK_OP_IMPL(Check_EQ, ==)  // Compilation error with CHECK_EQ(NULL, x)?

**Comment by 707503331** [comment]
/home/kevin/mytest/projects/paddle/Serving/build/Paddle/third_party/install/glog/include/glog/logging.h:717:1: note: in expansion of macro ‘DEFINE_CHECK_OP_IMPL’
 DEFINE_CHECK_OP_IMPL(Check_EQ, ==)  // Compilation error with CHECK_EQ(NULL, x)?

**Comment by 707503331** [comment]
/home/kevin/mytest/projects/paddle/Serving/build/Paddle/third_party/install/glog/include/glog/logging.h:717:32: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
 DEFINE_CHECK_OP_IMPL(Check_EQ, ==)  // Compilation error with CHECK_EQ(NULL, x)?
/home/kevin/mytest/projects/paddle/Serving/build/Paddle/third_party/install/protobuf/include/google/protobuf/stubs/port.h:200:53: note: in definition of macro ‘GOOGLE_PREDICT_TRUE’
 #define GOOGLE_PREDICT_TRUE(x) (__builtin_expect(!!(x), 1))
                                                     ^
/home/kevin/mytest/projects/paddle/Serving/build/Paddle/third_party/install/glog/include/glog/logging.h:717:1: note: in expansion of macro ‘DEFINE_CHECK_OP_IMPL’
 DEFINE_CHECK_OP_IMPL(Check_EQ, ==)  // Compilation error with CHECK_EQ(NULL, x)?
 ^~~~~~~~~~~~~~~~~~~~
Scanning dependencies of target build_strategy
[ 39%] Building CXX object paddle/fluid/framework/details/CMakeFiles/build_strategy.dir/build_strategy.cc.o

**Comment by 707503331** [comment]
/usr/bin/ld: cannot find /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/crtn.o: Too many open files
/usr/bin/ld: cannot find /usr/lib/gcc/x86_64-linux-gnu/7/crtoffloadend.o: Too many open files
collect2: error: ld returned 1 exit status
paddle/fluid/inference/CMakeFiles/paddle_fluid_shared.dir/build.make:1142: recipe for target 'paddle/fluid/inference/libpaddle_fluid.so' failed
make[5]: *** [paddle/fluid/inference/libpaddle_fluid.so] Error 1
CMakeFiles/Makefile2:50703: recipe for target 'paddle/fluid/inference/CMakeFiles/paddle_fluid_shared.dir/all' failed
make[4]: *** [paddle/fluid/inference/CMakeFiles/paddle_fluid_shared.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make[3]: *** [all] Error 2

**Comment by 707503331** [comment]
-- Could NOT find PythonLibs (missing: PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS) (Required is exact version "3.6.7")
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
-- Found apache ant 1.10.5: /usr/bin/ant
-- Found JNI: /usr/lib/jvm/default-java/lib/libjawt.so

**Comment by wangguibao** [comment]
```
/usr/bin/ld: cannot find /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/crtn.o: Too many open files
/usr/bin/ld: cannot find /usr/lib/gcc/x86_64-linux-gnu/7/crtoffloadend.o: Too many open files
```
这个地方可能是出错原因，可以用如下命令看一下当前系统允许的最大open file数
```
ulimit -n
```

如有管理员权限可以试着改大一点看看，例如改成10240：
```
ulimit -n 10240
```

**Comment by 707503331** [comment]
python 版本 有要求吗？我用的是Python 2.7.15rc1
上面的错误有提示： Required is exact version "3.6.7"

**Comment by wangguibao** [comment]
```
-- Could NOT find PythonLibs (missing: PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS) (Required is exact version "3.6.7")
```
这个地方说明系统没有安装python，或者没有将PYTHON_LIBRARIES或PYTHON_INCLUDE_DIRS环境变量设好，可以装一下python，然后将对应的路径export到环境变量里，例如：
```
export PYTHON_INCLUDE_DIR=/path/to/python/include/python2.7
export PYTHON_LIBRARY=/path/to/python/lib/libpython2.7.so
```

**Comment by wangguibao** [comment]
> python 版本 有要求吗？我用的是Python 2.7.15rc1
> 上面的错误有提示： Required is exact version "3.6.7"

应该不需要固定版本的python

**Comment by 707503331** [comment]
好的，谢谢！
我想再问一下，用java直接调用 python脚本应该也可以实现 预测功能，并且更简单。
这跟 paddle_serving 有什么区别吗？用 paddle serving 有什么优势吗？




------------------ 原始邮件 ------------------
发件人: "Wang Guibao"<notifications@github.com>;
发送时间: 2019年6月25日(星期二) 中午11:44
收件人: "PaddlePaddle/Serving"<Serving@noreply.github.com>;
抄送: "Kevin Bu"<707503331@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [PaddlePaddle/Serving] ubuntu18.04 下按照INSTALL.md的说明进行执行报错。 (#13)



 
python 版本 有要求吗？我用的是Python 2.7.15rc1
 上面的错误有提示： Required is exact version "3.6.7"
  
应该不需要固定版本的python

**Comment by wangguibao** [comment]
Serving主要是为生产环境大规模部署预测服务用的，类似tensorflow Serving，解决训练后模型的应用部署问题。

如果是小规模预测验证，可以用你说的方法

**Comment by 707503331** [comment]
好的，明白了，谢谢！




------------------ 原始邮件 ------------------
发件人: "Wang Guibao"<notifications@github.com>;
发送时间: 2019年6月25日(星期二) 中午1:05
收件人: "PaddlePaddle/Serving"<Serving@noreply.github.com>;
抄送: "Kevin Bu"<707503331@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [PaddlePaddle/Serving] ubuntu18.04 下按照INSTALL.md的说明进行执行报错。 (#13)




Serving主要是为生产环境大规模部署预测服务用的，类似tensorflow Serving，解决训练后模型的应用部署问题。
 
如果是小规模预测验证，可以用你说的方法

**Comment by 707503331** [comment]
本地python环境问题，再自己研究下，谢谢您的解答，辛苦了！
