### ISSUE TITLE
部署serving的error

### ISSUE THREAD

**Issue by iwnl-chr1s** [PaddlePaddle/Serving#1300]
调用paddle_serving_server.serve时候出现error
可能是miss了哪个步骤吧，无从下手 :( 

![image](https://user-images.githubusercontent.com/56196194/125419110-a3505b26-8078-4a0e-9f46-c02b756b70aa.png)

**Comment by TeslaZhao** [comment]
您好，请补充一下您安装serving的版本，机器环境，模型，服务启动的方法

**Comment by iwnl-chr1s** [comment]
> 您好，请补充一下您安装serving的版本，机器环境，模型，服务启动的方法

测试用例跑出来了！
这个issue，我是从“python”改用“python3” 就没了
后来也出现了跟issue#1265的同样的error，细读底下各位好大哥的讨论，用0.6.2的version就搞定了
“pip3 install paddle-serving-server==0.6.2 paddle-serving-app==0.6.2 paddle-serving-client==0.6.2 -i https://mirrors.aliyun.com/pypi/simple/”
    劳烦了>.<

**Comment by HexToString** [comment]
不客气。
有任何问题，欢迎随时来提问
