### ISSUE TITLE
用docker的方式部署能支持加载多个模型吗？

### ISSUE THREAD

**Issue by Jnoee** [PaddlePaddle/Serving#1301]
用docker的方式部署能支持加载多个模型吗？
怎么做？有没有例子？

**Comment by TeslaZhao** [comment]
不支持单个Serving服务加载多个模型，但可以启动多个Serving服务

**Comment by HexToString** [comment]
支持的，目前有三种做法供您选择
1、如果您使用的Pipeline模式部署，那么目前就支持多模型。只需要修改配置文件即可，见https://github.com/PaddlePaddle/Serving/blob/v0.6.0/python/examples/pipeline/ocr/config.yml
2、如果您使用的是grpc或者http方式，可以通过两次请求，来实现多模型串联，但如您可见，会对性能有一定的影响，如想使用此方式请参考https://github.com/PaddlePaddle/Serving/tree/v0.6.0/python/examples/ocr
该部分的实现方式即是在一个模型的返回处理时启动另外一个服务。
3、目前在develop分支，我们已经支持了Server端直接加载多个模型，该部分功能会在下个版本发布，目前也可以使用，但develop分支会随时合入代码，可能会有不稳定的情况。请参考
https://github.com/PaddlePaddle/Serving/blob/develop/README_CN.md#%E5%BD%93%E6%82%A8%E7%9A%84%E6%9F%90%E4%B8%AA%E6%A8%A1%E5%9E%8B%E6%83%B3%E4%BD%BF%E7%94%A8%E5%A4%9A%E5%BC%A0gpu%E5%8D%A1%E9%83%A8%E7%BD%B2%E6%97%B6
但是，两个模型之间的数据前后处理，需要您在C++Server上自己去实现。
如果模型A的输出不需要经过任何处理直接交给模型B的话，那么您几乎不用改动任何代码。

如果后续有任何使用问题，欢迎继续提问。
感谢您的持续关注，谢谢。

**Comment by Jnoee** [comment]
好的，期待新版本。

**Comment by HexToString** [comment]
好的，感谢您的持续关注，新版本应该很快就会发布，会有性能提升以及整体的一些变化。

**Comment by dwdcth** [comment]
期待，快点发布支持多模型的版本

**Comment by yqp1453552101** [comment]
> 支持的，目前有三种做法供您选择 1、如果您使用的Pipeline模式部署，那么目前就支持多模型。只需要修改配置文件即可，见https://github.com/PaddlePaddle/Serving/blob/v0.6.0/python/examples/pipeline/ocr/config.yml 2、如果您使用的是grpc或者http方式，可以通过两次请求，来实现多模型串联，但如您可见，会对性能有一定的影响，如想使用此方式请参考https://github.com/PaddlePaddle/Serving/tree/v0.6.0/python/examples/ocr 该部分的实现方式即是在一个模型的返回处理时启动另外一个服务。 3、目前在develop分支，我们已经支持了Server端直接加载多个模型，该部分功能会在下个版本发布，目前也可以使用，但develop分支会随时合入代码，可能会有不稳定的情况。请参考 https://github.com/PaddlePaddle/Serving/blob/develop/README_CN.md#%E5%BD%93%E6%82%A8%E7%9A%84%E6%9F%90%E4%B8%AA%E6%A8%A1%E5%9E%8B%E6%83%B3%E4%BD%BF%E7%94%A8%E5%A4%9A%E5%BC%A0gpu%E5%8D%A1%E9%83%A8%E7%BD%B2%E6%97%B6 但是，两个模型之间的数据前后处理，需要您在C++Server上自己去实现。 如果模型A的输出不需要经过任何处理直接交给模型B的话，那么您几乎不用改动任何代码。
> 
> 如果后续有任何使用问题，欢迎继续提问。 感谢您的持续关注，谢谢。

你好，第一种做法应该还是模型串联的做法吧，不支持模型并联吧；
请问第三种方法是指的同时加载多个独立模型吗？目前功能实现了吗
