### ISSUE TITLE
有运行时镜像吗？devel镜像太大了

### ISSUE THREAD

**Issue by Jnoee** [PaddlePaddle/Serving#1302]
带cuda的镜像14G，不带cuda的镜像5.8G。
有没有精简的镜像？只需要支持加载模型运行的最简镜像。

**Comment by bjjwwang** [comment]
有的 https://github.com/PaddlePaddle/Serving/blob/develop/doc/DOCKER_IMAGES.md#attachment-the-list-of-all-the-docker-images 

最下面的表格

**Comment by Jnoee** [comment]
runtime镜像也很大，跟devel没啥差别呀：
registry.baidubce.com/paddlepaddle/serving   0.6.2-cuda11-py38-runtime   600adaa64afa   3 weeks ago    13.7GB
registry.baidubce.com/paddlepaddle/serving   0.6.2-cuda11-cudnn8-devel   f07b3f6d4645   2 months ago   14GB

**Comment by zouxiaoshi** [comment]
> runtime镜像也很大，跟devel没啥差别呀：
> registry.baidubce.com/paddlepaddle/serving 0.6.2-cuda11-py38-runtime 600adaa64afa 3 weeks ago 13.7GB
> registry.baidubce.com/paddlepaddle/serving 0.6.2-cuda11-cudnn8-devel f07b3f6d4645 2 months ago 14GB

自己手动制作镜像吧，参考
https://github.com/PaddlePaddle/Serving/blob/v0.6.0/tools/Dockerfile.runtime_template
把一些必要的都装完了，整完大概11个G.
官方的runtime镜像有很多python版本，可直接先下了个官方runtime镜像，然后再删除多余的python版本。

nvidia 的 base 镜像才不到3个G，希望官方能优化下镜像大小。

**Comment by hbo-lambda** [comment]
确实大，不知该不该继续用了。torchserve是3.7G。官方有没有其他的方案可以 减小镜像体积的
