### ISSUE TITLE
如图，目标检测，模型直接预测没问题，部署成serving，通过rpc访问，返回结果，框偏了

### ISSUE THREAD

**Issue by lizhangling1** [PaddlePaddle/Serving#1307]
![image](https://user-images.githubusercontent.com/55176464/125586930-14342a89-db54-4fe9-95d0-9c2470618a99.png)

**Comment by bjjwwang** [comment]
这个一般得看看 预处理结束 ，预测结束 ，和后处理结束 能否与 本地预测保持一致。
检查顺序是从前到后，一般来说 很可能是前处理的逻辑和本地预测有diff

**Comment by Nick198903** [comment]
解析结果的代码有bug，自己写一个即可

**Comment by TeslaZhao** [comment]
您好，是框架解析结果的代码有问题吗？能否贴一下有问题的代码？

**Comment by Nick198903** [comment]
> 您好，是框架解析结果的代码有问题吗？能否贴一下有问题的代码？

不好意思 调用参数没看清楚，自己又收撸一份，代码没问题
