### ISSUE TITLE
如何导出.proto文件？

### ISSUE THREAD

**Issue by Hengmen** [PaddlePaddle/Serving#1310]
使用https://github.com/PaddlePaddle/Serving/blob/v0.6.0/doc/SAVE_CN.md中的说明
成功保存用于Paddle Serving的模型，已可以正常使用Python客户端与服务端的模型进行通信，得到识别结果。

现希望用C++编写另外的客户端，要求高并发，高效的通信，选择方式使用bRPC进行通信。
bRPC需要.prtot文件进行ProtoBuf编码，但是导出文件中只有.prototxt文件，没有.prtot文件。.prototxt文件中包含的信息少于.prtot文件，我无法从.prototxt文件导出.prtot文件。

我现在的问题是缺少.prtot文件，无法使用bRPC进行通信。

**Comment by HexToString** [comment]
您好，模型中是不包含proto文件的。
我想您可能对两者的概念理解有些偏差。
prototxt其实只是一个模型输入信息的集合，如果你高兴完全可以用txt存储。
而proto是规定了rpc传输的数据交换格式，类似于http通信中的json。
在我们的框架代码中，已经包含了proto，约定好了格式，所以您不需要再定义proto，见
https://github.com/PaddlePaddle/Serving/blob/v0.6.0/core/general-server/proto/general_model_service.proto
另外，目前的python/examples 路径下的大部分示例，其实都是python通过pybind方式调用C++的brpc客户端发起的访问，如果您跑的示例是这个，您大可不必再编写C++ brpc Client，它只是多了一道pybind的调用耗时与数据的拷贝。
当然，如果您想连这个也省去，您可以参考下面这个直接使用C++ brpc Client
https://github.com/PaddlePaddle/Serving/blob/v0.6.0/core/general-client/src/general_model_main.cpp

不知道是否解答了您的疑惑，如有问题，请继续在本帖提问。

**Comment by Hengmen** [comment]
谢谢您的解释，我先理解您提供的网页中的内容。
