### ISSUE TITLE
pipeline serving 方式部署模型是否支持模型加解密

### ISSUE THREAD

**Issue by dianziMAN** [PaddlePaddle/Serving#1313]
我查看了 Serving/python/examples/encryption/ 这个关于模型加解密的例子，请问采用pipeline serving方式部署模型是否支持加解密操作？需要做哪些配置？

**Comment by TeslaZhao** [comment]
您好，Serving/python/examples/encryption/示例展示了通过 运行python encrypt.py实现模型加密。部署方法采用python调起C++ Server并加载已加密模型（python -m paddle_serving_server.serve --model encrypt_server/ --port 9300 --use_encryption_model）。

python pipeline 的local推理方式不支持模型加解密，必须在C++框架下支持模型加解密，python代码加密一直是python语言弱项，通过反汇编工具很轻松地反解出python源码，使用python代码做解密，无法保护模型的安全。

**Comment by TeslaZhao** [comment]
> 我查看了 Serving/python/examples/encryption/ 这个关于模型加解密的例子，请问采用pipeline serving方式部署模型是否支持加解密操作？需要做哪些配置？

在Pipeline模式下可以采用Remote方式访问远端C++ Server，C++ Server中加载加密模型。与local方式推理相比，性能略有下降，但安全性有很好的保证，不知道这种方式是否满足您的需求?

**Comment by dianziMAN** [comment]
> > 我查看了 Serving/python/examples/encryption/ 这个关于模型加解密的例子，请问采用pipeline serving方式部署模型是否支持加解密操作？需要做哪些配置？
> 
> 在Pipeline模式下可以采用Remote方式访问远端C++ Server，C++ Server中加载加密模型。与local方式推理相比，性能略有下降，但安全性有很好的保证，不知道这种方式是否满足您的需求?

我会按照您说的方式多做一些尝试，感谢您的耐心解答。
