### ISSUE TITLE
RTX 6000显卡服务端PP YOLOv2 推演速度

### ISSUE THREAD

**Issue by Nick198903** [PaddlePaddle/Serving#1315]
RTX6000 单卡服务器上布置了Paddle-Serving服务，在开启服务的时候尝试了 --precision fp32、----precision fp16， --precision int8，--use_trt，测试PP yolov2推演（仅推演，不包含预处理+后处理）性能，推演时间都是130ms左右，这有点难以理解，毕竟精度减半，速度应该有较大提升才对，求指点

**Comment by TeslaZhao** [comment]
您好，您使用的Serving版本，推理方式（a.Python WebService, b.Python Pipeline, c.C++ Serving），使用HTTP or RPC方式？

**Comment by Nick198903** [comment]
> 您好，您使用的Serving版本，推理方式（a.Python WebService, b.Python Pipeline, c.C++ Serving），使用HTTP or RPC方式？
你好 我使用的0.6版本，python Web，RPC

**Comment by TeslaZhao** [comment]
使用此方法吗？  https://github.com/PaddlePaddle/Serving/blob/v0.6.0/doc/DESIGN_DOC_CN.md#42-web%E6%9C%8D%E5%8A%A1%E7%A4%BA%E4%BE%8B

**Comment by Nick198903** [comment]
> 使用此方法吗？ https://github.com/PaddlePaddle/Serving/blob/v0.6.0/doc/DESIGN_DOC_CN.md#42-web%E6%9C%8D%E5%8A%A1%E7%A4%BA%E4%BE%8B
你好 我是模仿https://github.com/PaddlePaddle/Serving/blob/v0.6.0/python/examples/detection/ppyolo_r50vd_dcn_1x_coco/README_CN.md
这个进行测试的

**Comment by TeslaZhao** [comment]
在RTX6000 显卡上使用paddle inference单测，测试过推理性能吗？低精度和trt的设置同时要开启--ir_optim，每种--precision fp32、----precision fp16， --precision int8，--use_trt，--ir_optim=True 情况下的的推理时间是大概是多少？

**Comment by Nick198903** [comment]
> 在RTX6000 显卡上使用paddle inference单测，测试过推理性能吗？低精度和trt的设置同时要开启--ir_optim，每种--precision fp32、----precision fp16， --precision int8，--use_trt，--ir_optim=True 情况下的的推理时间是大概是多少？

好的 我测试下

**Comment by Nick198903** [comment]
问题解决 确实是因为没有开启ir_optim的原因， 谢谢

**Comment by TeslaZhao** [comment]
好的
