### ISSUE TITLE
模型部署后占用的GPU显存大小与什么相关？

### ISSUE THREAD

**Issue by zouxiaoshi** [PaddlePaddle/Serving#1316]
感觉显存不太够用，所以想有没有什么办法可以节约GPU显存。

## 环境：
显卡： Tesla P4   Tesla P100
paddle-serving-server-gpu 0.6.1.post102
paddlepaddle-gpu          2.1.0
paddle-serving-client     0.6.1
paddle-serving-app        0.6.1

## 启动方式：
```bash
python -m paddle_serving_server.serve \
--model serving_server \
--thread 2 --port 9000 \
--gpu_ids 0 \
--use_trt \
--precision FP16
```

## 测试如下：  (测试1-3 用的是Tesla P4)
```
测试1： 同一模型架构，不同体积。 model_server, model_mobile(轻量backbone,量化压缩后的模型）
模型                     模型大小                     模型占用GPU显存
model_server            108MB                      2243MB
model_mobile            2.6MB                       2243MB

测试2：不同模型架构，相似体积。
模型                     模型大小                  模型占用GPU显存
model_A                  108MB                       2243MB
model_B                  114MB                      2243MB

测试3： 同一模型，是否启用tensorRT模式 （tensorRT模式下还尝试了不同precision FP32,FP16，GPU显存无变化）
TensorRt                  模型大小              模型占用GPU显存
启用                          108MB                      2243MB
不启用                      108MB                     2243MB

测试4： 不同GPU 同一模型 同一runtime镜像
GPU型号             占用模型大小
Tesla P4                 2243MB
Tesla P100             2405MB
```

SO,
模型占用GPU显存大小倒底与什么有关呢，
如何在不影响性能情况下，减小GPU显存？

**Comment by HexToString** [comment]
首先显存占用大是由于预先在显卡上分配了两个G的数据，之前之所以这么考虑是为了防止由于数据传入导致显存不够时，还需要分配显存，从而影响性能。
解决办法：
修改Serving/paddle_inference/paddle/include/paddle_engine.h文件中
config.EnableUseGpu(2000, FLAGS_gpuid);
将2000改为50。

这只会影响您的第一次预测，显存不够时，会再额外开辟显存。
此时，修改后您需要重新编译，并设置serving_bin环境变量，请参考https://github.com/PaddlePaddle/Serving/blob/v0.6.0/doc/COMPILE_CN.md

在即将到来的新版本中，我们会默认将显存改小。

**Comment by zouxiaoshi** [comment]
> 首先显存占用大是由于预先在显卡上分配了两个G的数据，之前之所以这么考虑是为了防止由于数据传入导致显存不够时，还需要分配显存，从而影响性能。
> 解决办法：
> 修改Serving/paddle_inference/paddle/include/paddle_engine.h文件中
> config.EnableUseGpu(2000, FLAGS_gpuid);
> 将2000改为50。
> 
> 这只会影响您的第一次预测，显存不够时，会再额外开辟显存。
> 此时，修改后您需要重新编译，并设置serving_bin环境变量，请参考https://github.com/PaddlePaddle/Serving/blob/v0.6.0/doc/COMPILE_CN.md
> 
> 在即将到来的新版本中，我们会默认将显存改小。

非常感谢。
打扰再提一点想法。
可否将GPU显存占用大小变为启动模型时的参数，分为三档：
1. 像现在2GB那样，系统设置默认大小
2. 占用最小显存，后续动态分配
3. 人工设置显存占用大小

GPU资源比较紧缺，希望能更灵活配置GPU资源。多谢。

**Comment by HexToString** [comment]
您的建议非常好。
我们会考虑您的建议。
