### ISSUE TITLE
OCR pipeline server 显存限制问题

### ISSUE THREAD

**Issue by Jeffrey98-AI** [PaddlePaddle/Serving#1317]
paddle ocr pipeline server传入比较大的图像的时候会报下面的错误，测试小图像的base64传入却是正常的，大图分辨率1068*6118

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1626861998 (unix time) try "date -d @1626861998" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 12224 (TID 0x7fdadb87b700) from PID 0 ***]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
软件版本：
paddle-serving-app        0.6.0
paddle-serving-client     0.6.0
paddle-serving-server-gpu 0.6.0.post102
paddlepaddle-gpu          2.1.0

调试了一下，发现与图像分辨率没什么关系，OCR 检测OP是没问题的，识别OP里面预处理也没问题，没有运行到后处理那一步，应该是在识别的预测阶段出错，与文本行数有关，33行以下就没问题，超过33行就会出现上面的错误

**Comment by HexToString** [comment]
为了尽快复现您的问题，请您提供一下您的版本信息。
以及跑的是什么模型，图片大小大概是多大？

**Comment by HexToString** [comment]
好的，我们会尽快复现。
也推荐你使用gdb调试一下，看看到底是哪里报错。
如果您自己解决了问题，也麻烦请您分享一下您的经验，能够帮助到更多的人。

**Comment by TeslaZhao** [comment]
GLOG_v=3 python3 web_service.py，您好，使用GLOG_v=3 启动服务，会打印出更多的报错信息。另外，您使用的是GPU推理吗，观察一下显存的变化，在大图的时候显存使用率到多少？

**Comment by Jeffrey98-AI** [comment]
> GLOG_v=3 python3 web_service.py，您好，使用GLOG_v=3 启动服务，会打印出更多的报错信息。另外，您使用的是GPU推理吗，观察一下显存的变化，在大图的时候显存使用率到多少？
![微信图片_20210723120059](https://user-images.githubusercontent.com/18739799/126736078-4aa8d32f-c0c5-44aa-bc1e-9721ff837909.png)
图像一般50多行，1000字左右，测试4卡V100 GPU 最大并发12

**Comment by TeslaZhao** [comment]
GLOG_v=3 在出现core dump过程的日志打印有变化吗？

**Comment by Jeffrey98-AI** [comment]
> 好的，我们会尽快复现。
> 也推荐你使用gdb调试一下，看看到底是哪里报错。
> 如果您自己解决了问题，也麻烦请您分享一下您的经验，能够帮助到更多的人。

问题出现在识别里面的minibatch batch size 大小的设置，web_service.py 里面 max_batch_size 这个参数我直接给了一个比较大的值，没有拆分minibatch，我这一张图50行左右直接合成一个batch，这样单个batch的文本行数就会比较大，出现上面那个错误，拆分minibatch 之后就没有这个问题了。

**Comment by Jeffrey98-AI** [comment]
> GLOG_v=3 在出现core dump过程的日志打印有变化吗？

I0723 06:38:20.467614 46914 conv_cudnn_op.cu:96] Compute ConvOp with cuDNN: data_format=NCHW compute_format=NCHW
I0723 06:38:20.468361 46914 conv_cudnn_helper.h:249] Fallback to non-v7 method to find conv algorithm becasue the workspace size request(802160640) exceeds the limit(536870912)

---------------------------------
在那个C++ Traceback 错误附近发现了这个日志打印输出，这应该是做了什么限制吧？

**Comment by HexToString** [comment]
首先，恭喜您破案了。
这是C++ 端有一个数据传输的最大限制，默认的最大单次传输数据量限制为512MB。
如果您是通过命令行启动，您可以通过命令行参数，--max_body_size 来指定（单位为Bytes）
或者您可以直接修改paddle-serving-server安装目录下的serve.py文件中的
default=512 * 1024 * 1024,
这一行。

感谢您提供的宝贵信息，我们会在修复这个不太合理的大小限制设定。

**Comment by Jeffrey98-AI** [comment]
> 首先，恭喜您破案了。
> 这是C++ 端有一个数据传输的最大限制，默认的最大单次传输数据量限制为512MB。
> 如果您是通过命令行启动，您可以通过命令行参数，--max_body_size 来指定（单位为Bytes）
> 或者您可以直接修改paddle-serving-server安装目录下的serve.py文件中的
> default=512 * 1024 * 1024,
> 这一行。
> 
> 感谢您提供的宝贵信息，我们会在修复这个不太合理的大小限制设定。

--------------------------------------------------
按照提到的两种方式去改 max_body_size 这个参数都没用，实际运行时还是512x1024x1024

**Comment by HexToString** [comment]
serve.py和server.py文件中应该都有这个设定，最终这个大小，是在您的终端命令行中会出现 --max_body_size 您需要观察一下，这个是否是您设定的值。
或者您直接命令行传入这个参数的具体数值也是可以的。
下个版本我们会修复这个问题，给您的使用带来了不便，非常抱歉。
感谢您的持续关注。

**Comment by HexToString** [comment]
经过核查，您是对的。
我们的程序代码在两个地方(Client端和Server)分别设置了该参数，所以您修改后仍无效。
如果您需要立即修改，请修改
修改paddle-serving-client安装目录下的client.py文件中的
os.environ["FLAGS_max_body_size"] = str(512 * 1024 * 1024)
或者在Client端，设置环境变量export FLAGS_max_body_size=您想要的大小。
加上上面Server端的修改，此时则不会出现问题。

非常感谢您提供的宝贵信息。

**Comment by Jeffrey98-AI** [comment]
> 经过核查，您是对的。
> 我们的程序代码在两个地方(Client端和Server)分别设置了该参数，所以您修改后仍无效。
> 如果您需要立即修改，请修改
> 修改paddle-serving-client安装目录下的client.py文件中的
> os.environ["FLAGS_max_body_size"] = str(512 * 1024 * 1024)
> 或者在Client端，设置环境变量export FLAGS_max_body_size=您想要的大小。
> 加上上面Server端的修改，此时则不会出现问题。
> 
> 非常感谢您提供的宝贵信息。

--------------------------------------------------------------
安装目录下的 serve.py client.py 都改了，仍然无效。
在小图预测文本检测阶段竟然也出现了 Fallback to non-v7 method to find conv algorithm becasue the workspace size request(562888704) exceeds the limit(536870912) 这种错误，图像DetOP 预处理后维度 (1,3,160,608) ，然而把图像拓展到两张（2,3,160,608）却是正常的,（1,3,1068,6118)这么大的图检测OP都不会超出500M的显存限制，(1,3,160,608)这种小图的检测却超出了500M ，检测的server模型由https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_server_v2.0_det_infer.tar 推理模型转换得到。

**Comment by HexToString** [comment]
已经给您在别的帖子回复，这是由于GRPC->BRPC有两层RPC都限制了大小导致的。
之前给您的，是修改BRPC的，因为看到您的报错信息都是在C++端。
但是可能您的GRPC端也会存在大小的限制问题。
另外推荐您使用Pipeline+local的方式，会比这种GRPC-->BRPC 的方式快。
或者您可以直接使用C++串联OCR模型。但两个模型之间的前后处理可能需要您自己根据需求在原有代码基础上修改。
