### ISSUE TITLE
Jetson

### ISSUE THREAD

**Issue by Sqhttwl** [PaddlePaddle/Serving#1322]
请问Serving0.6.0在jetson平台使用，直接pip或者docket pull就可以，还是需要进行其他环境方面的编译。

**Comment by zhangjun** [comment]
> 请问Serving0.6.0在jetson平台使用，直接pip或者docket pull就可以，还是需要进行其他环境方面的编译。

目前serving不支持jetson平台部署。建议使用预测库方式部署，参见https://paddleinference.paddlepaddle.org.cn/demo_tutorial/cuda_jetson_demo.html。

也可以使用从[paddle linux预测库](https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html)下载安装python 预测库，并使用serving WebService localpredict部署方式。
