### ISSUE TITLE
加载优化器参数文件后报错conv2d_2.w_0_moment1_0 should in state dict

### ISSUE THREAD

**Issue by Tears1997** [PaddlePaddle/Serving#1323]
如题，在一个.py文件中训练模型并保存模型和优化器参数文件后，执行另一个训练方法（使用相同的模型类创建的对象，保证模型结构没有更改，也保证不存在中文路径加载错误问题），使用opt.set_state_dict(opt_dict)加载刚才保存的优化器参数文件会报错AssertionError: Optimizer set error, conv2d_2.w_0_moment1_0 should in state dict。

但是奇怪的是，如果先执行训练保存优化器参数文件，然后停止运行，然后把前面的训练部分注释掉，而直接执行加载优化器参数文件后进行训练，则一切正常。不知道是什么情况。无论是在aistudio还是本地pycharm运行都存在这个问题。

另外，这个教程页面的代码就存在这个问题：https://www.paddlepaddle.org.cn/tutorials/projectdetail/1516118

在上面的链接【10 【手写数字识别】之动转静部署】这个教程中一共有三个cell，若从头到尾执行所有cell，就会以100%的概率复现该问题。然后接着点击【代码执行器 -> 重启执行器】，重启执行器后，先执行定义网络结构的那个cell（即第一个cell），再执行加载参数文件并训练的cell（即最后一个cell），就一切正常不会报错。不知是什么原因.

另外，如果从头到尾连续执行三个cell后，再多次点击执行最后的一个cell，每次点击后观察报错信息，会发现每次报的错误不一样，具体是AssertionError: Optimizer set error, conv2d_【X】.w_0_moment1_0 should in state dict这行报错信息中【X】的位置第一次是2，接下里每次执行都会加2，分别变成4、6、8、10、12....

**Comment by TeslaZhao** [comment]
您好，训练/模型加载相关的问题建议到 paddle(https://github.com/PaddlePaddle/Paddle) 提issue。
