### ISSUE TITLE
训练好的transformer翻译模型部署到服务器不能预测

### ISSUE THREAD

**Issue by dlkht** [PaddlePaddle/Serving#1326]
1. 按照https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/machine_translation/transformer操作训练，可以在本地电脑python环境预测模型，结果可以。
2. 但按照https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/machine_translation/transformer/deploy/serving说明部署后，不能预测，客户端返回提示failed call predictor with req: insts { tensor_array { int64_data: 36 int64_data: 19 int64_data: 37 int64_data:。。。。}
3. 部署环境：paddlepaddle-gpu==2.1.1.post102, paddle-server-gpu==0.6.2,  paddle-server-app==0.6.2,
   没有安装tensorRT.

**Comment by TeslaZhao** [comment]
您好，服务端启动正常吗，有没有报错信息？

**Comment by dlkht** [comment]
> 您好，服务端启动正常吗，有没有报错信息？
有，提示如下信息，改用paddle_serving_serve_gpu==0.5.0后就可以正确预测了，是不是0.6.2版本必须要安装tensorRT?
“/usr/local/python3.7.0/lib/python3.7/site-packages/paddle_serving_server/serving-gpu-102-0.6.2/serving: error while loading shared libraries: libnvinfer.so.7: cannot open shared object file: No such file or directory”

**Comment by TeslaZhao** [comment]
https://github.com/PaddlePaddle/Serving/blob/v0.6.0/doc/FAQ.md#q-libnvinferso-cannot-open-shared-object-file-no-such-file-or-directory

**Comment by dlkht** [comment]
> https://github.com/PaddlePaddle/Serving/blob/v0.6.0/doc/FAQ.md#q-libnvinferso-cannot-open-shared-object-file-no-such-file-or-directory

好的，谢谢！我将缺少的SO都拷贝到相应路径下了，但最后还是提示缺少文件：/usr/local/python3.7.0/lib/python3.7/site-packages/paddle_serving_server/serving-gpu-102-0.6.2/serving: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /usr/local/python3.7.0/lib/python3.7/site-packages/paddle_serving_server/serving-gpu-102-0.6.2/libnvinfer.so.7)
文件libm.so.6: version `GLIBC_2.27'在哪里找得到？

**Comment by TeslaZhao** [comment]
如果在原生linux的glibc的版本和依赖的glibc版本不匹配，解决方法：
1.推荐使用docker环境安装Serving
2.安装glibc_2_27，https://blog.csdn.net/qq_39503880/article/details/110277422

**Comment by dlkht** [comment]
谢谢！

**Comment by dlkht** [comment]
现在能正常预测了
还有一个疑问，服务端安装不带tensorRT的server(版本0.5.0），其预测速度要比带TensorRT的版本（0.6.2)要快一些，这是什么原因呢？不是用了tensorRT更快吗？

**Comment by TeslaZhao** [comment]
您使用了哪些优化选项，2个版本的平均延时是多少？

**Comment by dlkht** [comment]
谢谢!应该是没使能tensorrt,我到nlp哪里提个issue

**Comment by TeslaZhao** [comment]
开启tensorrt需要同步开启ir_optim
