### ISSUE TITLE
Error response from daemon: Get https://registry.baidubce.com/v2/: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by Andy546** [PaddlePaddle/Serving#1327]
[黄埔学院]
系统：Centos 7
PaddlePaddle-gpu: 2.1.0
问题1. 在拉取Paddle Serving镜像时一直失败
使用命令：nvidia-docker pull registry.baidubce.com/paddlepaddle/serving:0.6.0-cuda10.2-cudnn8-devel
报错如下：
<img width="1163" alt="截屏2021-07-29 09 49 55" src="https://user-images.githubusercontent.com/10570127/127420851-5a62ae30-cf56-4161-89bf-ec8894f26e36.png">
问题2. cudnn我使用的是7，但是镜像里没有cuda10.2与cudnn7的组合，这样会有问题吗

**Comment by TeslaZhao** [comment]
nvidia-docker pull registry.baidubce.com/paddlepaddle/serving:0.6.0-cuda10.2-cudnn8-devel  -i https://pypi.tuna.tsinghua.edu.cn/simple

**Comment by Andy546** [comment]
> nvidia-docker pull registry.baidubce.com/paddlepaddle/serving:0.6.0-cuda10.2-cudnn8-devel -i https://pypi.tuna.tsinghua.edu.cn/simple

docker有-i 这个参数吗

**Comment by TeslaZhao** [comment]
抱歉，-i是pip 的命令，你遇到的问题参考下面链接。

https://stackoverflow.com/questions/50768317/docker-pull-certificate-signed-by-unknown-authority

**Comment by Andy546** [comment]
> 抱歉，-i是pip 的命令，你遇到的问题参考下面链接。
> 
> https://stackoverflow.com/questions/50768317/docker-pull-certificate-signed-by-unknown-authority

你好，目前找到原因了是内网代理限制
