### ISSUE TITLE
使用yolov4例子报错

### ISSUE THREAD

**Issue by Andy546** [PaddlePaddle/Serving#1328]
环境：
docker PaddleServing serving:0.6.0-cuda10.2-cudnn8-devel
在镜像内安装了
paddle-serving-app        0.6.0
paddle-serving-client     0.6.0
paddle-serving-server-gpu 0.6.0.post102
paddlepaddle-gpu          2.1.0
运行examples/yolov4例子时一直报错TypeError: 'NoneType' object does not support item assignment
<img width="602" alt="截屏2021-07-30 09 09 47" src="https://user-images.githubusercontent.com/10570127/127585329-72be2708-28a5-45b9-af77-693af0a31f0b.png">

**Comment by TeslaZhao** [comment]
fetch_map是none，结果没有返回，您使用python webservice、python pipeline、C++ Serving中哪种部署方式？

**Comment by Andy546** [comment]
使用的是github这个目录里的步骤
[https://github.com/PaddlePaddle/Serving/tree/v0.5.0/python/examples/yolov4](url)

**Comment by TeslaZhao** [comment]
您已经安装了0.6.0的版本，代码示例也使用v0.6.0的代码示例。https://github.com/PaddlePaddle/Serving/tree/v0.6.0/python/examples/yolov4

另外，服务启动后，检查一下服务启动是否正常？发送请求后，是否有报错信息？

**Comment by Andy546** [comment]
> 您已经安装了0.6.0的版本，代码示例也使用v0.6.0的代码示例。https://github.com/PaddlePaddle/Serving/tree/v0.6.0/python/examples/yolov4
> 
> 另外，服务启动后，检查一下服务启动是否正常？发送请求后，是否有报错信息？

请求没有报错信息，就是一直不通，不知道为啥.....

**Comment by TeslaZhao** [comment]
![image](https://user-images.githubusercontent.com/6309021/127611159-07938010-d6e7-485b-96af-5b2bdf777808.png)
服务端启动截图

![image](https://user-images.githubusercontent.com/6309021/127611218-1fdb0e53-543d-4354-a172-c0bfd49e1250.png)
client启动截图

output目录下结果
![image](https://user-images.githubusercontent.com/6309021/127611285-90c3e1d0-0361-44f6-a2aa-564360f0e90b.png)

**Comment by TeslaZhao** [comment]
您看一下服务端启动后效果是否一致？

**Comment by Andy546** [comment]
> 您看一下服务端启动后效果是否一致？

OK了，是端口号设置的问题。还有个问题请教下，如果自己训练的PaddleDetection模型用的是yolov3_mobilenet_v3_large_ssld_270e_voc.yml配置文件，参考的部署是
[https://github.com/PaddlePaddle/Serving/tree/v0.6.0/python/examples/pipeline/PaddleDetection/yolov3](url)
问题如下：
1. config.xml为什么要配置两个port，如果docker部署的话，这两个端口号是不是都要做端口映射
2. config.xml是不是要自己配置啊，export_model.py生成Serving模型后没有config.xml文件
谢谢

**Comment by TeslaZhao** [comment]
1.两个port 分别是rpc_port 和http_port，即启动一个服务会同时处理rpc和http请求。docker部署需要做端口映射
2.config.yml需要手动配置，可以参考下面示例，只需要修改op相关的参数即可。
https://github.com/PaddlePaddle/Serving/blob/v0.6.0/python/examples/pipeline/simple_web_service/config.yml

**Comment by Andy546** [comment]
> 1.两个port 分别是rpc_port 和http_port，即启动一个服务会同时处理rpc和http请求。docker部署需要做端口映射
> 2.config.yml需要手动配置，可以参考下面示例，只需要修改op相关的参数即可。
> https://github.com/PaddlePaddle/Serving/blob/v0.6.0/python/examples/pipeline/simple_web_service/config.yml

好的，谢谢，我试一下
