### ISSUE TITLE
关于热更新的问题

### ISSUE THREAD

**Issue by Karenlyw** [PaddlePaddle/Serving#1331]
您好，我想请问如果不用monitor服务，直接替换serving_server中的模型文件，不重启server服务的话可以实现模型热更新吗？

**Comment by TeslaZhao** [comment]
不能

**Comment by Karenlyw** [comment]
> 不能

使用general monitor访问远程训练服务器 报错failed: Connection refused.请问这个是为什么呢？远程访问是否有默认端口呢？
