### ISSUE TITLE
Serving 是否支持TTS流式合成这种任务？

### ISSUE THREAD

**Issue by youngstu** [PaddlePaddle/Serving#1332]
Serving 是否支持TTS流式合成这种任务？

**Comment by TeslaZhao** [comment]
您好，PaddleServing目前不支持TTS流式，我们正在收集相关的需求，待需求明确和方案调研完成可加入开发任务队列中。您可以具体说一下您的业务场景，使用场景，同类的Serving服务支持TTS的情况，或示例等？这将有助于我们了解业务需求。

**Comment by youngstu** [comment]
您好，描述如下：


1、业务和使用场景
我们业务场景是实时播报场景，为了降低播报延迟，需要tts支持流式合成。调研了一下发现市场上TTS基本都是流式的（包括百度、讯飞、微软等）。

2、问题
1）PaddleServing 仅支持tts非流式合成（http协议）？
2）PaddleServing 支持流式tts这种任务（websocket协议）需要做哪些支持，是否有支持计划？
3）PaddleServing 增加TTS这种流式合成任务支持，在算法层是否需要做一些开发？

**Comment by TeslaZhao** [comment]
非流式TTS，使用http协议，模型服务是无状态的，理论上PaddleServing上可以直接部署的。目前TTS模型没有部署测试过。

流式TTS，使用websocket协议，一般会采用Nginx做反向代理和SSL校验，upstream为ws-proxy能hold住长连接，并进行协议转换，转成rpc/stream等，再交给模型推理服务进行处理。整套服务架构非常复杂的，对PaddleServing而言，定位接收rpc/stream做模型服务化部署，Nginx + ws-proxy工作不会参与。

支持流式TTS需要的工作非常多，支持stearm协议，在异步流水线调度增加数据流的控制策略等，需要详细调研和工程设计，预计在Q4开发完成。

**Comment by yt605155624** [comment]
mark

**Comment by yt605155624** [comment]
算法层面，不考虑文本前端耗时，要达到实时的效果，声学模型和声码器要选择非自回归的模型（如，fastspeech系列和 GAN/FLOW based vocoder），如果您的所说的online模型要求输入一个字就合成一个字，那就需要声学模型本身对短文本的处理能力强（丧失gst的前提下也能做好），感觉目前能做的比较好的就是fastspeech2了，同时可能要要求您输入的文本是正则化以后的，最好直接是音素（因为文本正则，多音字预测要考虑上下文信息）。
ps, paddle 有提供 TTS 套件，欢迎关注https://github.com/PaddlePaddle/Parakeet

**Comment by youngstu** [comment]
paddle/Serving 是否支持torchscript、tflite模型云端部署呢？现在流式TTS支持开发进度如何呢？

**Comment by TeslaZhao** [comment]
> paddle/Serving 是否支持torchscript、tflite模型云端部署呢？现在流式TTS支持开发进度如何呢？

不直接支持上述2种模型，可以使用x2paddle工具，将模型转成paddle模型并部署。
流式TTS功能已排在v0.8版本中，预计在11月或12月开发，我们即将发布v0.7版本

**Comment by youngstu** [comment]
0.8版本预计什么时间发布呢？或者支持流式TTS功能什么时间发布呢？

**Comment by youngstu** [comment]
和pytorch Serve和Tensorflow Serving 相比有什么优势呢？

**Comment by TeslaZhao** [comment]
v0.8版本预计在1月中下旬发布
