### ISSUE TITLE
docker 部署两个服务报错

### ISSUE THREAD

**Issue by Andy546** [PaddlePaddle/Serving#1333]
[黄埔学院]
docker部署了两个服务（文字检测和文字识别），但是有冲突，启动一个后另一个会无法启动或者直接被kill。
环境
python 3.7.11
paddle-serving-app                0.6.0
paddle-serving-client             0.6.0
paddle-serving-server             0.6.0
paddle2onnx                       0.7
paddlehub                         2.1.0
paddlenlp                         2.0.7
paddlepaddle                      2.1.0

文字检测参考：[https://github.com/PaddlePaddle/Serving/tree/v0.6.0/python/examples/pipeline/PaddleDetection/yolov3](url)
文字识别使用的是PaddleHub启动，参考 [https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.2/deploy/hubserving/readme.md](url)
问题1. 先启动文字检测服务(Paddle Serving)后，PaddleHub无法启动，启动直接kill
paddlehub被kill
![image](https://user-images.githubusercontent.com/10570127/128106236-6f5693ae-b38e-4ef4-8fb9-3dd52d298bc2.png)
启动PaddleHub时Paddle Serving 如下输出
<img width="1186" alt="截屏2021-08-04 09 16 51" src="https://user-images.githubusercontent.com/10570127/128106841-30f92ced-ecdf-4361-bf18-074efbee22d8.png">
问题2. 先启动文字识别服务(Paddle hub)，再启动文字识别服务，PaddleHub也直接被kill
<img width="1751" alt="截屏2021-08-04 09 22 14" src="https://user-images.githubusercontent.com/10570127/128106943-94d8016b-e894-40ef-b2ca-c02d1935db7a.png">

**Comment by bjjwwang** [comment]
问题1有个疑问 两个端口一样吗
问题2 我其实没看懂 “问题2. 先启动文字识别服务(Paddle hub)，再启动文字识别服务，PaddleHub也直接被kill” 是不是哪个地方描述的不对。

**Comment by Andy546** [comment]
> 问题1有个疑问 两个端口一样吗
> 问题2 我其实没看懂 “问题2. 先启动文字识别服务(Paddle hub)，再启动文字识别服务，PaddleHub也直接被kill” 是不是哪个地方描述的不对。

两个端口不一样，问题2写错了，先启动文字识别服务(Paddle hub)，再启动文字检测服务(Paddle Serving)

**Comment by Andy546** [comment]
目前来看可能是因为容器占用资源过多，内存或者cpu，换个好点的服务器可以了。还有个问题请教下，如果自己构建CPU版的Paddle Serving镜像的话用哪个dockerfile？
我看了下Dockerfile.devel文件里用的是FROM hub.baidubce.com/ctr/cuda:9.0-cudnn7-devel-ubuntu16.04，这不也是GPU版的吗？

**Comment by bjjwwang** [comment]
> 目前来看可能是因为容器占用资源过多，内存或者cpu，换个好点的服务器可以了。还有个问题请教下，如果自己构建CPU版的Paddle Serving镜像的话用哪个dockerfile？
> 我看了下Dockerfile.devel文件里用的是FROM hub.baidubce.com/ctr/cuda:9.0-cudnn7-devel-ubuntu16.04，这不也是GPU版的吗？

不好意思 才看到。
是的，目前这个是跟随Paddle那边一起给的，所以CPU也沿用cuda9的镜像作为base。

**Comment by Andy546** [comment]
> > 目前来看可能是因为容器占用资源过多，内存或者cpu，换个好点的服务器可以了。还有个问题请教下，如果自己构建CPU版的Paddle Serving镜像的话用哪个dockerfile？
> > 我看了下Dockerfile.devel文件里用的是FROM hub.baidubce.com/ctr/cuda:9.0-cudnn7-devel-ubuntu16.04，这不也是GPU版的吗？
> 
> 不好意思 才看到。
> 是的，目前这个是跟随Paddle那边一起给的，所以CPU也沿用cuda9的镜像作为base。
你好，我在使用 [https://github.com/PaddlePaddle/Serving/blob/v0.6.0/tools/Dockerfile.devel](url)进行构建时，一直无法成功，报错如下，请问你们可以构建成功吗？
<img width="1752" alt="截屏2021-08-05 21 57 47" src="https://user-images.githubusercontent.com/10570127/128438680-c0e1ef82-7ce2-4296-8e89-0a1c9c8b5190.png">

**Comment by Andy546** [comment]
> > 目前来看可能是因为容器占用资源过多，内存或者cpu，换个好点的服务器可以了。还有个问题请教下，如果自己构建CPU版的Paddle Serving镜像的话用哪个dockerfile？
> > 我看了下Dockerfile.devel文件里用的是FROM hub.baidubce.com/ctr/cuda:9.0-cudnn7-devel-ubuntu16.04，这不也是GPU版的吗？
> 
> 不好意思 才看到。
> 是的，目前这个是跟随Paddle那边一起给的，所以CPU也沿用cuda9的镜像作为base。


你好，我在使用 [https://github.com/PaddlePaddle/Serving/blob/v0.6.0/tools/Dockerfile.devel](https://github.com/PaddlePaddle/Serving/blob/v0.6.0/tools/Dockerfile.devel) 进行构建时，一直无法成功，报错如下，请问你们可以构建成功吗？
<img width="1752" alt="截屏2021-08-05 21 57 47" src="https://user-images.githubusercontent.com/10570127/128438803-bb42bbfb-a36f-4eba-8d13-b73ce204825c.png">

**Comment by Andy546** [comment]
[黄埔学院]
在安装gcc的时候报错
<img width="1747" alt="截屏2021-08-06 10 42 10" src="https://user-images.githubusercontent.com/10570127/128448046-727282a9-5687-4b8e-a45f-f8b6f1f09fc3.png">

**Comment by bjjwwang** [comment]
当时是成功的，安装GCC 8.2非常的久，我在后台跑一次看看

**Comment by Andy546** [comment]
> 当时是成功的，安装GCC 8.2非常的久，我在后台跑一次看看

好的，谢谢，一直卡在GCC8.2安装失败这

**Comment by Andy546** [comment]
> 当时是成功的，安装GCC 8.2非常的久，我在后台跑一次看看

你好，请问下你那可以跑成功吗？

**Comment by bjjwwang** [comment]
> > 当时是成功的，安装GCC 8.2非常的久，我在后台跑一次看看
> 
> 你好，请问下你那可以跑成功吗？

我这里是成功的

**Comment by bjjwwang** [comment]
方便发一下命令吗
docker build 那个

**Comment by Andy546** [comment]
> 方便发一下命令吗
> docker build 那个

使用的dockerfile是 [https://github.com/PaddlePaddle/Serving/blob/v0.6.0/tools/Dockerfile.devel](url)，我重命名为Dockerfile。构建命令是
`docker build -t paddleserving:v0.1 .`
Dockerfile里需要COPY的文件已经在Dockerfile同目录下准备好了。

**Comment by bjjwwang** [comment]
哦哦 因为有相对路径的原因，最好是 docker build -f tools/Dockerfile.devel -t paddleserving:v0.1 .

**Comment by Andy546** [comment]
> 哦哦 因为有相对路径的原因，最好是 docker build -f tools/Dockerfile.devel -t paddleserving:v0.1 .

这块问题好像不是在路径这，好像是在安装GCC 8.2时报错

**Comment by bjjwwang** [comment]
> 这块问题好像不是在路径这，好像是在安装GCC 8.2时报错

可以看下dockerfile里面的COPY命令，有些依赖的文件也要确保都在。
很可能前面的一些问题导致gcc82没编过去。

**Comment by Andy546** [comment]
> > 这块问题好像不是在路径这，好像是在安装GCC 8.2时报错
> 
> 可以看下dockerfile里面的COPY命令，有些依赖的文件也要确保都在。
> 很可能前面的一些问题导致gcc82没编过去。

好的，我再检查检查，谢谢

**Comment by Andy546** [comment]
> > 这块问题好像不是在路径这，好像是在安装GCC 8.2时报错
> 
> 可以看下dockerfile里面的COPY命令，有些依赖的文件也要确保都在。
> 很可能前面的一些问题导致gcc82没编过去。

你好，还是有同样的问题。本机环境需要装GCC吗？Dockerfile里的基础镜像hub.baidubce.com/ctr/cuda:9.0-cudnn7-devel-ubuntu16.04镜像是不是缺东西啊？

**Comment by TeslaZhao** [comment]
您好，您是以 PaddleServing的 Dockerfile 作为base 制作新的docker 镜像吗？

**Comment by Andy546** [comment]
是啊，Dockerfile一点也没改
