### ISSUE TITLE
自定义sdk借用paddle-serving部署

### ISSUE THREAD

**Issue by 77h2l** [PaddlePaddle/Serving#1334]
假设我现在有一个自己的sdk,想借助paddle-serving 部署简单的服务，需要怎么操作？

**Comment by TeslaZhao** [comment]
sdk是指？

**Comment by 77h2l** [comment]
> sdk是指？

比如将paddleocr通过封装工程接口的形式，封装成sdk后，怎么快速通用的通过paddle-serving来部署服务（不通过paddle-ocr部署demo里面修改内部代码的方式）？

**Comment by TeslaZhao** [comment]
Paddle Serving一定需要用到Paddle OCR的模型，这部分和SDK无关。

可以使用Python Pipeline方式，OCR模型的前后处理通过sdk接口来解析？
