### ISSUE TITLE
pipeline 模式启动server 无法添加类似命令行启动的参数

### ISSUE THREAD

**Issue by Jeffrey98-AI** [PaddlePaddle/Serving#1343]
命令行启动 server 实际是运行如下的命令：
/usr/local/lib/python3.6/site-packages/paddle_serving_server/serving-gpu-102-0.6.0/serving -enable_model_toolkit -inferservice_path workdir_0 -inferservice_file infer_service.prototxt -max_concurrency 0 -num_threads 2 -port 12000 -precision fp32 -use_calib False -reload_interval_s 10 -resource_path workdir_0 -resource_file resource.prototxt -workflow_path workdir_0 -workflow_file workflow.prototxt -bthread_concurrency 2 -gpuid 0 -max_body_size 1073741824 

pipeline模式启动 server 并非如此，pipeline 模式如何添加 --max_body_size 参数

**Comment by HexToString** [comment]
您好，由于我们工作的疏忽。并未在pipeline模式下，开发设置该参数的接口。
您可以按照以下步骤去修改：
1、pip3.6 show paddle-serving-server
2、到安装目录下，一般是位于Location: /usr/local/lib/python3.6/site-packages/paddle_serving_server/
3、修改此目录下的 pipeline/pipeline_server.py  和 pipeline/pipeline_client.py文件
4、修改其中max_receive_message_length 和 max_send_message_length字段，单位是字节。一般是512*1024*1024,表示512M，您可以根据自己的需要修改。

下个版本中会修复此问题，给您带来不便，敬请谅解。

**Comment by Jeffrey98-AI** [comment]
修改 max_receive_message_length 和 max_send_message_length 这两个字段也是无效的，pipeline OCR 的检测、识别两个OP的client_type 都是 local_predictor

**Comment by TeslaZhao** [comment]
max_receive_message_length 和 max_send_message_length 是grpc.option参数，修改后网络交互的数据Body限制会改变。

另外，您使用的是http模式还是grpc模式，http模式？

**Comment by Jeffrey98-AI** [comment]
客户端是 http 模式

**Comment by HexToString** [comment]
那如果是http模式，可能是我们grpc-gateway支持的http模式的max_body的默认限制，我们确认一下。
