### ISSUE TITLE
pipeline没有使用gpu

### ISSUE THREAD

**Issue by Karenlyw** [PaddlePaddle/Serving#1356]
config.yml里设置了device_type=2
`op:
   ivane_op:
        timeout: -1
        retry: 1 
        #concurrency: 3
        batch_size: 1 
        auto_batching_timeout: -1 
        local_service_conf:
            device_type: 2
            client_type: 'local_predictor'
            model_config: '/home/Serving/serving_server/'
            fetch_list: ["fc_0.tmp_2"]
            devices: "0" 
`            
用python3.6 pipeline.py启动pipeline服务，但是gpu监控里查不到对应的进程id，而且推理速度非常慢，感觉是没用到gpu。请问这个是啥情况呢？

**Comment by TeslaZhao** [comment]
1、您是在docker中部署pipeline服务吗，nvidia-smi是查不到进程ID的。

2、可以指定devices: "2"，可以看到2显卡上显存的变化吗？

3、开启TensorRT 需要同步开启ir_optim开关, 默认False。可参考python/examples/pipeline/simple_web_service/config.yml
            ir_optim: True

**Comment by Karenlyw** [comment]
> 1、您是在docker中部署pipeline服务吗，nvidia-smi是查不到进程ID的。
> 
> 2、可以指定devices: "2"，可以看到2显卡上显存的变化吗？
> 
> 3、开启TensorRT 需要同步开启ir_optim开关, 默认False。可参考python/examples/pipeline/simple_web_service/config.yml
> ir_optim: True

1、是用的docker，不过我之前部署的常规的paddle serving也是用的docker，是可以查到进程id的。
2、device指定的”0“，启动pipeline没有看到显存的变化
<img width="496" alt="0b710c9037ed326f7636e72234c969d" src="https://user-images.githubusercontent.com/58201310/130165690-d59d490e-1de6-45e1-ad75-5af4e32f4f50.png">
3、已开启，仍未解决。另如高并发请求，需要调高哪些参数呢？多谢！
完整config粘贴如下：

`
http_port: 18080 
worker_num: 10
build_dag_each_worker: false
dag:
    is_thread_op: False
    retry: 1
    use_profile: false


op:
   ivane_op:
        timeout: -1 
        retry: 1 
        batch_size: 1 
        auto_batching_timeout: -1 # auto-batching 超时时间，单位为毫秒。默认为 -1 即不超时
        local_service_conf:
            device_type: 2
            client_type: local_predictor
            model_config: /home/Serving/serving_server/
            fetch_list: ["fc_0.tmp_2"]
            devices: "0" # 模型启动在哪个设备上，可以指定 gpu 卡号（如 "0,1,2"），默认为 cpu
            ir_optim: true # ir 优化选项，默认为 false
            use_trt: true

`

**Comment by knwng** [comment]
`build_dag_each_worker` 改成True试过吗？
