### ISSUE TITLE
anaconda下的python 运行 serving_server报错No module named paddle_serving_server_gpu.serve

### ISSUE THREAD

**Issue by windy-zhr** [PaddlePaddle/Serving#1360]
anaconda下的python 运行paddle_serving_server
/u01/anaconda3/bin/python: No module named paddle_serving_server_gpu.serve
![image](https://user-images.githubusercontent.com/79828574/130212750-3241723b-d12d-4131-9c07-17575cbdefb7.png)

源网页是
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/text_classification/pretrained_models
![image](https://user-images.githubusercontent.com/79828574/130212363-e52ed973-ff35-4fdc-b5c6-9c15bf44ce37.png)
环境信息：
![image](https://user-images.githubusercontent.com/79828574/130212582-cdda2da1-179f-476a-aca9-1c92a25287cc.png)
annaconda python 3.7

**Comment by HexToString** [comment]
直接 paddle_serving_server.serve即可
