### ISSUE TITLE
paddle serving的lac只有分词，没有词性标注么？

### ISSUE THREAD

**Issue by weixiu00** [PaddlePaddle/Serving#1361]
hub serving 的lac模块既支持分词也支持词性标注，为啥paddle serving lac的例子只有分词结果呢

**Comment by TeslaZhao** [comment]
您好，同样的lac模型分类，具体的模型不同。另一方面，HubServing与PaddleServing的侧重点有所不同，PaddleServing更专注于高性能、工业级、大模型的部署能力，对于模型的更新频率相对较低，同样可参考Tensorflow-Serving，在模型示例上非常少。
