### ISSUE TITLE
除了支持cpu, gpu paddle serving还能支持其他AI加速器吗？

### ISSUE THREAD

**Issue by dulvqingyunLT** [PaddlePaddle/Serving#1363]
比如说TPU，或者说自己研制的AI加速器，如果想用paddle serving来做部署，需要定制化开发哪些地方呢？

**Comment by TeslaZhao** [comment]
以TPU为例：
1.引入TPU的推理库，类似与paddle_Inferece.so
2.在Serving的inference层：/core/paddle_inference目录，参考paddle_engine.h, paddle_engine.cpp，实现tpu_inference的封装。
3.在调度层中，修改使用tpu_inference
4.联编
