### ISSUE TITLE
关于 OcrService pipeline 部署相关请教

### ISSUE THREAD

**Issue by wa3926** [PaddlePaddle/Serving#1364]
serving 版本 0.6.0  paddle版本 2.0 以上  
![image](https://user-images.githubusercontent.com/53547082/130895955-0460c91e-8790-41dd-a081-fe96b86a98d5.png)

我这边想在检测模型之前加一个方向分类器模型  但是我想通过客户端传递过来的参数 来判断是否需要执行方向分类模型  本地我尝试过3个模型串联可以成功   选择性执行模型不知道有没有参考的实例，求指导！

**Comment by TeslaZhao** [comment]
您好，我们有相选择性执行OP部署，可以这样实现的（在OP的前处理做判断，可跳过process阶段，交给后处理）
1.模型串联：方向分类OP -> Det  -> OCR
2. is_thread_op: False，选择进程模型方式
3. 在方向分类OP实现中，preprcess的返回值第二个参数是is_skip_process，根据您的判断在这里设置True：跳过预测，False：执行预测。
4. 在方向分类OP实现中，postprocess组织参数交给Det.

关于跳过预测的示例，会在下个版本中补充。

**Comment by wa3926** [comment]
@TeslaZhao  大佬你好   按你说的跳过预测 确实可以了 ！ 我还有一个问题  在Det模型后面 我有一个手写和印刷2分类的模型    

在这个二分类模型postprocess里面我想 根据返回的值  将一部分 检测框 dt_boxes  送到手写体模型识别里   一部分dt_boxes  送到印刷体模型里面。         不知道是否可以实现同时调用 手写和印刷识别模型    然后最后汇总数据返回   。还是说只能继续串联模型，数据分别经过手写体OP和印刷体Op 最后返回。  现在线上遇到的场景是一张图片既有印刷体也有手写体    求大佬指点一下

**Comment by TeslaZhao** [comment]
只能继续串联模型，数据分别经过手写体OP和印刷体Op 最后返回

**Comment by wa3926** [comment]
@TeslaZhao  感谢指点 这样的话耗时可能会增加一点！
