### ISSUE TITLE
solo模型  解析fetch var 报错

### ISSUE THREAD

**Issue by zouxiaoshi** [PaddlePaddle/Serving#1365]
您好：

模型是用的实例分割的 [solo模型](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/configs/solov2/README.md)
代码如下：
```python
from paddle_serving_client import Client
from paddle_serving_app.reader import *

preprocess = Sequential([
    File2Image(), 
    BGR2RGB(),
    Div(255),
    Resize((512,512)),
    Normalize([0.485, 0.456, 0.406],[0.229, 0.224, 0.225]),
    Transpose((2, 0, 1)),
    PadStride(32),
])

img_path = './imgs/000363.jpg'
im = preprocess(img_path)

client = Client()
client.load_client_config("client_config/serving_client_conf.prototxt")
client.connect(['10.25.131.11:9007'])

fetch_map = client.predict(
    feed={
        "image": np.array(im).astype(np.float32),
        "im_shape": np.array([512,512]),
        "scale_factor":np.array([1, 1]),
    },
    fetch=[
             "save_infer_model/scale_0.tmp_1", # segm
            "save_infer_model/scale_1.tmp_1", # category id
            "save_infer_model/scale_2.tmp_1", # score
             "save_infer_model/scale_3.tmp_1" # box num
            ],
    batch=False
)
print(fetch_map)
```

#### fetch 中包含 “save_infer_model/scale_0.tmp_1” 时
```bash
Traceback (most recent call last):
  File "test_model.py", line 25, in <module>
    fetch_map = client.predict(
  File "/usr/local/lib/python3.8/site-packages/paddle_serving_client/client.py", line 482, in predict
    result_map[name] = result_batch_handle.get_int32_by_name(
AttributeError: 'paddle_serving_client.serving_client.PredictorRes' object has no attribute 'get_int32_by_name'

```
#### fetch 中包含 “save_infer_model/scale_3.tmp_1” 时
```bash
Traceback (most recent call last):
  File "test_model.py", line 25, in <module>
    fetch_map = client.predict(
  File "/usr/local/lib/python3.8/site-packages/paddle_serving_client/client.py", line 457, in predict
    raise ValueError(
ValueError: Failed to fetch, maybe the type of [save_infer_model/scale_3.tmp_1] is wrong, please check the model file

```

#### serving_server_conf.prototxt 文件如下：
```text
feed_var {
  name: "im_shape"
  alias_name: "im_shape"
  is_lod_tensor: false
  feed_type: 1
  shape: 2
}
feed_var {
  name: "image"
  alias_name: "image"
  is_lod_tensor: false
  feed_type: 1
  shape: 3
}
feed_var {
  name: "scale_factor"
  alias_name: "scale_factor"
  is_lod_tensor: false
  feed_type: 1
  shape: 2
}
fetch_var {
  name: "save_infer_model/scale_0.tmp_1"
  alias_name: "save_infer_model/scale_0.tmp_1"
  is_lod_tensor: true
  fetch_type: 2
  shape: -1
}
fetch_var {
  name: "save_infer_model/scale_1.tmp_1"
  alias_name: "save_infer_model/scale_1.tmp_1"
  is_lod_tensor: true
  fetch_type: 0
  shape: -1
}
fetch_var {
  name: "save_infer_model/scale_2.tmp_1"
  alias_name: "save_infer_model/scale_2.tmp_1"
  is_lod_tensor: true
  fetch_type: 1
  shape: -1
}
fetch_var {
  name: "save_infer_model/scale_3.tmp_1"
  alias_name: "save_infer_model/scale_3.tmp_1"
  is_lod_tensor: true
  shape: -1
}
```

#### 环境：
```
paddle-serving-app 0.6.1
paddle-serving-client 0.6.1
paddle-serving-server-gpu 0.6.1.post102
paddlepaddle-gpu 2.1.2
```

**Comment by TeslaZhao** [comment]
您好，我们验证一下

**Comment by ShiningZhang** [comment]
您好，我们会基于develop分支进行问题修复，待修复后告知

**Comment by zouxiaoshi** [comment]
> 您好，我们会基于develop分支进行问题修复，待修复后告知

您好，月底功能要上线，如果月底前没有新的release，如果方便的话，问题修复后，可否帮忙编译下。 【Linux x86, GPU, CUDA10.2, python3.8, with TensorRt】
十分感谢。

**Comment by TeslaZhao** [comment]
好的

**Comment by ShiningZhang** [comment]
您好，该问题已修复。可以使用develop分支编译安装，并对模型进行转换及测试。
转换方法参考：https://github.com/PaddlePaddle/Serving/blob/develop/doc/SAVE_CN.md

**Comment by ShiningZhang** [comment]
您好，编译包下载地址如下：

1. https://paddle-serving.bj.bcebos.com/test-dev/whl/paddle_serving_server_gpu-0.0.0.post102-py3-none-any.whl
2. https://paddle-serving.bj.bcebos.com/test-dev/bin/serving-gpu-102-0.0.0.tar.gz
3. https://paddle-serving.bj.bcebos.com/test-dev/whl/paddle_serving_client-0.0.0-cp38-none-any.whl
4. https://paddle-serving.bj.bcebos.com/test-dev/whl/paddle_serving_app-0.0.0-py3-none-any.whl

**Comment by zouxiaoshi** [comment]
> 您好，编译包下载地址如下：
> 
> 1. https://paddle-serving.bj.bcebos.com/test-dev/whl/paddle_serving_server_gpu-0.0.0.post102-py3-none-any.whl
> 2. https://paddle-serving.bj.bcebos.com/test-dev/bin/serving-gpu-102-0.0.0.tar.gz
> 3. https://paddle-serving.bj.bcebos.com/test-dev/whl/paddle_serving_client-0.0.0-cp38-none-any.whl
> 4. https://paddle-serving.bj.bcebos.com/test-dev/whl/paddle_serving_app-0.0.0-py3-none-any.whl

非常感谢。 这两天比较忙，周末我再测试下。

**Comment by zouxiaoshi** [comment]
> 您好，编译包下载地址如下：
> 
> 1. https://paddle-serving.bj.bcebos.com/test-dev/whl/paddle_serving_server_gpu-0.0.0.post102-py3-none-any.whl
> 2. https://paddle-serving.bj.bcebos.com/test-dev/bin/serving-gpu-102-0.0.0.tar.gz
> 3. https://paddle-serving.bj.bcebos.com/test-dev/whl/paddle_serving_client-0.0.0-cp38-none-any.whl
> 4. https://paddle-serving.bj.bcebos.com/test-dev/whl/paddle_serving_app-0.0.0-py3-none-any.whl

您好，非常感觉您的编译。
周末测试了下，运行的时候，依然存在如下问题：
```bash
Failed to fetch, maybe the type of [save_infer_model/scale_3.tmp_1] is wrong
```
直觉上应该是fetch_type不存在的原因，在 serving_server_conf.prototxt 文件中，确实相应的fetch_type不存在，
```bash
fetch_var {
  name: "save_infer_model/scale_3.tmp_1"
  alias_name: "save_infer_model/scale_3.tmp_1"
  is_lod_tensor: true
  shape: -1
}
```

不知道这个fetch_type可以手动添加吗， 如何在 serving_server_conf.stream.prototxt文件中进行修改？
save_infer_model/scale_3.tmp_1 对应的是实例分割中的mask。

**Comment by ShiningZhang** [comment]
> > 您好，编译包下载地址如下：
> > 
> > 1. https://paddle-serving.bj.bcebos.com/test-dev/whl/paddle_serving_server_gpu-0.0.0.post102-py3-none-any.whl
> > 2. https://paddle-serving.bj.bcebos.com/test-dev/bin/serving-gpu-102-0.0.0.tar.gz
> > 3. https://paddle-serving.bj.bcebos.com/test-dev/whl/paddle_serving_client-0.0.0-cp38-none-any.whl
> > 4. https://paddle-serving.bj.bcebos.com/test-dev/whl/paddle_serving_app-0.0.0-py3-none-any.whl
> 
> 您好，非常感觉您的编译。
> 周末测试了下，运行的时候，依然存在如下问题：
> 
> ```shell
> Failed to fetch, maybe the type of [save_infer_model/scale_3.tmp_1] is wrong
> ```
> 
> 直觉上应该是fetch_type不存在的原因，在 serving_server_conf.prototxt 文件中，确实相应的fetch_type不存在，
> 
> ```shell
> fetch_var {
>   name: "save_infer_model/scale_3.tmp_1"
>   alias_name: "save_infer_model/scale_3.tmp_1"
>   is_lod_tensor: true
>   shape: -1
> }
> ```
> 
> 不知道这个fetch_type可以手动添加吗， 如何在 serving_server_conf.stream.prototxt文件中进行修改？
> save_infer_model/scale_3.tmp_1 对应的是实例分割中的mask。

 您好，之前您在PaddleDetection中获取到的配置由于使用老版本paddle_serving_client进行生成，所以生成的配置文件有问题。请安装新的paddle_serving_client后，本地对模型生成serving配置，具体方法请参考：https://github.com/PaddlePaddle/Serving/blob/develop/doc/SAVE_CN.md
如果save_infer_model/scale_3.tmp_1 对应数据类型为uint8的话，也可以手动添加fetch_type: 7，但还是建议使用最新的安装包进行重新生成

**Comment by zouxiaoshi** [comment]
> r_model/scale_3.t

您好：
在运行用paddle dection训练yolov3模型时，产生如下报错：
```bash
terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():  

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------

----------------------
Error Message Summary:
----------------------
PreconditionNotMetError: The variable named  is not found in the scope of the exector.
  [Hint: executor_->scope()->FindVar(name) should not be null.] (at /paddle/paddle/fluid/inference/api/analysis_predictor.cc:788)
```

环境就是 您最新编译的paddle serving 库。

**Comment by zouxiaoshi** [comment]
> > > 您好，编译包下载地址如下：
> > > 
> > > 1. https://paddle-serving.bj.bcebos.com/test-dev/whl/paddle_serving_server_gpu-0.0.0.post102-py3-none-any.whl
> > > 2. https://paddle-serving.bj.bcebos.com/test-dev/bin/serving-gpu-102-0.0.0.tar.gz
> > > 3. https://paddle-serving.bj.bcebos.com/test-dev/whl/paddle_serving_client-0.0.0-cp38-none-any.whl
> > > 4. https://paddle-serving.bj.bcebos.com/test-dev/whl/paddle_serving_app-0.0.0-py3-none-any.whl
> > 
> > 
> > 您好，非常感觉您的编译。
> > 周末测试了下，运行的时候，依然存在如下问题：
> > ```shell
> > Failed to fetch, maybe the type of [save_infer_model/scale_3.tmp_1] is wrong
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 直觉上应该是fetch_type不存在的原因，在 serving_server_conf.prototxt 文件中，确实相应的fetch_type不存在，
> > ```shell
> > fetch_var {
> >   name: "save_infer_model/scale_3.tmp_1"
> >   alias_name: "save_infer_model/scale_3.tmp_1"
> >   is_lod_tensor: true
> >   shape: -1
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 不知道这个fetch_type可以手动添加吗， 如何在 serving_server_conf.stream.prototxt文件中进行修改？
> > save_infer_model/scale_3.tmp_1 对应的是实例分割中的mask。
> 
> 您好，之前您在PaddleDetection中获取到的配置由于使用老版本paddle_serving_client进行生成，所以生成的配置文件有问题。请安装新的paddle_serving_client后，本地对模型生成serving配置，具体方法请参考：https://github.com/PaddlePaddle/Serving/blob/develop/doc/SAVE_CN.md
> 如果save_infer_model/scale_3.tmp_1 对应数据类型为uint8的话，也可以手动添加fetch_type: 7，但还是建议使用最新的安装包进行重新生成

您好：

在测试时solo模型时，产生如下错误：
```bash
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/paddle_serving_server/pipeline/operator.py", line 1101, in _run_postprocess
    postped_data, prod_errcode, prod_errinfo = self.postprocess(
TypeError: postprocess() takes 4 positional arguments but 5 were given
ERROR 2021-09-23 09:55:07,410 [dag.py:408] (data_id=0 log_id=0) Failed to predict: (data_id=0 log_id=0) [det|0] Failed to postprocess: postprocess() takes 4 positional arguments but 5 were given
```

在运行yolov3模型时，产生如下错误：
```bash
terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():  

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------

----------------------
Error Message Summary:
----------------------
PreconditionNotMetError: The variable named  is not found in the scope of the exector.
  [Hint: executor_->scope()->FindVar(name) should not be null.] (at /paddle/paddle/fluid/inference/api/analysis_predictor.cc:788)
```

环境就是 您最新编译的paddle serving 库。

**Comment by ShiningZhang** [comment]
> > > > 您好，编译包下载地址如下：
> > > > 
> > > > 1. https://paddle-serving.bj.bcebos.com/test-dev/whl/paddle_serving_server_gpu-0.0.0.post102-py3-none-any.whl
> > > > 2. https://paddle-serving.bj.bcebos.com/test-dev/bin/serving-gpu-102-0.0.0.tar.gz
> > > > 3. https://paddle-serving.bj.bcebos.com/test-dev/whl/paddle_serving_client-0.0.0-cp38-none-any.whl
> > > > 4. https://paddle-serving.bj.bcebos.com/test-dev/whl/paddle_serving_app-0.0.0-py3-none-any.whl
> > > 
> > > 
> > > 您好，非常感觉您的编译。
> > > 周末测试了下，运行的时候，依然存在如下问题：
> > > ```shell
> > > Failed to fetch, maybe the type of [save_infer_model/scale_3.tmp_1] is wrong
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 直觉上应该是fetch_type不存在的原因，在 serving_server_conf.prototxt 文件中，确实相应的fetch_type不存在，
> > > ```shell
> > > fetch_var {
> > >   name: "save_infer_model/scale_3.tmp_1"
> > >   alias_name: "save_infer_model/scale_3.tmp_1"
> > >   is_lod_tensor: true
> > >   shape: -1
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 不知道这个fetch_type可以手动添加吗， 如何在 serving_server_conf.stream.prototxt文件中进行修改？
> > > save_infer_model/scale_3.tmp_1 对应的是实例分割中的mask。
> > 
> > 
> > 您好，之前您在PaddleDetection中获取到的配置由于使用老版本paddle_serving_client进行生成，所以生成的配置文件有问题。请安装新的paddle_serving_client后，本地对模型生成serving配置，具体方法请参考：https://github.com/PaddlePaddle/Serving/blob/develop/doc/SAVE_CN.md
> > 如果save_infer_model/scale_3.tmp_1 对应数据类型为uint8的话，也可以手动添加fetch_type: 7，但还是建议使用最新的安装包进行重新生成
> 
> 您好：
> 
> 在测试时solo模型时，产生如下错误：
> 
> ```shell
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/site-packages/paddle_serving_server/pipeline/operator.py", line 1101, in _run_postprocess
>     postped_data, prod_errcode, prod_errinfo = self.postprocess(
> TypeError: postprocess() takes 4 positional arguments but 5 were given
> ERROR 2021-09-23 09:55:07,410 [dag.py:408] (data_id=0 log_id=0) Failed to predict: (data_id=0 log_id=0) [det|0] Failed to postprocess: postprocess() takes 4 positional arguments but 5 were given
> ```
> 
> 在运行yolov3模型时，产生如下错误：
> 
> ```shell
> terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
>   what():  
> 
> --------------------------------------
> C++ Traceback (most recent call last):
> --------------------------------------
> 
> ----------------------
> Error Message Summary:
> ----------------------
> PreconditionNotMetError: The variable named  is not found in the scope of the exector.
>   [Hint: executor_->scope()->FindVar(name) should not be null.] (at /paddle/paddle/fluid/inference/api/analysis_predictor.cc:788)
> ```
> 
> 环境就是 您最新编译的paddle serving 库。

您好，solo模型的错误信息看起来是使用pipeline服务，请参考pipeline开发文档进行设计：
https://github.com/PaddlePaddle/Serving/blob/develop/doc/PIPELINE_SERVING_CN.md
yolov3模型的错误信息为paddle预测库爆出，可以通过以下两个环境变量打开更多日志信息帮助调试。如果仍无法解决，建议您去https://github.com/PaddlePaddle/Paddle 空间提issue。
export GLOG_v=10
export FLAGS_call_stack_level=2

**Comment by TeslaZhao** [comment]
takes 4 positional arguments but 5 were given

您好，您使用的代码分支和Pip install serving版本不一致。develop分支上增加了1个参数。建议您同时使用develop 分支代码 + pip instal develop安装包(https://github.com/PaddlePaddle/Serving/blob/develop/doc/LATEST_PACKAGES.md)

**Comment by zouxiaoshi** [comment]
> takes 4 positional arguments but 5 were given
> 
> 您好，您使用的代码分支和Pip install serving版本不一致。develop分支上增加了1个参数。建议您同时使用develop 分支代码 + pip instal develop安装包(https://github.com/PaddlePaddle/Serving/blob/develop/doc/LATEST_PACKAGES.md)

您好：
多谢解答。
试了下，确实是代码版本原因。
还有一点很疑惑，pipeline的预测结果有问题，对于solo模型而言，只能检测出一个目标。
模型预测结果样例：
```bash
{'save_infer_model/scale_0.tmp_1': array([31], dtype=int32), 'save_infer_model/scale_1.tmp_1': array([1], dtype=int64), 'save_infer_model/scale_2.tmp_1': array([0.95314413], dtype=float32), 'save_infer_model/scale_3.tmp_1': array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]], dtype=uint8)}
```
这里面的  **'save_infer_model/scale_0.tmp_1': array([31],** 代表着，应该有 31个目标，可后面的字段仅包含一个目标的结果。

后来通过paddle serving部署后，直接调模型，结果是正常的，能够检测出多个目标。

**Comment by zouxiaoshi** [comment]
> > > > > 您好，编译包下载地址如下：
> > > > > 
> > > > > 1. https://paddle-serving.bj.bcebos.com/test-dev/whl/paddle_serving_server_gpu-0.0.0.post102-py3-none-any.whl
> > > > > 2. https://paddle-serving.bj.bcebos.com/test-dev/bin/serving-gpu-102-0.0.0.tar.gz
> > > > > 3. https://paddle-serving.bj.bcebos.com/test-dev/whl/paddle_serving_client-0.0.0-cp38-none-any.whl
> > > > > 4. https://paddle-serving.bj.bcebos.com/test-dev/whl/paddle_serving_app-0.0.0-py3-none-any.whl
> > > > 
> > > > 
> > > > 您好，非常感觉您的编译。
> > > > 周末测试了下，运行的时候，依然存在如下问题：
> > > > ```shell
> > > > Failed to fetch, maybe the type of [save_infer_model/scale_3.tmp_1] is wrong
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 直觉上应该是fetch_type不存在的原因，在 serving_server_conf.prototxt 文件中，确实相应的fetch_type不存在，
> > > > ```shell
> > > > fetch_var {
> > > >   name: "save_infer_model/scale_3.tmp_1"
> > > >   alias_name: "save_infer_model/scale_3.tmp_1"
> > > >   is_lod_tensor: true
> > > >   shape: -1
> > > > }
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 不知道这个fetch_type可以手动添加吗， 如何在 serving_server_conf.stream.prototxt文件中进行修改？
> > > > save_infer_model/scale_3.tmp_1 对应的是实例分割中的mask。
> > > 
> > > 
> > > 您好，之前您在PaddleDetection中获取到的配置由于使用老版本paddle_serving_client进行生成，所以生成的配置文件有问题。请安装新的paddle_serving_client后，本地对模型生成serving配置，具体方法请参考：https://github.com/PaddlePaddle/Serving/blob/develop/doc/SAVE_CN.md
> > > 如果save_infer_model/scale_3.tmp_1 对应数据类型为uint8的话，也可以手动添加fetch_type: 7，但还是建议使用最新的安装包进行重新生成
> > 
> > 
> > 您好：
> > 在测试时solo模型时，产生如下错误：
> > ```shell
> > Traceback (most recent call last):
> >   File "/usr/local/lib/python3.8/site-packages/paddle_serving_server/pipeline/operator.py", line 1101, in _run_postprocess
> >     postped_data, prod_errcode, prod_errinfo = self.postprocess(
> > TypeError: postprocess() takes 4 positional arguments but 5 were given
> > ERROR 2021-09-23 09:55:07,410 [dag.py:408] (data_id=0 log_id=0) Failed to predict: (data_id=0 log_id=0) [det|0] Failed to postprocess: postprocess() takes 4 positional arguments but 5 were given
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 在运行yolov3模型时，产生如下错误：
> > ```shell
> > terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
> >   what():  
> > 
> > --------------------------------------
> > C++ Traceback (most recent call last):
> > --------------------------------------
> > 
> > ----------------------
> > Error Message Summary:
> > ----------------------
> > PreconditionNotMetError: The variable named  is not found in the scope of the exector.
> >   [Hint: executor_->scope()->FindVar(name) should not be null.] (at /paddle/paddle/fluid/inference/api/analysis_predictor.cc:788)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 环境就是 您最新编译的paddle serving 库。
> 
> 您好，solo模型的错误信息看起来是使用pipeline服务，请参考pipeline开发文档进行设计：
> https://github.com/PaddlePaddle/Serving/blob/develop/doc/PIPELINE_SERVING_CN.md
> yolov3模型的错误信息为paddle预测库爆出，可以通过以下两个环境变量打开更多日志信息帮助调试。如果仍无法解决，建议您去https://github.com/PaddlePaddle/Paddle 空间提issue。
> export GLOG_v=10
> export FLAGS_call_stack_level=2

您好：
谢谢解答。

yolo模型是由于 GPU驱动问题，我们的测试服务器GPU驱动太低，后来在家里测试时，发现能用，最后定位到GPU驱动的原因。

solo 模型的错误是 代码版本的原因。
在develop分支中， postprocess 多增加了个参数 **data_id**。 修改后，可成功部署。
在用pipeline部署solo进行测试时，发现预测结果有问题。
能过pipeline预测得到的fetch_map 可通过paddle server 预测得出的fetch_map， 这俩fetch_map不完全一致。

尝试了不同的图像，以及不同的solo模型， pipeline只能检测出一个目标。
pipeline和paddle server 在 预处理阶段得到的图像是完全一样的。
目前只能把问题定位到 pipeline 的process 阶段。
