### ISSUE TITLE
在aistudio notebook上部署出错

### ISSUE THREAD

**Issue by huilin16** [PaddlePaddle/Serving#1367]
运行代码：

from paddle_serving_client import Client
client = Client()
client.load_client_config("uci_housing_client/serving_client_conf.prototxt")

报错：
ImportError: libcrypto.so.10: cannot open shared object file: No such file or directory

notebook环境：
paddlepaddle2.1.2
python3.7
使用pip命令安装了paddle-serving-server 、paddle-serving-client 、paddle-serving-app

**Comment by huilin16** [comment]
![1](https://user-images.githubusercontent.com/36887207/131105933-a127bb9a-61bf-453f-ae91-bd850d3fece2.png)

**Comment by TeslaZhao** [comment]
您好，您安装的paddle Serving哪个版本？

**Comment by huilin16** [comment]
> 您好，您安装的paddle Serving哪个版本？
您好，我的环境配置：
paddlepaddle-gpu==2.1.2
paddle-serving-app==0.6.3
paddle-serving-client==0.6.3
paddle-serving-server==0.6.3

**Comment by bjjwwang** [comment]
```
wget https://paddle-serving.bj.bcebos.com/others/centos_ssl.tar && \
    tar xf centos_ssl.tar && rm -rf centos_ssl.tar && \
    mv libcrypto.so.1.0.2k /usr/lib/libcrypto.so.1.0.2k && mv libssl.so.1.0.2k /usr/lib/libssl.so.1.0.2k && \
    ln -sf /usr/lib/libcrypto.so.1.0.2k /usr/lib/libcrypto.so.10 && \
    ln -sf /usr/lib/libssl.so.1.0.2k /usr/lib/libssl.so.10 && \
    ln -sf /usr/lib/libcrypto.so.10 /usr/lib/libcrypto.so && \
    ln -sf /usr/lib/libssl.so.10 /usr/lib/libssl.so
```
具体的路径 你可以看看，放到一个你有权限的地方。
然后export到LD_LIBRARY_PATH就行

**Comment by huilin16** [comment]
好的，多谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jiawei ***@***.***&gt;; 
发送时间: 2021年9月2日(星期四) 下午3:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/Serving] 在aistudio notebook上部署出错 (#1367)





 wget https://paddle-serving.bj.bcebos.com/others/centos_ssl.tar &amp;&amp; \     tar xf centos_ssl.tar &amp;&amp; rm -rf centos_ssl.tar &amp;&amp; \     mv libcrypto.so.1.0.2k /usr/lib/libcrypto.so.1.0.2k &amp;&amp; mv libssl.so.1.0.2k /usr/lib/libssl.so.1.0.2k &amp;&amp; \     ln -sf /usr/lib/libcrypto.so.1.0.2k /usr/lib/libcrypto.so.10 &amp;&amp; \     ln -sf /usr/lib/libssl.so.1.0.2k /usr/lib/libssl.so.10 &amp;&amp; \     ln -sf /usr/lib/libcrypto.so.10 /usr/lib/libcrypto.so &amp;&amp; \     ln -sf /usr/lib/libssl.so.10 /usr/lib/libssl.so  
具体的路径 你可以看看，放到一个你有权限的地方。
 然后export到LD_LIBRARY_PATH就行
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by skywalk163** [comment]
感谢，我也碰到这个报错了，按照你的方法解决了。
我用的方法是创建一个lib目录放置：
wget https://paddle-serving.bj.bcebos.com/others/centos_ssl.tar && \
    tar xf centos_ssl.tar && rm -rf centos_ssl.tar && \
    ln -sf libcrypto.so.1.0.2k libcrypto.so.10 && \
    ln -sf libssl.so.1.0.2k libssl.so.10 && \
    ln -sf libcrypto.so.10 libcrypto.so && \
    ln -sf libssl.so.10 libssl.so
然后将这个lib目录export到LD_LIBRARY_PATH

export LD_LIBRARY_PATH=/home/aistudio/lib:$LD_LIBRARY_PATH

**Comment by huilin16** [comment]
十分感谢，我试一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月10日(星期五) 中午11:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/Serving] 在aistudio notebook上部署出错 (#1367)





 
感谢，我也碰到这个报错了，按照你的方法解决了。
 我用的方法是创建一个lib目录放置：
 wget https://paddle-serving.bj.bcebos.com/others/centos_ssl.tar &amp;&amp; 
 tar xf centos_ssl.tar &amp;&amp; rm -rf centos_ssl.tar &amp;&amp; 
 ln -sf libcrypto.so.1.0.2k libcrypto.so.10 &amp;&amp; 
 ln -sf libssl.so.1.0.2k libssl.so.10 &amp;&amp; 
 ln -sf libcrypto.so.10 libcrypto.so &amp;&amp; 
 ln -sf libssl.so.10 libssl.so
 然后将这个lib目录export到LD_LIBRARY_PATH
 
export LD_LIBRARY_PATH=/home/aistudio/lib:$LD_LIBRARY_PATH
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
