### ISSUE TITLE
部署自己训练模型问题

### ISSUE THREAD

**Issue by Ray8716397** [PaddlePaddle/Serving#1368]
![Selection_001](https://user-images.githubusercontent.com/45814273/131302830-b6e3ee7d-4b23-406e-b373-e12a6544a9fa.png)

我试着以pdserving方式部署ocr pipeline，但是预测的时候报错说:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/paddle_py38/lib/python3.8/site-packages/paddle_serving_server/pipeline/operator.py", line 790, in _run_process
    midped_batch = self.process(feed_batch, typical_logid)
  File "/opt/anaconda3/envs/paddle_py38/lib/python3.8/site-packages/paddle_serving_server/pipeline/operator.py", line 443, in process
    call_result = self.client.predict(
  File "/opt/anaconda3/envs/paddle_py38/lib/python3.8/site-packages/paddle_serving_app/local_predict.py", line 219, in predict
    if isinstance(feed[name], list):
KeyError: 'x'

请问我转换的模型正确吗，还是哪里出的问题

**Comment by TeslaZhao** [comment]
您好，您安装的PaddleServing的版本是多少？

**Comment by Ray8716397** [comment]
> 您好，您安装的PaddleServing的版本是多少？

您好，是默认的0.6.0

**Comment by TeslaZhao** [comment]
这个报错的意思是，请求数据中没叫'x' 的feed var。建议在preprocess函数中打印你的Input_dict

**Comment by Ray8716397** [comment]
> 这个报错的意思是，请求数据中没叫'x' 的feed var。建议在preprocess函数中打印你的Input_dict

ERROR 2021-09-06 15:11:19,965 [operator.py:931] (data_id=0 log_id=0) [rec|0] Failed to postprocess: 'ctc_greedy_decoder_0.tmp_0.lod'
Traceback (most recent call last):
  File "/opt/anaconda3/envs/paddle_py38/lib/python3.8/site-packages/paddle_serving_server/pipeline/operator.py", line 925, in _run_postprocess
    postped_data, prod_errcode, prod_errinfo = self.postprocess(
  File "/home/guijutech/Workspace/github/Serving/python/examples/pipeline/ocr/web_service.py", line 162, in postprocess
    one_batch_res = self.ocr_reader.postprocess(
  File "/opt/anaconda3/envs/paddle_py38/lib/python3.8/site-packages/paddle_serving_app/reader/ocr_reader.py", line 178, in postprocess
    rec_idx_lod = outputs["ctc_greedy_decoder_0.tmp_0.lod"]
KeyError: 'ctc_greedy_decoder_0.tmp_0.lod'

你好，我把Input_dict里的image改成x了，然后运行pipeline_rpc_client.py后说KeyError: 'ctc_greedy_decoder_0.tmp_0.lod'

我使用的是自己训练的日语模型，请问是不是有什么参数没设置正确导致和官网给的serving模型配置文件文件不一样

这是我转换推理模型后出来的配置文件
feed_var {
  name: "x"
  alias_name: "x"
  is_lod_tensor: false
  feed_type: 1
  shape: 3
  shape: 32
}
fetch_var {
  name: "save_infer_model/scale_0.tmp_1"
  alias_name: "save_infer_model/scale_0.tmp_1"
  is_lod_tensor: true
  fetch_type: 1
  shape: -1
}

**Comment by TeslaZhao** [comment]
ocr_reader这里有一个地方是我们写的不好，建议在/opt/anaconda3/envs/paddle_py38/lib/python3.8/site-packages/paddle_serving_app/reader/ocr_reader.py文件中，将ctc_greedy_decoder_0.tmp_0.lod，换成你的save_infer_model/scale_0.tmp_1

**Comment by Ray8716397** [comment]
> ocr_reader这里有一个地方是我们写的不好，建议在/opt/anaconda3/envs/paddle_py38/lib/python3.8/site-packages/paddle_serving_app/reader/ocr_reader.py文件中，将ctc_greedy_decoder_0.tmp_0.lod，换成你的save_infer_model/scale_0.tmp_1

那postprocess里面的还有"ctc_greedy_decoder_0.tmp_0"和"softmax_0.tmp_0"应该改成什么？

    def postprocess(self, outputs, with_score=False):
        rec_res = []
        rec_idx_lod = outputs["ctc_greedy_decoder_0.tmp_0.lod"]
        rec_idx_batch = outputs["ctc_greedy_decoder_0.tmp_0"]
        if with_score:
            predict_lod = outputs["softmax_0.tmp_0.lod"]
        for rno in range(len(rec_idx_lod) - 1):
            beg = rec_idx_lod[rno]
            end = rec_idx_lod[rno + 1]
            if isinstance(rec_idx_batch, list):
                rec_idx_tmp = [x[0] for x in rec_idx_batch[beg:end]]
            else:  #nd array
                rec_idx_tmp = rec_idx_batch[beg:end, 0]
            preds_text = self.char_ops.decode(rec_idx_tmp)
            if with_score:
                beg = predict_lod[rno]
                end = predict_lod[rno + 1]
                if isinstance(outputs["softmax_0.tmp_0"], list):
                    outputs["softmax_0.tmp_0"] = np.array(outputs[
                        "softmax_0.tmp_0"]).astype(np.float32)
                probs = outputs["softmax_0.tmp_0"][beg:end, :]
                ind = np.argmax(probs, axis=1)
                blank = probs.shape[1]
                valid_ind = np.where(ind != (blank - 1))[0]
                score = np.mean(probs[valid_ind, ind[valid_ind]])
                rec_res.append([preds_text, score])
            else:
                rec_res.append([preds_text])
        return rec_res

**Comment by TeslaZhao** [comment]
把output输出一下，因为模型输入和输出结构和原模型不同，按实际的情况来

**Comment by Ray8716397** [comment]
> 把output输出一下，因为模型输入和输出结构和原模型不同，按实际的情况来

好的，这是output的输出

output:
{'save_infer_model/scale_0.tmp_1': array([[[9.99993205e-01, 3.86573329e-10, 3.86573329e-10, ...,
         3.86573329e-10, 3.86573329e-10, 1.28827807e-07],
        [9.99995947e-01, 9.67648739e-11, 9.67648739e-11, ...,
         9.67648739e-11, 9.67648739e-11, 9.96097569e-08],
        [9.99842882e-01, 1.68521153e-09, 1.68521153e-09, ...,
         1.68521153e-09, 1.68521153e-09, 9.95395794e-07],
        ...,
        [1.00000000e+00, 5.15480063e-12, 5.15480063e-12, ...,
         5.15480063e-12, 5.15480063e-12, 4.03368616e-10],
        [1.00000000e+00, 9.03526472e-12, 9.03526472e-12, ...,
         9.03526472e-12, 9.03526472e-12, 1.01644071e-09],
        [9.99999166e-01, 1.03872917e-10, 1.03872917e-10, ...,
         1.03872917e-10, 1.03872917e-10, 1.12403731e-08]],

       [[9.99987841e-01, 6.48810339e-10, 6.48810339e-10, ...,
         6.48810339e-10, 6.48810339e-10, 1.34159919e-08],
        [9.99903917e-01, 6.40344611e-10, 6.40344611e-10, ...,
         6.40344611e-10, 6.40344611e-10, 6.07129591e-09],
        [1.90413196e-03, 1.29085231e-06, 1.29085231e-06, ...,
         1.29085231e-06, 1.29085231e-06, 7.54524592e-07],
        ...,
        [1.00000000e+00, 3.94227186e-12, 3.94227186e-12, ...,
         3.94227186e-12, 3.94227186e-12, 2.71071915e-10],
        [1.00000000e+00, 6.73037667e-12, 6.73037667e-12, ...,
         6.73037667e-12, 6.73037667e-12, 7.81976595e-10],
        [9.99999285e-01, 7.92487673e-11, 7.92487673e-11, ...,
         7.92487673e-11, 7.92487673e-11, 8.98214392e-09]],

       [[9.99993086e-01, 2.48569526e-10, 2.48569526e-10, ...,
         2.48569526e-10, 2.48569526e-10, 9.71351355e-08],
        [9.99966741e-01, 1.47930834e-10, 1.47930834e-10, ...,
         1.47930834e-10, 1.47930834e-10, 1.41814596e-07],
        [1.68271847e-02, 6.11077894e-07, 6.11077894e-07, ...,
         6.11077894e-07, 6.11077894e-07, 3.13323515e-04],
        ...,
        [1.00000000e+00, 4.64211091e-12, 4.64211091e-12, ...,
         4.64211091e-12, 4.64211091e-12, 4.46157222e-10],
        [1.00000000e+00, 8.06029288e-12, 8.06029288e-12, ...,
         8.06029288e-12, 8.06029288e-12, 1.26632316e-09],
        [9.99999285e-01, 8.78504838e-11, 8.78504838e-11, ...,
         8.78504838e-11, 8.78504838e-11, 1.31570799e-08]],

       ...,

       [[9.99984860e-01, 1.10692155e-09, 1.10692155e-09, ...,
         1.10692155e-09, 1.10692155e-09, 8.85332980e-08],
        [9.99996901e-01, 1.77229370e-10, 1.77229370e-10, ...,
         1.77229370e-10, 1.77229370e-10, 1.37091680e-08],
        [9.99996901e-01, 8.46575449e-11, 8.46575449e-11, ...,
         8.46575449e-11, 8.46575449e-11, 4.29198321e-09],
        ...,
        [1.00000000e+00, 4.75047345e-12, 4.75047345e-12, ...,
         4.75047345e-12, 4.75047345e-12, 4.88246443e-10],
        [1.00000000e+00, 8.28747834e-12, 8.28747834e-12, ...,
         8.28747834e-12, 8.28747834e-12, 1.38846212e-09],
        [9.99999285e-01, 8.92717220e-11, 8.92717220e-11, ...,
         8.92717220e-11, 8.92717220e-11, 1.41004453e-08]],

       [[9.99998450e-01, 4.87260232e-11, 4.87260232e-11, ...,
         4.87260232e-11, 4.87260232e-11, 7.46942175e-10],
        [9.99999881e-01, 3.72255655e-12, 3.72255655e-12, ...,
         3.72255655e-12, 3.72255655e-12, 2.35952299e-11],
        [9.99997377e-01, 9.00354027e-11, 9.00354027e-11, ...,
         9.00354027e-11, 9.00354027e-11, 1.14596777e-10],
        ...,
        [1.00000000e+00, 4.51526143e-12, 4.51526143e-12, ...,
         4.51526143e-12, 4.51526143e-12, 4.62453825e-10],
        [1.00000000e+00, 7.81197589e-12, 7.81197589e-12, ...,
         7.81197589e-12, 7.81197589e-12, 1.29601196e-09],
        [9.99999285e-01, 8.50414600e-11, 8.50414600e-11, ...,
         8.50414600e-11, 8.50414600e-11, 1.33330591e-08]],

       [[9.99997377e-01, 1.85576596e-10, 1.85576596e-10, ...,
         1.85576596e-10, 1.85576596e-10, 3.36759087e-09],
        [9.99989986e-01, 1.70556042e-10, 1.70556042e-10, ...,
         1.70556042e-10, 1.70556042e-10, 2.71979284e-09],
        [7.46064074e-03, 2.70255441e-06, 2.70255441e-06, ...,
         2.70255441e-06, 2.70255441e-06, 7.51891093e-06],
        ...,
        [1.00000000e+00, 4.58512438e-12, 4.58512438e-12, ...,
         4.58512438e-12, 4.58512438e-12, 4.54873583e-10],
        [9.99999523e-01, 4.98686439e-11, 4.98686439e-11, ...,
         4.98686439e-11, 4.98686439e-11, 8.28480040e-09],
        [9.43769574e-01, 2.76676178e-06, 2.76676178e-06, ...,
         2.76676178e-06, 2.76676178e-06, 1.34333066e-04]]], dtype=float32)}

outputs['save_infer_model/scale_0.tmp_1'].shape:
(42, 124, 6625)

**Comment by guijuzhejiang** [comment]
字典变了

**Comment by Ray8716397** [comment]
class OCRReader(object):
    def __init__(self,
                 algorithm="CRNN",
                 image_shape=[3, 32, 320],
                 char_type="japan",
                 batch_num=1,
                 char_dict_path="./japan_dict_guiju.txt"):


如上更改了字典路径后webservice不输出outputs结果了，也没有报错，就卡住

**Comment by Ray8716397** [comment]
@TeslaZhao @HexToString 请问目前是不是还不支持其他语言的服务化部署

**Comment by zoe531** [comment]
这个问题还没解决吧，这个怎么改呢，单独部署rec 模型还是有问题的

def postprocess(self, outputs, with_score=False):
    rec_res = []
    rec_idx_lod = outputs["ctc_greedy_decoder_0.tmp_0.lod"]
    rec_idx_batch = outputs["ctc_greedy_decoder_0.tmp_0"]
    if with_score:
        predict_lod = outputs["softmax_0.tmp_0.lod"]
    for rno in range(len(rec_idx_lod) - 1):
        beg = rec_idx_lod[rno]
        end = rec_idx_lod[rno + 1]
        if isinstance(rec_idx_batch, list):
            rec_idx_tmp = [x[0] for x in rec_idx_batch[beg:end]]
        else:  #nd array
            rec_idx_tmp = rec_idx_batch[beg:end, 0]
        preds_text = self.char_ops.decode(rec_idx_tmp)
        if with_score:
            beg = predict_lod[rno]
            end = predict_lod[rno + 1]
            if isinstance(outputs["softmax_0.tmp_0"], list):
                outputs["softmax_0.tmp_0"] = np.array(outputs[
                    "softmax_0.tmp_0"]).astype(np.float32)
            probs = outputs["softmax_0.tmp_0"][beg:end, :]
            ind = np.argmax(probs, axis=1)
            blank = probs.shape[1]
            valid_ind = np.where(ind != (blank - 1))[0]
            score = np.mean(probs[valid_ind, ind[valid_ind]])
            rec_res.append([preds_text, score])
        else:
            rec_res.append([preds_text])
    return rec_res

**Comment by Ray8716397** [comment]
> 这个问题还没解决吧，这个怎么改呢，单独部署rec 模型还是有问题的
> 
> def postprocess(self, outputs, with_score=False):
> rec_res = []
> rec_idx_lod = outputs["ctc_greedy_decoder_0.tmp_0.lod"]
> rec_idx_batch = outputs["ctc_greedy_decoder_0.tmp_0"]
> if with_score:
> predict_lod = outputs["softmax_0.tmp_0.lod"]
> for rno in range(len(rec_idx_lod) - 1):
> beg = rec_idx_lod[rno]
> end = rec_idx_lod[rno + 1]
> if isinstance(rec_idx_batch, list):
> rec_idx_tmp = [x[0] for x in rec_idx_batch[beg:end]]
> else: #nd array
> rec_idx_tmp = rec_idx_batch[beg:end, 0]
> preds_text = self.char_ops.decode(rec_idx_tmp)
> if with_score:
> beg = predict_lod[rno]
> end = predict_lod[rno + 1]
> if isinstance(outputs["softmax_0.tmp_0"], list):
> outputs["softmax_0.tmp_0"] = np.array(outputs[
> "softmax_0.tmp_0"]).astype(np.float32)
> probs = outputs["softmax_0.tmp_0"][beg:end, :]
> ind = np.argmax(probs, axis=1)
> blank = probs.shape[1]
> valid_ind = np.where(ind != (blank - 1))[0]
> score = np.mean(probs[valid_ind, ind[valid_ind]])
> rec_res.append([preds_text, score])
> else:
> rec_res.append([preds_text])
> return rec_res

hubserving那边有代码可以抄

**Comment by zoe531** [comment]
大佬，能麻烦说下在哪个具体模块吗，没找到

**Comment by zoe531** [comment]
> 这个问题还没解决吧，这个怎么改呢，单独部署rec 模型还是有问题的
> 
> def postprocess(self, outputs, with_score=False):
> rec_res = []
> rec_idx_lod = outputs["ctc_greedy_decoder_0.tmp_0.lod"]
> rec_idx_batch = outputs["ctc_greedy_decoder_0.tmp_0"]
> if with_score:
> predict_lod = outputs["softmax_0.tmp_0.lod"]
> for rno in range(len(rec_idx_lod) - 1):
> beg = rec_idx_lod[rno]
> end = rec_idx_lod[rno + 1]
> if isinstance(rec_idx_batch, list):
> rec_idx_tmp = [x[0] for x in rec_idx_batch[beg:end]]
> else: #nd array
> rec_idx_tmp = rec_idx_batch[beg:end, 0]
> preds_text = self.char_ops.decode(rec_idx_tmp)
> if with_score:
> beg = predict_lod[rno]
> end = predict_lod[rno + 1]
> if isinstance(outputs["softmax_0.tmp_0"], list):
> outputs["softmax_0.tmp_0"] = np.array(outputs[
> "softmax_0.tmp_0"]).astype(np.float32)
> probs = outputs["softmax_0.tmp_0"][beg:end, :]
> ind = np.argmax(probs, axis=1)
> blank = probs.shape[1]
> valid_ind = np.where(ind != (blank - 1))[0]
> score = np.mean(probs[valid_ind, ind[valid_ind]])
> rec_res.append([preds_text, score])
> else:
> rec_res.append([preds_text])
> return rec_res



> > 这个问题还没解决吧，这个怎么改呢，单独部署rec 模型还是有问题的
> > def postprocess(self, outputs, with_score=False):
> > rec_res = []
> > rec_idx_lod = outputs["ctc_greedy_decoder_0.tmp_0.lod"]
> > rec_idx_batch = outputs["ctc_greedy_decoder_0.tmp_0"]
> > if with_score:
> > predict_lod = outputs["softmax_0.tmp_0.lod"]
> > for rno in range(len(rec_idx_lod) - 1):
> > beg = rec_idx_lod[rno]
> > end = rec_idx_lod[rno + 1]
> > if isinstance(rec_idx_batch, list):
> > rec_idx_tmp = [x[0] for x in rec_idx_batch[beg:end]]
> > else: #nd array
> > rec_idx_tmp = rec_idx_batch[beg:end, 0]
> > preds_text = self.char_ops.decode(rec_idx_tmp)
> > if with_score:
> > beg = predict_lod[rno]
> > end = predict_lod[rno + 1]
> > if isinstance(outputs["softmax_0.tmp_0"], list):
> > outputs["softmax_0.tmp_0"] = np.array(outputs[
> > "softmax_0.tmp_0"]).astype(np.float32)
> > probs = outputs["softmax_0.tmp_0"][beg:end, :]
> > ind = np.argmax(probs, axis=1)
> > blank = probs.shape[1]
> > valid_ind = np.where(ind != (blank - 1))[0]
> > score = np.mean(probs[valid_ind, ind[valid_ind]])
> > rec_res.append([preds_text, score])
> > else:
> > rec_res.append([preds_text])
> > return rec_res
> 
> hubserving那边有代码可以抄

大佬，能麻烦说下在哪个具体模块吗，没找到

**Comment by Ray8716397** [comment]
你的问题是和我的问题一样的吗？

**Comment by Ray8716397** [comment]
class RecOp(Op):
    ignored_tokens = []

    def decode(self, text_index, text_prob=None, is_remove_duplicate=False):
        """ convert text-index into text-label. """
        result_list = []
        batch_size = len(text_index)
        for batch_idx in range(batch_size):
            char_list = []
            conf_list = []
            for idx in range(len(text_index[batch_idx])):
                if text_index[batch_idx][idx] in self.ignored_tokens:
                    continue
                if is_remove_duplicate:
                    # only for predict
                    if idx > 0 and text_index[batch_idx][idx - 1] == text_index[
                        batch_idx][idx]:
                        continue
                char_list.append(self.character [int(text_index[batch_idx][idx])])
                if text_prob is not None:
                    conf_list.append(text_prob[batch_idx][idx])
                else:
                    conf_list.append(1)
            text = ''.join(char_list)
            result_list.append((text, np.mean(conf_list)))
        return result_list

    def init_op(self):
        dict_fp = config['op']['rec']['dict_fp']
        self.ocr_reader = OCRReader(char_type='japan', char_dict_path=dict_fp)
        # self.ocr_reader = OCRReader()
        self.get_rotate_crop_image = GetRotateCropImage()
        self.sorted_boxes = SortedBoxes()

        character_str = ''
        with open(dict_fp, "rb") as fin:
            lines = fin.readlines()
            for i, line in enumerate(lines):
                line = line.decode('utf-8').strip("\n").strip("\r\n")
                character_str += line
            character_str += " "

            self.character = list(character_str)

        self.character.append(' ')
        self.character = ['sos'] + self.character + ['eos']

        self.ignored_tokens = [0, len(self.character)-1]

    def preprocess(self, input_dicts, data_id, log_id):
        (_, input_dict), = input_dicts.items()
        raw_im = input_dict["x"]
        data = np.frombuffer(raw_im, np.uint8)
        im = cv2.imdecode(data, cv2.IMREAD_COLOR)
        dt_boxes = input_dict["dt_boxes"]
        dt_boxes = self.sorted_boxes(dt_boxes)
        feed_list = []
        img_list = []
        max_wh_ratio = 0

        ## One batch, the type of feed_data is dict.
        """ 
        for i, dtbox in enumerate(dt_boxes):
            boximg = self.get_rotate_crop_image(im, dt_boxes[i])
            img_list.append(boximg)
            h, w = boximg.shape[0:2]
            wh_ratio = w * 1.0 / h
            max_wh_ratio = max(max_wh_ratio, wh_ratio)
        _, w, h = self.ocr_reader.resize_norm_img(img_list[0],
                                                  max_wh_ratio).shape
        imgs = np.zeros((len(img_list), 3, w, h)).astype('float32')
        for id, img in enumerate(img_list):
            norm_img = self.ocr_reader.resize_norm_img(img, max_wh_ratio)
            imgs[id] = norm_img
        feed = {"image": imgs.copy()}

        """

        ## Many mini-batchs, the type of feed_data is list.
        max_batch_size = len(dt_boxes)

        # If max_batch_size is 0, skipping predict stage
        if max_batch_size == 0:
            return {}, True, None, ""
        boxes_size = len(dt_boxes)
        batch_size = boxes_size // max_batch_size
        rem = boxes_size % max_batch_size
        #_LOGGER.info("max_batch_len:{}, batch_size:{}, rem:{}, boxes_size:{}".format(max_batch_size, batch_size, rem, boxes_size))
        for bt_idx in range(0, batch_size + 1):
            imgs = None
            boxes_num_in_one_batch = 0
            if bt_idx == batch_size:
                if rem == 0:
                    continue
                else:
                    boxes_num_in_one_batch = rem
            elif bt_idx < batch_size:
                boxes_num_in_one_batch = max_batch_size
            else:
                _LOGGER.error("batch_size error, bt_idx={}, batch_size={}".
                              format(bt_idx, batch_size))
                break

            start = bt_idx * max_batch_size
            end = start + boxes_num_in_one_batch
            img_list = []
            for box_idx in range(start, end):
                boximg = self.get_rotate_crop_image(im, dt_boxes[box_idx])
                img_list.append(boximg)
                h, w = boximg.shape[0:2]
                wh_ratio = w * 1.0 / h
                max_wh_ratio = max(max_wh_ratio, wh_ratio)
            _, w, h = self.ocr_reader.resize_norm_img(img_list[0],
                                                      max_wh_ratio).shape
            #_LOGGER.info("---- idx:{}, w:{}, h:{}".format(bt_idx, w, h))

            imgs = np.zeros((boxes_num_in_one_batch, 3, w, h)).astype('float32')
            for id, img in enumerate(img_list):
                norm_img = self.ocr_reader.resize_norm_img(img, max_wh_ratio)
                imgs[id] = norm_img
            feed = {"x": imgs.copy()}
            feed_list.append(feed)
        #_LOGGER.info("feed_list : {}".format(feed_list))

        return feed_list, False, None, ""

    def postprocess(self, input_dicts, fetch_data, log_id):
        res_list = []
        if isinstance(fetch_data, dict):
            if len(fetch_data) > 0:
                rec_batch_res = self.ocr_reader.postprocess(
                    fetch_data, with_score=True)
                for res in rec_batch_res:
                    res_list.append(res[0])
        elif isinstance(fetch_data, list):
            for one_batch in fetch_data:
                preds_idx = one_batch['save_infer_model/scale_0.tmp_1'].argmax(axis=2)
                preds_prob = one_batch['save_infer_model/scale_0.tmp_1'].max(axis=2)
                text = self.decode(preds_idx, preds_prob, is_remove_duplicate=True)
                # one_batch_res = self.ocr_reader.postprocess(
                #     one_batch, with_score=True)
                res_l = []
                for dt_box, rec_res in zip(input_dicts['det']['dt_boxes'], text):
                    rec_text, rec_confidence = rec_res
                    text_region = [[int(x) for x in i] for i in dt_box]
                    res_l.append({'text': rec_text, 'confidence': rec_confidence, 'text_region':text_region})
                res_list.append(res_l)
        res = {"res": str(res_list)}
        return res, None, ""

**Comment by zoe531** [comment]
> class RecOp(Op):
> ignored_tokens = []
> 
> ```
> def decode(self, text_index, text_prob=None, is_remove_duplicate=False):
>     """ convert text-index into text-label. """
>     result_list = []
>     batch_size = len(text_index)
>     for batch_idx in range(batch_size):
>         char_list = []
>         conf_list = []
>         for idx in range(len(text_index[batch_idx])):
>             if text_index[batch_idx][idx] in self.ignored_tokens:
>                 continue
>             if is_remove_duplicate:
>                 # only for predict
>                 if idx > 0 and text_index[batch_idx][idx - 1] == text_index[
>                     batch_idx][idx]:
>                     continue
>             char_list.append(self.character [int(text_index[batch_idx][idx])])
>             if text_prob is not None:
>                 conf_list.append(text_prob[batch_idx][idx])
>             else:
>                 conf_list.append(1)
>         text = ''.join(char_list)
>         result_list.append((text, np.mean(conf_list)))
>     return result_list
> 
> def init_op(self):
>     dict_fp = config['op']['rec']['dict_fp']
>     self.ocr_reader = OCRReader(char_type='japan', char_dict_path=dict_fp)
>     # self.ocr_reader = OCRReader()
>     self.get_rotate_crop_image = GetRotateCropImage()
>     self.sorted_boxes = SortedBoxes()
> 
>     character_str = ''
>     with open(dict_fp, "rb") as fin:
>         lines = fin.readlines()
>         for i, line in enumerate(lines):
>             line = line.decode('utf-8').strip("\n").strip("\r\n")
>             character_str += line
>         character_str += " "
> 
>         self.character = list(character_str)
> 
>     self.character.append(' ')
>     self.character = ['sos'] + self.character + ['eos']
> 
>     self.ignored_tokens = [0, len(self.character)-1]
> 
> def preprocess(self, input_dicts, data_id, log_id):
>     (_, input_dict), = input_dicts.items()
>     raw_im = input_dict["x"]
>     data = np.frombuffer(raw_im, np.uint8)
>     im = cv2.imdecode(data, cv2.IMREAD_COLOR)
>     dt_boxes = input_dict["dt_boxes"]
>     dt_boxes = self.sorted_boxes(dt_boxes)
>     feed_list = []
>     img_list = []
>     max_wh_ratio = 0
> 
>     ## One batch, the type of feed_data is dict.
>     """ 
>     for i, dtbox in enumerate(dt_boxes):
>         boximg = self.get_rotate_crop_image(im, dt_boxes[i])
>         img_list.append(boximg)
>         h, w = boximg.shape[0:2]
>         wh_ratio = w * 1.0 / h
>         max_wh_ratio = max(max_wh_ratio, wh_ratio)
>     _, w, h = self.ocr_reader.resize_norm_img(img_list[0],
>                                               max_wh_ratio).shape
>     imgs = np.zeros((len(img_list), 3, w, h)).astype('float32')
>     for id, img in enumerate(img_list):
>         norm_img = self.ocr_reader.resize_norm_img(img, max_wh_ratio)
>         imgs[id] = norm_img
>     feed = {"image": imgs.copy()}
> 
>     """
> 
>     ## Many mini-batchs, the type of feed_data is list.
>     max_batch_size = len(dt_boxes)
> 
>     # If max_batch_size is 0, skipping predict stage
>     if max_batch_size == 0:
>         return {}, True, None, ""
>     boxes_size = len(dt_boxes)
>     batch_size = boxes_size // max_batch_size
>     rem = boxes_size % max_batch_size
>     #_LOGGER.info("max_batch_len:{}, batch_size:{}, rem:{}, boxes_size:{}".format(max_batch_size, batch_size, rem, boxes_size))
>     for bt_idx in range(0, batch_size + 1):
>         imgs = None
>         boxes_num_in_one_batch = 0
>         if bt_idx == batch_size:
>             if rem == 0:
>                 continue
>             else:
>                 boxes_num_in_one_batch = rem
>         elif bt_idx < batch_size:
>             boxes_num_in_one_batch = max_batch_size
>         else:
>             _LOGGER.error("batch_size error, bt_idx={}, batch_size={}".
>                           format(bt_idx, batch_size))
>             break
> 
>         start = bt_idx * max_batch_size
>         end = start + boxes_num_in_one_batch
>         img_list = []
>         for box_idx in range(start, end):
>             boximg = self.get_rotate_crop_image(im, dt_boxes[box_idx])
>             img_list.append(boximg)
>             h, w = boximg.shape[0:2]
>             wh_ratio = w * 1.0 / h
>             max_wh_ratio = max(max_wh_ratio, wh_ratio)
>         _, w, h = self.ocr_reader.resize_norm_img(img_list[0],
>                                                   max_wh_ratio).shape
>         #_LOGGER.info("---- idx:{}, w:{}, h:{}".format(bt_idx, w, h))
> 
>         imgs = np.zeros((boxes_num_in_one_batch, 3, w, h)).astype('float32')
>         for id, img in enumerate(img_list):
>             norm_img = self.ocr_reader.resize_norm_img(img, max_wh_ratio)
>             imgs[id] = norm_img
>         feed = {"x": imgs.copy()}
>         feed_list.append(feed)
>     #_LOGGER.info("feed_list : {}".format(feed_list))
> 
>     return feed_list, False, None, ""
> 
> def postprocess(self, input_dicts, fetch_data, log_id):
>     res_list = []
>     if isinstance(fetch_data, dict):
>         if len(fetch_data) > 0:
>             rec_batch_res = self.ocr_reader.postprocess(
>                 fetch_data, with_score=True)
>             for res in rec_batch_res:
>                 res_list.append(res[0])
>     elif isinstance(fetch_data, list):
>         for one_batch in fetch_data:
>             preds_idx = one_batch['save_infer_model/scale_0.tmp_1'].argmax(axis=2)
>             preds_prob = one_batch['save_infer_model/scale_0.tmp_1'].max(axis=2)
>             text = self.decode(preds_idx, preds_prob, is_remove_duplicate=True)
>             # one_batch_res = self.ocr_reader.postprocess(
>             #     one_batch, with_score=True)
>             res_l = []
>             for dt_box, rec_res in zip(input_dicts['det']['dt_boxes'], text):
>                 rec_text, rec_confidence = rec_res
>                 text_region = [[int(x) for x in i] for i in dt_box]
>                 res_l.append({'text': rec_text, 'confidence': rec_confidence, 'text_region':text_region})
>             res_list.append(res_l)
>     res = {"res": str(res_list)}
>     return res, None, ""
> ```

估计差不多，我是单独部署rec模型， 原来的ocr_reader.py 有问题跑不通，需要重写
