### ISSUE TITLE
部署ocr pipline服务出现问题

### ISSUE THREAD

**Issue by jtcjump** [PaddlePaddle/Serving#1382]
环境：
python3.7 cuda11
paddle-serving-app                0.6.2
paddle-serving-client             0.6.2
paddle-serving-server-gpu         0.6.2.post11
paddlepaddle-gpu                  2.1.2.post110
训练是没有问题的，

运行 python web_service.py >log.txt 后出现错误代码如下：
2021/09/10 15:13:23 start proxy service
W0910 15:13:25.915069 15963 analysis_predictor.cc:715] The one-time configuration of analysis predictor failed, which may be due to native predictor called first and its configurations taken effect.
W0910 15:13:25.958106 15973 analysis_predictor.cc:715] The one-time configuration of analysis predictor failed, which may be due to native predictor called first and its configurations taken effect.
W0910 15:13:25.961266 15956 analysis_predictor.cc:715] The one-time configuration of analysis predictor failed, which may be due to native predictor called first and its configurations taken effect.
W0910 15:13:26.001137 15984 analysis_predictor.cc:715] The one-time configuration of analysis predictor failed, which may be due to native predictor called first and its configurations taken effect.

**Comment by TeslaZhao** [comment]
您好，运行 tail -200 PipelineServingLogs/pipeline.log.wf  看下错误信息

**Comment by jtcjump** [comment]
> Message that will be displayed on users' first issue

CRITICAL 2021-09-10 15:58:46,795 [operator.py:1161] [rec|0] failed to init op: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "connections to all backends failing"
        debug_error_string = "{"created":"@1631260726.794581425","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":4165,"referenced_errors":[{"created":"@1631260726.794577426","description":"connections to all backends failing","file":"src/core/ext/filters/client_channel/lb_policy/round_robin/round_robin.cc","file_line":335,"grpc_status":14}]}"
>
Traceback (most recent call last):
  File "/opt/miniconda3/envs/paddle22/lib/python3.7/site-packages/paddle_serving_server/pipeline/operator.py", line 1156, in _run
    profiler = self._initialize(is_thread_op, concurrency_idx)
  File "/opt/miniconda3/envs/paddle22/lib/python3.7/site-packages/paddle_serving_server/pipeline/operator.py", line 1343, in _initialize
    self._server_endpoints)
  File "/opt/miniconda3/envs/paddle22/lib/python3.7/site-packages/paddle_serving_server/pipeline/operator.py", line 346, in init_client
    client.connect(server_endpoints)
  File "/opt/miniconda3/envs/paddle22/lib/python3.7/site-packages/paddle_serving_client/client.py", line 558, in connect
    resp = self.stub_.GetClientConfig(get_client_config_req)
  File "/opt/miniconda3/envs/paddle22/lib/python3.7/site-packages/grpc/_channel.py", line 923, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/opt/miniconda3/envs/paddle22/lib/python3.7/site-packages/grpc/_channel.py", line 826, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "connections to all backends failing"
        debug_error_string = "{"created":"@1631260726.794581425","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":4165,"referenced_errors":[{"created":"@1631260726.794577426","description":"connections to all backends failing","file":"src/core/ext/filters/client_channel/lb_policy/round_robin/round_robin.cc","file_line":335,"grpc_status":14}]}"

你好，帮忙看下了

**Comment by jtcjump** [comment]
> 您好，运行 tail -200 PipelineServingLogs/pipeline.log.wf 看下错误信息

又试了下mac，错误是这样的。。。 
环境：
paddle-serving-app                0.6.1
paddle-serving-client             0.6.1
paddle-serving-server             0.6.1
paddlepaddle                      2.1.2

ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'PipelineProcSyncManager.<locals>.PipelineManager'

**Comment by TeslaZhao** [comment]
您好，从您的错误信息看，您使用Pipeline的远程模式，即在config.yml中 op: client_type是brpc或grpc，推理过程会远程请求远端的C++ Server，错误的原因是C++ Server未启动或server_endpoints不正确。

我个人建议您采用local_predictor的方式，调用预测过程全部是python api，由于在进程内预测，与远程预测相比有更好的性能。请查看examples/pipeline/ocr示例（https://github.com/PaddlePaddle/Serving/blob/v0.6.2/python/examples/pipeline/ocr/）修改。
