### ISSUE TITLE
如何关闭占用端口的部署？

### ISSUE THREAD

**Issue by BothCats** [PaddlePaddle/Serving#1387]
使用PaddleServing，某次启动后发现config信息不对，再次启动服务会占用端口，如何关闭该服务，或者重新启动服务？

**Comment by BothCats** [comment]
/home/buu/anaconda3/envs/LHPP/lib/python3.7/site-packages/paddle_serving_server/pipeline/pipeline_server.py:340: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  conf = yaml.load(f.read())
Failed to prepare_server: prot 18091 is already used

**Comment by TeslaZhao** [comment]
ps aux | grep pipeline_server
kill -9 (all processes)
start server.

**Comment by BothCats** [comment]
已解决
