### ISSUE TITLE
怎么实现三个模型串联，已经实现两个模型串联，但只能预测一张图片

### ISSUE THREAD

**Issue by BothCats** [PaddlePaddle/Serving#1388]
![skd](https://user-images.githubusercontent.com/51903595/133438257-7cd694b5-ddc3-4097-9a7e-2813c739bb23.png)
图片路径没问题，但只能预测一张图片，其余会报错
而且pdserving的config只提供了det与rec，没有提供cls的接口，虽然不用也能识别，但是还是想加上cls模型

**Comment by TeslaZhao** [comment]
tail -1000 PipelineServingLogs/pipeline.log.wf 看一下错误信息。

对于OCR任务中增加cls模型，您可以参考已有ocr 示例的配置和代码，自行添加cls模型，det/rec的示例比较清楚，添加cls并不麻烦。如有遇到问题可以随时与我们联系。
