### ISSUE TITLE
请问有没有cuda11.2的serving-gpu安装包

### ISSUE THREAD

**Issue by hymanzhu1983** [PaddlePaddle/Serving#1391]
RTX3090得用cuda11.2以上才行，自己编译貌似有的麻烦

**Comment by hymanzhu1983** [comment]
自己编译到这步出错了
-- Using src='http://paddle-inference-lib.bj.bcebos.com/2.1.0-gpu-/paddle_inference.tgz'
CMake Error at extern_paddle-stamp/download-extern_paddle.cmake:159 (message):
  Each download failed!

    error: downloading 'http://paddle-inference-lib.bj.bcebos.com/2.1.0-gpu-/paddle_inference.tgz' failed
         status_code: 22
         status_string: "HTTP response code said error"
         log:
         --- LOG BEGIN ---
           Trying 220.181.33.44:80...

**Comment by TeslaZhao** [comment]
cuda11-cudnn8-tensorRT7 的serving docker支持 cuda11.2 环境的
https://github.com/PaddlePaddle/Serving/blob/v0.6.2/doc/DOCKER_IMAGES.md

**Comment by TeslaZhao** [comment]
安装包没有11.2的whl包，可以用11.0的docker环境 + 安装11.0的whl包，运行在cuda11.2的系统环境中
