### ISSUE TITLE
OCR Pipeline 增加坐标的返回

### ISSUE THREAD

**Issue by CharlesWu123** [PaddlePaddle/Serving#1392]
你好，我想在 OCR Pipeline 最后返回的时候带上每个文本的坐标值，这个应该怎么修改呢？
我在 RecOp 的 preprocess 里把排序后的坐标赋值给 self.det_boxes，然后在 postprocess 里边把 self.det_boxes 处理后作为返回值作为最终的坐标值返回，但是这样在 preprocess 和 postprocess 里边的 self.det_boxes 的值不一样，有改变，这又是为什么呢？

**Comment by TeslaZhao** [comment]
1.使用self传递数据首先要保证是线程模型，即在config.yml中要选择进程模式，is_thread_op: False
2.self.det_boxes传入的数据是不是浅拷贝的，需要deep copy?

**Comment by CharlesWu123** [comment]
我使用 deepcopy 传入 self.det_boxes 是可以，与 is_thread_op 为 true 或者 false 无关，我试了一下 is_thread_op 为 true 和 false 的情况，都可以。

**Comment by TeslaZhao** [comment]
ok，解决问题就好。在多线程模式（is_thread_op: True)下，多个线程同时修改self.det_boxes，也会引起问题。

**Comment by BeyondYourself** [comment]
@CharlesWu123 增加返回值，这个在客服端服务端代码是否可以提供一个样例参考一下
