### ISSUE TITLE
Warning: PaddlePaddle catches a failure signal, it may not work properly

### ISSUE THREAD

**Issue by NSL-Wx** [PaddlePaddle/Serving#1396]
第一次运行程序出现问题，重启后再次运行问题还是一样。
版本、环境信息：
1）	PaddlePaddle版本：1.7.2 （cpu）
2）	CPU：Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz   3.19 GHz
3）	系统环境：Ubuntu18.04（虚拟机）
4）	Python版本号 3.6.13
5）	问题描述：
 W0923 16:54:47.450151  3006 init.cc:209] Warning: PaddlePaddle catches a failure signal, it may not work properly
W0923 16:54:47.452323  3006 init.cc:211] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W0923 16:54:47.452795  3006 init.cc:214] The detail failure signal is:

W0923 16:54:47.455102  3006 init.cc:217] *** Aborted at 1632387287 (unix time) try "date -d @1632387287" if you are using GNU date ***
W0923 16:54:47.456691  3006 init.cc:217] PC: @                0x0 (unknown)
W0923 16:54:47.459455  3006 init.cc:217] *** SIGSEGV (@0x55c64a38f320) received by PID 3006 (TID 0x7fb8c3c090c0) from PID 1245246240; stack trace: ***
W0923 16:54:47.460755  3006 init.cc:217]     @     0x7fb8c3048980 (unknown)
W0923 16:54:47.461793  3006 init.cc:217]     @     0x55c64a38f320 (unknown)
Segmentation fault (core dumped)

**Comment by TeslaZhao** [comment]
您好，您是安装paddle serving，还是pip install paddlepaddle?

**Comment by NSL-Wx** [comment]
pip imstall paddlepaddle

**Comment by NSL-Wx** [comment]
python3 -m pip install paddlepaddle==1.7.2 -i https://mirror.baidu.com/pypi/simple

**Comment by TeslaZhao** [comment]
您好，安装paddle的问题，建议您去https://github.com/PaddlePaddle/Paddle 空间提issue。
