### ISSUE TITLE
Serve 服务启动加  use_multilang 参数后，python 客户端预测报错

### ISSUE THREAD

**Issue by lguowang** [PaddlePaddle/Serving#1398]
用以下命令服务端启动正常，python 客户端预测也正常。
python -m paddle_serving_server.serve --model serving_server --port 9393 --gpu_id 0  

用以下命令服务端启动正常，python 客户端执行 fetch_map = client.predict(***）预测报错
python -m paddle_serving_server.serve --model serving_server --port 9393 --gpu_id 0   --use_multilang

错误内容如下：

W0924 09:27:40.969290 13202 socket.cpp:1739] Fail to keep-write into fd=3 SocketId=1@127.0.0.1:9393@51798: Broken pipe [32]
W0924 09:27:40.969334 13208 redis_protocol.cpp:69] No corresponding PipelinedInfo in socket
W0924 09:27:40.970535 13201 redis_protocol.cpp:69] No corresponding PipelinedInfo in socket
W0924 09:27:40.970551 13202 socket.cpp:1739] Fail to keep-write into fd=7 SocketId=102@127.0.0.1:9393@51800: Broken pipe [32]
W0924 09:27:40.971127 13208 redis_protocol.cpp:69] No corresponding PipelinedInfo in socket
W0924 09:27:40.971158 13202 socket.cpp:1739] Fail to keep-write into fd=3 SocketId=104@127.0.0.1:9393@51802: Broken pipe [32]
W0924 09:27:40.971328 13187 predictor.hpp:129] inference call failed, message: [E1014]1/1 channels failed, fail_limit=1 [C0][E32]Fail to keep-write into fd=3 SocketId=1@127.0.0.1:9393@51798: Broken pipe [R1][E32]Fail to keep-write into fd=7 SocketId=102@127.0.0.1:9393@51800: Broken pipe [R2][E1014]Got EOF of fd=3 SocketId=104@127.0.0.1:9393@51802
E0924 09:27:40.971411 13187 general_model.cpp:423] failed call predictor with req: insts { tensor_array { float_data: 0.56078434 floa

**Comment by TeslaZhao** [comment]
您好，请不要使用--use_multilang的启动方式了，可以使用新方案：

1.使用develop分支，并安装develop分支Pip包(https://github.com/PaddlePaddle/Serving/blob/develop/doc/LATEST_PACKAGES.md)
2.参考文档启动服务，和client。https://github.com/PaddlePaddle/Serving/blob/develop/doc/HTTP_SERVICE_CN.md

**Comment by lguowang** [comment]
> 您好，请不要使用--use_multilang的启动方式了，可以使用新方案：
> 
> 1.使用develop分支，并安装develop分支Pip包(https://github.com/PaddlePaddle/Serving/blob/develop/doc/LATEST_PACKAGES.md)
> 2.参考文档启动服务，和client。https://github.com/PaddlePaddle/Serving/blob/develop/doc/HTTP_SERVICE_CN.md

**Comment by lguowang** [comment]
> 您好，请不要使用--use_multilang的启动方式了，可以使用新方案：
> 
> 1.使用develop分支，并安装develop分支Pip包(https://github.com/PaddlePaddle/Serving/blob/develop/doc/LATEST_PACKAGES.md)
> 2.参考文档启动服务，和client。https://github.com/PaddlePaddle/Serving/blob/develop/doc/HTTP_SERVICE_CN.md



用了这种方式，我要怎么用实现  Java的 RPC服务，有连接吗？
