### ISSUE TITLE
波士顿房价预测报错

### ISSUE THREAD

**Issue by bingo789** [PaddlePaddle/Serving#1401]
运行测试命令：
cd Serving/python/examples/fit_a_line
python test_client.py uci_housing_client/serving_client_conf.prototxt

报错：
Traceback (most recent call last):
  File "test_client.py", line 20, in <module>
    client = Client()
  File "/home/bingo/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle_serving_client/client.py", line 146, in __init__
    from .serving_client import PredictorRes
ImportError: libcrypto.so.10: cannot open shared object file: No such file or directory

ide查看源码发现 from .serving_client import PredictorRes 这句话无法导航到PredictorRes，也没发现serving_client目录和serving_client.py文件，请问是哪里的原因？

附版本信息：
paddle-serving-client             0.6.0
paddle-serving-server             0.6.0

**Comment by sdl415** [comment]
我遇到了同样的问题，重装 openssl-1.0.1e 就可以了。
开始时没有重装这个，而是把 python/site-packages/paddle_serving_server/serving-cpu-avx-mkl-0.6.3 下的so都ln到usr/lib下，没起作用，结果重装openssl-1.0.1e 就好了

**Comment by bingo789** [comment]
![openssl](https://user-images.githubusercontent.com/40812718/135010129-343a40b3-8a21-497b-9f32-fb10d5fe72fb.png)

我系统有3个版本的openssl，默认使用的是anaconda3/bin下的, 都比你提到的版本高。serving是在paddle环境下运行的，这种情况怎么弄？

**Comment by TeslaZhao** [comment]
您可以使用docker吗？在serving的docker里是已经配置好的

**Comment by bingo789** [comment]
好的，不过平时用笔记本电脑想看看效果，docker的serving差不多6个G，怕内存不够，所以看看能不能解决这个问题

**Comment by bingo789** [comment]
如果用docker部署，客户端也不能使用rpc吧

**Comment by ShiningZhang** [comment]
> 如果用docker部署，客户端也不能使用rpc吧

通过docker部署，客户端也可以访问，可以在创建docker时使用端口映射的方式将docker端口与本地端口对应
