### ISSUE TITLE
serving下的两个example执行结果后，识别框位置全都偏了，这是什么原因？

### ISSUE THREAD

**Issue by sdl415** [PaddlePaddle/Serving#1402]
环境：
VMware虚拟机
ubuntu 18.4 
paddlepaddle 2.1.3
Python 3.8.8
paddle serving server 0.6.3
paddle serving client 0.6.3
paddle serving app 0.6.3
paddle刚入门，自己试着训练目标检测模型的同时，把serving提供的例子跑了一下，采用CPU方式，结果发现识别框结果都跑偏了。
执行的两个example是：
/Serving-0.6.0/python/examples/yolov4 完全跑偏（标准框位置完全超出图片左边轴）
/Serving-0.6.0/python/examples/cascade_rcnn 完全跑偏（貌似整体向右下偏移了很多很多）
/Serving-0.6.0/python/examples/detection/yolov3_darknet53_270e_coco 向下跑偏
/Serving-0.6.0/python/examples/detection/ppyolo_r50vd_dcn_1x_coco 与yolov3_darknet53_270e_coco 一样的跑偏效果
/Serving-0.6.0/python/examples/detection/faster_rcnn_r50_fpn_1x_coco 结果正常，不跑偏

接下来，自己用paddleX训练了一个吸烟的目标检测模型，单模型测试，识别位置正常，且预测到一个结果。
将模型转化成serving可用的模型，继承Op，实现webservice
可问题来了：
1.同一张图片，与单模型测试时不同，这次回来三个识别框位置（但位置和大小相差不多）
2.识别框位置完全偏移了，与上述example里的问题一样，且程序不报错，完全不知道原因
我用paddlex 训练时，主要参数如下：
模型：FastRcnn
backbone选择：ResNet50_vd
其它参数都是paddleX默认参数

转换后得到的 serving_server_conf.prototxt 如下：

feed_var {
  name: "image"
  alias_name: "image"
  is_lod_tensor: false
  feed_type: 1
  shape: 3
}
feed_var {
  name: "im_info"
  alias_name: "im_info"
  is_lod_tensor: false
  feed_type: 1
  shape: 3
}
feed_var {
  name: "im_shape"
  alias_name: "im_shape"
  is_lod_tensor: false
  feed_type: 1
  shape: 3
}
fetch_var {
  name: "save_infer_model/scale_0.tmp_0"
  alias_name: "save_infer_model/scale_0.tmp_0"
  is_lod_tensor: true
  fetch_type: 1
  shape: -1
}

webservice 代码如下：
’‘’
init_op 中 Resize参数是 ((800, 1333))，位置不对，换成（640,640）位置也不对,为啥？
‘’‘
from paddle_serving_server.web_service import WebService, Op
import logging
import numpy as np
import sys
import cv2
from paddle_serving_app.reader import *
import base64

class FasterRCNNOp(Op):
    def init_op(self):
        self.img_preprocess = Sequential([
            BGR2RGB(), Div(255.0),
            Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225], False),
            Resize((640, 640)), Transpose((2, 0, 1)), PadStride(32)
        ])
        self.img_postprocess = RCNNPostprocess("label_list.txt", "output")

    def preprocess(self, input_dicts, data_id, log_id):
        (_, input_dict), = input_dicts.items()
        imgs = []
        #print("keys", input_dict.keys())
        for key in input_dict.keys():
            data = base64.b64decode(input_dict[key].encode('utf8'))
            data = np.fromstring(data, np.uint8)
            im = cv2.imdecode(data, cv2.IMREAD_COLOR)
            im = self.img_preprocess(im)
            imgs.append({
              "image": im[np.newaxis,:],
              "im_shape": np.array(list(im.shape[1:]) + [1.0])[np.newaxis,:],
              "im_info": np.array(list(im.shape[1:]) + [1.0])[np.newaxis,:]
            })

        feed_dict = {
            "image": np.concatenate([x["image"] for x in imgs], axis=0),
            "im_shape": np.concatenate([x["im_shape"] + [1.0] for x in imgs], axis=0),
            "im_info": np.concatenate([x["im_shape"] + [1.0] for x in imgs], axis=0)
        }
        #for key in feed_dict.keys():
        #    print(key, feed_dict[key].shape)
        return feed_dict, False, None, ""

    def postprocess(self, input_dicts, fetch_dict, log_id):

        print(fetch_dict)
        res_dict = {"bbox_result": str(self.img_postprocess(fetch_dict, visualize=False))}
        return res_dict, None, ""

class FasterRCNNService(WebService):
    def get_pipeline_response(self, read_op):
        faster_rcnn_op = FasterRCNNOp(name="faster_rcnn", input_ops=[read_op])
        return faster_rcnn_op

fasterrcnn_service = FasterRCNNService(name="faster_rcnn")
fasterrcnn_service.prepare_pipeline_config("config.yml")
fasterrcnn_service.run_service()

**Comment by bjjwwang** [comment]
这种情况需要和本地的预测进行比对。
```
    feed_dict = {
        "image": np.concatenate([x["image"] for x in imgs], axis=0),
        "im_shape": np.concatenate([x["im_shape"] + [1.0] for x in imgs], axis=0),
        "im_info": np.concatenate([x["im_shape"] + [1.0] for x in imgs], axis=0)
    } 
```
比如在preprocess当中需要看看 这些key对应的np array的shape 和value是不是符合预期， image比较大可以大概看看
然后是postprcess的fetch dict和bbox的信息。
```
def postprocess(self, input_dicts, fetch_dict, log_id):

    print(fetch_dict)
    res_dict = {"bbox_result": str(self.img_postprocess(fetch_dict, visualize=False))}
    return res_dict, None, ""
```
