### ISSUE TITLE
从动态图模型导出

### ISSUE THREAD

**Issue by yt605155624** [PaddlePaddle/Serving#1404]
https://github.com/PaddlePaddle/Serving/blob/v0.6.0/doc/SAVE_CN.md 中提到从动态图模型导出，但是从 --model_filename dygraph_model.pdmodel --params_filename dygraph_model.pdiparams 看来，似乎还是需要走一下 paddle 动转静的流程把模型保存成静态图才可以（静态图：*.pdmodel, *.pdiparams 和 *.pdiparams.info）, 然而目前如果模型代码里面有非 paddle 原生算子（如 有些 算子是 paddle 不支持的，需要自己写一下，在此过程中可能会引入 numpy 等），动转静是无法走通的，请问 serving 有木有提供直接从模型代码保存 serving 所需模型文件的接口呢？（比如你们提供了一个类似于 `paddle.jit.save` 的函数可以直接把模型转成 *.prototxt 但是比它做的更好甚至可以支持非 paddle 算子..）

**Comment by bjjwwang** [comment]
如果把paddle.jit.save 的结果 直接 convert 会有什么样的问题

**Comment by yt605155624** [comment]
现在的问题是 paddle.jit.save 走不通，根本保存不出来模型图文件.. 但是我仔细想了一下，没有用过咱们的 *.prototxt 文件，但是 caffe 的模型结构也是用 *.prototxt 文件来描述的，里面描述了一堆算子，所以如果某个算子是 paddle 不支持的话，咱们的 *.prototxt 文件也是没法子用的对嘛

**Comment by bjjwwang** [comment]
对。我请教了框架组的同学。
如果你的op是用python写的也就是PyLayer，是不可以用于预测的，因为pyLayer的性能很差，它的定位是用于快速迭代的，如果固化下来要拿去预测，一定要开发这个op的C++版本的。
你那边开发的op有写C++版本吗

**Comment by yt605155624** [comment]
没有，如果实现了 serving 可以直接外挂 cpp 文件的嘛

**Comment by bjjwwang** [comment]
> 没有，如果实现了 serving 可以直接外挂 cpp 文件的嘛

如果是用C++ brpc那一套预测的，需要重新编译libpaddle_fluid.so，然后联合编译serving。
如果用的paddle的python预测接口，需要重新编译paddle的whl包。
