### ISSUE TITLE
seving 版本0.6.2 ，HTTP服务 异常

### ISSUE THREAD

**Issue by lguowang** [PaddlePaddle/Serving#1405]
seving 版本0.6.2 ，启用RPC服务正常
python3 -m paddle_serving_server.serve --model uci_housing_model --thread 10 --port 9292

但测试 HTTP服务 异常
请问用什么版本可以正常测试HTTP服务，有图片相关的案例吗？需要测试可用的；

另外，能更新一下说明文档吗？

**Comment by HexToString** [comment]
推荐您使用最新develop分支的http服务，这个更快一些。
下载包的地址参考文档：https://github.com/PaddlePaddle/Serving/blob/v0.6.0/doc/LATEST_PACKAGES.md
相关的原理解释和使用说明参见：https://github.com/PaddlePaddle/Serving/blob/develop/doc/HTTP_SERVICE_CN.md

在不久的将来，develop分支的这些改动会加入到0.7.0版本中

**Comment by lguowang** [comment]
请问有类似这种测试图片HTTP服务的吗？
不懂图片要怎么请求
curl -XPOST http://0.0.0.0:9393/GeneralModelService/inference -d ' {"tensor":[{"float_data":[0.0137,-0.1136,0.2553,-0.0692,0.0582,-0.0727,-0.1583,-0.0584,0.6283,0.4919,0.1856,0.0795,-0.0332],"elem_type":1,"name":"x","alias_name":"x","shape":[1,13]}],"fetch_var_names":["price"],"log_id":0}'

**Comment by lguowang** [comment]
> 推荐您使用最新develop分支的http服务，这个更快一些。 下载包的地址参考文档：https://github.com/PaddlePaddle/Serving/blob/v0.6.0/doc/LATEST_PACKAGES.md 相关的原理解释和使用说明参见：https://github.com/PaddlePaddle/Serving/blob/develop/doc/HTTP_SERVICE_CN.md
> 
> 在不久的将来，develop分支的这些改动会加入到0.7.0版本中


请问有类似这种测试图片HTTP服务的吗？
不懂图片要怎么请求
curl -XPOST http://0.0.0.0:9393/GeneralModelService/inference -d ' {"tensor":[{"float_data":[0.0137,-0.1136,0.2553,-0.0692,0.0582,-0.0727,-0.1583,-0.0584,0.6283,0.4919,0.1856,0.0795,-0.0332],"elem_type":1,"name":"x","alias_name":"x","shape":[1,13]}],"fetch_var_names":["price"],"log_id":0}'

**Comment by lguowang** [comment]
@TeslaZhao 



> 请问有类似这种测试图片HTTP服务的吗？ 不懂图片要怎么请求 curl -XPOST http://0.0.0.0:9393/GeneralModelService/inference -d ' {"tensor":[{"float_data":[0.0137,-0.1136,0.2553,-0.0692,0.0582,-0.0727,-0.1583,-0.0584,0.6283,0.4919,0.1856,0.0795,-0.0332],"elem_type":1,"name":"x","alias_name":"x","shape":[1,13]}],"fetch_var_names":["price"],"log_id":0}'
