### ISSUE TITLE
serving部署后为什么预测结果里有非常多置信度低的bbox？

### ISSUE THREAD

**Issue by sdl415** [PaddlePaddle/Serving#1407]
Serving部署运行后，预测结果中很有多置信度低的bbox，这些无效的结果是否可以在server端去除掉？通过什么方式呢？config.yml 中是否有这种参数可以 过滤掉置信度的bbox？
目前我的思路是自己在 server端的postprocess 方法中设置一个阈值（如0.3）大于这个阈值的才返回。不知道这个功能是不是paddle serving 已经实现了，请高人指点！！
另外，有一点十分不解，为啥用用

python -m paddle_serving_server.serve --model serving_server --port 9494 --gpu_ids 1

部署 output 就一个bbox，难道paddle_serving_server.serve 自动过滤掉低置信度的bbox了？
自己写的web_server就这么多置信度低的bbox呢，实在不解，请百度的大神们给解惑！

Serving 目标监测 预测结果如下：
{'err_no': 0, 'err_msg': '', 'key': ['bbox_result'], 'value': ["[{'category_id': 0, 'bbox': [187.03741455078125, 255.63929748535156, 205.98016357421875, 88.82615661621094], 'score': 0.9474021196365356}, {'category_id': 0, 'bbox': [181.50440979003906, 254.72242736816406, 208.88352966308594, 90.91026306152344], 'score': 0.05671010911464691}, {'category_id': 0, 'bbox': [401.2098693847656, 517.982666015625, 72.83221435546875, 43.914306640625], 'score': 0.02684014104306698}, {'category_id': 0, 'bbox': [412.7727355957031, 263.4219970703125, 93.93243408203125, 84.128662109375], 'score': 0.022902952507138252}, {'category_id': 0, 'bbox': [328.75335693359375, 502.7386779785156, 201.367919921875, 137.25302124023438], 'score': 0.021608827635645866}, {'category_id': 0, 'bbox': [97.00177001953125, 175.4281463623047, 400.4940185546875, 257.75282287597656], 'score': 0.017718592658638954}, {'category_id': 0, 'bbox': [361.63916015625, 564.093994140625, 31.89556884765625, 75.906005859375], 'score': 0.01378613617271185}, {'category_id': 0, 'bbox': [468.4181213378906, 15.370582580566406, 41.89312744140625, 180.01937103271484], 'score': 0.012252263724803925}, {'category_id': 0, 'bbox': [509.7027282714844, 498.7590026855469, 34.746673583984375, 32.500396728515625], 'score': 0.01143593993037939}]"]}

**Comment by TeslaZhao** [comment]
对于bbox的自定义处理逻辑可以在webservice.py的postprocess中处理函数。

python -m paddle_serving_server.serve --model serving_server --port 9494 --gpu_ids 1
是启动一个serving推理服务，pipeline作为client远端请求此服务。可以看config.yml中的client_type类型
