### ISSUE TITLE
OSError: /usr/local/lib/python3.6/dist-packages/paddle_serving_server/pipeline/gateway/libproxy_server.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by jiafuzeng** [PaddlePaddle/Serving#1408]
NVIDIA Jetson AGX Xavier Jetpack 4.5.1 
![image](https://user-images.githubusercontent.com/39875080/135713420-40d8b5ac-6939-415f-b70e-c797bdbb0926.png)

**Comment by bjjwwang** [comment]
可以先ldd 这个so文件，看看是不是有什么缺失的。
感觉应该是指令集不太兼容，有可能要自行编译client.
```
https://github.com/PaddlePaddle/Serving/blob/v0.6.0/doc/COMPILE_CN.md
```

**Comment by WuXinZhiMing** [comment]
其实目录下是有这个文件的, 是gcc版本问题，可以通过  gcc -v 查看下.    我遇到过这个问题，当时系统centos7.5 ，gcc版本4.8，我把gcc升级到8.3就可以了
