### ISSUE TITLE
paddle serving rpc: GPU预测时，结果有问题

### ISSUE THREAD

**Issue by jeffzhengye** [PaddlePaddle/Serving#1409]
paddle serving rpc使用GPU（3080 Ti）时做obj detect 预测出来，数据都是负数，这个肯定时错的，不知道什么原因？
如果serving时使用cpu，配置device cpu, 一切都是正常没有问题

此外，我在另外一台机器上使用同样的配置方式，cpu，gpu（rtx 6000） serving都是好的。

请问这个环境的bug可能在哪里？在线等，谢谢！

**Comment by bjjwwang** [comment]
方便透露下 cuda和cudnn版本 以及 nvidia-smi的驱动版本吗

**Comment by jeffzhengye** [comment]
@bjjwwang 为什么paddle 不能像tensorflow 把问题直接打印出来？ 
paddle 相关的项目都不写文档，然后exception 都不能打印出可debug的信息，这样做开源有什么意思啊

**Comment by TeslaZhao** [comment]
您好，感谢您使用Paddle，对您的遭遇表示遗憾。根据您的描述在rtx 6000环境下可运行，在GPU（3080 Ti）可以预测出结果，但预测结果不正确。排查这种问题需要耐心，因为不是系统或框架出现Exception、core或打印出系统信息，需要加一些辅助日志来排查。

如您所说，当前paddle Serving文档不够详细，遇到问题错误不够完善，我们正在改善和重新设计文档和教程，以提升易用性。
