### ISSUE TITLE
请教一个问题，aistudio 部署时，传入视频做目标跟踪，其reader应该怎么写

### ISSUE THREAD

**Issue by aFtBfF** [PaddlePaddle/Serving#1423]
![image](https://user-images.githubusercontent.com/22255835/137694137-c2c9ae0a-d9dd-49ef-963e-1c4bbbc71f4d.png)

请教一个问题，aistudio 部署时，传入视频做目标跟踪，其reader应该怎么写

**Comment by TeslaZhao** [comment]
目标跟踪的feed 参数有几个，分别是什么类型？

**Comment by aFtBfF** [comment]
不太确定参数需要弄成什么样子，是可以是一个视频呢，还是需要处理成一组图片
模型是用paddledetection中的fairmot训练出来的，导出model后，想使用aistudio的部署功能测试一下线上服务。输入是单个视频，然后aistudio中有个reader需要处理一下这个视频。现在不知道这个reader该如何下手。

**Comment by aFtBfF** [comment]
![image](https://user-images.githubusercontent.com/22255835/137836748-9732a016-14db-470f-89c7-8296226c644e.png)
参数是这个样子的

**Comment by aFtBfF** [comment]
![截图](https://user-images.githubusercontent.com/22255835/137836925-65d6578f-4b0b-4c8e-a907-56d888239dbd.jpg)
参数是这个样子的

**Comment by TeslaZhao** [comment]
模型从哪得到的，或者基于什么模型训练的？

从模型的feed参数看，输入是图片类型的，那么显然需要将视频切帧到图片。因此，是不是可以考虑用opencv或其他视频处理库实现图片切帧？

**Comment by aFtBfF** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/configs/mot/fairmot/README_cn.md
模型是通过paddledetection的fairmot训练出来的
