### ISSUE TITLE
tensorrt dynamic input shape

### ISSUE THREAD

**Issue by zouxiaoshi** [PaddlePaddle/Serving#1425]
# 问题描述
用 develop分支编译的 paddle serving 部署 OCR识别模型(https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_rec_infer.tar) 
 识别速度特别慢。（用6.1版本的paddle serving 同一张照片 0.03s, develop分支编译版本则是0.2s，差了6倍）后来，用了trt后，速度有了明显提高，达到了0.07s, 但是 在使用时有如下报错： 【报错显示paddle serving使用的tensorrt版本太低，无法使用dynamic input shape 】
这里必须使用dynamic input shape， 固定input shape，识别效果不佳。

# 报错
```bash
InvalidArgumentError: Input shapes are inconsistent with the model. Expect [3, 32, 100] in model description, but got [3, 32, 318] in runtime. TRT 5 or lower version does not support dynamic input shapes. Please check and modify your input shapes.
  [Hint: Expected model_input_shape == runtime_input_shape == true, but received model_input_shape == runtime_input_shape:0 != true:1.] (at /paddle/paddle/fluid/operators/tensorrt/tensorrt_engine_op.h:76)
```

# 环境：【最新 develop分支 编译】
```bash
paddle-serving-app        0.0.0
paddle-serving-client     0.0.0
paddle-serving-server-gpu 0.0.0.post102
paddlepaddle-gpu          2.1.0

GPU: P100 
CUDA: 10.2
python 3.8
```

# 补充信息
在镜像中能找到 7.x 版本的 TensorRt, 位于 /usr/local/TensorRT-7.1.3.4

# TODO
请问，如何解决 tensor rt dynamic input shape问题，是需要在镜像中，重新安装 tesnorrt吗？ 
还是说，需要重新编译 paddle-serving-server-gpu?
或者说，需要通过其他方式解决。

谢谢。

**Comment by ShiningZhang** [comment]
您好，看起来您在运行服务时使用python启动服务，请在运行服务时指定serving路径，方法为设置环境变量export SERVING_BIN=bin/serving，这里bin/serving是您编译出的serving路径，一般位于build/core/general-server/serving

**Comment by zouxiaoshi** [comment]
> 您好，看起来您在运行服务时使用python启动服务，请在运行服务时指定serving路径，方法为设置环境变量export SERVING_BIN=bin/serving，这里bin/serving是您编译出的serving路径，一般位于build/core/general-server/serving

您好：

serving_bin 用的是 https://paddle-serving.bj.bcebos.com/test-dev/bin/serving-gpu-102-0.0.0.tar.gz   下载此文件后将其解压并重命名为serving_bin，随后将其放至 /usr/local/ 并设置 export SERVING_BIN=/usr/local/serving_bin/serving

启动命令如下：
```bash
python -m paddle_serving_server.serve \
--model /home/ppocr_rec_mobile_2.0_serving \
--thread 4 --port 10100 \
--gpu_ids 0 \
--use_trt \
--precision FP16
```

报错如下：
```bash
InvalidArgumentError: Input shapes are inconsistent with the model. Expect [3, 32, 100] in model description, but got [3, 32, 305] in runtime. TRT 5 or lower version does not support dynamic input shapes. Please check and modify your input shapes.
  [Hint: Expected model_input_shape == runtime_input_shape == true, but received model_input_shape == runtime_input_shape:0 != true:1.] (at /paddle/paddle/fluid/operators/tensorrt/tensorrt_engine_op.h:76)
```
