### ISSUE TITLE
PaddleServing在做图片处理的时候疯狂的读取磁盘是什么原因？

### ISSUE THREAD

**Issue by zero20121222** [PaddlePaddle/Serving#1426]
![image](https://user-images.githubusercontent.com/6296864/137890127-e31d8ea8-864c-4441-90ef-a918db4850b9.png)

**Comment by felixhjh** [comment]
请问下您用的哪个模型部署出现这种状况吗？ 可以麻烦上传一下启动serving时候的命令截图吗？
