### ISSUE TITLE
Serving 支持python的前处理和后处理但由于python GIL全局锁存在怎样支持并发呢？

### ISSUE THREAD

**Issue by youngstu** [PaddlePaddle/Serving#1430]
Serving 支持python的前处理和后处理但由于python GIL全局锁存在怎样支持并发呢？

**Comment by TeslaZhao** [comment]
框架实现多进程并发，每个进程内前后处理不用线程并发

**Comment by youngstu** [comment]
那是不是可以在前后处理用python写任何自定义的逻辑了？不用担心并发问题？

**Comment by TeslaZhao** [comment]
是的，在前后处理中写自定义逻辑，不用在此处考虑并发。在框架的配置文件config.yml中设置op并发度即可。可参考示例https://github.com/PaddlePaddle/Serving/tree/v0.6.0/python/examples/pipeline/ocr
