### ISSUE TITLE
PaddleServing相较与TorchServe和TensorflowServing 有什么优势呢？

### ISSUE THREAD

**Issue by youngstu** [PaddlePaddle/Serving#1432]
PaddleServing相较与TorchServe和TensorflowServing 有什么优势呢？包括性能和使用方面.

**Comment by TeslaZhao** [comment]
以Restnet50模型为例，相同模型上相同的请求量，PaddleServing的吞吐高于tf-serving，GPU利用率低于tf-serving。数据已经这里出来，会在V0.7 版本发布（11月中旬）发布。TorchServe没有对齐的模型，暂无法比较
