### ISSUE TITLE
Pytorch训练的模型有什么方法在PaddleServing部署吗？

### ISSUE THREAD

**Issue by youngstu** [PaddlePaddle/Serving#1433]
Pytorch训练的模型有什么方法在PaddleServing部署吗？

**Comment by TeslaZhao** [comment]
https://github.com/PaddlePaddle/X2Paddle

**Comment by youngstu** [comment]
pytorch模型应该是直接支持的，也不需要转换。因为pytorch是python api，直接像前后处理一下写python代码来完成pytorch模型推理。

**Comment by TeslaZhao** [comment]
您说Pytorch模型不需要转换，就可以用使用Paddle的推理框架推理吗？

**Comment by youngstu** [comment]
在前处理import torch，用torch模型模型推理。paddle部分把前处理torch预测结果透传给后处理即可。

**Comment by 1037419569** [comment]
> 

我用的python pipeline  在web_service中 import torch  服务都起不来。。。。
