### ISSUE TITLE
error while loading shared libraries: libnvinfer.so.7: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by youngstu** [PaddlePaddle/Serving#1435]
python3.6/site-packages/paddle_serving_server/serving-gpu-cuda11-0.0.0/serving: error while loading shared libraries: libnvinfer.so.7: cannot open shared object file: No such file or directory

**Comment by TeslaZhao** [comment]
您使用的系统环境，Serving版本请发一下

**Comment by youngstu** [comment]
Centos 7.5, serving==0.6.0

**Comment by wstchhwp** [comment]
你好，请问这个是怎么解决的呢
