### ISSUE TITLE
PaddleServing和Triton Inference Server 相比较有什么优势？

### ISSUE THREAD

**Issue by youngstu** [PaddlePaddle/Serving#1443]
PaddleServing和Triton Inference Server 相比较有什么优势？性能和易用性方面有对比和评估吗？

**Comment by TeslaZhao** [comment]
性能尚未比较，Q4会增加性能对比。与TF-serving相比，Paddle Serving性能上有优势
C++框架方面功能上大部分是相近的
paddleServing提供Python的Pipeline，覆盖更多的异构硬件、更多的模型示例
