### ISSUE TITLE
TypeError: load() missing 1 required positional argument: 'Loader'

### ISSUE THREAD

**Issue by youngstu** [PaddlePaddle/Serving#1444]
https://github.com/PaddlePaddle/Serving/tree/v0.6.0/python/examples/pipeline/ocr 

python web_service.py 
执行报错如下：
![Screenshot from 2021-10-27 14-45-31](https://user-images.githubusercontent.com/26452514/139013894-1ac6f525-99b9-46f6-8149-600202d77d94.png)

**Comment by youngstu** [comment]
pip install pyyaml==5.4.1 解决了

**Comment by TeslaZhao** [comment]
develop分支已经修复，使用新版本的yaml的库要求增加了Loader参数。有2种解决方案：
1.重新安装pyyaml，pyyaml>=1.3.0修改为pyyaml>=1.3.0, <6.0
2.使用develop分支代码，使用Latest安装包https://github.com/PaddlePaddle/Serving/blob/develop/doc/LATEST_PACKAGES.md
