### ISSUE TITLE
PaddleServing Op不需要模型推理，只需要前后处理支持？

### ISSUE THREAD

**Issue by youngstu** [PaddlePaddle/Serving#1445]
PaddleServing Op不需要模型推理，只需要前后处理支持？

如：只需要preprocess和postprocess但不需要process该如何设置呢？ 如下图OP4

![image](https://user-images.githubusercontent.com/26452514/139026124-44287782-c232-4a66-b863-c63035587622.png)

**Comment by TeslaZhao** [comment]
跳过推理阶段：
preprocess返回结果列表的第二个结果是is_skip_process=True表示是否跳过当前OP的process阶段，直接进入postprocess处理

https://github.com/PaddlePaddle/Serving/blob/v0.6.0/doc/PIPELINE_SERVING_CN.md#42-%E8%B7%B3%E8%BF%87op-process%E9%98%B6%E6%AE%B5

**Comment by youngstu** [comment]
![image](https://user-images.githubusercontent.com/26452514/139031202-5522b39b-868b-4862-8082-3e3438148eb3.png)

如果没有模型，应该不配置model_config就可以了。is_skip_process=True应该适用于前处理出错等情况。

**Comment by TeslaZhao** [comment]
不配置模型，用这框架只做逻辑处理吗，这个用法很奇特。is_skip_process=True同样适用于跳过process阶段
