### ISSUE TITLE
如果是本机调用，OP的预测类型local_predictor类型是否是更合适些？

### ISSUE THREAD

**Issue by youngstu** [PaddlePaddle/Serving#1446]
![Screenshot from 2021-10-27 15-53-36](https://user-images.githubusercontent.com/26452514/139023700-b7e40940-e42b-47b9-94ca-11b06787762f.png)

如果是本机调用，OP的预测类型local_predictor类型是否是更合适些？

**Comment by TeslaZhao** [comment]
是的，性能也是最佳
