### ISSUE TITLE
worker_num和concurrency区别是？

### ISSUE THREAD

**Issue by youngstu** [PaddlePaddle/Serving#1448]
![Screenshot from 2021-10-27 16-05-21](https://user-images.githubusercontent.com/26452514/139025865-e14fcf6a-ebe5-4c32-b502-d520658b17c2.png)

如上图worker_num和concurrency区别是？

**Comment by TeslaZhao** [comment]
worker_num 是框架级别并行，concurrency是OP级别并行。
