### ISSUE TITLE
build_dag_each_worker和is_thread_op 各自作用是什么？

### ISSUE THREAD

**Issue by youngstu** [PaddlePaddle/Serving#1449]
![image](https://user-images.githubusercontent.com/26452514/139027227-9dbaa965-cb76-4046-a0c9-f4731ad8e049.png)

build_dag_each_worker和is_thread_op 各自作用是什么呢？如果是线程方式如何解决GIL锁问题？

**Comment by TeslaZhao** [comment]
build_dag_each_worker 是框架级别并行与worker_num一起使用。是否创建多套DAG框架实例，当build_dag_each_worker=True时，worker_num数量是多套DAG框架的数量；如果build_dag_each_worker=False时，worker_num表示grpc的并发数

is_thread_op表示op是线程或进程级别，由于Python有GIL，因此推荐使用进程（is_thread_op: False）
