### ISSUE TITLE
在前后处理完成paddle模型推理方案中，在op init函数初始化paddle模型报错

### ISSUE THREAD

**Issue by youngstu** [PaddlePaddle/Serving#1450]
由于paddle动态图转静态图失败，计划省去process环节，直接在post_process完成paddle模型推理。因此需要在init函数里面完成模型加载和初始化，但是cuda报错（查资料好像是由于多进程原因）。

![image](https://user-images.githubusercontent.com/26452514/139039684-f5af40c0-e047-49c7-8906-1fecef054bbd.png)

**Comment by TeslaZhao** [comment]
不要在web_service.py中直接或间接import paddle，放到op的init_op，preproces，postprocess中import.
