### ISSUE TITLE
PaddleServing 是否可以像Triton支持python backend？

### ISSUE THREAD

**Issue by youngstu** [PaddlePaddle/Serving#1451]
PaddleServing 是否可以像Triton支持python backend？如果支持基本可以直接把paddle训练代码迁移过来就能直接部署服务，也不需要其他模型动态图转静态图转Serving等流程。

**Comment by TeslaZhao** [comment]
这种方式我们调研一下哈，Q4的排期已经满了，如果要做的话会放到下个Q
