### ISSUE TITLE
rpc client和server之间通讯不支持numpy/list/tuple/dict等相对复杂一些数据类型

### ISSUE THREAD

**Issue by youngstu** [PaddlePaddle/Serving#1453]
rpc client和server之间通讯不支持numpy/list/tuple/dict等相对复杂一些数据类型。仅支持字符串类型。
后续是否有支持numpy/list/tuple/dict 自动序列化和反序列化计划呢？每次都要base64编解码比较繁琐。

**Comment by TeslaZhao** [comment]
develop 分支上client/server的protobuf结果中已加入Tensor结构，可安装此格式组装Tensor。通常，RPC交互不会直接使用python numpy/list/tuple/dict，但pipeline client中已经封装了对于numpy类型、string类型到proto结构转换。

https://github.com/PaddlePaddle/Serving/blob/develop/python/pipeline/proto/pipeline_service.proto
