### ISSUE TITLE
connections to all backends failing

### ISSUE THREAD

**Issue by youngstu** [PaddlePaddle/Serving#1454]
![image](https://user-images.githubusercontent.com/26452514/139218303-79c72081-e541-40de-b541-07cfcaea34eb.png)

在一个服务中使用rpc请求另一个服务报错如上，帮忙分析一下，谢谢～

**Comment by TeslaZhao** [comment]
请帖出代码

**Comment by youngstu** [comment]
设置了代理原因，unset http_proxy 解决了
