### ISSUE TITLE
Serving 相较于Flask或Django Web服务器有何优势呢？

### ISSUE THREAD

**Issue by youngstu** [PaddlePaddle/Serving#1456]
您好，Serving 相较于Flask或Django Web服务器有什么优势呢？简单测试了一下，性能层面Serving比Flask要差一些，而且经常会有波动，波动情况性能就差得比较多。帮忙研究一下，谢谢~

**Comment by TeslaZhao** [comment]
Flask或Django Web是支持HTTP协议，而Pipeline Serving使用grpc + grpc-gateway作为网络框架，同时支持HTTP和gRPC协议，网络框架性能上不会差，由于都是python网络框架，相比于C/C++/GO/JAVA框架的性能会差很多。

使用Flask或Django Web会采用同步处理方式；而Pipeline Serving网络框架同步，内部处理异步。在单次请求耗时上同步更好一点，在吞吐上异步更好，而你说的性能波动需要详细描述一下。
