### ISSUE TITLE
多线程rpc函数需要每次都创建rpc_client和connect？

### ISSUE THREAD

**Issue by youngstu** [PaddlePaddle/Serving#1457]
您好，请问多线程rpc函数需要每次都创建rpc_client和connect？还是创建一个rpc_client池子，如果rpc_client池子怎么判断rpc请求状态（比如上一个rpc请求没有完成，又发起新的请求如何处理）？

**Comment by TeslaZhao** [comment]
只需要创建和connect一次

**Comment by youngstu** [comment]
如果只创建一次，多线程情况下怎么复用client呢
