### ISSUE TITLE
TTS合成一个段落，单句调用rpc并行合成比一个段落单次合成慢很多

### ISSUE THREAD

**Issue by youngstu** [PaddlePaddle/Serving#1458]
您好，TTS合成一个段落，单句调用rpc并行合成比一个段落单次合成慢很多，且多线程rpc请求并行合成时间逐次变长。帮忙分析一下，谢谢~

**Comment by TeslaZhao** [comment]
可能处理过程有堆积，分析方法是在参考（python/examples/pipeline/simple_web_service/config.yml文件），在dag段中增加tracer，单位是秒。

dag:
    #op资源类型, True, 为线程模型；False，为进程模型
    is_thread_op: False

    #tracer
    tracer:
        interval_s: 10

在Pipeline运行目录下会生成PipelineServingLogs/pipeline.tracer 文件，文件中有各个阶段耗时的统计
