### ISSUE TITLE
rpc性能不是很好并且不是很稳定，经常性通讯时长1s多

### ISSUE THREAD

**Issue by youngstu** [PaddlePaddle/Serving#1460]
您好，rpc性能不是很好并且不是很稳定，经常性通讯时长1s多，帮忙看下原因，谢谢。

**Comment by TeslaZhao** [comment]
可能处理过程有堆积，分析方法是在参考（python/examples/pipeline/simple_web_service/config.yml文件），在dag段中增加tracer，单位是秒。

dag:
#op资源类型, True, 为线程模型；False，为进程模型
is_thread_op: False

#tracer
tracer:
    interval_s: 10
在Pipeline运行目录下会生成PipelineServingLogs/pipeline.tracer 文件，文件中有各个阶段耗时的统计

确定慢的原因后，我们再一起考虑如何优化~

**Comment by youngstu** [comment]
> > #tracer tracer: interval_s: 10 在Pipeline运行目录下会生成PipelineServingLogs/pipeline.tracer 文件，文件中有各个阶段耗时的统计
> > 确定慢的原因后，我们再一起考虑如何优化~
> 
> 感谢，在@TeslaZhao 帮助下原因定位了。这是因为concurrency较多时刚开始有的进程没有初始化原因，预测时间包含了部分进程初始化时间，后面等所有进程都初始化了，稳定下来性能还是挺不错的。

**Comment by TeslaZhao** [comment]
不客气
