### ISSUE TITLE
Kong UI is not working.

### ISSUE THREAD

**Issue by YC7225** [PaddlePaddle/Serving#1462]
I have tried docker auth tutorial kong ui for me https://127.0.0.1:8001 not working me. its showing nothing to me any idea how can i check and get the tokens key for api call?

**Comment by bjjwwang** [comment]
it should be  https://127.0.0.1:8005

**Comment by YC7225** [comment]
working thanks! can i use this to do changes without konga normal openssl i am sharing example here :- http://technotes.videreresearch.com/security/securing-grpc-connection-with-ssl-a-python-example

**Comment by bjjwwang** [comment]
Thanks for sharing.
Sorry that I am not very familiar with stuff related to openssl. I will have a try and tell you an answer.

And if you wanna have a try, I guess you should checkout "python/pipeline/pipeline_server.py" and "python/pipeline/pipeline_client.py".

**Comment by YC7225** [comment]
i am getting some grpc issue after doing changes :- 
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "connections to all backends failing"
        debug_error_string = "{"created":"@1635504972.644843820","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":4165,"referenced_errors":[{"created":"@1635504972.644840284","description":"connections to all backends failing","file":"src/core/ext/filters/client_channel/lb_policy/round_robin/round_robin.cc","file_line":335,"grpc_status":14}]}"
