### ISSUE TITLE
在serving中部署了OCR，最后只能得到识别的文字，怎样才能获得对于文字的位置，另外多个预测出来的结果的顺序会不会变

### ISSUE THREAD

**Issue by pipishaw** [PaddlePaddle/Serving#1463]
1、在serving中部署了OCR，最后只能得到识别的文字，怎样才能获得对于文字的位置，
2、检测模型检测多个结果，识别模型预测出来的结果的顺序和检测模型给出的顺序是不是一样，（我试的结果是有时候一样，有时候不一样）

**Comment by ShiningZhang** [comment]
您好
1、可以自行修改代码，输出文字位置。位置信息保存在ocr_web_server.py中的dt_boxes。可根据自身需求进行输出。
2、检测模型结果进行后处理时有进行排序操作，具体逻辑可以参考ocr_web_server.py中的preprocess函数

**Comment by bikerr** [comment]
@ShiningZhang 
`
RecOp.postprocess(input_dicts, fetch_data, data_id, log_id)  
`方法参数中`input_dicts` 中`dt_boxes` 信息和`preprocess` 方法中信息不一致 是否可以提供下说明

**Comment by LiangDazhu** [comment]
@ShiningZhang @bikerr 麻烦问下， 
“RecOp.postprocess(input_dicts, fetch_data, data_id, log_id) 方法参数中input_dicts 中dt_boxes 信息和preprocess 方法中信息不一致”
 这个您解决了吗，我看官方文档说这两个参数应该是一致的， 但是实际打印发现是不一致的， 麻烦问下您是怎么解决的，谢谢啦

**Comment by Jaccica** [comment]
大佬，我只想输出得到的文字信息，不想要置信度信息和框信息，请问怎么修改代码？谢谢！
