### ISSUE TITLE
性能指示不明确，待改进

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/Serving#1471]
你好，我在查看关于[ocr服务](https://github.com/PaddlePaddle/Serving/blob/v0.7.0/python/examples/ocr/README_CN.md#:~:text=python3%20ocr_web_client.py-,%E6%80%A7%E8%83%BD%E6%8C%87%E6%A0%87,-CPU%3A%20Intel(R))的启动部署案例的时候，关于性能指标是CPU环境下还是GPU环境下的呢，这方面不清楚，望解答

**Comment by TeslaZhao** [comment]
感谢您的建议，性能指标是GPU下的

**Comment by BeyondYourself** [comment]
明白，谢谢解答
