### ISSUE TITLE
(NotFound) Cannot open file ../../../output/pp_rec_infer/__model__, please confirm whether the file is normal.

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/Serving#1477]
在windows上进行服务部署测试的时候出现下面的异常
`(NotFound) Cannot open file ../../../output/pp_rec_infer/__model__, please confirm whether the file is normal.`

其中paddle的版本为2.1，训练的模型也为新框架训练的模型
serving的版本为0.6.3
__model__应该是1.X预测保存的模型格式吧，2.X没有这种保存方法了吧

**Comment by BeyondYourself** [comment]
代码是直接在本地运行的，非docker部署

**Comment by BeyondYourself** [comment]
找到问题原因 了是因为预测模型没有转换成serving可用的模型。错误应该再提示一下是否进行模型转换，或者加一个校验，是否是适合serving直接可用的模型较为恰当

**Comment by TeslaZhao** [comment]
好的，我们加一下校验
