### ISSUE TITLE
部署单个模型，不用Pipeline是否会更好

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/Serving#1480]
在实际业务中会有多个模型的部署，有个疑问，如果只用单个模型部署，是否需要采用pipeline。这种有对比过效率吗

**Comment by TeslaZhao** [comment]
单模型用flask模式是可以的，可参考https://github.com/PaddlePaddle/Serving/blob/v0.6.0/doc/WINDOWS_TUTORIAL_CN.md

如果对吞吐或并发更高要求建议使用pipeline模式，对性能和并发有极致要求建议使用C++模式。
C++模式：

**Comment by BeyondYourself** [comment]
多谢大佬的耐心解答

**Comment by BeyondYourself** [comment]
![image](https://user-images.githubusercontent.com/12640462/141073355-c2186cb2-7b6e-45c2-8b48-990f57b0a1a3.png)
@TeslaZhao  现在webservice默认就是开启了pipeline了吧。目前没有办法直接不适用pipeline吧？
我的方法基本和上述你给的链接里的写法差不多，还是会有Pipeline的日志生成

> 单模型用flask模式是可以的，可参考https://github.com/PaddlePaddle/Serving/blob/v0.6.0/doc/WINDOWS_TUTORIAL_CN.md
> 
> 如果对吞吐或并发更高要求建议使用pipeline模式，对性能和并发有极致要求建议使用C++模式。 C++模式：

**Comment by TeslaZhao** [comment]
主要区别启动函数不同，Flask: run_rpc_service/run_web_service，Pipeline: run_service

参考
[bert示例](https://github.com/PaddlePaddle/Serving/blob/v0.6.0/python/examples/bert/bert_web_service_gpu.py)
[bert pipeline示例](https://github.com/PaddlePaddle/Serving/blob/v0.6.0/python/examples/pipeline/bert/web_service.py)
