### ISSUE TITLE
Paddle的Serving支持在paddlecloud上部署吗？

### ISSUE THREAD

**Issue by HuimengZhang** [PaddlePaddle/Serving#1491]
想在paddlecloud上部署一个NER服务，想问一下如何支持

**Comment by TeslaZhao** [comment]
您使用开源paddlecloud吗，还是百度内部paddle cloud?

**Comment by HuimengZhang** [comment]
百度内部paddle cloud

**Comment by TeslaZhao** [comment]
百度内部paddle cloud没有实际部署过，厂内的Opera环境是部署过的
