### ISSUE TITLE
基于PaddleServing的服务化部署识别模型，精度下降

### ISSUE THREAD

**Issue by lexiaoyuan** [PaddlePaddle/Serving#1530]
基于[PaddleOCR](https://github.com/PaddlePaddle/PaddleOCR)项目，使用自定义数据集和字典训练的识别模型，inference模型识别效果很好，参考[文档](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/deploy/pdserving/README_CN.md),，安装的环境：
```bash
pip3 install paddle-serving-server==0.6.1 # for CPU
pip3 install paddle-serving-client==0.6.3
pip3 install paddle-serving-app==0.6.3
```
模型转换和启动服务都是成功的。
发送服务请求之后
```
python3 pipeline_http_client.py
```
得到的结果如下：(10张图片有4张识别错误（多识别了一个字符或少识别了一个字符））
```
(paddle_env) watermeter@iZ2vc1hkgmux9pl3e4tngrZ:~/projects/PaddleOCR/deploy/pdserving$ python3 pipeline_http_client.py
{'err_no': 0, 'err_msg': '', 'key': ['res'], 'value': ["['0011']"]} # 识别错误
{'err_no': 0, 'err_msg': '', 'key': ['res'], 'value': ["['00011']"]}
{'err_no': 0, 'err_msg': '', 'key': ['res'], 'value': ["['80178']"]}
{'err_no': 0, 'err_msg': '', 'key': ['res'], 'value': ["['00118']"]}
{'err_no': 0, 'err_msg': '', 'key': ['res'], 'value': ["['001122']"]} # 识别错误
{'err_no': 0, 'err_msg': '', 'key': ['res'], 'value': ["['00119']"]}
{'err_no': 0, 'err_msg': '', 'key': ['res'], 'value': ["['00113']"]}
{'err_no': 0, 'err_msg': '', 'key': ['res'], 'value': ["['0011#']"]}
{'err_no': 0, 'err_msg': '', 'key': ['res'], 'value': ["['000034']"]} # 识别错误
{'err_no': 0, 'err_msg': '', 'key': ['res'], 'value': ["['001122']"]} # 识别错误
==> total number of test imgs:  10
```
补充：
检测模型和识别模型串联推理的效果是很好的，10张图片都是正确的。
串联推理：
```
python3 tools/infer/predict_system.py --image_dir="./doc/watermeter_test/det/" --det_model_dir="./inference/det_db_watermeter/" --rec_model_dir="./inference/rec_number_watermeter_ch/" --use_angle_cls=false --use_gpu=false
```
串联推理部分输出：
```
[2021/11/16 16:34:05] root INFO: 0011#, 0.952
[2021/11/16 16:34:08] root INFO: 00011, 0.906
[2021/11/16 16:34:09] root INFO: 00003, 0.881
[2021/11/16 16:34:10] root INFO: 80178, 0.937
[2021/11/16 16:34:12] root INFO: 00112, 0.908
[2021/11/16 16:34:15] root INFO: 00112, 0.941
[2021/11/16 16:34:17] root INFO: 0011#, 0.991
[2021/11/16 16:34:19] root INFO: 0011#, 0.999
[2021/11/16 16:34:21] root INFO: 00118, 0.883
[2021/11/16 16:34:23] root INFO: 00119, 0.969
[2021/11/16 16:34:25] root INFO: The predict total time is 21.36901330947876
[2021/11/16 16:34:25] root INFO:
The predict total time is 8.96869683265686
```

**Comment by lexiaoyuan** [comment]
补充：上述使用的推理模型是使用PaddleOCR中原始字典`ppocr/utils/ppocr_keys_v1.txt`训练得到的。
和这个问题[https://github.com/PaddlePaddle/Paddle-Lite/issues/7676](https://github.com/PaddlePaddle/Paddle-Lite/issues/7676)类似，如果使用自定义的字典训练，串联推理时，效果也很好。但是使用`paddle_serving_client.convert`转模型后，效果就变差了。

```
# 使用自定义的字典训练得到的推理模型串联推理
python3 tools/infer/predict_system.py --image_dir="./doc/watermeter_test/det/" --det_model_dir="./inference/det_db_watermeter/" --rec_model_dir="./inference/rec_number_watermeter/" --use_angle_cls=false --use_gpu=false --rec_char_type="ch" --rec_char_dict_path='ppocr/utils/dict/water_meter_number_dict.txt'
```
部分输出：（10张测试图片识别都是正确的）
```
[2021/11/18 20:45:28] root INFO: 0  Predict time of ./doc/watermeter_test/det/1634806777128.jpg: 1.255s
[2021/11/18 20:45:28] root INFO: 0011#, 0.983
[2021/11/18 20:45:32] root INFO: 1  Predict time of ./doc/watermeter_test/det/1634980422234395.jpg: 0.936s
[2021/11/18 20:45:32] root INFO: 00011, 1.000
[2021/11/18 20:45:32] root INFO: 2  Predict time of ./doc/watermeter_test/det/20200525142632.jpg: 0.566s
[2021/11/18 20:45:32] root INFO: 00003, 1.000
[2021/11/18 20:45:34] root INFO: 3  Predict time of ./doc/watermeter_test/det/22.jpg: 0.964s
[2021/11/18 20:45:34] root INFO: 80178, 0.988
[2021/11/18 20:45:36] root INFO: 4  Predict time of ./doc/watermeter_test/det/IMG20211021125209.jpg: 0.876s
[2021/11/18 20:45:36] root INFO: 00112, 0.978
[2021/11/18 20:45:38] root INFO: 5  Predict time of ./doc/watermeter_test/det/IMG20211021125216.jpg: 0.937s
[2021/11/18 20:45:38] root INFO: 00112, 0.994
[2021/11/18 20:45:40] root INFO: 6  Predict time of ./doc/watermeter_test/det/IMG20211021125628.jpg: 0.974s
[2021/11/18 20:45:40] root INFO: 0011#, 0.992
[2021/11/18 20:45:43] root INFO: 7  Predict time of ./doc/watermeter_test/det/IMG20211021125641.jpg: 0.928s
[2021/11/18 20:45:43] root INFO: 0011#, 1.000
[2021/11/18 20:45:45] root INFO: 8  Predict time of ./doc/watermeter_test/det/IMG20211023120327.jpg: 1.027s
[2021/11/18 20:45:45] root INFO: 00118, 0.990
[2021/11/18 20:45:47] root INFO: 9  Predict time of ./doc/watermeter_test/det/IMG20211023121227.jpg: 0.913s
[2021/11/18 20:45:47] root INFO: 00119, 0.925
The predict total time is 9.376071453094482
```
使用自定义字典训练得到的inference模型通过`paddle_serving_client.convert`转换成易于server部署的模型格式后，在[config.yml](https://github.com/PaddlePaddle/PaddleOCR/blob/8b3b7879c466e160567b59f0d388c25e97c7b44e/deploy/pdserving/config.yml#L63)中[web_service.py](https://github.com/PaddlePaddle/PaddleOCR/blob/8b3b7879c466e160567b59f0d388c25e97c7b44e/deploy/pdserving/web_service.py#L72)中配置了自定义训练得到的模型和字典，但是，识别模型的预测结果不好：（10张图片全部识别错误）
```
# 使用自定义的字典训练得到的推理模型转serving部署模型后预测结果：
{'err_no': 0, 'err_msg': '', 'key': ['res'], 'value': ["['0']"]}
{'err_no': 0, 'err_msg': '', 'key': ['res'], 'value': ["['0']"]}
{'err_no': 0, 'err_msg': '', 'key': ['res'], 'value': ["['80']"]}
{'err_no': 0, 'err_msg': '', 'key': ['res'], 'value': ["['0']"]}
{'err_no': 0, 'err_msg': '', 'key': ['res'], 'value': ["['0']"]}
{'err_no': 0, 'err_msg': '', 'key': ['res'], 'value': ["['0']"]}
{'err_no': 0, 'err_msg': '', 'key': ['res'], 'value': ["['00']"]}
{'err_no': 0, 'err_msg': '', 'key': ['res'], 'value': ["['0']"]}
{'err_no': 0, 'err_msg': '', 'key': ['res'], 'value': ["['0']"]}
{'err_no': 0, 'err_msg': '', 'key': ['res'], 'value': ["['0']"]}
==> total number of test imgs:  10
```
识别的结果和[https://github.com/PaddlePaddle/Paddle-Lite/issues/7676](https://github.com/PaddlePaddle/Paddle-Lite/issues/7676)中再Android中识别的结果一样。

**Comment by Yinyihang857** [comment]
> 补充：上述使用的推理模型是使用PaddleOCR中原始字典`ppocr/utils/ppocr_keys_v1.txt`训练得到的。 和这个问题[PaddlePaddle/Paddle-Lite#7676](https://github.com/PaddlePaddle/Paddle-Lite/issues/7676)类似，如果使用自定义的字典训练，串联推理时，效果也很好。但是使用`paddle_serving_client.convert`转模型后，效果就变差了。
> 
> ```
> # 使用自定义的字典训练得到的推理模型串联推理
> python3 tools/infer/predict_system.py --image_dir="./doc/watermeter_test/det/" --det_model_dir="./inference/det_db_watermeter/" --rec_model_dir="./inference/rec_number_watermeter/" --use_angle_cls=false --use_gpu=false --rec_char_type="ch" --rec_char_dict_path='ppocr/utils/dict/water_meter_number_dict.txt'
> ```
> 
> 部分输出：（10张测试图片识别都是正确的）
> 
> ```
> [2021/11/18 20:45:28] root INFO: 0  Predict time of ./doc/watermeter_test/det/1634806777128.jpg: 1.255s
> [2021/11/18 20:45:28] root INFO: 0011#, 0.983
> [2021/11/18 20:45:32] root INFO: 1  Predict time of ./doc/watermeter_test/det/1634980422234395.jpg: 0.936s
> [2021/11/18 20:45:32] root INFO: 00011, 1.000
> [2021/11/18 20:45:32] root INFO: 2  Predict time of ./doc/watermeter_test/det/20200525142632.jpg: 0.566s
> [2021/11/18 20:45:32] root INFO: 00003, 1.000
> [2021/11/18 20:45:34] root INFO: 3  Predict time of ./doc/watermeter_test/det/22.jpg: 0.964s
> [2021/11/18 20:45:34] root INFO: 80178, 0.988
> [2021/11/18 20:45:36] root INFO: 4  Predict time of ./doc/watermeter_test/det/IMG20211021125209.jpg: 0.876s
> [2021/11/18 20:45:36] root INFO: 00112, 0.978
> [2021/11/18 20:45:38] root INFO: 5  Predict time of ./doc/watermeter_test/det/IMG20211021125216.jpg: 0.937s
> [2021/11/18 20:45:38] root INFO: 00112, 0.994
> [2021/11/18 20:45:40] root INFO: 6  Predict time of ./doc/watermeter_test/det/IMG20211021125628.jpg: 0.974s
> [2021/11/18 20:45:40] root INFO: 0011#, 0.992
> [2021/11/18 20:45:43] root INFO: 7  Predict time of ./doc/watermeter_test/det/IMG20211021125641.jpg: 0.928s
> [2021/11/18 20:45:43] root INFO: 0011#, 1.000
> [2021/11/18 20:45:45] root INFO: 8  Predict time of ./doc/watermeter_test/det/IMG20211023120327.jpg: 1.027s
> [2021/11/18 20:45:45] root INFO: 00118, 0.990
> [2021/11/18 20:45:47] root INFO: 9  Predict time of ./doc/watermeter_test/det/IMG20211023121227.jpg: 0.913s
> [2021/11/18 20:45:47] root INFO: 00119, 0.925
> The predict total time is 9.376071453094482
> ```
> 
> 使用自定义字典训练得到的inference模型通过`paddle_serving_client.convert`转换成易于server部署的模型格式后，在[config.yml](https://github.com/PaddlePaddle/PaddleOCR/blob/8b3b7879c466e160567b59f0d388c25e97c7b44e/deploy/pdserving/config.yml#L63)中[web_service.py](https://github.com/PaddlePaddle/PaddleOCR/blob/8b3b7879c466e160567b59f0d388c25e97c7b44e/deploy/pdserving/web_service.py#L72)中配置了自定义训练得到的模型和字典，但是，识别模型的预测结果不好：（10张图片全部识别错误）
> 
> ```
> # 使用自定义的字典训练得到的推理模型转serving部署模型后预测结果：
> {'err_no': 0, 'err_msg': '', 'key': ['res'], 'value': ["['0']"]}
> {'err_no': 0, 'err_msg': '', 'key': ['res'], 'value': ["['0']"]}
> {'err_no': 0, 'err_msg': '', 'key': ['res'], 'value': ["['80']"]}
> {'err_no': 0, 'err_msg': '', 'key': ['res'], 'value': ["['0']"]}
> {'err_no': 0, 'err_msg': '', 'key': ['res'], 'value': ["['0']"]}
> {'err_no': 0, 'err_msg': '', 'key': ['res'], 'value': ["['0']"]}
> {'err_no': 0, 'err_msg': '', 'key': ['res'], 'value': ["['00']"]}
> {'err_no': 0, 'err_msg': '', 'key': ['res'], 'value': ["['0']"]}
> {'err_no': 0, 'err_msg': '', 'key': ['res'], 'value': ["['0']"]}
> {'err_no': 0, 'err_msg': '', 'key': ['res'], 'value': ["['0']"]}
> ==> total number of test imgs:  10
> ```
> 
> 识别的结果和[PaddlePaddle/Paddle-Lite#7676](https://github.com/PaddlePaddle/Paddle-Lite/issues/7676)中再Android中识别的结果一样。

hello兄弟，我在部署过程中也遇见了和你同样的问题，通过paddle_serving_client.convert转模型后，识别精度和结果不好的问题，你这个最后是怎么解决的呢？

**Comment by Jaccica** [comment]
您好，请问这个问题如何解决的呢？谢谢！
