### ISSUE TITLE
GetClientConfig好像没有了？

### ISSUE THREAD

**Issue by OptimusV5** [PaddlePaddle/Serving#1531]
GetClientConfig接口在0.7.0版本里面找不到了？是不提供了么？那只能读本地模型配置文件么？

**Comment by ShiningZhang** [comment]
> GetClientConfig

您好，当前只支持使用本地模型配置文件了，不再提供GetClientConfig接口

**Comment by TeslaZhao** [comment]
https://github.com/PaddlePaddle/Serving/blob/v0.7.0/doc/Serving_Configure_CN.md
