### ISSUE TITLE
How to get serving-gateway/proto? in proxy_server.go

### ISSUE THREAD

**Issue by YC7225** [PaddlePaddle/Serving#1533]
How to get serving-gateway/proto? in proxy_server.go

using go get for package initialization?

**Comment by felixhjh** [comment]
Please refer to [util.py](https://github.com/PaddlePaddle/Serving/blob/v0.7.0/python/util.py)   
def  gen_pipeline_code(package_name):

**Comment by YC7225** [comment]
not working stil showing serving-gateway not found.

**Comment by felixhjh** [comment]
Actually, in def gen_pipeline_code(package_name) 
the command `go mod init serving-gateway & go mod vendor && go mod tidy`  is to create serving-gateway module
Howerver if you want to build libproxy_server.so after that, There are several dependencies, the most easiest way is to refer [Compile_CN](https://github.com/PaddlePaddle/Serving/blob/v0.7.0/doc/Compile_CN.md) to compile PaddleServing. After compiling,  you will find  `gateway.pb.go` `gateway.pb.gw.go` in `python/paddle_serving_server/pipeline/gateway/proto`.  Then libproxy_server.so can be built successfully.

**Comment by YC7225** [comment]
i guess i have some path issue is that :- serving-gateway/proto: package serving-gateway/proto is not in GOROOT (/usr/local/go/src/serving-gateway/proto)? or is it correct?

**Comment by felixhjh** [comment]
I don't think so. Actually, go.mod is to manage dependencies outside $GOPATH/src. I suggest you read about the [official document about Using Go Modules](https://go.dev/blog/using-go-modules). It will be much helpful for you.
