### ISSUE TITLE
异构环境适配需求

### ISSUE THREAD

**Issue by ponycloud235** [PaddlePaddle/Serving#1534]
我们这样有十几台的服务器是x86+华为Ascend 310的异构架构运行paddle框架需求，考虑适配下？ 
目前是采用paddlite方式进行适配

**Comment by ShiningZhang** [comment]
您好，本季度计划进行arm+ascend310的适配，后边会考虑将x86+ascend310适配加入计划中，敬请期待。

**Comment by ponycloud235** [comment]
> 后边会考虑将x86+ascend310适配加

好的，谢谢。
