### ISSUE TITLE
启动服务端，加载模型异常

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/Serving#1548]
在远程启动服务的时候，在加载模型的时候出现以下异常，在其他服务器上用同样的模型配置，可以正常启动。
求教各位解答，谢谢

![image](https://user-images.githubusercontent.com/12640462/144784628-0c6096b7-a6de-433c-a728-682d5657da85.png)

**Comment by BeyondYourself** [comment]
![image](https://user-images.githubusercontent.com/12640462/144963042-824b057b-87cf-4899-9c29-03572901f1d5.png)
这个是完整的打印信息

采用wheel离线方式安装的

**Comment by BeyondYourself** [comment]
另外上述还有一个问题就是采用serving的模型转换代码，
![image](https://user-images.githubusercontent.com/12640462/144975633-f5af89e4-8e4c-47f2-aed1-6c2b86b48aed.png)

没有成功转换模型，只是把模型复制了一遍，这个是什么原因呢

**Comment by TeslaZhao** [comment]
使用的Paddle的版本，以及Serving的版本是？

**Comment by TeslaZhao** [comment]
转换模型过程有报错吗？

**Comment by BeyondYourself** [comment]
paddle 和serviing 都是用的最新的稳定版本。模型转换过程没有报错。我在其他服务器上用同样的代码就可以，唯独有一台机器不能转换模型。
服务启动后，抛出上面的一异常，最后还有个很大的core文件生成

**Comment by TeslaZhao** [comment]
core的信息截图发一下吗？还有这台报错的机器和其他机器有哪些不同呢？

**Comment by 1019058432** [comment]
@TeslaZhao 您好，我在转换ch_ppocr_server_v2.0_det_infer和ch_ppocr_server_v2.0_rec_infer模型到Serving模型时很顺利，但在启动服务时查看日志rec初始化失败了，请问我该如何操作才能获得正确的模型并且正常启动服务呢？
![05AF919C-6A27-462c-818E-15A5C64DDDD3](https://user-images.githubusercontent.com/61678719/148034945-471b28fc-dee6-4206-8be8-6799b03e38a1.png)
![96B1FE3B-07F9-4c18-AC32-FE8BA2F67C51](https://user-images.githubusercontent.com/61678719/148034961-e8ea4e5d-7958-4f7e-bf82-8772c6ce6cf0.png)

**Comment by BeyondYourself** [comment]
> 

你这个目前是没有找到数据字典，建议字典先配置成绝对路径试试

**Comment by 1019058432** [comment]
> > 
> 
> 你这个目前是没有找到数据字典，建议字典先配置成绝对路径试试

谢谢，有效。另外向请问inference模型转换到Serving的模型时是否需要修改代码？我启动服务端后查看日志无报错，但在运行http客户端的时候出现了如：
[https://github.com/PaddlePaddle/Serving/issues/1368#issue-982486235](url)
一样的错误

**Comment by BeyondYourself** [comment]
> > > 
> > 
> > 
> > 你这个目前是没有找到数据字典，建议字典先配置成绝对路径试试
> 
> 谢谢，有效。另外向请问inference模型转换到Serving的模型时是否需要修改代码？我启动服务端后查看日志无报错，但在运行http客户端的时候出现了如： [https://github.com/PaddlePaddle/Serving/issues/1368#issue-982486235](url) 一样的错误

一般模型转换是不需要修改相关的东西，只要把转换路径以及待转换的模型写好即可。你的问题可以发出来看看具体是什么吗，1386这个issue里写的有点杂

**Comment by 1019058432** [comment]
您好，这是启动http链接后出现的错误信息
![D5999AA1-1D6B-4c56-989B-8FA51901EC14](https://user-images.githubusercontent.com/61678719/148165316-6647d124-327c-467a-a298-03c2e38b1910.png)
![1CE4B8BE-735E-4779-A94F-372704AEE1F1](https://user-images.githubusercontent.com/61678719/148165486-d781aa5a-3a74-40c4-b33d-e1b56326d211.png)

**Comment by BeyondYourself** [comment]
> 您好，这是启动http链接后出现的错误信息 ![D5999AA1-1D6B-4c56-989B-8FA51901EC14](https://user-images.githubusercontent.com/61678719/148165316-6647d124-327c-467a-a298-03c2e38b1910.png) ![1CE4B8BE-735E-4779-A94F-372704AEE1F1](https://user-images.githubusercontent.com/61678719/148165486-d781aa5a-3a74-40c4-b33d-e1b56326d211.png)


这个应该是需要设置你的key吧，paddleserving转换后生成的poto文件中，默认image好像命名为x,你可以将这部分命名统一

**Comment by 1019058432** [comment]
好的，我试了一下吧服务端web_service.py中的image该成proto文件中的feed_var命名x后确实有变化了，我继续改完试试，非常感谢
