### ISSUE TITLE
房价预测例子使用HTTP不能走通

### ISSUE THREAD

**Issue by snoopy1316** [PaddlePaddle/Serving#1553]
使用docker，paddle Serving 0.7.0，按照文档一步一步走下来，在使用HTTP方法预测房价时在服务端输入python3 -m paddle_serving_server.serve --model uci_housing_model --thread 10 --port 9292 --name uci
出现
![image](https://user-images.githubusercontent.com/94336500/145175358-5dcb91d3-b554-49a6-a28e-ad55472c7bd3.png)
![image](https://user-images.githubusercontent.com/94336500/145175756-28205cd8-b2c4-49b0-a299-448b32f98fcf.png)

**Comment by snoopy1316** [comment]
参考文档：https://github.com/PaddlePaddle/Serving/blob/v0.7.0/doc/Quick_Start_CN.md

**Comment by TeslaZhao** [comment]
您好，我们的文档有点问题，请把--name  uci去掉。

使用的paddle serving的版本是v0.7.0吗？

**Comment by snoopy1316** [comment]
> 

对，是最新版本
