### ISSUE TITLE
serving部署自己的模型预测发生错误

### ISSUE THREAD

**Issue by wxf764571829** [PaddlePaddle/Serving#1559]
client端：
I1210 16:46:38.004170 23575 naming_service_thread.cpp:202] brpc::policy::ListNamingService("127.0.0.1:9292"): added 1
I1210 16:46:39.292992 23575 general_model.cpp:490] [client]logid=0,client_cost=1244.69ms,
{}
Traceback (most recent call last):
  File "../../deploy/serving/test_client.py", line 75, in <module>
    postprocess(fetch_map)
  File "/home/ubuntu01/anaconda3/envs/paddleserving/lib/python3.8/site-packages/paddle_serving_app/reader/image_reader.py", line 426, in __call__
    bbox_result = self._get_bbox_result(image_with_bbox, fetch_name,
  File "/home/ubuntu01/anaconda3/envs/paddleserving/lib/python3.8/site-packages/paddle_serving_app/reader/image_reader.py", line 343, in _get_bbox_result
    output = fetch_map[fetch_name]
KeyError: ''

服务端：
Error Message Summary:
----------------------
InvalidArgumentError: The 'shape' attribute in ReshapeOp is invalid. The input tensor X'size must be divisible by known capacity of 'shape'. But received X's shape = [1, 33, 19, 19], X's size = 11913, 'shape' is [-1, 3, 11, 400], known capacity of 'shape' is -13200.
  [Hint: Expected output_shape[unk_dim_idx] * capacity == -in_size, but received output_shape[unk_dim_idx] * capacity:0 != -in_size:-11913.] (at /paddle/paddle/fluid/operators/reshape_op.cc:210)
  [operator < reshape2 > error]
Aborted (core dumped)

请求大佬们帮忙看下，万分感谢

**Comment by HexToString** [comment]
看报错信息，你这个要么是模型的问题，要么是输入的问题，可能与Serving的关系不太大。

**Comment by wxf764571829** [comment]
> 看报错信息，你这个要么是模型的问题，要么是输入的问题，可能与Serving的关系不太大。

  我这边检查过了 模型本身没问题，我也重新按照这里的文档进行了模型转换https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/deploy/serving，输入的我这边只是借用训练的图片来测试，测试代码在这基础上进行的基础修改：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/deploy/serving/test_client.py

**Comment by wxf764571829** [comment]
> 看报错信息，你这个要么是模型的问题，要么是输入的问题，可能与Serving的关系不太大。

大佬，serving预测框和本地预测结果偏移了很多，这个情况是什么原因导致的呢？有什么解决途径吗？

**Comment by wxf764571829** [comment]
> 看报错信息，你这个要么是模型的问题，要么是输入的问题，可能与Serving的关系不太大。

另外这里的preprocess中的resize该如何合理设置呢？这里设置不当就会出现我最开始的那个问题 也就是您说的输入问题

**Comment by wxf764571829** [comment]
> 看报错信息，你这个要么是模型的问题，要么是输入的问题，可能与Serving的关系不太大。
另外预测有的图片时发生以下错误
paddle_serving_app/reader/image_reader.py", line 344, in _get_bbox_result
    lod = [fetch_map[fetch_name + '.lod']]
KeyError: 'save_infer_model/scale_0.tmp_1.lod'

**Comment by TeslaZhao** [comment]
您好，先加入微信群，帖一下配置和代码，帮你分析。
![image](https://user-images.githubusercontent.com/6309021/145923340-d6be607e-0044-46d9-895d-835e05497e59.png)

**Comment by wxf764571829** [comment]
> 您好，先加入微信群，帖一下配置和代码，帮你分析。 ![image](https://user-images.githubusercontent.com/6309021/145923340-d6be607e-0044-46d9-895d-835e05497e59.png)

非常感谢您的帮助

**Comment by fanruifeng** [comment]
> 

你好, 请问下这个问题解决了嘛  我目前部署的时候  也报这个错误
