### ISSUE TITLE
部署安装paddleServing v0.7.0，在paddleOCR例子中，获取模型之后，开启服务异常

### ISSUE THREAD

**Issue by snoopy1316** [PaddlePaddle/Serving#1561]
在linux中docker内部署安装paddleServing v0.7.0，在paddleOCR例子中，获取模型之后，开启服务，输入python3 web_service.py，显示
![image](https://user-images.githubusercontent.com/94336500/145768996-44ca3d27-5391-4de1-bbb9-32c61817d20e.png)
在客户端输入python3 pipeline_http_client.py，无任何响应

**Comment by TeslaZhao** [comment]
https://github.com/PaddlePaddle/Serving/blob/v0.7.0/doc/Python_Pipeline/Pipeline_Design_CN.md#5%E6%97%A5%E5%BF%97%E8%BF%BD%E8%B8%AA

您好，使用tail -1000 PipelineServingLogs/pipeline.log.wf 查看具体的错误信息
