### ISSUE TITLE
paddle detection 进行serving部署时产生的问题 

### ISSUE THREAD

**Issue by snoopy1316** [PaddlePaddle/Serving#1564]
使用paddle servingv0.7.0,在docker中部署，在启动服务端时，显示没有paddle_serving_server模块，但是在使用serving时已经下载了，在路径中可查，具体情况如下：
![image](https://user-images.githubusercontent.com/94336500/146290983-4214a0c1-028d-42c6-9a2c-c5690e811eda.png)
![image](https://user-images.githubusercontent.com/94336500/146291019-0409a416-667c-4344-8d92-a5d70b89278d.png)
请教该如何解决
参考文档:https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/deploy/serving
https://github.com/PaddlePaddle/Serving/blob/v0.7.0/doc/Quick_Start_CN.md

**Comment by bjjwwang** [comment]
这两个不是一个python
/usr/bin/python 应该是python2.7
应该用 python3.6 paddle_serving_server*****

**Comment by snoopy1316** [comment]
> 这两个不是一个python /usr/bin/python 应该是python2.7 应该用 python3.6 paddle_serving_server****
我是按照教程来安装，遇到这样的情况，应该怎么指定版本呢
