### ISSUE TITLE
使用PaddleServing v0.7.0,dui paddledetection部署serving 服务，并使用Java的客户端

### ISSUE THREAD

**Issue by snoopy1316** [PaddlePaddle/Serving#1574]
在serving端使用python3 -m paddle_serving_server.serve --model serving_server --port 9494 --gpu_ids 0开启服务，另一台电脑在客户端具体应该怎么做

在第二个链接使用的预测房价中客户端语句 ：
cd ../../../java/examples/target
java -cp paddle-serving-sdk-java-examples-0.0.1-jar-with-dependencies.jar PipelineClientExample indarray_predict
现在更换PaddleDetection，用Java客户端端口号以及IP怎样设置

参考链接：https://github.com/PaddlePaddle/Serving/tree/v0.7.0/examples/C%2B%2B/PaddleDetection/yolov3_darknet53_270e_coco
https://github.com/PaddlePaddle/Serving/blob/v0.7.0/java/README_CN.md

（Paddle Detection 服务端和客户端用两台电脑进行）

**Comment by HexToString** [comment]
感觉您这个有点混乱，首先，您应该知道您使用的到底是C++BRPC-Server,还是Python Pipeline Server。
按照您的启动命令，python3 -m paddle_serving_server.serve --model serving_server --port 9494 --gpu_ids 0，您使用的是C++ Server，这时候请参考
https://github.com/PaddlePaddle/Serving/blob/v0.7.0/java/README_CN.md#%E8%AF%B7%E6%B1%82brpc-server
和
https://github.com/PaddlePaddle/Serving/blob/v0.7.0/java/examples/src/main/java/PaddleServingClientExample.java
来编写您自己的Java Client代码。

代码只是一个简单的示例，供您参考。
您需要的输入数据的处理、端口号IP的修改、后处理等等一系列操作都需要您在代码中修改，然后编译。重新执行。
