### ISSUE TITLE
串联服务

### ISSUE THREAD

**Issue by ZTurboX** [PaddlePaddle/Serving#1591]
搭建pipline串联服务，是如何加载模型的?没有找到加载模型的方法

**Comment by TeslaZhao** [comment]
您好，python pipeline模型加载模型通过config.yml 中指定model_config: ResNet50_vd/ppcls_model/ 即可

https://github.com/PaddlePaddle/Serving/blob/v0.7.0/examples/Pipeline/PaddleClas/ResNet50_vd/config.yml
