### ISSUE TITLE
编译 paddle-serving-server 出错

### ISSUE THREAD

**Issue by CharlesWu123** [PaddlePaddle/Serving#1593]
我没有修改任何文件，使用的是 paddlepaddle/serving:0.7.0-cuda11.2-cudnn8-devel 镜像，在编译 paddle-serving-server 的时候出错
<img width="942" alt="wecom-temp-d8d5e9fec10c760cd028edc4062264ca" src="https://user-images.githubusercontent.com/38948322/149897976-c4996e11-1eb6-4320-bff3-562772b20547.png">

按照 https://github.com/PaddlePaddle/Serving/blob/v0.7.0/doc/Compile_CN.md 这个文档进行编译的

**Comment by TeslaZhao** [comment]
需要开代理，看日志是git资源下载的问题

**Comment by Yinyihang857** [comment]
> 我没有修改任何文件，使用的是 paddlepaddle/serving:0.7.0-cuda11.2-cudnn8-devel 镜像，在编译 paddle-serving-server 的时候出错 <img alt="wecom-temp-d8d5e9fec10c760cd028edc4062264ca" width="942" src="https://user-images.githubusercontent.com/38948322/149897976-c4996e11-1eb6-4320-bff3-562772b20547.png">
> 
> 按照 https://github.com/PaddlePaddle/Serving/blob/v0.7.0/doc/Compile_CN.md 这个文档进行编译的

您这个问题解决了吗？我开代理了也是编译失败

**Comment by pupubushilulu** [comment]
请问问题解决了吗 我开了代理也编译失败
