### ISSUE TITLE
如何使用http服务远程访问

### ISSUE THREAD

**Issue by Huihuihh** [PaddlePaddle/Serving#1599]
针对yolov3模型，执行命令`python -m paddle_serving_server_gpu.serve --model serving_server/ --port 9393 --gpu_id 0`后，启动了一个服务端，如何远程访问服务进行推理

**Comment by TeslaZhao** [comment]
您好，可以参考examples:

1.yolov3_darknet53_270e_coco
https://github.com/PaddlePaddle/Serving/tree/v0.7.0/examples/C%2B%2B/PaddleDetection/yolov3_darknet53_270e_coco

2.yolov4
https://github.com/PaddlePaddle/Serving/tree/v0.7.0/examples/C%2B%2B/PaddleDetection/yolov4

**Comment by Huihuihh** [comment]
> 您好，可以参考examples:
> 
> 1.yolov3_darknet53_270e_coco https://github.com/PaddlePaddle/Serving/tree/v0.7.0/examples/C%2B%2B/PaddleDetection/yolov3_darknet53_270e_coco
> 
> 2.yolov4 https://github.com/PaddlePaddle/Serving/tree/v0.7.0/examples/C%2B%2B/PaddleDetection/yolov4

无法满足我的需求，我是使用的这个例子，我想知道启动一个服务之后，如何远程服务器进行访问推理

**Comment by HexToString** [comment]
首先，您使用的可能还是老版本的paddle serving吧，在新的0.7.0版本中，直接启动服务端即可支持HTTP远程访问。

https://github.com/PaddlePaddle/Serving/blob/v0.7.0/doc/C%2B%2B_Serving/Http_Service_CN.md

**Comment by Yan-Ke** [comment]
> 首先，您使用的可能还是老版本的paddle serving吧，在新的0.7.0版本中，直接启动服务端即可支持HTTP远程访问。
> 
> https://github.com/PaddlePaddle/Serving/blob/v0.7.0/doc/C%2B%2B_Serving/Http_Service_CN.md

请问参数和路径是怎么传递的，有没有说明文档?
