### ISSUE TITLE
关于编译SDK-CPP部分时的错误

### ISSUE THREAD

**Issue by joelyang97** [PaddlePaddle/Serving#16]
一些环境信息
系统:Ubuntu 16.04.5 LTS
gcc/g++: 5.4.0
cmake: 3.5.1
python: 2.7.12

出现的情况
CMake过程中没有错误，顺利完成Configure。之后在make的过程中，前面是正常的，但是在编译SDK-CPP部分的时候会报出一些编译错误。下面截取其中主要的一些报错信息(基本都是语法错误)：
1 /usr/include/c++/5/backward/hash_fun.h:136:12: error: previous definition of ‘struct __gnu_cxx::hash<int>’
     struct hash<int>
2 serving/build/third_party/install/brpc/include/butil/strings/string_piece.h:416:70: error: ‘bool butil::operator!=(const StringPiece16&, const StringPiece16&)’ must have an argument of class or enumerated type
 inline bool operator!=(const StringPiece16& x, const StringPiece16& y) {
3 serving/build/third_party/install/brpc/include/butil/strings/string_piece.h:378:53: error: ‘string16’ was not declared in this scope
 extern template class BUTIL_EXPORT BasicStringPiece<string16>;
4 serving/build/third_party/install/brpc/include/butil/strings/string16.h:180:25: error: ‘basic_string’ is not a class template
 class BUTIL_EXPORT std::basic_string<butil::char16, butil::string16_char_traits>;

个人的想法
个人是觉得是由于自己的环境导致的，但是在CMake自动配置的时候没有报错。所以，想请您给一些建议，或者将您编译成功的环境告知一下(gcc版本，系统版本等)。

**Comment by wangguibao** [comment]
Serving还没有在gcc 5上验证过，我们开发编译用的环境是gcc 4.8.2
我们尽快想办法在gcc 5上验一下，抱歉

**Comment by joelyang97** [comment]
> Serving还没有在gcc 5上验证过，我们开发编译用的环境是gcc 4.8.2
> 我们尽快想办法在gcc 5上验一下，抱歉

没关系。我换成GCC4.8.2试一下。感谢您和您所在的团队所做的开发和开源工作。

**Comment by wangguibao** [comment]
本地用gcc 5.2编译依赖模块brpc时不通过，报如下错误
```
In file included from Serving/build/third_party/brpc/src/extern_brpc/src/brpc/policy/dh.cpp:20:0:
Serving/build/third_party/brpc/src/extern_brpc/src/butil/ssl_compat.h: In function ‘int EVP_PKEY_base_id(const EVP_PKEY*)’:
Serving/build/third_party/brpc/src/extern_brpc/src/butil/ssl_compat.h:520:17: error: redefinition of ‘int EVP_PKEY_base_id(const EVP_PKEY*)’
 BRPC_INLINE int EVP_PKEY_base_id(const EVP_PKEY *pkey) {
                 ^
Serving/build/third_party/brpc/src/extern_brpc/src/butil/ssl_compat.h:516:17: note: ‘int EVP_PKEY_base_id(const EVP_PKEY*)’ previously defined here
 BRPC_INLINE int EVP_PKEY_base_id(const EVP_PKEY *pkey) {
                 ^
```

ssl_compat.h中确实有2个一样的函数定义，已经给brpc repo提issue，待修复中

**Comment by wangguibao** [comment]
@joelyang97
我在本地用 GCC 5.4.0编译了一遍工程，修复了一个build error #26 
但是除此之外，在编译sdk-cpp目录时，没有遇到你issue里贴的错误。。

**Comment by wangguibao** [comment]
> 本地用gcc 5.2编译依赖模块brpc时不通过，报如下错误
> 
> ```
> In file included from Serving/build/third_party/brpc/src/extern_brpc/src/brpc/policy/dh.cpp:20:0:
> Serving/build/third_party/brpc/src/extern_brpc/src/butil/ssl_compat.h: In function ‘int EVP_PKEY_base_id(const EVP_PKEY*)’:
> Serving/build/third_party/brpc/src/extern_brpc/src/butil/ssl_compat.h:520:17: error: redefinition of ‘int EVP_PKEY_base_id(const EVP_PKEY*)’
>  BRPC_INLINE int EVP_PKEY_base_id(const EVP_PKEY *pkey) {
>                  ^
> Serving/build/third_party/brpc/src/extern_brpc/src/butil/ssl_compat.h:516:17: note: ‘int EVP_PKEY_base_id(const EVP_PKEY*)’ previously defined here
>  BRPC_INLINE int EVP_PKEY_base_id(const EVP_PKEY *pkey) {
>                  ^
> ```
> 
> ssl_compat.h中确实有2个一样的函数定义，已经给brpc repo提issue，待修复中

BRPC的函数重复定义，brpc团队已经修复了
https://github.com/apache/incubator-brpc/issues/833

**Comment by joelyang97** [comment]
> > 本地用gcc 5.2编译依赖模块brpc时不通过，报如下错误
> > ```
> > In file included from Serving/build/third_party/brpc/src/extern_brpc/src/brpc/policy/dh.cpp:20:0:
> > Serving/build/third_party/brpc/src/extern_brpc/src/butil/ssl_compat.h: In function ‘int EVP_PKEY_base_id(const EVP_PKEY*)’:
> > Serving/build/third_party/brpc/src/extern_brpc/src/butil/ssl_compat.h:520:17: error: redefinition of ‘int EVP_PKEY_base_id(const EVP_PKEY*)’
> >  BRPC_INLINE int EVP_PKEY_base_id(const EVP_PKEY *pkey) {
> >                  ^
> > Serving/build/third_party/brpc/src/extern_brpc/src/butil/ssl_compat.h:516:17: note: ‘int EVP_PKEY_base_id(const EVP_PKEY*)’ previously defined here
> >  BRPC_INLINE int EVP_PKEY_base_id(const EVP_PKEY *pkey) {
> >                  ^
> > ```
> > 
> > 
> > ssl_compat.h中确实有2个一样的函数定义，已经给brpc repo提issue，待修复中
> 
> BRPC的函数重复定义，brpc团队已经修复了
> [apache/incubator-brpc#833](https://github.com/apache/incubator-brpc/issues/833)

感谢您的工作。我自己尝试一下，应该是我这边的环境问题了。如果我成功了，我会把这issue关掉。我会积极向您反馈。

**Comment by joelyang97** [comment]
昨晚编译成功。
具体环境为: 
ubuntu14.04 64位
g++/gcc 4.8
cmake 3.5
同时在过程中发现需要安装几个依赖的库用下面的命令安装:
sudo apt-get install libbz2-dev libssl-dev

两个小的建议:
1. 同时建议后期可以把链接库改为动态链接库，在编译链接过程中如果是链接静态库，不知道为什么demo-client这个项目下面，有关链接到libbrpc.a这个静态库的链接都会报ssl相关函数未定义的错误。明明brpc编译是没有问题的。我的解决办法是把所有的link.txt和relink.txt中的链接libbrpc.a的项都链接到libbrpc.so动态链接库上。
2.建议修改一下CMakeList文件，将各个项目的安装目录定位到/usr/local中。现在编译安装后，我还得重新修改LD_LIBRARY_PATH等系统环境变量，以定位到各种库文件和头文件。如果能修改CMakeList让他们都安装在/usr/local目录下或者自动化添加环境变量，就太好了。可以省去用户很多事情。

最后一个闲谈，
发现了一个很奇怪的事情是,在ubuntu16.04和ubuntu18.04上编译时，编译的顺序好像和ubuntu14.04不太一样。不知道是不是因为这个导致高版本编译失败。

最后，感谢您和您的团队的努力和工作。辛苦了
