### ISSUE TITLE
OSError:  '/usr/lib/libproxy_server.so' (no such file)

### ISSUE THREAD

**Issue by ZTurboX** [PaddlePaddle/Serving#1607]
OS: macOS Monterey 12.1

该目录下存在libproxy_server.so，gcc version 8.5

用pipline方法报错
OSError: dlopen(/Users/zhentao/opt/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle_serving_server/pipeline/gateway/libproxy_server.so, 0x0006): tried: '/Users/zhentao/opt/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle_serving_server/pipeline/gateway/libproxy_server.so' (not a mach-o file), '/usr/local/lib/libproxy_server.so' (no such file), '/usr/lib/libproxy_server.so' (no such file)

**Comment by TeslaZhao** [comment]
你好，macOS系统下要使用linux docker上部署Serving，目前不支持原生mac部署

**Comment by mjwSilence** [comment]
> 你好，macOS系统下要使用linux docker上部署Serving，目前不支持原生mac部署

请问是什么意思？我也遇到了差不多的问题，mac本地跑程序不能去读.so文件吗？
