### ISSUE TITLE
启动 CPU Docker出错，求老师指点

### ISSUE THREAD

**Issue by lifloveyou** [PaddlePaddle/Serving#1612]
启动 CPU Docker操作中
执行命令docker pull paddlepaddle/serving:0.7.0-devel出现下方错误
Error response from daemon: Get https://registry-1.docker.io/v2/: x509: certificate is valid for *.jgj25ec6i17v8.us-east-1.cs.amazonlightsail.com, not registry-1.docker.i
使用的是虚拟机中的centos7系统，在其上安装了docker

**Comment by TeslaZhao** [comment]
你好，参考这2篇文档试试
https://blog.csdn.net/KEY0323/article/details/95949986
https://www.cnblogs.com/liuqingzheng/p/14818346.html
