### ISSUE TITLE
pipline client

### ISSUE THREAD

**Issue by ZTurboX** [PaddlePaddle/Serving#1613]
用pipline时，在client端调用server服务输出的结果用于业务逻辑，可否再包一层flask接口

**Comment by TeslaZhao** [comment]
包一层flask接口的目的是什么？

**Comment by ZTurboX** [comment]
> 包一层flask接口的目的是什么？

server只是用来部署服务的，client返回的模型输出用来处理业务层逻辑代码，flask接口用于外部调用
