### ISSUE TITLE
pip3 install -r python/requirements.txt报错

### ISSUE THREAD

**Issue by lifloveyou** [PaddlePaddle/Serving#1614]
执行pip3 install -r python/requirements.txt报如下错误
Could not find a version that satisfies the requirement grpcio-tools>=1.28.1 (from -r python/requirements.txt (line 7)) (from versions: )
No matching distribution found for grpcio-tools>=1.28.1 (from -r python/requirements.txt (line 7))

**Comment by TeslaZhao** [comment]
是不是因为mac os的原因，在linux docker里执行是没有问题的
![image](https://user-images.githubusercontent.com/6309021/151160445-161419e0-af48-4127-ac17-8f88d7bcb7db.png)

**Comment by lifloveyou** [comment]
> 是不是因为mac os的原因，在linux docker里执行是没有问题的 ![image](https://user-images.githubusercontent.com/6309021/151160445-161419e0-af48-4127-ac17-8f88d7bcb7db.png)

我是windows里的vwvare中装了一个centos7，centos中安装的docker。

**Comment by BeyondYourself** [comment]
可以先升级一下pip再试试
