### ISSUE TITLE
啥意思Message that will be displayed on users' first issue

### ISSUE THREAD

**Issue by lifloveyou** [PaddlePaddle/Serving#1615]
Message that will be displayed on users' first issue

_Originally posted by @github-actions[bot] in https://github.com/PaddlePaddle/Serving/issues/1612#issuecomment-1022060670_

**Comment by TeslaZhao** [comment]
#1612  issue已回复

Message that will be displayed on users' first issue
是机器人自动回复，忽略

**Comment by lifloveyou** [comment]
感谢
