### ISSUE TITLE
请问 TRACER中的in是代表什么

### ISSUE THREAD

**Issue by klw2020** [PaddlePaddle/Serving#1634]
为什么只有一次请求的时候in反而变大，还大于10秒了

![image](https://user-images.githubusercontent.com/53896985/153702048-8faffc35-75bf-4ce7-a928-c987e7415d80.png)
![image](https://user-images.githubusercontent.com/53896985/153702071-ceab988a-9dbf-432a-aa70-5cc948ae30fa.png)

**Comment by TeslaZhao** [comment]
已在微信群回复
