### ISSUE TITLE
自训练模型在serving部署后预测错误

### ISSUE THREAD

**Issue by zhaoyids** [PaddlePaddle/Serving#1638]
我训练用的是obj365里的cascade_rcnn_dcnv2_se154_vd_fpn_gn_cas.yml，报错
Traceback (most recent call last):
  File "test_client.py", line 38, in <module>
    fetch_map["image"] = sys.argv[1]
TypeError: 'NoneType' object does not support item assignment

这是client代码
import sys
import numpy as np
from paddle_serving_client import Client
from paddle_serving_app.reader import *
import cv2

preprocess = DetectionSequential([
    DetectionFile2Image(),
    DetectionNormalize([102.9801,115.9465,122.7717],[1.0,1.0,1.0],False),

#    DetectionTranspose((2, 0, 1)), DetectionPadStride(32)
])

postprocess = RCNNPostprocess("label_list.txt", "output")
client = Client()

client.load_client_config("../serving_client/serving_client_conf.prototxt")
client.connect(['127.0.0.1:9292'])
print(client)
print("----------------------------------------------------")
im, im_info = preprocess(sys.argv[1])
fetch_map = client.predict(
    feed={
        "image": im,

        "im_shape": np.array([320,480,1]),

        "im_info": np.array([480,640,2]),
    },
    fetch=["multiclass_nms_0.tmp_0"],
    batch=False)

print(fetch_map)
print(sys.argv[1])
fetch_map["image"] = sys.argv[1]
postprocess(fetch_map)

这是输入输出
feed_var {
  name: "image"
  alias_name: "image"
  is_lod_tensor: false
  feed_type: 1
  shape: 3
}
feed_var {
  name: "im_info"
  alias_name: "im_info"
  is_lod_tensor: false
  feed_type: 1
  shape: 3
}
feed_var {
  name: "im_shape"
  alias_name: "im_shape"
  is_lod_tensor: false
  feed_type: 1
  shape: 3
}
fetch_var {
  name: "multiclass_nms_0.tmp_0"
  alias_name: "multiclass_nms_0.tmp_0"
  is_lod_tensor: true
  fetch_type: 1
  shape: -1
}

**Comment by felixhjh** [comment]
1. 可以查看下log/serving*的log，具体报错在哪里，这边看是预测并未成功
2. 您方便给下模型的链接吗？这边需要自测一下
3. 加入Paddle Serving Github首页的serving官方微信群反馈问题回复会更加及时，高效

**Comment by zhaoyids** [comment]
谢谢答复，那个log文件夹下的serving.ERROR里的内容是这样的：
Log file created at: 2022/02/22 07:14:21
Running on machine: 3721b56fa86a
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0222 07:14:21.292266   328 cache.cpp:58] invalid cache path serving_server//cube_cache
~                                                                                              

另外，我第一次运行python3 test_client.py 1.jpg报错：
Traceback (most recent call last):
  File "test_client.py", line 39, in <module>
    postprocess(fetch_map)
  File "/usr/local/lib/python3.6/site-packages/paddle_serving_app/reader/image_reader.py", line 427, in __call__
    self.clsid2catid)
  File "/usr/local/lib/python3.6/site-packages/paddle_serving_app/reader/image_reader.py", line 343, in _get_bbox_result    output = fetch_map[fetch_name]
KeyError: ''

第二次以及以后运行python3 test_client.py 1.jpg报错：
Traceback (most recent call last):
  File "test_client.py", line 38, in <module>
    fetch_map["image"] = sys.argv[1]

然后我这里调试的时候发现打印结果里fetch_map打印出来是None，也就是client.predict()返回值为none，我觉得是我输入的feed不对，我这个配置文件的feed_var的shape都是3，我看GitHub例子里也没有shape=3的，所以我也不太清楚该怎么输入这个数据

对于第二点，我的模型是部署到我本机的docker上的，这个我不知道怎么给模型链接，不过我可以在aistudio上新建一个项目，把模型放在里面。

**Comment by ddgetget** [comment]
> 谢谢答复，那个log文件夹下的serving.ERROR里的内容是这样的： Log file created at: 2022/02/22 07:14:21 Running on machine: 3721b56fa86a Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg E0222 07:14:21.292266 328 cache.cpp:58] invalid cache path serving_server//cube_cache ~
> 
> 另外，我第一次运行python3 test_client.py 1.jpg报错： Traceback (most recent call last): File "test_client.py", line 39, in postprocess(fetch_map) File "/usr/local/lib/python3.6/site-packages/paddle_serving_app/reader/image_reader.py", line 427, in **call** self.clsid2catid) File "/usr/local/lib/python3.6/site-packages/paddle_serving_app/reader/image_reader.py", line 343, in _get_bbox_result output = fetch_map[fetch_name] KeyError: ''
> 
> 第二次以及以后运行python3 test_client.py 1.jpg报错： Traceback (most recent call last): File "test_client.py", line 38, in fetch_map["image"] = sys.argv[1]
> 
> 然后我这里调试的时候发现打印结果里fetch_map打印出来是None，也就是client.predict()返回值为none，我觉得是我输入的feed不对，我这个配置文件的feed_var的shape都是3，我看GitHub例子里也没有shape=3的，所以我也不太清楚该怎么输入这个数据
> 
> 对于第二点，我的模型是部署到我本机的docker上的，这个我不知道怎么给模型链接，不过我可以在aistudio上新建一个项目，把模型放在里面。

你的弄好了没，我自己训练另一个模型，也是这样的，无法识别这个key,但是官网的给的anki，所有的都可以运行
