### ISSUE TITLE
paddleServing JavaSdk 不可用

### ISSUE THREAD

**Issue by yqsoooo** [PaddlePaddle/Serving#1721]
paddle-serving-sdk-java-0.0.1.jar
![image](https://user-images.githubusercontent.com/15975613/158598086-7ed28dc6-2544-4368-8c4d-36a1269b8677.png)

引用Serving0.8.2版本的java examples里的PaddleServingClientExample.java  但好像这个jar包版本不对啊

**Comment by yqsoooo** [comment]
![image](https://user-images.githubusercontent.com/15975613/158599619-3c1a4554-49b3-467b-ae26-c89bfa8a3354.png)

**Comment by wangzhedong** [comment]
我也发现这个问题了，setIP方法根本就不存在，估计是百度自己偷偷改jar包了，但是没有更改版本号
