### ISSUE TITLE
0.8.2 版本的JAVA_SDK疑问

### ISSUE THREAD

**Issue by yqsoooo** [PaddlePaddle/Serving#1722]
通过Java_SDK_CN.md 
wget https://paddle-serving.bj.bcebos.com/jar/paddle-serving-sdk-java-0.0.1.jar

下载下来查看其中的Client对象和examples中的PaddleServingClientExample.java 完全对不上。

**Comment by yqsoooo** [comment]
![image](https://user-images.githubusercontent.com/15975613/158615604-92012f97-c616-4c2d-9065-3df34d67ecbe.png)
![image](https://user-images.githubusercontent.com/15975613/158615682-d5f1de5d-7485-4482-b1da-5e6bb3ea42d4.png)

**Comment by ChiTaoGIS** [comment]
你的Serving工程git pull 镜像不对，git pull，然后 编译一下就好
