### ISSUE TITLE
pipeline serving 0.7.0 rpc服务端启动错误

### ISSUE THREAD

**Issue by zhuangzheng** [PaddlePaddle/Serving#1723]
### 使用pipeline 部署OCR模型，client是local predictor正常执行，选rpc报错
![1](https://user-images.githubusercontent.com/22436644/158752370-f8d6d36a-336a-4433-9aac-cff1dd3bffb9.png)
pipeline日志是这样
![2](https://user-images.githubusercontent.com/22436644/158752385-1a3cfea7-8a51-444e-aa14-a79e4722bb8e.png)
unknown client type grpc

版本是:
-paddlepaddle==2.2.2, cpu
-serving==0.7.0
系统环境是Win10上的linux docker

**Comment by TeslaZhao** [comment]
您好，您Pip install的版本是v0.7.0，那么您使用的Serving 代码的版本是？
