### ISSUE TITLE
PaddleServingClientExample.java 编译错误

### ISSUE THREAD

**Issue by tfft2126** [PaddlePaddle/Serving#1725]
PaddleServingClientExample.java 里面使用的
io.paddle.serving.client.Client 没有setIP，setPort，loadClientConfig函数
jar包是paddle-serving-sdk-java-0.0.1.jar，顺便问一下有没有API地址

**Comment by HexToString** [comment]
https://github.com/PaddlePaddle/Serving/blob/v0.8.3/java/src/main/java/io/paddle/serving/client/Client.java

**Comment by HexToString** [comment]
使用v0.8.3的版本就可以

**Comment by tfft2126** [comment]
> 使用v0.8.3的版本就可以

我使用的jar包是这个，请问是版本不对吗？我把0.0.1改成0.8.3会找不到资源。https://paddle-serving.bj.bcebos.com/jar/paddle-serving-sdk-java-0.0.1.jar。  我看https://github.com/PaddlePaddle/Serving/blob/v0.8.3/doc/Java_SDK_EN.md是这么写的
