### ISSUE TITLE
关于Paddlle无法识别CUDA的问题

### ISSUE THREAD

**Issue by byteszard** [PaddlePaddle/Serving#1726]
第一次使用GPU资源部署PaddleOCR，出现了一些问题，多次尝试无法解决后求助。

- 宿主机是`ubuntu20.04`,只安装了`nvidia`驱动，没有安装`cuda`和`cudnn`。
- 使用官方镜像：`registry.baidubce.com/paddlepaddle/serving:0.8.0-cuda11.2-cudnn8-runtime`。

出现如下问题：

1. 问题一（docker启动时）：
![image](https://user-images.githubusercontent.com/16896367/158934432-792cd2e0-0f02-464c-a573-d097a890ee5c.png)

2. 问题二（docker启动后，送入图片预测）：
![image](https://user-images.githubusercontent.com/16896367/158934600-757f18fb-7645-4005-ac4c-ad3694396444.png)

在容器中执行`nvidia-smi`
![image](https://user-images.githubusercontent.com/16896367/158934723-2cb8ef69-0cba-4949-84c6-96979550311f.png)
镜像里的安装包
![image](https://user-images.githubusercontent.com/16896367/158936832-7c991190-046d-4879-8a27-959d8b3f96c3.png)

部分dockerfile代码如下：
```dockerfile
FROM registry.baidubce.com/paddlepaddle/serving:0.8.0-cuda11.2-cudnn8-runtime as serving

ENV TZ=Asia/Shanghai

RUN ln -s /usr/local/cuda/lib64/libcublas.so.11   /usr/lib/libcublas.so && \
    ln -s /usr/local/cuda/lib64/libcusolver.so.11   /usr/lib/libcusolver.so && \
    ln -s /usr/lib/x86_64-linux-gnu/libcudnn.so.8 /usr/lib/libcudnn.so

FROM serving as prepare

WORKDIR ppocr

RUN wget https://paddleocr.bj.bcebos.com/PP-OCRv2/chinese/ch_PP-OCRv2_det_infer.tar -O ch_PP-OCRv2_det_infer.tar && \
    tar -xf ch_PP-OCRv2_det_infer.tar && \
    wget https://paddleocr.bj.bcebos.com/PP-OCRv2/chinese/ch_PP-OCRv2_rec_infer.tar -O ch_PP-OCRv2_rec_infer.tar && \
    tar -xf ch_PP-OCRv2_rec_infer.tar && \
    ln -s /usr/local/bin/python3.7 /usr/local/bin/python && \
    python -m paddle_serving_client.convert --dirname ./ch_PP-OCRv2_det_infer/ \
                                         --model_filename inference.pdmodel          \
                                         --params_filename inference.pdiparams       \
                                         --serving_server ./ppocrv2_det_serving/ \
                                         --serving_client ./ppocrv2_det_client/ && \
    python -m paddle_serving_client.convert --dirname ./ch_PP-OCRv2_rec_infer/ \
                                         --model_filename inference.pdmodel          \
                                         --params_filename inference.pdiparams       \
                                         --serving_server ./ppocrv2_rec_serving/  \
                                         --serving_client ./ppocrv2_rec_client/ && \
    rm -rf *_infer.tar *_infer
```
启动命令尝试使用过如下几种方式，均无法解决；
1. `docker run -itd --gpus all`
2. `docker run -itd --gpus all -e NVIDIA_DRIVER_CAPABILITIES=compute,utility -e NVIDIA_VISIBLE_DEVICES=all`
3. `nvidia-docker run --runtime=nvidia`

**Comment by ShiningZhang** [comment]
这边看到送入图片预测时日志显示使用0卡执行了预测，也获取了正常结果

**Comment by byteszard** [comment]
> 

日志上的Warnning问题怎么处理，如果GPU能够识别，那docker启动时，paddle无法识别cuda问题那个Warnning怎么处理；而且还没有本地Mac上起docker，通过CPU预测速度快；通过日志可以看见，大量时间耗在`device_context`检查环境那块；
