### ISSUE TITLE
JAVA Client SDK使用问题。

### ISSUE THREAD

**Issue by yqsoooo** [PaddlePaddle/Serving#1729]
使用paddleServing 0.8.2  C++  部署了一个自训练的PPyolo_mb_Small模型。
使用/Serving/examples/C++/PaddleDetection/ppyolo_r50vd_dcn_1x_coco/test_client.py  修改resize尺寸后，可以正常使用
![image](https://user-images.githubusercontent.com/15975613/159264817-4c1ea9cf-5270-4c80-82ce-7a7dfb808907.png)
![image](https://user-images.githubusercontent.com/15975613/159265091-4e7eac9d-aec4-42cd-8370-abe41b2970e1.png)

但是使用java client sdk时，遇到一些问题。由于javaSDK只提供了yolov4的模型样例，我尝试修改了feedData。

代码如下
![image](https://user-images.githubusercontent.com/15975613/159265568-ab14774f-e727-4960-9c5f-0f476aad96d0.png)

serving_client_conf.prototxt内容
![image](https://user-images.githubusercontent.com/15975613/159265647-39769abb-7ed0-45b9-a6f7-8568202f44f0.png)

**Comment by yqsoooo** [comment]
？

**Comment by HexToString** [comment]
你是哪里有问题呢？

**Comment by HexToString** [comment]
在你截的图中没看到，你具体遇到了什么问题

**Comment by yqsoooo** [comment]
JAVA识别结果
![image](https://user-images.githubusercontent.com/15975613/159879141-1ae33dd0-45b8-42c4-bb2c-08d42f638de5.png)

![image](https://user-images.githubusercontent.com/15975613/159879014-cefc48d7-b792-47da-8bd9-f2ad17851f81.png)

**Comment by yqsoooo** [comment]
![image](https://user-images.githubusercontent.com/15975613/159878787-dc84aac0-a20c-4098-b386-2b6dcb236f13.png)
我猜测是不是我的feeddata 传输的有问题。 因为同样的图片 使用python client sdk可以预测成功

**Comment by yqsoooo** [comment]
等待回复

**Comment by zjyhll** [comment]
java里面怎么加这两个东西
 protected float[] inputMean = new float[]{0.485f, 0.456f, 0.406f};
protected float[] inputStd = new float[]{0.229f, 0.224f, 0.225f};
