### ISSUE TITLE
Exception: Op type general_reader is not supported right now

### ISSUE THREAD

**Issue by taoge2222** [PaddlePaddle/Serving#1730]
在0.83版serving的安装目录paddle-serving-server/dag.py的22行定义的self.op_list = [
            "GeneralInferOp",
            "GeneralReaderOp",
            "GeneralResponseOp",
            "GeneralTextReaderOp",
            "GeneralTextResponseOp",
            "GeneralSingleKVOp",
            "GeneralDistKVInferOp",
            "GeneralDistKVOp",
            "GeneralCopyOp",
            "GeneralDetectionOp",
        ]
以前版本定义的是字典格式，由于版本升级，的安装目录paddle-serving-server/pipeline/local_service_handler.py的285行-301行中的函数调用op_maker.create（）仍按照字典方式调用引起错误。
修改方法：
read_op = op_maker.create('GeneralReaderOp')
general_infer_op = op_maker.create('GeneralInferOp')
general_response_op = op_maker.create('GeneralResponseOp')

**Comment by HexToString** [comment]
你不仅自己解决了问题，还找到了原因，推荐你直接提个PR，我来给你审核通过，下个版本会把你作为贡献者加入到首页

**Comment by huaxiangsiyi** [comment]
改问题没提交修改后的版本吗？
