### ISSUE TITLE
ERROR: paddle_serving_client-0.8.3-cp37-none-any.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by mingo-doer** [PaddlePaddle/Serving#1741]
ERROR: paddle_serving_client-0.8.3-cp37-none-any.whl is not a supported wheel on this platform.

paddleocr的部署  安装失败
使用阿里云  linux 服务器

**Comment by TeslaZhao** [comment]
你好，在群里已沟通

**Comment by jiangbowen** [comment]
您好，怎么解决的，我也遇到相同的问题

**Comment by tingsi** [comment]
> 你好，在群里已沟通
> 您好，怎么解决的，我也遇到相同的问题

同问，怎么解决的？

**Comment by tingsi** [comment]
> > 你好，在群里已沟通
> > 您好，怎么解决的，我也遇到相同的问题
> 
> 同问，怎么解决的？

我这儿找到的解决办法：在
https://github.com/PaddlePaddle/Serving/blob/v0.8.3/doc/Latest_Packages_CN.md
这里找到完整的包列表，安装环境匹配的版本。

我的python是3.8的，默认演示给的是3.7的，会出现本issue提示的错误。  改成 3.8的包后顺利安装。
