### ISSUE TITLE
/site-packages/paddle_serving_server/serve.py中的binurl已经过期

### ISSUE THREAD

**Issue by lightbordwin** [PaddlePaddle/Serving#1743]
/site-packages/paddle_serving_server/serve.py 中的binurl使用的是https://paddle-serving.bj.bcebos.com/bin/serving-cpu-avx-mkl-0.8.3.tar.gz，这个地址已经无法访问，现在只能使用https://paddle-serving.bj.bcebos.com/test-dev/bin/serving-cpu-avx-mkl-0.8.3.tar.gz 请及时更新paddle_serving_server，不然第一次启动paddleserving的时候会出现无法下载bin的问题

**Comment by TeslaZhao** [comment]
您下载wheel安装会遇到这个问题，我们已经补充文件上去了，现在下载再安装就没问题了。通过pypi安装的wheel 是完全OK。
