### ISSUE TITLE
服务部署时，提示没有--name参数

### ISSUE THREAD

**Issue by yafeisong** [PaddlePaddle/Serving#1745]
python37 -m paddle_serving_server.serve --model uci_housing_model --thread 10 --port 9292 --name uci
/usr/local/python3/lib/python3.7/runpy.py:125: RuntimeWarning: 'paddle_serving_server.serve' found in sys.modules after import of package 'paddle_serving_server', but p                     rior to execution of 'paddle_serving_server.serve'; this may result in unpredictable behaviour
serve: error: unrecognized arguments: --name

**Comment by TeslaZhao** [comment]
您好，您使用的 Paddle Serving 版本太低。请更新到v0.8.3版本，不需要使用 --name，服务端会同时开启 http/rpc 服务。

快速开始：https://github.com/PaddlePaddle/Serving/blob/v0.8.3/doc/Quick_Start_EN.md
