### ISSUE TITLE
Failed to inference: Service name error.

### ISSUE THREAD

**Issue by Jnoee** [PaddlePaddle/Serving#1747]
从0.6.2升级到0.7.0，原来的正常的服务报这样的错，是什么原因呢？

**Comment by TeslaZhao** [comment]
您好，请发一下错误信息？

**Comment by Jnoee** [comment]
{
    "err_no": 7,
    "err_msg": "Failed to inference: Service name error.",
    "key": [],
    "value": [],
    "tensors": []
}

请求过去就返回这个，日志里看不到任何错误信息。

**Comment by Jnoee** [comment]
我这边是一个容器中同时启动多个服务，启动1-2个服务时没有这个问题，启动3-4个服务时就会出现该错误。在0.6.0的时候没有这个问题，升级到0.7.0以后出现该问题。

**Comment by Jnoee** [comment]
找到原因了，配置文件里没有设置rpc_port，同时启动多个服务时端口串了。
