### ISSUE TITLE
pip install failed pip安装失败

### ISSUE THREAD

**Issue by casolxia** [PaddlePaddle/Serving#175]
whl文件也搜不到
Looking in indexes: https://pypi.mirrors.ustc.edu.cn/simple/
Collecting paddle-serving-client
  ERROR: Could not find a version that satisfies the requirement paddle-serving-client (from versions: none)
ERROR: No matching distribution found for paddle-serving-client

**Comment by guru4elephant** [comment]
please check now, wheel packages uploaded. @casolxia
