### ISSUE TITLE
windows系统安装docker  paddleServing可以使用GPU吗？

### ISSUE THREAD

**Issue by meishitouzhele** [PaddlePaddle/Serving#1750]
windows系统安装docker  paddleServing可以使用GPU吗？我看paddleserving中使用docker需要安装nvidia-docker，但是win10系统是没办法安装nvidia-docker吧？  是不是就是说，win10系统如果想通过docker，只能使用cpu模式？
那么，win10系统如果想使用paddleServing的GPU模式，怎么才能行？

**Comment by TeslaZhao** [comment]
你说的对，windows不支持 nvidia-docker ，因此只能在原生windows系统上使用 Paddle Serving，我们提供了一种简单部署的方式，参考：https://github.com/PaddlePaddle/Serving/blob/develop/doc/Windows_Tutorial_CN.md

**Comment by meishitouzhele** [comment]
感谢
