### ISSUE TITLE
AttributeError: 'Program' object has no attribute '_remove_training_info'

### ISSUE THREAD

**Issue by Roly-Yang** [PaddlePaddle/Serving#1751]
My environment:
ubuntu 18.0  base on GPU
paddledetection==2.3.0
paddleserving==0.8.3
 --------------------------------------------------------------------------------------------
I want to export my model file,so I input:
python tools/export_model.py -c configs/ssd/ssd_mobilenet_v1_300_120e_voc.yml --output_dir=./inference_model -o weights=output/ssd_mobilenet_v1_300_120e_voc/model_final.pdparams --export_serving_model=True
----------------------------------------------------------------------------------------------
The question I met is as follow:
Traceback (most recent call last):
  File "tools/export_model.py", line 115, in <module>
    main()
  File "tools/export_model.py", line 111, in main
    run(FLAGS, cfg)
  File "tools/export_model.py", line 90, in run
    params_filename="model.pdiparams")
  File "/home/phm/J/Anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle_serving_client/io/__init__.py", line 334, in inference_model_to_serving
    model_filename, params_filename, show_proto, feed_alias_names, fetch_alias_names)
  File "/home/phm/J/Anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle_serving_client/io/__init__.py", line 214, in save_model
    new_model_file.write(main_program._remove_training_info(False).desc.serialize_to_string())
AttributeError: 'Program' object has no attribute '_remove_training_info'
----------------------------------------------------------------------------------------------------
Thanks

**Comment by Roly-Yang** [comment]
something need to be appended:
I tried to reinstall the paddleserving by this direction：
pip install paddle-serving-client==0.7.0 -i https://mirror.baidu.com/pypi/simple
Unfortunately, it also has this default in the title.

**Comment by TeslaZhao** [comment]
升级Paddle到2.2.2
