### ISSUE TITLE
边缘端AI解决方案中视频解码部分如何处理

### ISSUE THREAD

**Issue by ChenjieXu** [PaddlePaddle/Serving#1754]
边缘端AI解决方案中视频解码部分如何处理，比如在jetson上面，解码有NVDEC硬件进行解码，这部分如何与Serving代码进行结合？有没有完整的例子。
微信交流群二维码过期了，能否拉我一下进群讨论？

**Comment by TeslaZhao** [comment]
已更新二维码。
对于NVDEC硬件解码，我们没有做过相关工作，但可以一起研究讨论

**Comment by ChenjieXu** [comment]
您好，我只是举个例子，因为在华为硬件上也有一个d啥的做硬解码。请问这个在边缘侧使用边缘盒子硬件硬解码您这边是否有方案？比如我用百度边缘盒子，Paddle Serving部署上去，怎么对视频进行处理？
