### ISSUE TITLE
边缘端AI如何进行多模型部署

### ISSUE THREAD

**Issue by ChenjieXu** [PaddlePaddle/Serving#1755]
在单机上需要部署两个独立的模型，是启动两个独立的serving服务，还是在一个serving服务中挂在两个模型，两个模型的调用是否有动态调度，是否会有资源抢占的情况？

**Comment by TeslaZhao** [comment]
请问，2个独立的模型，模型之间没有联系，建议您部署2个独立的serving服务。

**Comment by TeslaZhao** [comment]
2个模型的Serving实例运行中会占用各自的GPU资源，如果共用1张显卡，保证显存充足即可，会抢占显卡计算资源，比如一个模型的把显存计算全部占用，另一个模型会等待。

**Comment by ChenjieXu** [comment]
您好，是两个独立的模型。假如两个模型有优先级，想要根据优先级进行动态批处理，是否有可能实现？
