### ISSUE TITLE
ASR语音模型部署

### ISSUE THREAD

**Issue by Chenwe111** [PaddlePaddle/Serving#1756]
请问现在支持语音ASR的部署吗？有没有相应的example

**Comment by TeslaZhao** [comment]
支持，公司内部有项目已经使用Paddle Serving部署了案例，但是没有开源，exmaples我近期会推动一下

**Comment by Chenwe111** [comment]
> 支持，公司内部有项目已经使用Paddle Serving部署了案例，但是没有开源，exmaples我近期会推动一下
ok，谢谢，等待您的好消息

**Comment by learningpro** [comment]
可以开放出来ASR部署的example 么 @TeslaZhao
