### ISSUE TITLE
关于pipeline serving时，返回结果的batch拆分问题

### ISSUE THREAD

**Issue by KRuok** [PaddlePaddle/Serving#1757]
目前使用的模型来自paddlex 训练的 FasterRCNN，在参考官方FasterRCNN例子使用pipeline serving时只返回第一个结果。

定位了一下问题，官方提供的FasterRCNN serving例子的模型可能来自老版本保存格式为 \_\_model__  __params__在调用时会返回lodTensor，并根据lod截取相应的长度
![image](https://user-images.githubusercontent.com/50342689/164361215-5373a05b-208a-4808-835e-e6436e42bda6.png)

而我们使用paddlex导出的模型为2.x版本导出的推理模型，保存格式为.pdmodel  .pdiparams，调用时返回normal tensor，无法根据lod截取对应的长度，所以只截取了第一个
![image](https://user-images.githubusercontent.com/50342689/164362332-43505758-6f37-4f1c-80ab-6001388c80bd.png)

对于paddle的FasterRCNN类模型来说，默认的fetch_targets都会有两个值，一个对应识别bbox结果（scale_0.tmp1 与 concat_12.tmp_0），一个对应返回的bbox的数量（scale_1.tmp_1 与 multiclass_nms3_0.tmp2），可以使用对应bbox数量来截取以替代lod做返回结果拆分。但考虑到不同模型的返回不一样，尤其对于返回结果变长需要拆分的，是否有更统一的办法

**Comment by TeslaZhao** [comment]
您好，您咨询的问题是模型结构变化，如何适配新的结果。这个问题我关注一下，近期给你一个答复，欢迎您加入到官网首页的微信群。
