### ISSUE TITLE
部署预测运行时，偶发Failed to fetch错误

### ISSUE THREAD

**Issue by morrigank12** [PaddlePaddle/Serving#1758]
使用PaddleDetection训练的模型，以PaddleServing参数导出模型部署，导出的模型中serving_client_conf.prototxt内容如下：
feed_var {
  name: "im_shape"
  alias_name: "im_shape"
  is_lod_tensor: false
  feed_type: 1
  shape: 2
}
feed_var {
  name: "image"
  alias_name: "image"
  is_lod_tensor: false
  feed_type: 1
  shape: 3
  shape: 608
  shape: 608
}
feed_var {
  name: "scale_factor"
  alias_name: "scale_factor"
  is_lod_tensor: false
  feed_type: 1
  shape: 2
}
fetch_var {
  name: "multiclass_nms3_0.tmp_0"
  alias_name: "multiclass_nms3_0.tmp_0"
  is_lod_tensor: true
  fetch_type: 1
  shape: -1
}
fetch_var {
  name: "multiclass_nms3_0.tmp_2"
  alias_name: "multiclass_nms3_0.tmp_2"
  is_lod_tensor: false
  fetch_type: 2
}

python脚本中预测相关代码如下：
             preprocess = DetectionSequential([
                DetectionFile2Image(),
                DetectionNormalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225], True),
                DetectionResize((800, 1333), True, interpolation=cv2.INTER_LINEAR),
                DetectionTranspose((2, 0, 1)),
                DetectionPadStride(128)
            ])

            postprocess = RCNNPostprocess("/home/models/220406/label_list.txt", output_dir)
            client = Client()
            client.load_client_config("/home/models/220406/serving_client/serving_client_conf.prototxt")
            client.connect(['127.0.0.1:9494'])

            im, im_info = preprocess(path)
            fetch_map = client.predict(
                feed={
                    "image": im,
                    "im_shape": np.array(list(im.shape[1:])).reshape(-1),
                    "scale_factor": im_info['scale_factor'],
                },
                fetch='multiclass_nms3_0.tmp_0')
            fetch_map["image"] = path
            postprocess(fetch_map)
大部分情况下可以正常预测，但是某些图片会报如下错误：

2022-04-22 08:26:37 - Failed to fetch, maybe the type of [multiclass_nms3_0.tmp_0] is wrong, please check the model file
Traceback (most recent call last):
  File "/home/scripts/Watcher_py/prehandler.py", line 62, in on_created
    fetch='multiclass_nms3_0.tmp_0')
  File "/usr/local/lib/python3.7/site-packages/paddle_serving_client/client.py", line 500, in predict
    name))
ValueError: Failed to fetch, maybe the type of [multiclass_nms3_0.tmp_0] is wrong, please check the model file

会报这种错的图片，重复进行预测每次稳定都会报错，这张图片中没有可以检测的目标，但不确定是否所有报错图片都没有目标。
模型训练使用**GPU**训练，部署的服务器使用**CPU**进行预测，和这个有关系吗？
如果需要提供其他文件，请指出。

**Comment by TeslaZhao** [comment]
『模型训练使用GPU训练，部署的服务器使用CPU进行预测，和这个有关系吗？』和训练没有关系

『这张图片中没有可以检测的目标』导致fetch的结果不全，所以报错。建议说没有目标结果是不是返回一个默认值

**Comment by morrigank12** [comment]
> 『模型训练使用GPU训练，部署的服务器使用CPU进行预测，和这个有关系吗？』和训练没有关系
> 
> 『这张图片中没有可以检测的目标』导致fetch的结果不全，所以报错。建议说没有目标结果是不是返回一个默认值

感谢，那么这种情况要如何处理呢，没有见到predict方法有默认值选项。
还是说catch到这个错误就默认是无目标图片呢。

**Comment by TeslaZhao** [comment]
建议修改模型结构，当无检查目标时，multiclass_nms3_0.tmp_0可以返回一个默认值。或者修改 predict 相关代码

**Comment by morrigank12** [comment]
请问如何修改模型结构呢，有没有相关文档链接

**Comment by TeslaZhao** [comment]
需要修改模型训练的代码，在最后一层返回结果时候时候加一个有无检测目标的判断。

还有一种方法，修改 Paddle_Serving_Client包里predict函数500行，把` raise ValueError` 改成 `continue`
。
<img width="701" alt="image" src="https://user-images.githubusercontent.com/6309021/166861521-00f07a6e-9c5a-4db5-96b8-bb45a38ce460.png">

**Comment by morrigank12** [comment]
感谢答疑
