### ISSUE TITLE
docker部署serving的image_reader.py文件在哪里

### ISSUE THREAD

**Issue by cutexiaokele** [PaddlePaddle/Serving#1760]
谁能告知下 docker 方式 serving下载的环境在哪里啊  paddle_serving_app提供的图像预处理或后期处理结果可能与自己训练的模型存在偏差，需要到python安装包path/to/python3.6/site-packages/paddle_serving_app/reader/下修改image_reader.py文件  找不到这个文件

![image](https://user-images.githubusercontent.com/60963646/164971445-1038fdf7-b0a5-4f91-bfd9-5b245b5721d4.png)
我想后续处理检测的结果，直接输出检测到的对象和分数应该处理哪里

**Comment by TeslaZhao** [comment]
pip3 install paddle-serving-app==0.8.3 -i https://pypi.tuna.tsinghua.edu.cn/simple

find /usr -name 'image_reader.py'
