### ISSUE TITLE
pp-tracking可以用paddleserving进行部署嘛

### ISSUE THREAD

**Issue by susan-812** [PaddlePaddle/Serving#1762]
我把fairmot_hrnetv2_w18_dlafpn_30e_576x320.pdparams模型导出为paddleserving需要的格式，然后在服务端启动成功了，但是不知道怎么通过客户端把想要跟踪的视频发送给服务端检测跟踪后返回给客户端进行显示。就想问问pp-tracking里面的模型是可以用paddleserving进行部署的嘛

**Comment by TeslaZhao** [comment]
对于在Client和Server之间传递视频文件，一般会采用2种办法：1.将视频用base64打包，传递到Server端Decode再进行前处理；第二种方法，如果视频有URL的，可以传视频URL或CDN地址 到Server端，在前处理过程wget下来再进行处理。

**Comment by TeslaZhao** [comment]
参考示例：https://github.com/PaddlePaddle/Serving/tree/develop/examples/Pipeline/PaddleVideo/PPTSN_K400
