### ISSUE TITLE
使用serving Pipeline 部署 当尺寸为960*1280时报错

### ISSUE THREAD

**Issue by cutexiaokele** [PaddlePaddle/Serving#1765]
InvalidArgumentError: The 3-th dimension of input[0] and input[1] is expected to be equal.But received input[0]'s shape = [1, 160, 40, 32], input[1]'s shape = [1, 160, 40, 31].
      [Hint: Expected inputs_dims[0][j] == inputs_dims[i][j], but received inputs_dims[0][j]:32 != inputs_dims[i][j]:31.] (at /paddle/paddle/fluid/operators/concat_op.h:63)

不知道什么问题

**Comment by cutexiaokele** [comment]
是不死对输入的尺寸有什么要求，不按照640*640输入久报错吗，训练的模型时设置的是640*640 C++不报错呢

**Comment by cutexiaokele** [comment]
没人吗？ 我直接用Detection的 python tools/infer.py   可以预测 部署到serving 久不可以了

**Comment by TeslaZhao** [comment]
您好，上面的报错信息是说经过预处理后，input[0]和input[1]的输入信息不符合计算要求。用Detection的 python tools/infer.py 可以预测。说明在前处理部分是有差异的，建议您对比 Detection和 Serving preprocess过程做一下对比，然后调整处理过程。
