### ISSUE TITLE
pp-tracking里的模型是否可以用paddleserving进行服务器部署

### ISSUE THREAD

**Issue by susan-812** [PaddlePaddle/Serving#1769]

**Comment by susan-812** [comment]
就想请问一下pp-tracking里的模型可不可以用paddleserving进行部署

**Comment by leiqing1** [comment]
> 就想请问一下pp-tracking里的模型可不可以用paddleserving进行部署

可以的。Paddle Serving是服务化部署框架，常规模型都可以部署的。 （个别不常见的模型，存在算子不支持的情况）
