### ISSUE TITLE
pymilvus 2.0.2和PaddleServing底层包不兼容，重新编译PaddleServing包，源码编译出错

### ISSUE THREAD

**Issue by AI-Mart** [PaddlePaddle/Serving#1777]
详细介绍见链接：https://blog.csdn.net/qq_15821487/article/details/124703947?csdn_share_tail=%7B%22type%22%3A%22blog%22%2C%22rType%22%3A%22article%22%2C%22rId%22%3A%22124703947%22%2C%22source%22%3A%22qq_15821487%22%7D&ctrtid=MwBDd

报错
`[2022-05-10 12:06:31] The conflict is caused by:
[2022-05-10 12:06:31]     paddle-serving-server-gpu 0.8.3.post101 depends on grpcio<=1.33.2
[2022-05-10 12:06:31]     paddle-serving-client 0.8.3 depends on grpcio<=1.33.2
[2022-05-10 12:06:31]     pymilvus 2.0.2 depends on grpcio==1.37.1
[2022-05-10 12:06:31] 
[2022-05-10 12:06:31] To fix this you could try to:
[2022-05-10 12:06:31] 1. loosen the range of package versions you've specified
[2022-05-10 12:06:31] 2. remove package versions to allow pip attempt to solve the dependency
`

源码编译报错：
`CMakeFiles/Makefile2:757: recipe for target 'CMakeFiles/extern_gflags.dir/all' failed
make[1]: *** [CMakeFiles/extern_gflags.dir/all] Error 2
fatal: unable to access 'https://github.com/pybind/pybind11.git/': Failed to connect to github.com port 443: Connection timed out
fatal: unable to access 'https://github.com/madler/zlib.git/': Failed to connect to github.com port 443: Connection timed out
-- Had to git clone more than once:
          3 times.
CMake Error at /home/Serving/build_server/third_party/pybind/tmp/extern_pybind-gitclone.cmake:31 (message):
  Failed to clone repository: 'https://github.com/pybind/pybind11.git'
`

**Comment by TeslaZhao** [comment]
下载失败，已提供带有 代码和编译文件的 docker 镜像
docker pull registry.baidubce.com/paddlepaddle/serving:0.8.0-cuda11.2-cudnn8-devel-with-codes

**Comment by AI-Mart** [comment]
需求是
paddle-serving-server-gpu==0.8.3.post101
paddle-serving-client==0.8.3，这两个包的依赖包grpcio和grpcio-tool改成1.37.1

需要在这个镜像registry.baidubce.com/paddlepaddle/serving:0.8.0-cuda10.1-cudnn7-devel的基础上，打包python3.7版本

你发的这个带有代码和编译文件的 docker镜像版本和上面的镜像不兼容，拷贝了所有相关的第三方依赖后，还是报错，报错内容已经发你了，这个问题卡了一个礼拜了，麻烦尽快协助解决下，谢谢

**Comment by TeslaZhao** [comment]
grpcio和grpcio-tool改成1.37.1 的需求我们会排期升级，预计在v0.9版本发布后(5.20)会响应的需求，在develop分支发布。

另外，您也可以按照Serving代码编译方法，先自行升级打包，不用等待官方版本发布。

已提供带有编译包的镜像，我们需要进一步测试并检查报错原因。
