### ISSUE TITLE
关于客户端增加其他值传入服务器端

### ISSUE THREAD

**Issue by 1037419569** [PaddlePaddle/Serving#1784]
![图片](https://user-images.githubusercontent.com/58407657/168999029-41690e6e-4686-4727-a906-8a308d0eed63.png)
在ocr的paddle serving中 使用的pipeline  如何在上图的data中，添加一个别的数值，然后和图片一起，送入服务器端？

**Comment by TeslaZhao** [comment]
可以的，在"key"和"value"数组中顺序添加。例如：
data = {"key": ["image", "wav", "txt"]}, "value": [image, wav, txt]
