### ISSUE TITLE
关于Serving0.8.3部署OCR模型检测精度下降和识别结果问题

### ISSUE THREAD

**Issue by Yinyihang857** [PaddlePaddle/Serving#1786]
python=3.8
paddlepaddle==2.2.2
paddle-serving-server==0.8.3
服务器是centos7，cpu

1.paddle_serving_client.convert转换ch_PP-OCRv3_rec_infer和ch_PP-OCRv3_det_infer模型
2.python3 web_service.py

通过post请求预测接口，同一张图片的预测结果和tools/infer/predict_system.py预测结果不一致，相差在20%

请问这个问题该如何解决

**Comment by Yinyihang857** [comment]
补充：
图片全部是960x618，200kb左右
压测serving接口100并发平均耗时在40s左右，单次耗时在2~3秒
![image](https://user-images.githubusercontent.com/38742830/169666767-6c0ecfa7-2f5b-4b94-881c-8b1a62005972.png)

下面图片是serving日志截图：
![image](https://user-images.githubusercontent.com/38742830/169666825-988f2b8e-87bc-43d8-ac4a-3c5c8d463506.png)

在不损失精度前提下，改如何提升识别速度呢？

**Comment by TeslaZhao** [comment]
1.精度

使用paddle_serving_client.convert转换ch_PP-OCRv3_rec_infer和ch_PP-OCRv3_det_infer模型后，比较 *.pdmodel 和 *.pdiparams 文件与原始文件的md5 值。如果相同则则不是模型保存问题，建议检查模型前处理

2.提升性能
先补充一下信息：

1. cpu 推理、GPU 推理 或 TensorRT推理?
2. 是否开启量化？
3. 进程或线程模式？
4. 2个op分别开启的并发数量？

**Comment by Yinyihang857** [comment]
1.精度问题
我核实了下*.pdmodel和源文件的MD5值时不一样，但是*.pdiparams和源文件的MD5值时一样的
这是md5检测结果：
![5d4a11ee21b67d1e5dddeef174e33b7](https://user-images.githubusercontent.com/38742830/170532080-2e934b77-4b64-436f-a325-5ccd716a373b.png)

转换方式是按照ocr的文档来的，如何检查模型前处理的问题呢？
![image](https://user-images.githubusercontent.com/38742830/170533772-83b95e12-e550-4722-8592-462fa224d506.png)

2.提升性能补充信息如下：
1.cpu推理
2.未使用量化模型
3.进程模式
4.det检测模型时20并发，rec识别模型时10并发
config.yml配置文件如下
![9e325b8fe84beb1e1cae7c12df34a2b](https://user-images.githubusercontent.com/38742830/170534561-df6517fe-e719-44d8-9e81-eeec9cf98ba7.png)
![28c3f8e3266e5d75a123a200e70dcee](https://user-images.githubusercontent.com/38742830/170534640-d5e7eccb-1e29-495c-9836-085ffdf31951.png)

3.目前cpu使用mkldnn加速，会推理失败，日志报错内容如下：
![464fdc69507dca955a50a2f0a69d387](https://user-images.githubusercontent.com/38742830/170534852-db4bad2a-9e03-4519-9081-6dc86c4479bd.png)
