### ISSUE TITLE
关于Serving编译失败问题

### ISSUE THREAD

**Issue by Yinyihang857** [PaddlePaddle/Serving#1805]
使用serving docker开发镜像版本：registry.baidubce.com/paddlepaddle/serving:0.8.0-devel
编译安装过程中报错如下图：
![image](https://user-images.githubusercontent.com/38742830/170773944-74513866-2c7d-4ebc-9cd9-540f4d73aabd.png)

报错显示git clone代码失败，网络链接超时
但是我单独使用git clone https://github.com/pybind/pybind11.git 是能正常拉取代码的且网络是和github链接正常。
请问这种问题我能否在make之前单独把依赖程序git clone 下来吗？但是这些clone下的代码要放在那个目录下才能在make时识别到

**Comment by Yinyihang857** [comment]
使用serving docker开发镜像版本：registry.baidubce.com/paddlepaddle/serving:0.9.0-devel

**Comment by Yinyihang857** [comment]
使用serving docker开发镜像版本：registry.baidubce.com/paddlepaddle/serving:0.9.0-devel
网络超时问题已经解决，下载依赖可以正常现在，但是编码执行报错，已经根据编译文档试了很多遍

镜像是CPU版镜像
报错截图如下：
![1](https://user-images.githubusercontent.com/38742830/171039241-6d3759cd-63dc-4a8e-8d55-960ad7ca6646.png)

cmake命令：
cmake -DPYTHON_INCLUDE_DIR=$PYTHON_INCLUDE_DIR/ \
    -DPYTHON_LIBRARIES=$PYTHON_LIBRARIES \
    -DPYTHON_EXECUTABLE=$PYTHON_EXECUTABLE \
    -DOPENCV_DIR=/home/opencv-3.4.7/opencv3 \
    -DWITH_OPENCV=ON \
    -DWITH_GPU=OFF \
    -DSERVER=ON ..

openCV已提前编译成功

**Comment by self-discipline-zhu** [comment]
我 openCV 编译的时候出现内存不足的情况，请问您有遇到过这个情况么
```
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
```

**Comment by TeslaZhao** [comment]
您好，您需要使用能链接github 的代理，编译过程中要从github拉依赖库

**Comment by pupubushilulu** [comment]
> 使用serving docker开发镜像版本：registry.baidubce.com/paddlepaddle/serving:0.9.0-devel 网络超时问题已经解决，下载依赖可以正常现在，但是编码执行报错，已经根据编译文档试了很多遍
> 
> 镜像是CPU版镜像 报错截图如下： ![1](https://user-images.githubusercontent.com/38742830/171039241-6d3759cd-63dc-4a8e-8d55-960ad7ca6646.png)
> 
> cmake命令： cmake -DPYTHON_INCLUDE_DIR=$PYTHON_INCLUDE_DIR/ -DPYTHON_LIBRARIES=$PYTHON_LIBRARIES -DPYTHON_EXECUTABLE=$PYTHON_EXECUTABLE -DOPENCV_DIR=/home/opencv-3.4.7/opencv3 -DWITH_OPENCV=ON -DWITH_GPU=OFF -DSERVER=ON ..
> 
> openCV已提前编译成功

请问是如何解决的网络问题呢，我遇到的问题和您一样
