### ISSUE TITLE
询问PaddleServing模型是否支持模型并联

### ISSUE THREAD

**Issue by Andy02070** [PaddlePaddle/Serving#1809]
Paddleserving OCR例子中，web_service.py 实现了检测模型和识别模型的串联，我想实现首先输入数据通过检测模型，然后将检测结果根据判断条件分成两部分，分别送入不同的两个识别模型，即检测模型串联两个并联的识别模型，根据判断条件分支。想请教各位专家paddleserving是否支持，如何实现？

**Comment by TeslaZhao** [comment]
支持，可以参考imdb案例：https://github.com/PaddlePaddle/Serving/tree/v0.9.0/examples/Pipeline/imdb_model_ensemble
