### ISSUE TITLE
[Python] [serving-gateway] Build script seems not right. 编译脚本似乎有错，1.18高版本的GO会编译不过

### ISSUE THREAD

**Issue by tuimeo** [PaddlePaddle/Serving#1810]
问题描述：

GO 1.18.X --- 会在serving-gateway这里build不过。

描述：
Go版本差异造成。1.17的go， go mod vendor会自动做类似tidy的工作，不报错。1.18就不会，直接报错。

<img width="678" alt="image" src="https://user-images.githubusercontent.com/97085562/172550653-27e1c34b-9ec7-4695-9a9d-3e678fd72397.png">

python/util.py这里，  应该有点问题。
应该是先go mod tidy，然后再go mod vendor才对的。  

其实感觉好像不需要vendor啊。 vendor是在本地mod目录下，拷贝依赖进到vendor目录。 不需要魔改vendor的话，没必要这么做。

**Comment by TeslaZhao** [comment]
您好，当前Paddle Serving 使用版本go 1.17，对于升级要1.18的版本可能会有问题，需要一些适配工作。建议先按1.17版本使用，下个版本会考虑再升级
