### ISSUE TITLE
C++Serving 是否支持 TRT 模型的直接部署？

### ISSUE THREAD

**Issue by yang9112** [PaddlePaddle/Serving#1813]
1、如题：C++Serving 是否支持 TRT 模型的直接部署？
2、目前 cuda10.2应该是可以支持 TensorRT 8（对 BERT 类模型加速效果好），C++Serving 好像并没有提供对于的镜像，是否支持重新编译对应的C++ Serving（还是因为有问题，所以未提供）？

**Comment by TeslaZhao** [comment]
1. C++ Serving 支持 paddle模型的TensorRT部署
2. paddle serving 提供的GPU镜像都是带有TensorRT的，并且Paddle Serving的 C++ 安装包里也带有TensorRT，不用自己编译。相关链接：
1）使用Docker安装Paddle Serving：https://github.com/PaddlePaddle/Serving/blob/v0.9.0/doc/Install_CN.md
2）Docker镜像列表：https://github.com/PaddlePaddle/Serving/blob/v0.9.0/doc/Docker_Images_CN.md
3）TensorRT使用方法：https://github.com/PaddlePaddle/Serving/blob/v0.9.0/doc/Serving_Configure_CN.md#c-serving
4）TensorRT动态shape使用方案：https://github.com/PaddlePaddle/Serving/blob/v0.9.0/doc/TensorRT_Dynamic_Shape_CN.md

**Comment by safehumeng** [comment]
能否提供一下tenorRT的配置样例，现在全靠猜测呢

**Comment by yang9112** [comment]
> 能否提供一下tenorRT的配置样例，现在全靠猜测呢

可以参考下这个：https://github.com/yang9112/paddle-serving-experience
我基于 pipline 模式弄的，paddle 不支持原生 TRT 模型的部署，只支持 paddle inference 模型在运行的过程中转。

**Comment by safehumeng** [comment]
> > 能否提供一下tenorRT的配置样例，现在全靠猜测呢
> 
> 可以参考下这个：https://github.com/yang9112/paddle-serving-experience 我基于 pipline 模式弄的，paddle 不支持原生 TRT 模型的部署，只支持 paddle inference 模型在运行的过程中转。

感谢感谢，我也发现了只支持 paddle inference 模型在运行的过程中转，所以想看看有没有直接使用TRT模型的方式
