### ISSUE TITLE
build_dag_each_worker 设置为 True 且 worker_num > 1 时，只有一个进程在工作，其他进程在围观

### ISSUE THREAD

**Issue by shengzhou1216** [PaddlePaddle/Serving#1816]
请问 build_dag_each_worker 设置为 True 且 worker_num > 1 时 ， grpc-gateway 会自动做负载均衡吗？  如果不会 ，那么 build_dag_each_worker 为 True 的意义是什么？ 如果会，那么该怎样才能让多个进程同时工作？

**Comment by wujushan** [comment]
+1，遇到同样的问题。

**Comment by wang-tf** [comment]
+1
