### ISSUE TITLE
使用paddle_serving_server.serve启动后，如何使用http调用服务？

### ISSUE THREAD

**Issue by pierswu** [PaddlePaddle/Serving#1817]
我根据文档https://github.com/PaddlePaddle/Serving/blob/v0.9.0/examples/C%2B%2B/PaddleOCR/ocr/README_CN.md
试着部署一个环境

当我使用下面这个命令启动是，是可以通过地址(127.0.0.1:9292/ocr/prediction)调用服务的
`python3 ocr_web_server.py cpu`

但是如果我使用下面paddle_serving_server的方式启动，要怎么使用http调用呢？
`python3 -m paddle_serving_server.serve --model ocr_det_model --port 9292`

如果我继续调用/ocr/prediction，返回的结果是
`[127.0.0.1:9292][E1002]Fail to find method on /ocr/prediction`

**Comment by genius0182** [comment]
https://github.com/PaddlePaddle/Serving/blob/v0.9.0/doc/C%2B%2B_Serving/Http_Service_CN.md
希望这里能帮到你。
