### ISSUE TITLE
昇腾310 编译失败

### ISSUE THREAD

**Issue by 20102710038** [PaddlePaddle/Serving#1822]
按照下面的文档使用docker环境操作，用代理和不用代理都试过了，都会失败
https://github.com/PaddlePaddle/Serving/blob/develop/doc/Run_On_NPU_CN.md

报错如下：
[ 35%] Performing configure step for 'extern_prometheus'
CMake Error at /workspace/Serving-develop/build-server-npu/third_party/prometheus/src/extern_prometheus-stamp/extern_prometheus-configure-RelWithDebInfo.cmake:16 (message):
  Command failed: 1

   '/usr/bin/cmake' '-DCMAKE_CXX_COMPILER=/usr/bin/c++' '-DCMAKE_C_COMPILER=/usr/bin/cc' '-DCMAKE_C_FLAGS= -D__const__= -DUSE_PTHREAD -fPIC -fno-omit-frame-pointer -Wall -Wextra -Wno-unused-parameter -Wno-unused-function -Wno-error=literal-suffix -Wno-error=sign-compare -Wno-error=unused-local-typedefs -Wno-error=ignored-attributes -Wno-error=terminate -Wno-error=int-in-bool-context -Wimplicit-fallthrough=0 -Wno-error=maybe-uninitialized' '-DCMAKE_C_FLAGS_DEBUG=-g' '-DCMAKE_C_FLAGS_RELEASE=-O3 -DNDEBUG' '-DCMAKE_CXX_FLAGS= -std=c++11 -D__const__= -DUSE_PTHREAD -fPIC -fno-omit-frame-pointer -Wall -Wextra -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wno-unused-parameter -Wno-unused-function -Wno-error=literal-suffix -Wno-error=sign-compare -Wno-error=unused-local-typedefs -Wno-error=ignored-attributes -Wno-error=terminate -Wno-error=int-in-bool-context -Wimplicit-fallthrough=0 -Wno-error=maybe-uninitialized' '-DCMAKE_CXX_FLAGS_RELEASE= -O3 -Wall' '-DCMAKE_CXX_FLAGS_DEBUG= -O0 -Wall -g2 -ggdb' '-DCMAKE_INSTALL_PREFIX:PATH=/workspace/Serving-develop/build-server-npu/third_party/install/prometheus' '-DCMAKE_INSTALL_LIBDIR=/workspace/Serving-develop/build-server-npu/third_party/install/prometheus/lib' '-DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo' '-DBUILD_SHARED_LIBS=OFF' '-DENABLE_PUSH=OFF' '-DENABLE_COMPRESSION=OFF' '-DENABLE_TESTING=OFF' '-GUnix Makefiles' '/workspace/Serving-develop/build-server-npu/third_party/prometheus/src/extern_prometheus'

  See also

    /workspace/Serving-develop/build-server-npu/third_party/prometheus/src/extern_prometheus-stamp/extern_prometheus-configure-*.log

CMakeFiles/extern_prometheus.dir/build.make:106: recipe for target 'third_party/prometheus/src/extern_prometheus-stamp/extern_prometheus-configure' failed
make[2]: *** [third_party/prometheus/src/extern_prometheus-stamp/extern_prometheus-configure] Error 1
CMakeFiles/Makefile2:362: recipe for target 'CMakeFiles/extern_prometheus.dir/all' failed
make[1]: *** [CMakeFiles/extern_prometheus.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
-- Using src='http://paddle-serving.bj.bcebos.com/inferlib/2.3.0/cxx_c/Linux/ASCEND/arm64_gcc7.5_openblas_lite2.10/paddle_inference_install_dir.tgz'
CMake Error at extern_paddle-stamp/download-extern_paddle.cmake:157 (message):
  Each download failed!

    error: downloading 'http://paddle-serving.bj.bcebos.com/inferlib/2.3.0/cxx_c/Linux/ASCEND/arm64_gcc7.5_openblas_lite2.10/paddle_inference_install_dir.tgz' failed
         status_code: 22
         status_string: "HTTP response code said error"
         log:
         --- LOG BEGIN ---
           Trying 127.0.0.1...

  TCP_NODELAY set

  Connected to 127.0.0.1 (127.0.0.1) port 1080 (#0)

  GET
  http://paddle-serving.bj.bcebos.com/inferlib/2.3.0/cxx_c/Linux/ASCEND/arm64_gcc7.5_openblas_lite2.10/paddle_inference_install_dir.tgz
  HTTP/1.1

  Host: paddle-serving.bj.bcebos.com

  User-Agent: curl/7.58.0

  Accept: */*

  Proxy-Connection: Keep-Alive

  

  The requested URL returned error: 503 Service Unavailable

  stopped the pause stream!

  Closing connection 0

  

         --- LOG END ---

**Comment by kegehe** [comment]
问题解决了吗
