### ISSUE TITLE
prometheus配置

### ISSUE THREAD

**Issue by Enchanted0911** [PaddlePaddle/Serving#1848]
我尝试使用prometheus，按照官方demo添加了对应参数，但是服务启动就立即报错了。
系统 linux
pdserving版本: 0.9.0
cuda 11.2
cudnn 8.2.1
tensorrt 8.0.3.4
paddlepaddle 2.3
以下是我的报错信息
![image](https://user-images.githubusercontent.com/65162523/189322921-b53fbfeb-fdcc-4ef1-94fc-f421242c4e5a.png)
以下是我添加的配置
![image](https://user-images.githubusercontent.com/65162523/189323021-26c34bf5-a207-4d98-9a58-f33861c27930.png)

**Comment by Enchanted0911** [comment]
希望得到解答！

**Comment by DreamJokerMJ** [comment]
node-exporter和prometheus 有没有启动，node-exporter 是部署在被监控的服务器上，prometheus是监控服务器，提供可视化监控管理
