### ISSUE TITLE
请问kie推理模型可以集成到pdserving，用rpc请求预测结果吗？

### ISSUE THREAD

**Issue by sybest1259** [PaddlePaddle/Serving#1849]
问题：
目前使用paddleocr-release2.6已部署一套pdserving，采用rpc访问，模型使用ch_PP-OCRv3_det_slim和ch_PP-OCRv3_rec_slim，现在需要识别发票图片，需要使用kie相关功能，如何能将kie模型（比如SER、RE相关模型）集成到pdserving中呢？

**Comment by francisol** [comment]
我也有同样问题，请问有解决的办法吗

**Comment by danaodai** [comment]
理论上是也是可以的，正在摸索中+1

**Comment by Tanmay98** [comment]
Can we add table model to pdserving?
