### ISSUE TITLE
http api url

### ISSUE THREAD

**Issue by hbo-lambda** [PaddlePaddle/Serving#1855]
paddle serving通过如下命令启动后：
1.
ocr_rec_model ocr_det_model都是通过python -m.... 命令获得的，解压后，执行
```
python -m paddle_serving_server.serve --model ocr_rec_model ocr_det_model --thread 10 --port 9292
```
通过http的方式，客户端发请求时的url从哪儿得知呢？

**Comment by Jaccica** [comment]
url就是http://ip:端口/name/method.

**Comment by Yan-Ke** [comment]
> url就是[http://ip:端口/name/method](http://ip:%E7%AB%AF%E5%8F%A3/name/method).

请问name和method又是什么？模型部署好完全不知道这个接口访问规则是什么，怎么传参等等

**Comment by XS170411105276** [comment]
> > url就是[http://ip:端口/name/method](http://ip:%E7%AB%AF%E5%8F%A3/name/method).
> 
> 请问name和method又是什么？模型部署好完全不知道这个接口访问规则是什么，怎么传参等等

您好，请问您现在知道怎么用http请求传参了吗

**Comment by zyzz1974** [comment]
同样，使用http_pinepine_client.py报错如下
![image](https://user-images.githubusercontent.com/99126288/211994309-94b8c438-9c0e-44f4-9b6d-650038ba4215.png)

**Comment by XS170411105276** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by roomeo** [comment]
> > > url就是[http://ip:端口/name/method](http://ip:%E7%AB%AF%E5%8F%A3/name/method).
> > 
> > 
> > 请问name和method又是什么？模型部署好完全不知道这个接口访问规则是什么，怎么传参等等
> 
> 您好，请问您现在知道怎么用http请求传参了吗

请问目前pdserving method在哪里定义的呢
