### ISSUE TITLE
一个服务包含两个模型部署时Client怎么区分调用的是哪个模型？

### ISSUE THREAD

**Issue by XinyuDu** [PaddlePaddle/Serving#1858]
文档中提到（https://github.com/PaddlePaddle/Serving/blob/v0.9.0/doc/Serving_Configure_CN.md）：
**当您的一个服务包含两个模型部署时.**
`python3 -m paddle_serving_server.serve --model serving_model_1 serving_model_2 --thread 10 --port 9292`

请问client端怎么区分调用哪个模型进行inference呢？貌似模型的serving_client_conf.prototxt里面也没有模型的名称。
```
client = Client()
client.load_client_config(sys.argv[1:])
client.connect(["127.0.0.1:9292"])
fetch_map = client.predict(feed=feed, fetch=[], batch=True)
```

**Comment by pinngan** [comment]
我也想咨询这个问题，python3 -m paddle_serving_server.serve --model model_1 model_2 model_3 model_4--thread 10 --port 9292。能否通过客户端的传参来确定服务端使用1 2 3 4中哪一个模型推理。

**Comment by XS170411105276** [comment]
请问你们找到这个问题的解决方法了吗，我最近在做这个需求也是遇到这个问题，可以分享一下吗，谢谢！
