### ISSUE TITLE
请问我在进行http部署启动之后，我的预测路径是什么呢？

### ISSUE THREAD

**Issue by 1084667371** [PaddlePaddle/Serving#1871]
![image](https://user-images.githubusercontent.com/50902619/197973460-3bddd866-86f3-4b18-acad-ee4dc1974c22.png)

这里的路径启动也没有显示，换成自己的模型就不知道后边该写什么了

**Comment by 758915145** [comment]
> ![image](https://user-images.githubusercontent.com/50902619/197973460-3bddd866-86f3-4b18-acad-ee4dc1974c22.png)
> 
> 这里的路径启动也没有显示，换成自己的模型就不知道后边该写什么了

是/GeneralModelService/inference，老哥加个好友一起学习吧

**Comment by Jaccica** [comment]
这个是name和method.
