### ISSUE TITLE
昇腾310 编译失败

### ISSUE THREAD

**Issue by MyOnlyCat** [PaddlePaddle/Serving#1874]
#看样子像是地址失效了
```shell
CMake Error at extern_paddle-stamp/download-extern_paddle.cmake:170 (message):
  Each download failed!

    error: downloading 'http://paddle-serving.bj.bcebos.com/inferlib/2.3.0-rc0/cxx_c/Linux/ASCEND/arm64_gcc7.5_openblas_lite2.10/paddle_inference_install_dir.tgz' failed
          status_code: 22
          status_string: "HTTP response code said error"
          log:
          --- LOG BEGIN ---
            Trying 103.235.46.61:80...

  Connected to paddle-serving.bj.bcebos.com (103.235.46.61) port 80 (#0)

  GET
  /inferlib/2.3.0-rc0/cxx_c/Linux/ASCEND/arm64_gcc7.5_openblas_lite2.10/paddle_inference_install_dir.tgz
  HTTP/1.1

  Host: paddle-serving.bj.bcebos.com

  User-Agent: curl/7.81.0

  Accept: */*



  Mark bundle as not supporting multiuse

  HTTP/1.1 404 Not Found

  Date: Thu, 27 Oct 2022 15:56:15 GMT

  Content-Type: application/json; charset=utf-8

  Content-Length: 117

  Connection: keep-alive

  Server: BceBos

  x-bce-debug-id:
  KzZu5wj88xo0rq28URBIXobE0Xic3i3BtuUOHCZl4GyxMq4Xgdc2hyOX3tJjm+UM7UW4eKjalW9W4UjdcLqxIw==


  x-bce-request-id: 73f43ae5-7652-44c2-9558-84533950cba8

  x-bce-restore-cache: -

  x-bce-restore-tier: -

  The requested URL returned error: 404

  Closing connection 0



          --- LOG END ---

```

**Comment by MyOnlyCat** [comment]
有考虑修复吗?

**Comment by danyXu** [comment]
问题解决了吗

**Comment by kegehe** [comment]
现在也是遇到这个问题， 请问解决了吗

**Comment by kegehe** [comment]
> #看样子像是地址失效了
> 
> CMake Error at extern_paddle-stamp/download-extern_paddle.cmake:170 (message):
>   Each download failed!
> 
>     error: downloading 'http://paddle-serving.bj.bcebos.com/inferlib/2.3.0-rc0/cxx_c/Linux/ASCEND/arm64_gcc7.5_openblas_lite2.10/paddle_inference_install_dir.tgz' failed
>           status_code: 22
>           status_string: "HTTP response code said error"
>           log:
>           --- LOG BEGIN ---
>             Trying 103.235.46.61:80...
> 
>   Connected to paddle-serving.bj.bcebos.com (103.235.46.61) port 80 (#0)
> 
>   GET
>   /inferlib/2.3.0-rc0/cxx_c/Linux/ASCEND/arm64_gcc7.5_openblas_lite2.10/paddle_inference_install_dir.tgz
>   HTTP/1.1
> 
>   Host: paddle-serving.bj.bcebos.com
> 
>   User-Agent: curl/7.81.0
> 
>   Accept: */*
> 
> 
> 
>   Mark bundle as not supporting multiuse
> 
>   HTTP/1.1 404 Not Found
> 
>   Date: Thu, 27 Oct 2022 15:56:15 GMT
> 
>   Content-Type: application/json; charset=utf-8
> 
>   Content-Length: 117
> 
>   Connection: keep-alive
> 
>   Server: BceBos
> 
>   x-bce-debug-id:
>   KzZu5wj88xo0rq28URBIXobE0Xic3i3BtuUOHCZl4GyxMq4Xgdc2hyOX3tJjm+UM7UW4eKjalW9W4UjdcLqxIw==
> 
> 
>   x-bce-request-id: 73f43ae5-7652-44c2-9558-84533950cba8
> 
>   x-bce-restore-cache: -
> 
>   x-bce-restore-tier: -
> 
>   The requested URL returned error: 404
> 
>   Closing connection 0
> 
> 
> 
>           --- LOG END ---

也遇到这个问题，请问解决了吗
