### ISSUE TITLE
采用paddleserving部署OCR服务，只需要输出识别的字符串，如何修改代码？

### ISSUE THREAD

**Issue by Jaccica** [PaddlePaddle/Serving#1887]
采用paddleserving部署好了OCR服务，现在输出的结果包含识别的字符串和框信息，我现在只需要输出识别的字符串，请问怎么修改代码？
       我查了下web_service.py的代码，recOp返回的是字典，而不是字符。
![图片](https://user-images.githubusercontent.com/17899115/202600975-c7961466-37e6-425e-b80c-97febabd8dd4.png)

**Comment by HexToString** [comment]
在rec_op的后处理中修改返回的字段即可

**Comment by Jaccica** [comment]
> 在rec_op的后处理中修改返回的字段即可

好的，已解决。主要修改web_service.py中的RecOP。
`    def postprocess(self, input_dicts, fetch_data, data_id, log_id):
        rec_list = []
        dt_num = len(self.dt_list)
        if isinstance(fetch_data, dict):
            if len(fetch_data) > 0:
                rec_batch_res = self.ocr_reader.postprocess(
                    fetch_data, with_score=True)
                for res in rec_batch_res:
                    rec_list.append(res[0])
        elif isinstance(fetch_data, list):
            for one_batch in fetch_data:
                one_batch_res = self.ocr_reader.postprocess(
                    one_batch, with_score=True)
                for res in one_batch_res:
                    rec_list.append(res[0])
        """result_list = []
        for i in range(dt_num):
            text = rec_list[i]
            dt_box = self.dt_list[i]
            if text[1] >= 0.5:
                result_list.append([text, dt_box.tolist()])
        res = {"result": str(result_list)}"""
        
        res = {"result": str(rec_list)`

**Comment by Jaccica** [comment]
> 在rec_op的后处理中修改返回的字段即可

好的，已解决。主要修改web_service.py中的RecOP。
`   def postprocess(self, input_dicts, fetch_data, data_id, log_id):
        rec_list = []
        dt_num = len(self.dt_list)
        if isinstance(fetch_data, dict):
            if len(fetch_data) > 0:
                rec_batch_res = self.ocr_reader.postprocess(
                    fetch_data, with_score=True)
                for res in rec_batch_res:
                    rec_list.append(res[0])
        elif isinstance(fetch_data, list):
            for one_batch in fetch_data:
                one_batch_res = self.ocr_reader.postprocess(
                    one_batch, with_score=True)
                for res in one_batch_res:
                    rec_list.append(res[0])
        """result_list = []
        for i in range(dt_num):
            text = rec_list[i]
            dt_box = self.dt_list[i]
            if text[1] >= 0.5:
                result_list.append([text, dt_box.tolist()])
        res = {"result": str(result_list)}"""
        
        res = {"result": str(rec_list)}
        return res, None, ""`

**Comment by Jaccica** [comment]
> 在rec_op的后处理中修改返回的字段即可

好的，已解决，主要修改web_service.py中的RecOP. 修改后的代码如下：

   def postprocess(self, input_dicts, fetch_data, data_id, log_id):
        rec_list = []
        dt_num = len(self.dt_list)
        if isinstance(fetch_data, dict):
            if len(fetch_data) > 0:
                rec_batch_res = self.ocr_reader.postprocess(
                    fetch_data, with_score=True)
                for res in rec_batch_res:
                    rec_list.append(res[0])
        elif isinstance(fetch_data, list):
            for one_batch in fetch_data:
                one_batch_res = self.ocr_reader.postprocess(
                    one_batch, with_score=True)
                for res in one_batch_res:
                    rec_list.append(res[0])
        """result_list = []
        for i in range(dt_num):
            text = rec_list[i]
            dt_box = self.dt_list[i]
            if text[1] >= 0.5:
                result_list.append([text, dt_box.tolist()])
        res = {"result": str(result_list)}"""
        
        res = {"result": str(rec_list)}
        return res, None, ""
