### ISSUE TITLE
为什么RPC服务和Pipeline服务的输出不一样

### ISSUE THREAD

**Issue by zyf950120** [PaddlePaddle/Serving#1894]
遇见了很奇怪的情况：
1. fairmot-608*1088-vehicle模型，部署RPC服务，输出bbox_result维度是对的：(500, 6)
![image](https://user-images.githubusercontent.com/56629915/206353842-c689d54f-7839-4e2a-b473-5bf9990c5ff5.png)

2. fairmot-608*1088-vehicle模型，部署pipeline服务，输出bbox_result维度是错的：(1,  6)
![image](https://user-images.githubusercontent.com/56629915/206353793-2226e47b-707a-456c-a307-4a0ac32f02c4.png)

3. yolov3-darknet53模型，部署pipeline服务，输出bbox_result维度也是对的：(42,  6)
![image](https://user-images.githubusercontent.com/56629915/206353903-03669cf5-df94-4f2f-826c-56a3038945b9.png)

模型文件一样，图片一样，前后处理也一样，就是部署pipeline服务的fairmot模型输出不对，只能输出一个。。。

有没有大佬帮忙解决下，感谢

**Comment by vividzhang** [comment]
我用PaddleDetection项目中的web_server启动pipeline也遇到输出只取了第一个检测框的问题，打算放弃使用paddleSering时看到你这里提到使用RPC服务正确返回，所以想咨询下RPC server的部署方式，有没有示例文档呢？谢谢
