### ISSUE TITLE
No module named 'paddle_serving_server'

### ISSUE THREAD

**Issue by zyzz1974** [PaddlePaddle/Serving#1905]
pip list查看paddle_serving_server是存在的
![image](https://user-images.githubusercontent.com/99126288/211184039-0ee0b8b4-91de-4246-a79f-3adb39c7ef09.png)
[root@192 fit_a_line]# python -m paddle_serving_server.serve --model serving_server
/usr/bin/python: Error while finding module specification for 'paddle_serving_server.serve' (ModuleNotFoundError: No module named 'paddle_serving_server')
[root@192 fit_a_line]#

**Comment by HexToString** [comment]
你的python 和 pip 没对应上。
