### ISSUE TITLE
serving的重大bug

### ISSUE THREAD

**Issue by whtwhtw** [PaddlePaddle/Serving#1920]
当serving的server端接收到client发送的数据转换不成所需要的数据类型时，server会自动退出，这种bug不可理喻！

**Comment by wjplove8** [comment]
> 当serving的server端接收到client发送的数据转换不成所需要的数据类型时，server会自动退出，这种bug不可理喻！

哈哈哈哈，是的。我也发现了，只能docker自启。

**Comment by xuxiaobao-3** [comment]
不知道什么时候可以修复 每次都得重新启动
