### ISSUE TITLE
docker镜像编译失败啊

### ISSUE THREAD

**Issue by liuwqiang** [PaddlePaddle/Serving#1921]
我用 serving的docker镜像编译serving竟然编译失败了！我使用的镜像是 registry.baidubce.com/paddlepaddle/serving:0.9.0-devel

这是我的日志 
[编译.txt](https://github.com/PaddlePaddle/Serving/files/10799546/default.txt)

**Comment by liuwqiang** [comment]
报的错误是 Makefile:129: recipe for target 'all' failed make: *** [all] Error 2

**Comment by liuwqiang** [comment]
[错误.txt](https://github.com/PaddlePaddle/Serving/files/10799675/default.txt)
试了N中方法就是不行 我服气了

**Comment by delayk** [comment]
`/bin/sh: 1: ../../$PYTHON_EXECUTABLE: not found`
你的环境变量没设置

> [错误.txt](https://github.com/PaddlePaddle/Serving/files/10799675/default.txt)
> 试了N中方法就是不行 我服气了

**Comment by delayk** [comment]
在错误日志中搜failed，基本都能定位到问题
