### ISSUE TITLE
部署paddlenlp的mbart模型报错

### ISSUE THREAD

**Issue by Amy234543** [PaddlePaddle/Serving#1928]
python -m paddle_serving_server.serve --model SERVING_SERVER_DIR --thread 10 --port 9393 --gpu_id 0
执行上面命令报以下错误

Error Message Summary:
----------------------
NotFoundError: Operator (fusion_mbart_decoding) is not registered.
  [Hint: op_info_ptr should not be null.] (at /paddle/paddle/fluid/framework/op_info.h:151)

**Comment by whisky-12** [comment]
![image](https://user-images.githubusercontent.com/79358023/227483746-b68c766c-69fd-4260-847e-fc60375cc0ad.png)
打扰了 ，请教下，这里应该怎么修改配置 ，
目前提交请求后服务端报错
![image](https://user-images.githubusercontent.com/79358023/227484056-038970a7-96f8-4b52-820b-69c7987fde54.png)
