### ISSUE TITLE
PaddleOCR C++ Serving core dump!!!

### ISSUE THREAD

**Issue by yuanhaisu** [PaddlePaddle/Serving#1930]
paddleocr的serving部署方式下，发起预测触发core dump报错
![image](https://user-images.githubusercontent.com/11955508/225275639-9ea26d4d-26f8-4f4f-be4d-8fb28a9eaee7.png)

环境：
`docker image:paddlepaddle/paddle:2.4.2-gpu-cuda11.2-cudnn8.2-trt8.0`

驱动信息：
![image](https://user-images.githubusercontent.com/11955508/225267252-736da64e-f089-403a-81e4-5ae35e115adc.png)

```
paddle版本：
paddle-bfloat             0.1.2          
paddle-serving-app        0.9.0          
paddle-serving-client     0.9.0          
paddle-serving-server-gpu 0.9.0.post112  
paddlepaddle-gpu          2.3.0.post112
```

运行参数
```
Dir：Serving/examples/C++/PaddleOCR/ocr
serving：python3 -m paddle_serving_server.serve --model ocr_det_model ocr_rec_model --op GeneralDetectionOp GeneralRecOp --thread 4 --port 9293 --gpu_ids 0
client：python3 ocr_cpp_client.py ocr_det_client ocr_rec_client

serving_client_conf.prototxt配置
feed_var {
  name: "x"
  alias_name: "x"
  is_lod_tensor: false
  feed_type: 20
  shape: 1
}
```

**Comment by whisky-12** [comment]
![image](https://user-images.githubusercontent.com/79358023/227483746-b68c766c-69fd-4260-847e-fc60375cc0ad.png)
打扰了 ，请教下，这里应该怎么修改配置 ，
目前提交请求后服务端报错
![image](https://user-images.githubusercontent.com/79358023/227484056-038970a7-96f8-4b52-820b-69c7987fde54.png)
