### ISSUE TITLE
多个独立模型启动serving服务

### ISSUE THREAD

**Issue by gitmhg** [PaddlePaddle/Serving#1931]
paddle-serving-app        0.9.0
paddle-serving-client     0.9.0
paddle-serving-server     0.9.0
paddlepaddle              2.4.2
Linux ubuntu 20.04
你好，我现在有100个独立的模型，我想为这100个独立的模型同时启动推理服务，我尝试了pipline和web service,但是还是占用资源太大了，模型本身并不大，只是模型之外的框架解释器之类的占用太多了，我应该怎末启动服务才能最节省内存资源？期待您的回复

**Comment by whisky-12** [comment]
![image](https://user-images.githubusercontent.com/79358023/227483746-b68c766c-69fd-4260-847e-fc60375cc0ad.png)
打扰了 ，请教下，这里应该怎么修改配置 ，
目前提交请求后服务端报错
![image](https://user-images.githubusercontent.com/79358023/227484056-038970a7-96f8-4b52-820b-69c7987fde54.png)
