### ISSUE TITLE
使用paddleserver部署paddleCls，如何输出top5？

### ISSUE THREAD

**Issue by chengshaoxi0** [PaddlePaddle/Serving#1934]
使用paddleserver部署paddleCls，如何输出top5？

使用python predict_cls.py可以输出top5，但使用paddlerserver部署后只能输出top1，部署命令是python classification_web_service.py 。   在哪里可以修改输出类别数？？

**Comment by Jaccica** [comment]
> 

您好！请教下，paddleserving可以部署方向分类器吗？我没看到相关的接口啊。可以指导下不？谢谢！
