### ISSUE TITLE
ubuntu20.04 按照Docker安装Paddle Serving环境检查一直有错误。 xxx gpu environment running failure

### ISSUE THREAD

**Issue by fanxinkeji** [PaddlePaddle/Serving#1944]
折腾两天了，无论在线安装还是离线安装Wheel 包，环境检查都有错误
117a5d2df849 /paddle/Serving {v0.9.0} python3 -m paddle_serving_server.serve check
/usr/local/lib/python3.6/runpy.py:125: RuntimeWarning: 'paddle_serving_server.serve' found in sys.modules after import of package 'paddle_serving_server', but prior to execution of 'paddle_serving_server.serve'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
Welcome to the check env shell.Type help to list commands.

(Cmd) check_all
PaddlePaddle inference environment running success
C++ cpu environment running success
C++ gpu environment running failure, if you need this environment, please refer to https://github.com/PaddlePaddle/Serving/blob/develop/doc/Install_CN.md
Pipeline cpu environment running success
Pipeline gpu environment running failure, if you need this environment, please refer to https://github.com/PaddlePaddle/Serving/blob/develop/doc/Install_CN.md
(Cmd) exit
Check Environment Shell Exit
![2023-05-11 14-43-14 的屏幕截图](https://github.com/PaddlePaddle/Serving/assets/52989381/2fe7f0b1-e8cb-4ccd-ae6e-3ae5d132057b)

**Comment by anomousA** [comment]
+1，这个文档就是依托答辩
