### ISSUE TITLE
请问现在有官方的dockerfile了吗?

### ISSUE THREAD

**Issue by wwjjy** [PaddlePaddle/Serving#211]
如题，如果有的话，能否提供一下，文档里的链接点进去是404呀~

**Comment by bjjwwang** [comment]
目前还在开发中，应该会在这几天就会更新出来。
如果是想要编译，暂时可以下载镜像 hub.baidubce.com/ctr/paddleserving:latest

**Comment by Just-D** [comment]
> 目前还在开发中，应该会在这几天就会更新出来。
> 如果是想要编译，暂时可以下载镜像 hub.baidubce.com/ctr/paddleserving:latest

这docker里面工具都没装？

**Comment by barrierye** [comment]
最新版的运行镜像：
hub.baidubce.com/ctr/paddleserving:0.1.3
hub.baidubce.com/ctr/paddleserving:0.1.3-gpu
在容器内执行`pip install paddle-serving-server`或`pip install paddle-serving-server-gpu`即可使用
