### ISSUE TITLE
/python/examples/criteo_ctr/local_train.py 基于新版paddle提示警告

### ISSUE THREAD

**Issue by barrierye** [PaddlePaddle/Serving#232]
在新版paddle中添加了一个auc op相关的警告，见https://github.com/PaddlePaddle/Paddle/pull/19838
> please ensure that you have set the auc states to zeros before saving inference model

**Comment by barrierye** [comment]
还有一个报错：
> ValueError: var dense_input not in this block

**Comment by guru4elephant** [comment]
thx, fixed in https://github.com/PaddlePaddle/Serving/pull/235
