### ISSUE TITLE
无法下载paddle-serving-server

### ISSUE THREAD

**Issue by RockWater** [PaddlePaddle/Serving#258]
pip install paddle-serving-server
Collecting paddle-serving-server
  Could not find a version that satisfies the requirement paddle-serving-server (from versions: )
No matching distribution found for paddle-serving-server

**Comment by MRXLT** [comment]
你好，请问使用的python版本是多少呢，paddle serving目前还没有发布python3版本的安装包

**Comment by RockWater** [comment]
难怪。我用的是python3。谢谢。预计什么时候发布python3的版本呢

**Comment by MRXLT** [comment]
预计会在本月或下个月发布

**Comment by linhandev** [comment]
期待

**Comment by MRXLT** [comment]
已发布0.1.3版本，加入了对python3的支持
