### ISSUE TITLE
install and run auth do not match

### ISSUE THREAD

**Issue by guru4elephant** [PaddlePaddle/Serving#259]
![image](https://user-images.githubusercontent.com/35550832/76198225-a2eee300-6228-11ea-8697-e00c9526b1e7.png)

A user may install paddle-serving-server with root auth, but run with user auth. The serving binary can not be written on disk in this case, should report an friendly error.

**Comment by MRXLT** [comment]
this bug fixed in https://github.com/PaddlePaddle/Serving/pull/265
