### ISSUE TITLE
start gpu server failed when CUDA_VISIBLE_DEVICES is not set

### ISSUE THREAD

**Issue by houj04** [PaddlePaddle/Serving#278]
if the environment variable of CUDA_VISIBLE_DEVICES is not set, paddle_serving_server_gpu/serve.py will abort at line 67: gpus = os.environ["CUDA_VISIBLE_DEVICES"]

**Comment by guru4elephant** [comment]
https://github.com/PaddlePaddle/Serving/pull/268
