### ISSUE TITLE
增加对多种CPU指令集的适配

### ISSUE THREAD

**Issue by houj04** [PaddlePaddle/Serving#286]
背景：我在一台支持avx2指令集的机器上进行了编译和安装。然后将整个python包分发到其它机器上执行的时候报错
Illegal instruction (core dumped)
推测是分发的那批机器比较古老，cpu不支持avx2指令集。
希望的操作：可以运行时自动检测指令集，或者编译的时候可以增加选项以选择支持的指令集。因为编译的机器确实可能和运行的机器cpu型号不同。

**Comment by houj04** [comment]
我在cmake的时候刷了-DWITH_AVX=OFF好像也不行。编译出来的目标文件仍然是这个（路径里面带着avx）
python27-gcc482/lib/python2.7/site-packages/paddle_serving_server/serving-cpu-avx-openblas-0.1.3/serving
推测是中间某个步骤，从bos下载某个依赖的时候没有进行区分。

**Comment by MRXLT** [comment]
感谢反馈，serving目前提供了avx-mkl、avx-openblas和noav-openblas三种版本的二进制文件，会在server端第一次执行时根据机器环境下载，但是没有对avx2和avx进行区分，暂时可以通过在avx2的机器上使用1.7.1的inference lib进行编译，这样编译出的二进制文件可以兼容avx环境。
步骤：
修改https://github.com/PaddlePaddle/Serving/blob/develop/cmake/paddlepaddle.cmake#L34 中1.6.3为1.7.1
按照https://github.com/PaddlePaddle/Serving/blob/develop/doc/COMPILE.md 编译文档进行编译，使用编译出的二进制文件替换原来paddle_serving_server或paddle_serving_server_gpu模块安装路径下的二进制文件
