### ISSUE TITLE
web service not support multi-gpu

### ISSUE THREAD

**Issue by MRXLT** [PaddlePaddle/Serving#290]
当使用export CUDA_VISIBLE_DEVICES=0,1指定多卡时，web service无法实现多卡预测。
原因1
![image](https://user-images.githubusercontent.com/16594411/76817863-fff92300-683e-11ea-91e4-4703ce8cd188.png)
脚本中对于使用多卡的情况做了限制，不支持多卡，仅使用client_list[0]进行预测。
原因2
当修改掉以上代码后，启动预测服务，gpu 0上的预测服务正常，gpu 1上的预测服务挂掉
报错如下
![image](https://user-images.githubusercontent.com/16594411/76817985-5a927f00-683f-11ea-8da8-1cda90809059.png)

**Comment by guru4elephant** [comment]
https://github.com/PaddlePaddle/Serving/pull/293
