### ISSUE TITLE
gpu web service not support gpu 1

### ISSUE THREAD

**Issue by MRXLT** [PaddlePaddle/Serving#291]
当通过 export CUDA_VISIBLE_DEVICES=1指定使用gpu 1的时候，web service启动时报错

![image](https://user-images.githubusercontent.com/16594411/76818196-ed331e00-683f-11ea-81a0-081e7f64bec5.png)

**Comment by guru4elephant** [comment]
https://github.com/PaddlePaddle/Serving/pull/293
