### ISSUE TITLE
服务化部署了人像分割服务之后偶尔会出现500 Internal Server Error 请协助解决

### ISSUE THREAD

**Issue by lesterhnu** [PaddlePaddle/Serving#298]
![image](https://user-images.githubusercontent.com/42615458/76968851-8d826300-6964-11ea-93da-ce9c71d91bcc.png)

**Comment by guru4elephant** [comment]
能否提供一个复现环境？@lesterhnu

**Comment by lesterhnu** [comment]
> 能否提供一个复现环境？@lesterhnu
![image](https://user-images.githubusercontent.com/42615458/77025508-3d3eeb80-69cc-11ea-994c-9fb9d9febe27.png)
![image](https://user-images.githubusercontent.com/42615458/77025541-534cac00-69cc-11ea-8051-eb2a13a70da7.png)
![image](https://user-images.githubusercontent.com/42615458/77025553-5a73ba00-69cc-11ea-9744-c77573fecdb7.png)
![image](https://user-images.githubusercontent.com/42615458/77025593-7b3c0f80-69cc-11ea-89a9-03af21ab61b1.png)
centos7,python3安装的paddlehub，并不是一定出现的，初步统计发现图片体积大于2M的话会出现这个问题，

**Comment by guru4elephant** [comment]
这个是paddlehub的问题，请到paddlehub提问，paddle serving后续也会提供人像分割服务的部署示例和高性能版本，敬请关注。
