### ISSUE TITLE
自己训练的模型，如何转换成serving可以使用的模型

### ISSUE THREAD

**Issue by mcl-stone** [PaddlePaddle/Serving#305]

**Comment by mcl-stone** [comment]
使用PaddleDetection训练的模型

**Comment by MRXLT** [comment]
你好，可以使用paddle_serving_client.io.save_model接口，请参考这篇文档，https://github.com/PaddlePaddle/Serving/blob/develop/doc/SAVE.md

**Comment by mcl-stone** [comment]
感谢！
