### ISSUE TITLE
编译文档需要更新，里面仍有旧的CLIENT_ONLY参数

### ISSUE THREAD

**Issue by houj04** [PaddlePaddle/Serving#317]
这个commit把CLIENT_ONLY参数移除了，并增加了新的参数。
https://github.com/PaddlePaddle/Serving/commit/e8e19b21775ea9aeb350c0a5050f07ffa6535a8a
但是这个文档没有同步更新。
https://github.com/PaddlePaddle/Serving/blob/develop/doc/COMPILE.md

**Comment by barrierye** [comment]
感谢关注，文档已更新。
