### ISSUE TITLE
Paddle Serving 0.2.0 基础功能测试 imdb模型 README 文档错误

### ISSUE THREAD

**Issue by hysunflower** [PaddlePaddle/Serving#325]
详见 [DLTP-5021](http://newicafe.baidu.com:80/issue/DLTP-5021/show?from=page)

imdb 模型 README 页实例描述有误 [imdb](https://github.com/PaddlePaddle/Serving/tree/develop/python/examples/imdb)
![图片](https://user-images.githubusercontent.com/52739577/77395257-25a4a000-6ddc-11ea-9ea8-5fd2cfd47307.png)

**Comment by MRXLT** [comment]
fixed in https://github.com/PaddlePaddle/Serving/pull/338
