### ISSUE TITLE
参考编译文档从源码编译gpu版本失败

### ISSUE THREAD

**Issue by MRXLT** [PaddlePaddle/Serving#350]
<img width="1104" alt="编译GPU server" src="https://user-images.githubusercontent.com/16594411/77850039-7cf2a800-7202-11ea-978e-20a87b6aaaf5.png">

**Comment by barrierye** [comment]
请问是在本地编译还是在Docker环境中编译，可否提供一下复现的命令？

**Comment by hysunflower** [comment]
> 请问是在本地编译还是在Docker环境中编译，可否提供一下复现的命令？


docker 内编译，所用docker 镜像  hub.baidubce.com/ctr/paddleserving:0.1.3-gpu
所需编译 工具及其版本按照该 [dockerfile](https://github.com/PaddlePaddle/Serving/blob/develop/tools/Dockerfile.gpu.devel)准备
步骤
 * git clone https://github.com/PaddlePaddle/Serving
 * cd Serving && git submodule update --init --recursive
 * git checkout v0.2.0
 * mkdir build && cd build
 *  export PYTHONROOT=/usr/
 * cmake -DPYTHON_INCLUDE_DIR=$PYTHONROOT/include/python2.7/ -DPYTHON_LIBRARIES=$PYTHONROOT/lib/libpython2.7.so -DPYTHON_EXECUTABLE=$PYTHONROOT/bin/python -DSERVER=ON -DWITH_GPU=ON ..

**Comment by barrierye** [comment]
您好，gpu版本编译请使用[Dockerfile.gpu.devel（即您查看的Dockerfile）](https://github.com/PaddlePaddle/Serving/blob/develop/tools/Dockerfile.gpu.devel)，而运行镜像 hub.baidubce.com/ctr/paddleserving:0.1.3-gpu 是给运行而非编译使用的（由Dockerfile.gpu构建），暂时没有提供构建好的开发镜像。

两者的基础镜像不同，Dockerfile.gpu.devel使用的基础镜像为nvidia/cuda:9.0-cudnn7-devel-centos7，而Dockerfile.gpu使用的基础镜像为nvidia/cuda:9.0-cudnn7-runtime-centos7

**Comment by hysunflower** [comment]
> 您好，gpu版本编译请使用[Dockerfile.gpu.devel（即您查看的Dockerfile）](https://github.com/PaddlePaddle/Serving/blob/develop/tools/Dockerfile.gpu.devel)，而运行镜像 hub.baidubce.com/ctr/paddleserving:0.1.3-gpu 是给运行而非编译使用的（由Dockerfile.gpu构建），暂时没有提供构建好的开发镜像。
> 
> 两者的基础镜像不同，Dockerfile.gpu.devel使用的基础镜像为nvidia/cuda:9.0-cudnn7-devel-centos7，而Dockerfile.gpu使用的基础镜像为nvidia/cuda:9.0-cudnn7-runtime-centos7

好的，明白了，总体就是编译需要编译镜像，运行需要运行镜像，编译镜像支持运行，但是运行镜像不支持编译哈。

我试一下按照编译所需的dockerfile构建镜像然后编译。建议在 [如何编译serving](https://github.com/PaddlePaddle/Serving/blob/develop/doc/COMPILE.md)页面提供链接跳转至
[如何在Docker中运行PaddleServing](https://github.com/PaddlePaddle/Serving/blob/v0.2.0/doc/RUN_IN_DOCKER_CN.md) ,为用户提供dockerfile 构建编译镜像的用法

**Comment by barrierye** [comment]
好的，将会在RUN_IN_DOCKER文档中添加开发镜像相关的说明，感谢！

**Comment by hysunflower** [comment]
> 好的，将会在RUN_IN_DOCKER文档中添加开发镜像相关的说明，感谢！


试了一下按照 [Dockerfile.gpu.devel](https://github.com/PaddlePaddle/Serving/blob/develop/tools/Dockerfile.gpu.devel)构建镜像出现如下问题:
<img width="1354" alt="图片" src="https://user-images.githubusercontent.com/52739577/77905843-8a1e9e00-72b9-11ea-8214-5585f320d878.png">


步骤：
 * 拷贝dockerfile 内容到Dockerfile
 *  开代理
 *  docker build -t hub.baidubce.com/paddlepaddle/serving:0.1.3-gpu-build-to-compile .
不知是什么原因？

**Comment by barrierye** [comment]
> 试了一下按照 Dockerfile.gpu.devel构建镜像出现如下问题

看起来是下载get-pip.py的时候出现的问题，请问用您的代理可以顺利下载get-pip.py（`curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py`）吗？

**Comment by hysunflower** [comment]
> > 试了一下按照 Dockerfile.gpu.devel构建镜像出现如下问题
> 
> 看起来是下载get-pip.py的时候出现的问题，请问用您的代理可以顺利下载get-pip.py（`curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py`）吗？


可以的，如下
<img width="1029" alt="图片" src="https://user-images.githubusercontent.com/52739577/77907314-04e8b880-72bc-11ea-9864-ca211ff37adc.png">

<img width="370" alt="图片" src="https://user-images.githubusercontent.com/52739577/77907334-0dd98a00-72bc-11ea-9710-4a65506cd088.png">

**Comment by barrierye** [comment]
> 可以的，如下

想确认下您这个也是在代理环境下下载get-pip.py吗？
能否将Dockerfile中 `curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py >/dev/null`的 `>/dev/nul`删除，看看具体输出了什么呢

**Comment by hysunflower** [comment]
> > 可以的，如下
> 
> 想确认下您这个也是在代理环境下下载get-pip.py吗？
> 能否将Dockerfile中 `curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py >/dev/null`的 `>/dev/nul`删除，看看具体输出了什么呢

好的，我重新执行下docker build

**Comment by hysunflower** [comment]
> > 可以的，如下
> 
> 想确认下您这个也是在代理环境下下载get-pip.py吗？
> 能否将Dockerfile中 `curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py >/dev/null`的 `>/dev/nul`删除，看看具体输出了什么呢


重试之后 docker build 成功，之前可能是网络原因导致的下载失败？

然后编译server GPU版本执行 make -j10出现
<img width="342" alt="图片" src="https://user-images.githubusercontent.com/52739577/77918229-28b4fa00-72ce-11ea-8af5-b55a407143a0.png">
是还需要另外的编译依赖吗？我所理解的是dockerfile已经为用户提供了所有的依赖了

**Comment by barrierye** [comment]
> 是还需要另外的编译依赖吗？

是的，在make编译时需要下载一些第三方库进行编译，在过程中可能会因为网络原因而导致编译错误。您可以重新在本次make失败后继续make一下

**Comment by hysunflower** [comment]
> > 是还需要另外的编译依赖吗？
> 
> 是的，在make编译时需要下载一些第三方库进行编译，在过程中可能会因为网络原因而导致编译错误。您可以重新在本次make失败后继续make一下



<img width="904" alt="图片" src="https://user-images.githubusercontent.com/52739577/77924771-b1379880-72d6-11ea-8185-68a9321e94b7.png">

已成功编译

一个疑问，上述提到的编译需要用编译环境的dockerfile 来构建镜像，但是我之前用运行镜像起的docker 成功编译的client 、cpu server以及paddle-serving-app, 这三个是可以在运行或者开发镜像编译的而只有GPU 必须是开发镜像才可以吗？

**Comment by barrierye** [comment]
> 一个疑问，上述提到的编译需要用编译环境的dockerfile 来构建镜像，但是我之前用运行镜像起的docker 成功编译的client 、cpu server以及paddle-serving-app, 这三个是可以在运行或者开发镜像编译的而只有GPU 必须是开发镜像才可以吗？

您是否使用相应的docker.devel在CPU运行镜像中安装了必要的组件？

CPU版本的运行镜像和开发镜像都是同一个基础镜像，而GPU版本的运行镜像和开发镜像不是同一个基础镜像。

**Comment by hysunflower** [comment]
> > 一个疑问，上述提到的编译需要用编译环境的dockerfile 来构建镜像，但是我之前用运行镜像起的docker 成功编译的client 、cpu server以及paddle-serving-app, 这三个是可以在运行或者开发镜像编译的而只有GPU 必须是开发镜像才可以吗？
> 
> 您是否使用相应的docker.devel在CPU运行镜像中安装了必要的组件？
> 
> CPU版本的运行镜像和开发镜像都是同一个基础镜像，而GPU版本的运行镜像和开发镜像不是同一个基础镜像。



好的，多谢
