### ISSUE TITLE
参考run in docker文档，gpu docker build失败

### ISSUE THREAD

**Issue by MRXLT** [PaddlePaddle/Serving#351]
![image](https://user-images.githubusercontent.com/16594411/77850112-df4ba880-7202-11ea-9acb-2a51d48a8aa5.png)

**Comment by barrierye** [comment]
可否提供下相应的Docker版本和执行命令？没有复现出这个错误

**Comment by hysunflower** [comment]
* 使用的dockerfile 为由 serving 编译页跳转而来的[Dockerfile](https://github.com/PaddlePaddle/Serving/blob/develop/tools/Dockerfile.gpu.devel)
 *  [docker 构建页](https://github.com/PaddlePaddle/Serving/blob/v0.2.0/doc/RUN_IN_DOCKER_CN.md)的dockerfile 跳转和[serving编译页](https://github.com/PaddlePaddle/Serving/blob/develop/tools/Dockerfile.devel)的docker file跳转，所指向的具体内容（CPU 版本和GPU版本均是）有些许diff，上图所示为基于serving 编译页提供的dockerfile  构建docker，是否应该统一一下用同一个dockerfile，为用户提供一个稳定可构建的版本呢？

**Comment by barrierye** [comment]
您好，[serving编译页（COMPILE.md）](https://github.com/PaddlePaddle/Serving/blob/develop/doc/COMPILE.md)提供的是编译所需的Dockerfile（*.devel），[docker构建页（RUN_IN_DOCKER.md）](https://github.com/PaddlePaddle/Serving/blob/v0.2.0/doc/RUN_IN_DOCKER_CN.md)提供的是运行所需的Dockerfile（没有devel后缀）。因为编译需要一些运行时不需要的组件，所以两者有些许diff。

RUN_IN_DOCKER文档中使用的是运行所需的[Dockerfile.gpu](https://github.com/PaddlePaddle/Serving/blob/v0.2.0/tools/Dockerfile.gpu)。

看您的报错中有libSM-1.2.2相关package，是使用RUN_IN_DOCKER文档中的Dockerfile.gpu，可否提供具体的执行命令？我没有复现出这个错误

**Comment by hysunflower** [comment]
> 可否提供下相应的Docker版本和执行命令？没有复现出这个错误

docker 构建页的dockerfile 跳转可以成功构建 GPU 镜像 并通过测试GPU example
另外https://github.com/PaddlePaddle/Serving/blob/v0.2.0/doc/RUN_IN_DOCKER_CN.md
中此处
<img width="993" alt="图片" src="https://user-images.githubusercontent.com/52739577/77878591-385f1f00-728b-11ea-85d4-6016547eeb8d.png">

是否应该加上 --gpu_ids=XXX? 因为只export GPU 而不设置 --gpu_ids该参数 会报
<img width="1183" alt="图片" src="https://user-images.githubusercontent.com/52739577/77878480-f7670a80-728a-11ea-864f-45fa5c7c0fd7.png">
，这是否在预期内？

**Comment by barrierye** [comment]
> 是否应该加上 --gpu_ids=XXX

可否提供下机器上的gpu数，可能您的机器上没有两块gpu但是`export CUDA_VISIBLE_DEVICES`设置了两块。
另外`--gpu_ids=`会覆盖环境变量`CUDA_VISIBLE_DEVICES`，您是否用`--gpu_ids=0`只设置了一块gpu？

**Comment by hysunflower** [comment]
> > 是否应该加上 --gpu_ids=XXX
> 
> 可否提供下机器上的gpu数，可能您的机器上没有两块gpu但是`export CUDA_VISIBLE_DEVICES`设置了两块。
> 另外`--gpu_ids=`会覆盖环境变量`CUDA_VISIBLE_DEVICES`，您是否用`--gpu_ids=0`只设置了一块gpu？

八卡的机器

示例中--gpu_ids是缺省的，@MRXLT  已解答export 非必须 ，缺省情况下默认用0卡，但是实际情况是不export，缺省该参数会
<img width="1198" alt="图片" src="https://user-images.githubusercontent.com/52739577/77879932-1ca94800-728e-11ea-8661-a765f329e230.png">

**Comment by barrierye** [comment]
您好，缺省`CUDA_VISIBLE_DEVICES`和`gpu_ids`将使用0卡；另外查看了代码，这部分没有更新存在一个bug（您给的图）。

文档中将会补上`CUDA_VISIBLE_DEVICES`和`gpu_ids `的说明，感谢！

**Comment by barrierye** [comment]
> 您好，缺省CUDA_VISIBLE_DEVICES和gpu_ids将使用0卡；另外查看了代码，这部分没有更新存在一个bug（您给的图）。
文档中将会补上CUDA_VISIBLE_DEVICES和gpu_ids 的说明，感谢！

缺省`gpu_ids`将使用CPU，当`gpu_ids`超出`CUDA_VISIBLE_DEVICES`会报错
