### ISSUE TITLE
参考run in docker文档，构建cpu镜像失败

### ISSUE THREAD

**Issue by MRXLT** [PaddlePaddle/Serving#352]
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM centos:6.3
Pulling repository docker.io/library/centos
Could not reach any registry endpoint

**Comment by barrierye** [comment]
使用的是旧版Dockerfile，新版Dockerfile是基于centos:7.3.1611构建的，请根据文档中的[Dockerfile](https://github.com/PaddlePaddle/Serving/blob/develop/tools/Dockerfile)构建

**Comment by hysunflower** [comment]
> 使用的是旧版Dockerfile，新版Dockerfile是基于centos:7.3.1611构建的，请根据文档中的[Dockerfile](https://github.com/PaddlePaddle/Serving/blob/develop/tools/Dockerfile)构建

已重试，构建成功，并可通过  [构建docker ](https://github.com/PaddlePaddle/Serving/blob/v0.2.0/doc/RUN_IN_DOCKER_CN.md) CPU 版本  测试example
