### ISSUE TITLE
多进程使用出错

### ISSUE THREAD

**Issue by wangxicoding** [PaddlePaddle/Serving#356]
与paddle共用时，在Process开的子进程里面连接serving服务会出错。在使用线程或者不与paddle共用时没有问题
`client.connect([endpoint])`
![image](https://user-images.githubusercontent.com/10208305/77866414-8d883a00-7265-11ea-9bc9-93d84b95ea46.png)

**Comment by MRXLT** [comment]
经过沟通，在使用新版本的serving后没有再出现这个问题，推荐使用0.2.0版本或者develop版本
