### ISSUE TITLE
【需求】predict支持numpy

### ISSUE THREAD

**Issue by wangxicoding** [PaddlePaddle/Serving#357]
现在predict只支持list，效率较低，需要支持numpy
https://github.com/PaddlePaddle/Serving/blob/07fb167bb012b98602d589aae7fc57997d7e2f17/core/general-client/src/general_model.cpp#L135-L141

**Comment by guru4elephant** [comment]
有具体case嘛，提供一个环境看看

**Comment by guru4elephant** [comment]
https://github.com/PaddlePaddle/Serving/blob/develop/doc/BERT_10_MINS.md

**Comment by wangxicoding** [comment]
已支持 PR 
https://github.com/PaddlePaddle/Serving/pull/462
https://github.com/PaddlePaddle/Serving/pull/496
https://github.com/PaddlePaddle/Serving/pull/570
