### ISSUE TITLE
Start bert_as_service fail.

### ISSUE THREAD

**Issue by ShenYuhan** [PaddlePaddle/Serving#363]
Env:
PaddlePaddle: 1.6.2
Paddle_gpu_serving: 0.8.2
platform：Linux version 3.10.0_3-0-0-20 (gcc version 4.8.2 20140120 (Red Hat 4.8.2-16) (GCC) ) #1 SMP Thu May 24 14:41:54 CST 2018

When execute：
```python
from paddle_gpu_serving.run import BertServer
bs = BertServer(with_gpu=False)
bs.with_model("ernie")
bs.run(port=8010)
```

Exception info:
![image](https://user-images.githubusercontent.com/28444161/77892251-e62af780-72a4-11ea-93e3-6fdb1484f3b1.png)

**Comment by guru4elephant** [comment]
https://github.com/PaddlePaddle/Serving/blob/develop/doc/BERT_10_MINS.md 可以参考这个@ShenYuhan
