### ISSUE TITLE
PaddleDetection训练出来的模型，如何转换成PaddlePaddle/Serving可以部署的方式，求例子，弄了好久了还是不行

### ISSUE THREAD

**Issue by mcl-stone** [PaddlePaddle/Serving#377]

**Comment by guru4elephant** [comment]
收到，我们准备个例子

**Comment by mcl-stone** [comment]
感谢感谢

**Comment by mcl-stone** [comment]
> 收到，我们准备个例子

请问到时例子放在什么地方

**Comment by bjjwwang** [comment]
> > 收到，我们准备个例子
> 
> 请问到时例子放在什么地方

尽快给您一个可以wget的链接 压缩包解压就可以运行的那种

**Comment by mcl-stone** [comment]
> > > 收到，我们准备个例子
> > 
> > 
> > 请问到时例子放在什么地方
> 
> 尽快给您一个可以wget的链接 压缩包解压就可以运行的那种

感谢！

**Comment by bjjwwang** [comment]
我目前做了Serving保存的Pddet模型，我用yolov3的网络测试通过。可以在PaddleDetection目录下的tools/export_model.py的save_infer_model下做以下的改动，这样，就可以在pddet_serving_model下获取serving server端的模型配置，在pddet_client_conf获得客户端的配置。

![image](https://user-images.githubusercontent.com/23625746/78341895-03283900-75cb-11ea-93f1-78101d5cebff.png)
需要按照箭头处import serving的一个包
然后按照红框处，写好feed 和 fetch字典，运行export_model即可。

此外，还有数据的读取部分，可以参考Serving代码库下的python/examples/imagenet/image_reader.py

后期我们计划将Serving和PaddleDetection做更深度的整合。

**Comment by bjjwwang** [comment]
> > 收到，我们准备个例子
> 
> 请问到时例子放在什么地方

wget https://paddle-serving.bj.bcebos.com/unittest/pddet_yolov3_mobilenet_v1_fruit.tar.gz 里面是yolov3的模型可在serving启动。

**Comment by mcl-stone** [comment]
> 要按照箭头处import serving的一个包
> 然后按照红框处，写好feed 和 fetch字典，运行export_model即可。
> 
> 此外，还有数据的读取部分，可以参考Serving代码库下的python/examples/imagenet/image_reader.py
> 
> 后期我们计划将Serving和PaddleDetection做更深度的整合。

感谢！

**Comment by mcl-stone** [comment]
您好，按您的回复测试了下，报以下错误，我的cuda是10.1，但他找9.0版本
python3 -m paddle_serving_server_gpu.serve --model ./inference_model/yolov3_darknet_voc/hat_serving_model --port 9292 --gpu_ids 3
CUDA Version 10.1.105
mkdir: cannot create directory ‘workdir_3’: File exists
Going to Run Comand
/usr/local/lib/python3.6/dist-packages/paddle_serving_server_gpu/serving-gpu-0.2.0/serving -enable_model_toolkit -inferservice_path workdir_3 -inferservice_file infer_service.prototxt -max_concurrency 0 -num_threads 10 -port 9292 -reload_interval_s 10 -resource_path workdir_3 -resource_file resource.prototxt -workflow_path workdir_3 -workflow_file workflow.prototxt -bthread_concurrency 10 -gpuid 3 
/usr/local/lib/python3.6/dist-packages/paddle_serving_server_gpu/serving-gpu-0.2.0/serving: error while loading shared libraries: libcudart.so.9.0: cannot open shared object file: No such file or directory

**Comment by mcl-stone** [comment]
> > > 收到，我们准备个例子
> > 
> > 
> > 请问到时例子放在什么地方
> 
> wget https://paddle-serving.bj.bcebos.com/unittest/pddet_yolov3_mobilenet_v1_fruit.tar.gz 里面是yolov3的模型可在serving启动。

使用这个实例在serving中启动也是报上面一样的错误

**Comment by bjjwwang** [comment]
> > > > 收到，我们准备个例子
> > > 
> > > 
> > > 请问到时例子放在什么地方
> > 
> > 
> > wget https://paddle-serving.bj.bcebos.com/unittest/pddet_yolov3_mobilenet_v1_fruit.tar.gz 里面是yolov3的模型可在serving启动。
> 
> 使用这个实例在serving中启动也是报上面一样的错误

我建议要不要试一试Docker
首先参考下这个文档的GPU的部分 
https://github.com/PaddlePaddle/Serving/blob/develop/doc/RUN_IN_DOCKER_CN.md
然后以这个yolov3的模型为例

``` bash
nvidia-docker run -p 9292:9292 --name test -dit hub.baidubce.com/paddlepaddle/serving:0.2.0-gpu #端口可以自己定不一定是9292，如果不需要对外暴露只是做实验也可以把 -p 9292:9292直接去掉
nvidia-docker exec -it test bash
```
进入docker以后
```
wget https://paddle-serving.bj.bcebos.com/unittest/pddet_yolov3_mobilenet_v1_fruit.tar.gz 
tar xf pddet_yolov3_mobilenet_v1_fruit.tar.gz
cd model
python -m paddle_serving_server_gpu.serve --model ./pddet_serving_model/ --port 9292 --gpu_ids 0 # gpu id可以自己定，然后python3目前是不支持的
```
您可以试一下。

**Comment by mcl-stone** [comment]
> > > > > 收到，我们准备个例子
> > > > 
> > > > 
> > > > 请问到时例子放在什么地方
> > > 
> > > 
> > > wget https://paddle-serving.bj.bcebos.com/unittest/pddet_yolov3_mobilenet_v1_fruit.tar.gz 里面是yolov3的模型可在serving启动。
> > 
> > 
> > 使用这个实例在serving中启动也是报上面一样的错误
> 
> 我建议要不要试一试Docker
> 首先参考下这个文档的GPU的部分
> https://github.com/PaddlePaddle/Serving/blob/develop/doc/RUN_IN_DOCKER_CN.md
> 然后以这个yolov3的模型为例
> 
> ```shell
> nvidia-docker run -p 9292:9292 --name test -dit hub.baidubce.com/paddlepaddle/serving:0.2.0-gpu #端口可以自己定不一定是9292，如果不需要对外暴露只是做实验也可以把 -p 9292:9292直接去掉
> nvidia-docker exec -it test bash
> ```
> 
> 进入docker以后
> 
> ```
> wget https://paddle-serving.bj.bcebos.com/unittest/pddet_yolov3_mobilenet_v1_fruit.tar.gz 
> tar xf pddet_yolov3_mobilenet_v1_fruit.tar.gz
> cd model
> python -m paddle_serving_server_gpu.serve --model ./pddet_serving_model/ --port 9292 --gpu_ids 0 # gpu id可以自己定，然后python3目前是不支持的
> ```
> 
> 您可以试一下。

好的！感谢！你这最后说“python3目前是不支持的”，是paddle serving都不支持python3吗？

**Comment by bjjwwang** [comment]
> > > > > > 收到，我们准备个例子
> > > > > 
> > > > > 
> > > > > 请问到时例子放在什么地方
> > > > 
> > > > 
> > > > wget https://paddle-serving.bj.bcebos.com/unittest/pddet_yolov3_mobilenet_v1_fruit.tar.gz 里面是yolov3的模型可在serving启动。
> > > 
> > > 
> > > 使用这个实例在serving中启动也是报上面一样的错误
> > 
> > 
> > 我建议要不要试一试Docker
> > 首先参考下这个文档的GPU的部分
> > https://github.com/PaddlePaddle/Serving/blob/develop/doc/RUN_IN_DOCKER_CN.md
> > 然后以这个yolov3的模型为例
> > ```shell
> > nvidia-docker run -p 9292:9292 --name test -dit hub.baidubce.com/paddlepaddle/serving:0.2.0-gpu #端口可以自己定不一定是9292，如果不需要对外暴露只是做实验也可以把 -p 9292:9292直接去掉
> > nvidia-docker exec -it test bash
> > ```
> > 
> > 
> > 进入docker以后
> > ```
> > wget https://paddle-serving.bj.bcebos.com/unittest/pddet_yolov3_mobilenet_v1_fruit.tar.gz 
> > tar xf pddet_yolov3_mobilenet_v1_fruit.tar.gz
> > cd model
> > python -m paddle_serving_server_gpu.serve --model ./pddet_serving_model/ --port 9292 --gpu_ids 0 # gpu id可以自己定，然后python3目前是不支持的
> > ```
> > 
> > 
> > 您可以试一下。
> 
> 好的！感谢！你这最后说“python3目前是不支持的”，是paddle serving都不支持python3吗？

Paddle Serving的服务端Server不支持Python3。
但PaddleServing的客户端Client是支持的，未来还会做更多语言的支持。

**Comment by mcl-stone** [comment]
> > > > > > > 收到，我们准备个例子
> > > > > > 
> > > > > > 
> > > > > > 请问到时例子放在什么地方
> > > > > 
> > > > > 
> > > > > wget https://paddle-serving.bj.bcebos.com/unittest/pddet_yolov3_mobilenet_v1_fruit.tar.gz 里面是yolov3的模型可在serving启动。
> > > > 
> > > > 
> > > > 使用这个实例在serving中启动也是报上面一样的错误
> > > 
> > > 
> > > 我建议要不要试一试Docker
> > > 首先参考下这个文档的GPU的部分
> > > https://github.com/PaddlePaddle/Serving/blob/develop/doc/RUN_IN_DOCKER_CN.md
> > > 然后以这个yolov3的模型为例
> > > ```shell
> > > nvidia-docker run -p 9292:9292 --name test -dit hub.baidubce.com/paddlepaddle/serving:0.2.0-gpu #端口可以自己定不一定是9292，如果不需要对外暴露只是做实验也可以把 -p 9292:9292直接去掉
> > > nvidia-docker exec -it test bash
> > > ```
> > > 
> > > 
> > > 进入docker以后
> > > ```
> > > wget https://paddle-serving.bj.bcebos.com/unittest/pddet_yolov3_mobilenet_v1_fruit.tar.gz 
> > > tar xf pddet_yolov3_mobilenet_v1_fruit.tar.gz
> > > cd model
> > > python -m paddle_serving_server_gpu.serve --model ./pddet_serving_model/ --port 9292 --gpu_ids 0 # gpu id可以自己定，然后python3目前是不支持的
> > > ```
> > > 
> > > 
> > > 您可以试一下。
> > 
> > 
> > 好的！感谢！你这最后说“python3目前是不支持的”，是paddle serving都不支持python3吗？
> 
> Paddle Serving的服务端Server不支持Python3。
> 但PaddleServing的客户端Client是支持的，未来还会做更多语言的支持。

好的！那我用docker，感谢！

**Comment by mcl-stone** [comment]
我在docker中运行，使用的python2，还是这个错误root@a0d1adebb7ca:/paddle/Documents/PaddleDetection# python -m paddle_serving_server_gpu.serve --model uci_housing_model --thread 10 
gpu_ids not set, going to run cpu service.
CUDA Version 10.0.130
mkdir: cannot create directory 'workdir_-1': File exists
Going to Run Comand
/usr/local/lib/python2.7/dist-packages/paddle_serving_server_gpu/serving-gpu-0.2.0/serving -enable_model_toolkit -inferservice_path workdir_-1 -inferservice_file infer_service.prototxt -max_concurrency 0 -num_threads 10 -port 9292 -reload_interval_s 10 -resource_path workdir_-1 -resource_file resource.prototxt -workflow_path workdir_-1 -workflow_file workflow.prototxt -bthread_concurrency 10 -gpuid 0 
/usr/local/lib/python2.7/dist-packages/paddle_serving_server_gpu/serving-gpu-0.2.0/serving: error while loading shared libraries: libcudart.so.9.0: cannot open shared object file: No such file or directory

**Comment by barrierye** [comment]
> 我在docker中运行，使用的python2，还是这个错误root@a0d1adebb7ca:/paddle/Documents/PaddleDetection# python -m paddle_serving_server_gpu.serve --model uci_housing_model --thread 10
> gpu_ids not set, going to run cpu service.
> CUDA Version 10.0.130
> mkdir: cannot create directory 'workdir_-1': File exists
> Going to Run Comand
> /usr/local/lib/python2.7/dist-packages/paddle_serving_server_gpu/serving-gpu-0.2.0/serving -enable_model_toolkit -inferservice_path workdir_-1 -inferservice_file infer_service.prototxt -max_concurrency 0 -num_threads 10 -port 9292 -reload_interval_s 10 -resource_path workdir_-1 -resource_file resource.prototxt -workflow_path workdir_-1 -workflow_file workflow.prototxt -bthread_concurrency 10 -gpuid 0
> /usr/local/lib/python2.7/dist-packages/paddle_serving_server_gpu/serving-gpu-0.2.0/serving: error while loading shared libraries: libcudart.so.9.0: cannot open shared object file: No such file or directory

您好，想确认一下您使用的是哪个docker镜像。[RUN_IN_DOCKER](https://github.com/PaddlePaddle/Serving/blob/develop/doc/RUN_IN_DOCKER_CN.md)文档中暂时只提供了CUDA9的镜像，但您的Log信息中是`CUDA Version 10.0.130`

**Comment by wangjiawei04** [comment]
> 我在docker中运行，使用的python2，还是这个错误root@a0d1adebb7ca:/paddle/Documents/PaddleDetection# python -m paddle_serving_server_gpu.serve --model uci_housing_model --thread 10
> gpu_ids not set, going to run cpu service.
> CUDA Version 10.0.130
> mkdir: cannot create directory 'workdir_-1': File exists
> Going to Run Comand
> /usr/local/lib/python2.7/dist-packages/paddle_serving_server_gpu/serving-gpu-0.2.0/serving -enable_model_toolkit -inferservice_path workdir_-1 -inferservice_file infer_service.prototxt -max_concurrency 0 -num_threads 10 -port 9292 -reload_interval_s 10 -resource_path workdir_-1 -resource_file resource.prototxt -workflow_path workdir_-1 -workflow_file workflow.prototxt -bthread_concurrency 10 -gpuid 0
> /usr/local/lib/python2.7/dist-packages/paddle_serving_server_gpu/serving-gpu-0.2.0/serving: error while loading shared libraries: libcudart.so.9.0: cannot open shared object file: No such file or directory

用的是哪个docker镜像？ 
是`hub.baidubce.com/paddlepaddle/serving:0.2.0-gpu`这个吗

**Comment by mcl-stone** [comment]
> > 我在docker中运行，使用的python2，还是这个错误root@a0d1adebb7ca:/paddle/Documents/PaddleDetection# python -m paddle_serving_server_gpu.serve --model uci_housing_model --thread 10
> > gpu_ids not set, going to run cpu service.
> > CUDA Version 10.0.130
> > mkdir: cannot create directory 'workdir_-1': File exists
> > Going to Run Comand
> > /usr/local/lib/python2.7/dist-packages/paddle_serving_server_gpu/serving-gpu-0.2.0/serving -enable_model_toolkit -inferservice_path workdir_-1 -inferservice_file infer_service.prototxt -max_concurrency 0 -num_threads 10 -port 9292 -reload_interval_s 10 -resource_path workdir_-1 -resource_file resource.prototxt -workflow_path workdir_-1 -workflow_file workflow.prototxt -bthread_concurrency 10 -gpuid 0
> > /usr/local/lib/python2.7/dist-packages/paddle_serving_server_gpu/serving-gpu-0.2.0/serving: error while loading shared libraries: libcudart.so.9.0: cannot open shared object file: No such file or directory
> 
> 用的是哪个docker镜像？
> 是`hub.baidubce.com/paddlepaddle/serving:0.2.0-gpu`这个吗
> 我刚刚跑了一遍是可以的

我是使用的docker pull hub.baidubce.com/paddlepaddle/paddle:1.7.1-gpu-cuda10.0-cudnn7这个，里面安装了serving，这样不行吗？是不是必须用cuda9？那我也用这个镜像试试

**Comment by barrierye** [comment]
> > > 我在docker中运行，使用的python2，还是这个错误root@a0d1adebb7ca:/paddle/Documents/PaddleDetection# python -m paddle_serving_server_gpu.serve --model uci_housing_model --thread 10
> > > gpu_ids not set, going to run cpu service.
> > > CUDA Version 10.0.130
> > > mkdir: cannot create directory 'workdir_-1': File exists
> > > Going to Run Comand
> > > /usr/local/lib/python2.7/dist-packages/paddle_serving_server_gpu/serving-gpu-0.2.0/serving -enable_model_toolkit -inferservice_path workdir_-1 -inferservice_file infer_service.prototxt -max_concurrency 0 -num_threads 10 -port 9292 -reload_interval_s 10 -resource_path workdir_-1 -resource_file resource.prototxt -workflow_path workdir_-1 -workflow_file workflow.prototxt -bthread_concurrency 10 -gpuid 0
> > > /usr/local/lib/python2.7/dist-packages/paddle_serving_server_gpu/serving-gpu-0.2.0/serving: error while loading shared libraries: libcudart.so.9.0: cannot open shared object file: No such file or directory
> > 
> > 
> > 用的是哪个docker镜像？
> > 是`hub.baidubce.com/paddlepaddle/serving:0.2.0-gpu`这个吗
> > 我刚刚跑了一遍是可以的
> 
> 我是使用的docker pull hub.baidubce.com/paddlepaddle/paddle:1.7.1-gpu-cuda10.0-cudnn7这个，里面安装了serving，这样不行吗？是不是必须用cuda9？那我也用这个镜像试试

目前版本(Paddle Serving 0.2.0)只支持cuda9.0-cudnn7，需要使用对应的镜像才能运行。建议使用`hub.baidubce.com/paddlepaddle/serving:0.2.0-gpu`镜像（已经做好了环境适配）~

**Comment by mcl-stone** [comment]
![image](https://user-images.githubusercontent.com/62418900/78763231-74932d80-79b7-11ea-8e7f-c066ef3912c1.png)
![image](https://user-images.githubusercontent.com/62418900/78763312-8d034800-79b7-11ea-85e9-294631e1e712.png)
需要在docker内再安装什么吗？我有四个显卡，但docker内检测不到

**Comment by barrierye** [comment]
> ![image](https://user-images.githubusercontent.com/62418900/78763231-74932d80-79b7-11ea-8e7f-c066ef3912c1.png)
> ![image](https://user-images.githubusercontent.com/62418900/78763312-8d034800-79b7-11ea-85e9-294631e1e712.png)
> 需要在docker内再安装什么吗？我有四个显卡，但docker内检测不到

请问您是否按[RUN_IN_DOCKER](https://github.com/PaddlePaddle/Serving/blob/develop/doc/RUN_IN_DOCKER_CN.md)文档用`nvidia-docker`命令启动容器？

**Comment by mcl-stone** [comment]
> > ![image](https://user-images.githubusercontent.com/62418900/78763231-74932d80-79b7-11ea-8e7f-c066ef3912c1.png)
> > ![image](https://user-images.githubusercontent.com/62418900/78763312-8d034800-79b7-11ea-85e9-294631e1e712.png)
> > 需要在docker内再安装什么吗？我有四个显卡，但docker内检测不到
> 
> 请问您是否按[RUN_IN_DOCKER](https://github.com/PaddlePaddle/Serving/blob/develop/doc/RUN_IN_DOCKER_CN.md)文档用`nvidia-docker`命令启动容器？
按照官方安装和使用
![image](https://user-images.githubusercontent.com/62418900/78763651-000cbe80-79b8-11ea-8ee7-2206187503bb.png)
![image](https://user-images.githubusercontent.com/62418900/78763721-1a469c80-79b8-11ea-8c82-591ad37dcfc0.png)
需要用下面这个吗？
![image](https://user-images.githubusercontent.com/62418900/78763798-35191100-79b8-11ea-8d09-0d0f2b2d3adc.png)

**Comment by barrierye** [comment]
目前只测试过通过`nvidia-docker`命令启动容器。

可否提供一下您的启动命令？

**Comment by mcl-stone** [comment]
> 目前只测试过通过`nvidia-docker`命令启动容器。
> 
> 可否提供一下您的启动命令？

docker run -p 9292:9292 --name test -dit hub.baidubce.com/paddlepaddle/serving:0.2.0-gpu
docker exec -it test bash
就是把前面nvidia去掉了，那我也装上nvidia-docker试试把

**Comment by barrierye** [comment]
> > 目前只测试过通过`nvidia-docker`命令启动容器。
> > 可否提供一下您的启动命令？
> 
> docker run -p 9292:9292 --name test -dit hub.baidubce.com/paddlepaddle/serving:0.2.0-gpu
> docker exec -it test bash
> 就是把前面nvidia去掉了，那我也装上nvidia-docker试试把

需要GPU版的docker：
- `docker run --gpus all -dit hub.baidubce.com/paddlepaddle/serving:0.2.0-gpu`
- `nvidia-docker run -dit hub.baidubce.com/paddlepaddle/serving:0.2.0-gpu`

目前只测试过后者。

**Comment by mcl-stone** [comment]
> * docker run --gpus all -dit hub.baidubce.com/paddlepaddle/serving:0.2.0-gpu

好的！感谢！
