### ISSUE TITLE
按照编译文档编译Serving时出错

### ISSUE THREAD

**Issue by MRXLT** [PaddlePaddle/Serving#382]
参考https://github.com/PaddlePaddle/Serving/blob/develop/doc/COMPILE_CN.md
错误如下
![image](https://user-images.githubusercontent.com/16594411/78226323-22a56000-74fe-11ea-845e-21efd26d4c1c.png)

**Comment by hysunflower** [comment]
> 参考https://github.com/PaddlePaddle/Serving/blob/develop/doc/COMPILE_CN.md
> 错误如下
> ![image](https://user-images.githubusercontent.com/16594411/78226323-22a56000-74fe-11ea-845e-21efd26d4c1c.png)

 我这边可以编译成功。
* 所用docker 镜像为 [如何编译PaddleServing](https://github.com/PaddlePaddle/Serving/blob/develop/doc/COMPILE_CN.md) 页提供的GPU Dpckerfile 所编译好的镜像

 * 然后在v0.2.0分支上按照[如何编译PaddleServing](https://github.com/PaddlePaddle/Serving/blob/develop/doc/COMPILE_CN.md)  进行GPU 编译

 * 编译过程有make -j10 后2次失败，但是重试后最终能够成功编译
<img width="973" alt="图片" src="https://user-images.githubusercontent.com/52739577/78232279-96e40180-7506-11ea-8077-ee97bed09965.png">

**Comment by barrierye** [comment]
单线程编译没有问题，在使用多线程编译时（尤其是使用`-j10`）有可能会失败，多次重试后可以构建成功。

应该是makefile中缺失部分依赖，这是一个问题。

**Comment by barrierye** [comment]
您好，能否看下Error位置处，是否是以下报错？
```shell
/Serving/build/core/pdcodegen/pdcodegen: program not found or is not executable
```

**Comment by barrierye** [comment]
多线程编译存在另外一个错误，应该也是依赖问题：
```shell
Error copying file "/home/baiwei/Serving/build-server/third_party/brpc/src/extern_brpc-build/brpc/policy/baidu_rpc_meta.pb.h" to "/home/baiwei/Serving/build-server/third_party/brpc/src/extern_brpc-build/output/include/brpc/policy/baidu_rpc_meta.pb.h".
[  3%] [  4%] make[5]: *** [brpc/policy/baidu_rpc_meta.pb.h] 错误 1
make[5]: *** 正在等待未完成的任务....
```

**Comment by guru4elephant** [comment]
https://github.com/PaddlePaddle/Serving/pull/393 fixed.
