### ISSUE TITLE
server端不支持centos6 ,ubuntu16,ubuntu 18

### ISSUE THREAD

**Issue by MRXLT** [PaddlePaddle/Serving#383]
centos 6
![image](https://user-images.githubusercontent.com/16594411/78227832-79139e00-7500-11ea-9b53-e9b8d57701c2.png)

ubuntu 16
![image](https://user-images.githubusercontent.com/16594411/78227541-fdb1ec80-74ff-11ea-86cd-5838a7e6f713.png)
ubuntu 18
![image](https://user-images.githubusercontent.com/16594411/78227578-0b677200-7500-11ea-8288-a5ae65908849.png)

**Comment by guru4elephant** [comment]
官方给出按照docker启动server的方法，放在readme
