### ISSUE TITLE
变长序列输入导致Serving服务挂掉

### ISSUE THREAD

**Issue by wangxicoding** [PaddlePaddle/Serving#416]
如图，定义feed_var时，shape为(-1, max_seqlen, 1)也即(-1, 300, 1)。
但在实际输入时seqlen会变化，输入可能是(100, seqlen=101, 1)  (100, seqlen=231, 1) (100, seqlen=300, 1) ...
![image](https://user-images.githubusercontent.com/10208305/78622418-a624cf80-78b7-11ea-86cf-45480ea8efe5.png)

这种情况下predict会导致Serving服务挂掉
![image](https://user-images.githubusercontent.com/10208305/78623065-5f37d980-78b9-11ea-8ec3-06b80be554c0.png)

**Comment by bjjwwang** [comment]
感谢您的问题，收到，我们研究一下。
