### ISSUE TITLE
batch_size为1返回的fetch_map_list为dict

### ISSUE THREAD

**Issue by wangxicoding** [PaddlePaddle/Serving#433]
fetch_map_list = client.predict(feed=feed_map_list, fetch=fetch)

如果feed_map_list的len为1，即batch_size=1，则返回的fetch_map_list为 dict
若feed_map_list的len > 1，即batch_size>1，则返回的fetch_map_list为列表 [dict, ..., dict]

返回类型不一致，按照多batch时候的代码处理batch_size=1的场景会出错。希望可以把返回类型统一一下
![image](https://user-images.githubusercontent.com/10208305/78864616-8a175e80-7a6e-11ea-90fa-6e362db5a6ba.png)
![image](https://user-images.githubusercontent.com/10208305/78864658-a5826980-7a6e-11ea-81a2-5f3b47afa431.png)

**Comment by guru4elephant** [comment]
改为统一design，返回list

**Comment by MRXLT** [comment]
为了更灵活的支持各种模型的预测结果shape，将返回结果统一为dict格式，每个key内部为batch的预测结果，numpy array格式
https://github.com/PaddlePaddle/Serving/pull/462
