### ISSUE TITLE
导致Serving服务挂掉的场景

### ISSUE THREAD

**Issue by wangxicoding** [PaddlePaddle/Serving#434]
1、batch_size过大，显存爆掉

2、传入空数据
![image](https://user-images.githubusercontent.com/10208305/78865872-014df200-7a71-11ea-830d-0eddd08fc43d.png)

3、非法、不合规数据？如目前不支持的变长seqlen

服务需要健壮些，否则用户的某些操作一不小心就导致Serving挂掉了

**Comment by MRXLT** [comment]
感谢反馈，针对第2、3条，添加了对输入数据的格式检查，PR https://github.com/PaddlePaddle/Serving/pull/437
