### ISSUE TITLE
提供的编译docker里没有配置python3

### ISSUE THREAD

**Issue by hysunflower** [PaddlePaddle/Serving#436]
* 如链接 [How to compile PaddleServing](https://github.com/PaddlePaddle/Serving/blob/develop/doc/COMPILE.md)，，未配置py3
 * 在编好的dev 镜像安装anaconda 并创建3.6的环境后，编译过程出现
<img width="1158" alt="图片" src="https://user-images.githubusercontent.com/52739577/78876918-a7eebe80-7a82-11ea-990f-72a8ffc0e0a4.png">
<img width="638" alt="图片" src="https://user-images.githubusercontent.com/52739577/78877167-01ef8400-7a83-11ea-850b-f3694a1cd0fa.png">

<img width="1072" alt="图片" src="https://user-images.githubusercontent.com/52739577/78877058-d8cef380-7a82-11ea-973c-5314c05e110a.png">

编的时候除了最后的ERROR 中间没erro

 * 反复尝试后中间包了一次err ModuleNotFoundError: No module named 'google'
，pip 好protobuf 后编过了

**Comment by barrierye** [comment]
您好，后面会提供python3版本的镜像~
