### ISSUE TITLE
Serving性能相关问题

### ISSUE THREAD

**Issue by wangxicoding** [PaddlePaddle/Serving#445]
![image](https://user-images.githubusercontent.com/10208305/79088296-c56aa380-7d74-11ea-8549-95ef3b0f1ab8.png)

见之前issue https://github.com/PaddlePaddle/Serving/issues/432 ，batch_size=1时，fetch的数据量约为22.63MB。profile图中共有三个连接进程，每个batch_size=1。
可能由于fetch数据量较大，`postpro`部分占用时间较长，`client_infer`后面也出现较长的空挡，不知道是否是网络传输的空挡。
进程间不同通信的空挡较大可能是由于fetch数据较大，进程处理数据 + OutPutQueue.put() + InputQueue.get() 耗时较长造成的

**Comment by MRXLT** [comment]
感谢反馈，这里的时间空档包含了数据的网络传输、python和c++之间的内存拷贝，由于数据量较大导致耗时过多，我们后续会进行优化
