### ISSUE TITLE
client只支持在自己线程内使用？

### ISSUE THREAD

**Issue by wangxicoding** [PaddlePaddle/Serving#446]
client在主线程中定义连接server，开启线程池用主线程中定义的client predict，出现如下错误。目前client只支持在定义的线程内使用？
![image](https://user-images.githubusercontent.com/10208305/79100058-16d85a00-7d98-11ea-9d6f-aaed5b2af926.png)

**Comment by MRXLT** [comment]
目前predict接口暂不支持多线程调用，推荐使用多进程

**Comment by wangxicoding** [comment]
Fixed with PR https://github.com/PaddlePaddle/Serving/pull/601
