### ISSUE TITLE
创建多个client似乎没有并发

### ISSUE THREAD

**Issue by wangxicoding** [PaddlePaddle/Serving#447]
一个进程中创建多个线程，每个线程启动一个client连接同一个server，出现如下log，各个线程的client共用底层的链接？
![image](https://user-images.githubusercontent.com/10208305/79107507-10051380-7da7-11ea-90d2-bcac56e46c4b.png)

进行profile，图中开了三个进程，每个进程开两个线程连接同一server，不同进程连接不同server。从图看来同一线程里的多个client没有并发起来。
![image](https://user-images.githubusercontent.com/10208305/79107826-adf8de00-7da7-11ea-8096-c3ea3bf384b3.png)

速度测试，一个进程一个线程的速度和一个进程两个线程的速度 都为5.79s/step。对同一server开启多个线程连接没有速度上的提升。

**Comment by barrierye** [comment]
您好，之前确实是同进程的client共用底层连接，在这个PR中解决了：https://github.com/PaddlePaddle/Serving/pull/395

我们会尽快进行速度测试。

**Comment by wangxicoding** [comment]
> 您好，之前确实是同进程的client共用底层连接，在这个PR中解决了：#395
> 
> 我们会尽快进行速度测试。

嗯，现在是对同一server加大线程并发似乎没有效果

**Comment by barrierye** [comment]
目前同进程多Client没有速度提升，我们会尽快解决这个问题。

**Comment by barrierye** [comment]
> 每个进程开两个线程连接同一server

您好，目前由于Python GIL全局锁的问题，同进程内多个线程的Client不能做到并发。
后续我们会考虑Client异步predict，或是采用其他方式改善这个问题。

**Comment by Karenlyw** [comment]
> > 每个进程开两个线程连接同一server
> 
> 您好，目前由于Python GIL全局锁的问题，同进程内多个线程的Client不能做到并发。
> 后续我们会考虑Client异步predict，或是采用其他方式改善这个问题。

您好，请问多进程，每个进程创建一个client的话，可以支持并发嘛
