### ISSUE TITLE
PaddleDetection训练好的模型，如何通过Serving部署在服务器上，然后通过http/rpc的方式使用

### ISSUE THREAD

**Issue by omtbreak** [PaddlePaddle/Serving#464]

**Comment by guru4elephant** [comment]
https://github.com/PaddlePaddle/Serving/pull/448 会提供这个示例，即将合入@omtbreak

**Comment by omtbreak** [comment]
> #448 会提供这个示例，即将合入@omtbreak

请问多久可以提供，以及从哪里看呐

**Comment by guru4elephant** [comment]
https://github.com/PaddlePaddle/Serving/tree/develop/python/examples/faster_rcnn_model
@omtbreak

**Comment by omtbreak** [comment]
> https://github.com/PaddlePaddle/Serving/tree/develop/python/examples/faster_rcnn_model
> @omtbreak

感谢，还有一个问题，请问pddet_serving_model下的模型权重和由PaddleDetection训练得到的模型权重有什么区别，是需要转换嘛

**Comment by guru4elephant** [comment]
没有区别，只是里面有serving要求的配置文件@omtbreak

**Comment by omtbreak** [comment]
> 没有区别，只是里面有serving要求的配置文件@omtbreak

您好，以Faster RCNN来说，PaddleDetection训练得到的模型权重，保存类型为（ pdmodel, pdopt, pdparams）
而例子中 /faster_rcnn_model/pddet_serving_model 的提供下载的用于serving的模型权重是( _scale, _offset, _weights )  
这是有区别的吧，不知道如何进行转换，希望得到您的回复。

**Comment by guru4elephant** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/master/tools/export_serving_model.py @omtbreak 请参考这个工具导出部署包
