### ISSUE TITLE
check_cuda的方式有问题

### ISSUE THREAD

**Issue by wangxicoding** [PaddlePaddle/Serving#482]
![image](https://user-images.githubusercontent.com/10208305/80228625-db843800-8681-11ea-8eb1-90134ed5d9f7.png)
不能这样检查是否存在GPU的呀。服务部署挂了一片。。
可以检查环境变量中是否有cuda的so文件，但有so文件不一定有gpu设备，还需要检查是否有/dev/nvidia*

![image](https://user-images.githubusercontent.com/10208305/80228503-b4c60180-8681-11ea-8aca-6b4f06689c1a.png)
![image](https://user-images.githubusercontent.com/10208305/80228582-cad3c200-8681-11ea-9166-536f0e3721fe.png)

**Comment by guru4elephant** [comment]
收到，感谢反馈！@wangxicoding

**Comment by wangxicoding** [comment]
fix PR https://github.com/PaddlePaddle/Serving/pull/495
