### ISSUE TITLE
AI Studio使用py3找不到serve模块

### ISSUE THREAD

**Issue by guru4elephant** [PaddlePaddle/Serving#484]
![image](https://user-images.githubusercontent.com/35550832/80270533-8846cf80-86eb-11ea-8cb6-103103715022.png)
AI Studio使用py3找不到serve模块

**Comment by MRXLT** [comment]
经查看，用户安装了paddle_serving_server_gpu版本，所以使用时找不到paddle_serving_server，不过目前aistudio 使用的环境为ubuntu 16，存在环境兼容性的问题
