### ISSUE TITLE
已在Windows下安装Docker，我想将训练完成的模型发布到Serving中

### ISSUE THREAD

**Issue by wyc880622** [PaddlePaddle/Serving#494]
我按网址中的去做
https://github.com/PaddlePaddle/Serving/blob/develop/doc/RUN_IN_DOCKER.md
但在这条命令中让输入用户，我不知道是什么样子的。请问我应该怎么做才可以？
docker run -p 9292:9292 --name test -dit hub.baidubce.com/paddlepaddle/serving:0.2.0
docker exec -it test bash
![image](https://user-images.githubusercontent.com/25219834/80337669-09899800-888d-11ea-87c3-fec876ffce55.png)
是不是不在docker中安装也行？

**Comment by wyc880622** [comment]
![image](https://user-images.githubusercontent.com/25219834/80338830-e8767680-888f-11ea-8915-dc69f2f97cf7.png)

**Comment by barrierye** [comment]
> 我按网址中的去做
> https://github.com/PaddlePaddle/Serving/blob/develop/doc/RUN_IN_DOCKER.md
> 但在这条命令中让输入用户，我不知道是什么样子的。请问我应该怎么做才可以？
> docker run -p 9292:9292 --name test -dit hub.baidubce.com/paddlepaddle/serving:0.2.0
> docker exec -it test bash
> ![image](https://user-images.githubusercontent.com/25219834/80337669-09899800-888d-11ea-87c3-fec876ffce55.png)
> 是不是不在docker中安装也行？

您好，Paddle Serving目前只支持Linux环境，如果想在Windows下运行需要借助Docker。
您这里已经通过`docker exec -it test bash`进入了Docker容器，继续执行后续命令即可~

**Comment by wyc880622** [comment]
您这里已经通过docker exec -it test bash进入了Docker容器，继续执行后续命令即可？
您好，我现在很迷茫，不知道该如何进行命令了。

**Comment by barrierye** [comment]
> 
![image](https://user-images.githubusercontent.com/28446721/80342261-69d10780-8896-11ea-8259-96be6d2fdf2b.png)

您已经通过`docker exec -it test bash`命令进入了Docker容器（可以理解为一个虚拟的Linux环境），终端显示：
```shell
[root@c35105a3c265 /]#
```
接下来需要按照[文档](https://github.com/PaddlePaddle/Serving/blob/develop/doc/RUN_IN_DOCKER_CN.md)，安装PaddleServing（考虑到国内环境，下面命令使用了清华源加速下载）：
```shell
[root@c35105a3c265 /]# pip install paddle-serving-server -i https://pypi.tuna.tsinghua.edu.cn/simple
```
然后可以根据后面的测试example来运行。

获取模型文件：
```shell
[root@c35105a3c265 /]# wget --no-check-certificate https://paddle-serving.bj.bcebos.com/uci_housing.tar.gz
[root@c35105a3c265 /]# tar -xzf uci_housing.tar.gz
```

运行服务端（在后台运行）：
```shell
[root@c35105a3c265 /]# python -m paddle_serving_server.serve --model uci_housing_model --thread 10 --port 9292 --name uci >std.log 2>err.log &
```

测试（下面命令为向服务端发送一条HTTP POST信息）：
```shell
[root@c35105a3c265 /]# curl -H "Content-Type:application/json" -X POST -d '{"x": [0.0137, -0.1136, 0.2553, -0.0692, 0.0582, -0.0727, -0.1583, -0.0584, 0.6283, 0.4919, 0.1856, 0.0795, -0.0332], "fetch":["price"]}' http://127.0.0.1:9292/uci/prediction
```

**Comment by wyc880622** [comment]
![image](https://user-images.githubusercontent.com/25219834/80436915-d863a300-8932-11ea-8feb-cd70e1465642.png)
你好由于基础太薄，还需要像你请教，我现在已经将paddle-serving-server安装完成，运行下面命令就出现了问题，现在不知道应该如何解决。

**Comment by wyc880622** [comment]
![image](https://user-images.githubusercontent.com/25219834/80437804-385b4900-8935-11ea-973f-3b3e90f0123a.png)
你好zh'ge这个应该是出结果，但我现在还没有明白这里面的道理，我应该怎么发布我自己的模型到里面进行http调用。

**Comment by barrierye** [comment]
> ![image](https://user-images.githubusercontent.com/25219834/80437804-385b4900-8935-11ea-973f-3b3e90f0123a.png)
> 你好zh'ge这个应该是出结果，但我现在还没有明白这里面的道理，我应该怎么发布我自己的模型到里面进行http调用。

您好，Docker容器相当于一个虚拟的Linux环境，与Windows的操作不同（注意到您使用了`cd G:\Ha1con\Paddle\serving`Windows的路径）。

安装好paddle-serving-server的Python包后，就具备启动服务端的条件，但启动服务端还需要一个模型文件（注意到您装好Python包后直接启动了服务端）。

下载好我们准备的模型文件后，就可以基于该模型启动服务端，`python -m paddle_serving_server.serve --model uci_housing_model --thread 10 --port 9292 --name uci >std.log 2>err.log &`命令是在`9292`端口启动一个后台进程（注意到您多次使用了该命令，因为9292端口号已经被占用，所以后面几次启动失败）。

启动完毕后就可以执行预测。

对于您自己的模型，在训练完成后保存阶段，使用Paddle Serving的保存模型接口，目前是`paddle_serving_client.io.save_model`，参考[这个脚本](https://github.com/PaddlePaddle/Serving/blob/develop/python/examples/fit_a_line/local_train.py#L52)（需要安装`paddle-serving-server`或`paddle-serving-client`Python包），后续会在Paddle中集成该接口。
