### ISSUE TITLE
docker 内cuda和本机cuda版本不一样如何解决

### ISSUE THREAD

**Issue by dlkht** [PaddlePaddle/Serving#514]
按照paddle server说明拉了一个docker
nvidia-docker pull hub.baidubce.com/paddlepaddle/serving:0.2.0-gp
部署了tansformer模型，但预测发生错误

检查发现docker环境是cuda9.0, 而本机安裝的是10.01，所以部署怀疑是cuda版本问题引起，应该如何解决？谢谢

**Comment by MRXLT** [comment]
可以贴一下报错的截图吗

**Comment by dlkht** [comment]
输入预测命令
curl -H "Content-Type:application/json" -X POST -d '{"words": "你  好" , "fetch":["out_ids", "out_scores"]}' http://127.0.0.1:9292/transformer/prediction


服务端输出错误部分是：
I0430 08:18:01.036864  1150 analysis_predictor.cc:462] ======= optimize end =======
W0430 08:18:01.038638  1150 infer.h:473] Succ load common model[0x1cc9f510], path[transformer_model].
W0430 08:18:01.038657  1150 infer.h:171] Succ load model_data_pathtransformer_model
I0430 08:18:01.058286  1149 analysis_predictor.cc:462] ======= optimize end =======
W0430 08:18:01.060094  1149 infer.h:473] Succ load common model[0x1c72c4d0], path[transformer_model].
W0430 08:18:01.060114  1149 infer.h:171] Succ load model_data_pathtransformer_model
Process Process-4:1:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/site-packages/paddle_serving_server_gpu/web_service.py", line 105, in producers
    request_json["fetch"])
  File "transform_web_server.py", line 25, in preprocess
    feed_res = self.reader.process(feed["words"]) #.encode("utf-8"))
  File "/transformer_base_reader.py", line 526, in process
    place)
  File "/transformer_base_reader.py", line 493, in prepare_feed_dict_list
    ModelHyperParams.bos_idx, ModelHyperParams.n_head, place)
  File "/transformer_base_reader.py", line 224, in prepare_batch_input
    place, [range(trg_word.shape[0] + 1)] * 2)
  File "/transformer_base_reader.py", line 215, in to_lodtensor
    data_tensor.set(data, place)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   paddle::platform::SetDeviceId(int)
3   paddle::memory::allocation::CUDAAllocator::AllocateImpl(unsigned long)
4   paddle::memory::allocation::AlignedAllocator::AllocateImpl(unsigned long)
5   paddle::memory::allocation::AutoGrowthBestFitAllocator::AllocateImpl(unsigned long)
6   paddle::memory::allocation::RetryAllocator::AllocateImpl(unsigned long)
7   paddle::memory::allocation::AllocatorFacade::Alloc(paddle::platform::Place const&, unsigned long)
8   paddle::memory::allocation::AllocatorFacade::AllocShared(paddle::platform::Place const&, unsigned long)
9   paddle::memory::AllocShared(paddle::platform::Place const&, unsigned long)
10  paddle::framework::Tensor::mutable_data(paddle::platform::Place const&, paddle::framework::proto::VarType_Type, unsigned long)

----------------------
Error Message Summary:
----------------------
Error: cudaSetDevice failed in paddle::platform::SetDeviced, error code : 3, Please see detail in https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038: initialization error at (/paddle/paddle/fluid/platform/gpu_info.cc:240)

**Comment by dlkht** [comment]
看了一下网上也有人提出cuda error code : 3问题，与多进程有关？
