### ISSUE TITLE
windows不支持nvidia-docker 安装是这样的吗。

### ISSUE THREAD

**Issue by wyc880622** [PaddlePaddle/Serving#517]
百度大佬您好，我从网上查看windows不支持 nvidia-docker 安装，那paddleserving的部署是不是可以理解, paddleserving 不支持paddleDetection的训练文件部署。
我想运行如下示例  Image Classification
https://github.com/PaddlePaddle/Serving
但需要Note: This demo needs paddle-serving-server-gpu.
所以现在的paddleDetection部署问题进行预测有支持GPU的吗？
或者paddleServing的部署利用cpu如何实现paddleDection训练模型的预测。谢谢

**Comment by guru4elephant** [comment]
@wangjiawei04 能否提供一个简单的小模型，使用cpu即可预测

**Comment by wyc880622** [comment]
> 提供一个简单的小

我提供一个j简单的小模型吗？

**Comment by guru4elephant** [comment]
您提供也可以，我们来给demo @wyc880622

**Comment by wyc880622** [comment]
> 您提供也可以，我们来给demo @wyc880622
1.这里面是我本人自己导出的模型，fasterrcnn和yolo 目前yolo用main测试是成功。
链接：https://pan.baidu.com/s/1Bvz9F65tHX8W9woxKJ1R2w 密码：poxr

2.我有个问题，我在导出模型的时候yolo的yml和百度给官方yolo导出的模型yml有差异
具体差异是 本人导出的没有图片上的内容，百度的有。所以我自己加上了后，c++就可以预测了。不知道这是什么原因造成的。
![image](https://user-images.githubusercontent.com/25219834/80800066-1c78d100-8bdb-11ea-9e99-2d24be3b77e9.png)
3.还有一个问题
目前我在看c++的部署代码，由于本人不会c++想用c#来调用c++部署的类库。百度能否提供c++部署类库，供C#调用。谢谢

**Comment by guru4elephant** [comment]
我们Q2会开放多语言客户端的feature，敬请期待@wyc880622
