### ISSUE TITLE
patchelf导致so文件出错

### ISSUE THREAD

**Issue by wangxicoding** [PaddlePaddle/Serving#524]
https://github.com/PaddlePaddle/Serving/blob/f5fd7c9de42a5ff319a9fd32c53c6c1213e06f3e/python/paddle_serving_client/__init__.py#L128

![image](https://user-images.githubusercontent.com/10208305/80859424-8ce32900-8c93-11ea-9356-5da3d3bc0d98.png)

多个进程同时跑patchelf时会导致so文件出错，进程挂掉

**Comment by wangxicoding** [comment]
在安装的时候执行这个命令来解决？
不过厂内环境用gcc4.8.2编译使用patchelf重定向路径后会把gcc4.8.2的路径信息刷掉，glibc高版本会找不到，还能正常跑倒是有些奇怪。。

**Comment by MRXLT** [comment]
在https://github.com/PaddlePaddle/Serving/pull/532  中修复，将client定位so的方式从使用patchelf改为修改环境
