### ISSUE TITLE
PaddleDetection训练得到的模型权重转换至Serving部署可用的权重类型

### ISSUE THREAD

**Issue by omtbreak** [PaddlePaddle/Serving#529]
PaddleDetection训练得到的模型权重会得到 pdmodel, pdopt, pdparams三个文件
而[提供的例子](https://github.com/PaddlePaddle/Serving/tree/develop/python/examples/faster_rcnn_model) 下，/faster_rcnn_model/pddet_serving_model 的提供的用于serving的模型权重是是 _scale, _offset, _weights等类型的文件，希望获得如何转换的方式

**Comment by guru4elephant** [comment]
@omtbreak 可以试一下https://github.com/PaddlePaddle/Serving/blob/develop/doc/INFERNCE_TO_SERVING.md

**Comment by guru4elephant** [comment]
我们会在PaddleDetection中增加一个导出serving package的功能，请保持关注

**Comment by omtbreak** [comment]
> 我们会在PaddleDetection中增加一个导出serving package的功能，请保持关注

感谢您的回复，请问大体多久会提供这个功能呢？

**Comment by bjjwwang** [comment]
> > 我们会在PaddleDetection中增加一个导出serving package的功能，请保持关注
> > 感谢您的回复，请问大体多久会提供这个功能呢？
 
今天就会提供。我稍后继续跟进回复

**Comment by bjjwwang** [comment]
> > 我们会在PaddleDetection中增加一个导出serving package的功能，请保持关注
> 
> 感谢您的回复，请问大体多久会提供这个功能呢？

https://github.com/PaddlePaddle/PaddleDetection/pull/605 可以参考这个PR，目前在合入过程中。

**Comment by omtbreak** [comment]
> > > 我们会在PaddleDetection中增加一个导出serving package的功能，请保持关注
> > 
> > 
> > 感谢您的回复，请问大体多久会提供这个功能呢？
> 
> [PaddlePaddle/PaddleDetection#605](https://github.com/PaddlePaddle/PaddleDetection/pull/605) 可以参考这个PR，目前在合入过程中。

非常感谢您的工作！

**Comment by omtbreak** [comment]
> > > 我们会在PaddleDetection中增加一个导出serving package的功能，请保持关注
> > 
> > 
> > 感谢您的回复，请问大体多久会提供这个功能呢？
> 
> [PaddlePaddle/PaddleDetection#605](https://github.com/PaddlePaddle/PaddleDetection/pull/605) 可以参考这个PR，目前在合入过程中。



> > > 我们会在PaddleDetection中增加一个导出serving package的功能，请保持关注
> > 
> > 
> > 感谢您的回复，请问大体多久会提供这个功能呢？
> 
> [PaddlePaddle/PaddleDetection#605](https://github.com/PaddlePaddle/PaddleDetection/pull/605) 可以参考这个PR，目前在合入过程中。

您好，在使用过程中发现存在一个错误。
export_serving_model中引用的export_model的parse_reader方法中
```
for st in sample_transforms[1:]:
        method = st.__class__.__name__
        p = {'type': method.replace('Image', '')}
        params = st.__dict__
        params.pop('_id')
        if p['type'] == 'Resize' and has_shape_def:
            params['target_size'] = min(image_shape[
                1:]) if arch in scale_set else image_shape[1]
            params['max_size'] = max(image_shape[
                1:]) if arch in scale_set else 0
            params['image_shape'] = image_shape[1:]
        p.update(params)
        preprocess_list.append(p)
```
sample_transform获取到的是一个dict对象，和提供的代码有冲突，因此无法生成infer_cfg.yml，除此之外，都正常运行
