### ISSUE TITLE
部署transformer的情况变化

### ISSUE THREAD

**Issue by dlkht** [PaddlePaddle/Serving#536]
服务端升级serer到0.2.1，server收到的数据格式处理没问题了（将np.array转成list),但执行batch_predict（）时，client端收到{"result":"Request Value Error"}
server端提示：
2020-05-08 11:12:25,176-INFO: 172.17.0.1 - - [08/May/2020 11:12:25] "POST /transformer/prediction HTTP/1.1" 200 -
是什么原因？

**Comment by guru4elephant** [comment]
能否贴一些可复现的源码和模型包

**Comment by dlkht** [comment]
怎么上传文件和包呢

**Comment by MRXLT** [comment]
如果方便的话可以提供一下网盘链接，或者发送到我的邮箱xlt2024@gmail.com

**Comment by dlkht** [comment]
@MRXLT 你好！测试代码及model上传到网盘，已将网盘连接及提取码发到你的邮箱，下载压缩包后，请参阅read.me说明

**Comment by dlkht** [comment]
解压包后，麻烦将transformer_base_reader.py 第34和40行的tsfm_server改成tsfm_server_2

**Comment by MRXLT** [comment]
你好，在预处理的部分返回结果中包含了numpy arry的类型和lodtensor的类型，
![image](https://user-images.githubusercontent.com/16594411/81540267-f7871980-93a3-11ea-9198-7220bddcf63c.png)
serving暂时不支持这种输入方式，请将数据都转为numpy array类型或者都转为list类型

**Comment by dlkht** [comment]
好的，谢谢

**Comment by dlkht** [comment]
> 你好，在预处理的部分返回结果中包含了numpy arry的类型和lodtensor的类型，
> ![image](https://user-images.githubusercontent.com/16594411/81540267-f7871980-93a3-11ea-9198-7220bddcf63c.png)
> serving暂时不支持这种输入方式，请将数据都转为numpy array类型或者都转为list类型

你好！把输入全部用np.array表示后，仍有错误，提示如下。
I0512 14:44:14.721690 27671 naming_service_thread.cpp:209] brpc::policy::ListNamingService("127.0.0.1:12000,127.0.0.1:12001,127.0.0.1:12002,"): added 3
W0512 14:44:29.995329 27671 predictor.hpp:129] inference call failed, message: [E111]1/1 channels failed, fail_limit=1 [C0][E111]Fail to connect SocketId=3@127.0.0.1:12001: Connection refused [R1][E111]Fail to connect SocketId=113@127.0.0.1:12000: Connection refused [R2][E111]Fail to connect SocketId=8589934596@127.0.0.1:12002: Connection refused
E0512 14:44:29.995601 27671 general_model.cpp:525] failed call predictor with req: insts { tensor_array { float_data: 7 float_data: 24 float_data: 1 elem_type: 0 shape: 1 shape: 3 shape: 1 } tensor_array { float_data: 0 float_data: 1 float_data: 2 elem_type: 0 shape: 1 shape: 3 shape: 1 } tensor_array { float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 elem_type: 1 shape: 1 shape: 8 shape: 3 shape: 3 } tensor_array { float_data: 0 elem_type: 0 shape: 1 shape: 1 shape: 1 } tensor_array { float_data: 0 elem_type: 1 shape: 1 shape: 1 } tensor_array { float_data: 0 elem_type: 0 shape: 1 } tensor_array { float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 float_data: 0 elem_type: 1 shape: 1 shape: 8 shape: 1 shape: 3 } } fetch_var_names: "out_ids" fetch_var_names: "out_scores"
I0512 14:44:30.095656 27686 socket.cpp:2370] Checking SocketId=1@127.0.0.1:12001
I0512 14:44:30.095710 27684 socket.cpp:2370] Checking SocketId=0@127.0.0.1:12000
I0512 14:44:30.095712 27688 socket.cpp:2370] Checking SocketId=2@127.0.0.1:12002

**Comment by dlkht** [comment]
@MRXLT 你好！我发了个新邮件给你，麻烦帮找下原因，谢谢！

**Comment by MRXLT** [comment]
> @MRXLT 你好！我发了个新邮件给你，麻烦帮找下原因，谢谢！

收到了，我看一下

**Comment by MRXLT** [comment]
![image](https://user-images.githubusercontent.com/16594411/82012575-f3604200-96aa-11ea-8f19-1e27f2104a6a.png)
![image](https://user-images.githubusercontent.com/16594411/82012590-fe1ad700-96aa-11ea-8fb5-14c1daa79ab2.png)
图中这几个feed var的shape与保存的模型文件中的shape不一致，以trg_src_attn_bias为例，reader产出的shape应该是(1,8,150,150)
对于非lod tensor需要保证输入的shape与保存模型的输入shape一致，可以通过padding实现

**Comment by dlkht** [comment]
好的，谢谢！
