### ISSUE TITLE
paddle_serving_app无法使用Detection

### ISSUE THREAD

**Issue by omtbreak** [PaddlePaddle/Serving#544]
根据提供的[Faster RCNN示例](https://github.com/PaddlePaddle/Serving/tree/develop/python/examples/faster_rcnn_model)，在test_client.py中，
```
from paddle_serving_client import Client
import sys
import os
import time
from paddle_serving_app.reader.pddet import Detection
import numpy as np

py_version = sys.version_info[0]

feed_var_names = ['image', 'im_shape', 'im_info']
fetch_var_names = ['multiclass_nms']
pddet = Detection(config_path=sys.argv[2], output_dir="./output")
feed_dict = pddet.preprocess(feed_var_names, sys.argv[3])
client = Client()
client.load_client_config(sys.argv[1])
client.connect(['127.0.0.1:9494'])
fetch_map = client.predict(feed=feed_dict, fetch=fetch_var_names)
outs = fetch_map.values()
pddet.postprocess(fetch_map, fetch_var_names)
```
在pycharm或者linux命令行下，都对
```
from paddle_serving_app.reader.pddet import Detection
```
报错，找不到serving_app_reader.pddet模块

**Comment by guru4elephant** [comment]
请使用
https://github.com/PaddlePaddle/Serving/blob/develop/python/examples/faster_rcnn_model/new_test_client.py

**Comment by omtbreak** [comment]
> 请使用
> https://github.com/PaddlePaddle/Serving/blob/develop/python/examples/faster_rcnn_model/new_test_client.py

通过pip和pycharm安装的paddle-serving-app库依然找不到Sequential, File2Image, BGR2RGB等函数

**Comment by MRXLT** [comment]
请先使用链接中develop版本的安装包，0.0.3会在之后这正式发布
https://paddle-serving.bj.bcebos.com/whl/paddle_serving_app-0.0.3-py2-none-any.whl

**Comment by omtbreak** [comment]
> 请先使用链接中develop版本的安装包，0.0.3会在之后这正式发布
> https://paddle-serving.bj.bcebos.com/whl/paddle_serving_app-0.0.3-py2-none-any.whl

好的，请问可以提供python3的安装包嘛

**Comment by MRXLT** [comment]
> > 请先使用链接中develop版本的安装包，0.0.3会在之后这正式发布
> > https://paddle-serving.bj.bcebos.com/whl/paddle_serving_app-0.0.3-py2-none-any.whl
> 
> 好的，请问可以提供python3的安装包嘛

https://paddle-serving.bj.bcebos.com/whl/paddle_serving_app-0.0.3-py3-none-any.whl

**Comment by omtbreak** [comment]
> 请使用
> https://github.com/PaddlePaddle/Serving/blob/develop/python/examples/faster_rcnn_model/new_test_client.py

请问，新的new_test_client的运行命令和[示例](https://github.com/PaddlePaddle/Serving/tree/develop/python/examples/faster_rcnn_model)的readme中的运行命令应该不同了吧，new_test_client.py中的sys的各个参数应该是什么呢？

**Comment by omtbreak** [comment]
> 请使用
> https://github.com/PaddlePaddle/Serving/blob/develop/python/examples/faster_rcnn_model/new_test_client.py
请问，新的new_test_client的运行命令和示例的readme中的运行命令应该不同了吧，new_test_client.py中的sys的各个参数应该是什么呢？
