### ISSUE TITLE
预测库选项整理

### ISSUE THREAD

**Issue by guru4elephant** [PaddlePaddle/Serving#548]
预测库在默认apply pass的时候，可能会存在某些模型上无法work，为了保证用户能够优先使用正确的模型，C++一侧的预测库选项会默认关闭掉所有pass，用户在起服务的时候可以选择开启pass。

**Comment by MRXLT** [comment]
添加ir_optim参数控制是否开启pass优化
https://github.com/PaddlePaddle/Serving/pull/554
