### ISSUE TITLE
客户端调用 from .serving_client import PredictorClient 报错

### ISSUE THREAD

**Issue by omtbreak** [PaddlePaddle/Serving#553]
本机系统MaxOS，使用的 paddle_serving_client-0.2.2-py3-none-any.whl
```
from paddle_serving_client import Client
from paddle_serving_app.reader import *
import sys
import numpy as np

preprocess = Sequential([
    File2Image(), BGR2RGB(), Div(255.0),
    Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225], False),
    Resize(640, 640), Transpose((2, 0, 1))
])

postprocess = RCNNPostprocess("/Users/omtbreak/Desktop/untitled1/label_list.txt", "output")

client = Client()
client.load_client_config("/Users/omtbreak/Desktop/serving_client_conf.prototxt")
client.connect(['122.5.106.226:7788'])

im = preprocess('/Users/omtbreak/Desktop/000000570688.jpg')
fetch_map = client.predict(feed={"image": im, "im_info": np.array(list(im.shape[1:]) + [1.0]),
                                 "im_shape": np.array(list(im.shape[1:]) + [1.0])}, fetch=["multiclass_nms"])
fetch_map["image"] = '/Users/omtbreak/Desktop/000000570688.jpg'
postprocess(fetch_map)
print(fetch_map)
```
模型开启在Ubuntu18，客户端调用代码报错
```
File "/Users/omtbreak/Desktop/untitled1/test_client.py", line 15, in <module>
    client.load_client_config("/Users/omtbreak/Desktop/serving_client_conf.prototxt")
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/paddle_serving_client/__init__.py", line 129, in load_client_config
    from .serving_client import PredictorClient
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/paddle_serving_client/serving_client.so, 2): no suitable image found.  Did find:
	/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/paddle_serving_client/serving_client.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03
	/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/paddle_serving_client/serving_client.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03

```

**Comment by bjjwwang** [comment]
> 
> ```
> File "/Users/omtbreak/Desktop/untitled1/test_client.py", line 15, in <module>
>     client.load_client_config("/Users/omtbreak/Desktop/serving_client_conf.prototxt")
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/paddle_serving_client/__init__.py", line 129, in load_client_config
>     from .serving_client import PredictorClient
> ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/paddle_serving_client/serving_client.so, 2): no suitable image found.  Did find:
> 	/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/paddle_serving_client/serving_client.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03
> 	/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/paddle_serving_client/serving_client.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03
> ```
ubuntu 18的python 3.7是如何安装的。

**Comment by omtbreak** [comment]
> > ```
> > File "/Users/omtbreak/Desktop/untitled1/test_client.py", line 15, in <module>
> >     client.load_client_config("/Users/omtbreak/Desktop/serving_client_conf.prototxt")
> >   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/paddle_serving_client/__init__.py", line 129, in load_client_config
> >     from .serving_client import PredictorClient
> > ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/paddle_serving_client/serving_client.so, 2): no suitable image found.  Did find:
> > 	/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/paddle_serving_client/serving_client.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03
> > 	/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/paddle_serving_client/serving_client.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03
> > ```
> 
> 
> ubuntu 18的python 3.7是如何安装的。

使用如下命令安装的
```
pip3 --default-timeout=400  install paddle-serving-client -i https://pypi.tuna.tsinghua.edu.cn/simple --ignore-installed
   pip3 --default-timeout=400  install paddle-serving-server -i https://pypi.tuna.tsinghua.edu.cn/simple --ignore-installed # CPU
   pip3 --default-timeout=400  install paddle-serving-server-gpu -i https://pypi.tuna.tsinghua.edu.cn/simple --ignore-installed # GPU
   pip3 --default-timeout=400  install paddle-serving-app -i https://pypi.tuna.tsinghua.edu.cn/simple --ignore-installed
```
ubuntu的服务器处没有使用docker，但是正常开启了。
ImportError报错的是客户端处的load_client_config,和服务器处没关系，查找报错发现是paddle-serving-client源码中，调用了.serving_client中的PredictorClient
```
    def load_client_config(self, path):
        from .serving_client import PredictorClient
        from .serving_client import PredictorRes
        model_conf = m_config.GeneralModelConfig()
        f = open(path, 'r')
        model_conf = google.protobuf.text_format.Merge(
            str(f.read()), model_conf)
```
客户端处使用pip安装的paddle-serving-client没有serving_client.py
![截屏2020-05-1423 30 20](https://user-images.githubusercontent.com/12478872/81954593-9e391780-963b-11ea-8750-bc92152d3c83.png)

**Comment by bjjwwang** [comment]
好的 感谢 我今天复现一下。

**Comment by chengxurensheng666** [comment]
我也遇到了这个问题，请问解决了吗
