### ISSUE TITLE
criteo_ctr_with_cube目录中Readme的第一步编译源码的目的是什么？

### ISSUE THREAD

**Issue by jiangchao123** [PaddlePaddle/Serving#557]
https://github.com/PaddlePaddle/Serving/tree/develop/python/examples/criteo_ctr_with_cube
请问criteo_ctr_with_cube目录中Readme的第一步编译源码的目的是什么？文档里没有写的很明白，是必须要自己先编译源码，才能体验cube? 这个操作感觉很反锁
1.是不是要先安装cmake？
2.是不是必须要用python2.7来编译？

**Comment by bjjwwang** [comment]
> https://github.com/PaddlePaddle/Serving/tree/develop/python/examples/criteo_ctr_with_cube
> 请问criteo_ctr_with_cube目录中Readme的第一步编译源码的目的是什么？文档里没有写的很明白，是必须要自己先编译源码，才能体验cube? 这个操作感觉很反锁

现在不需要了，之前QA有提过一次，后来预先编译好了wget下来就可以了，文档中关于编译的部分会很快删除

> 1.是不是要先安装cmake？

现在已不需要

> 2.是不是必须要用python2.7来编译？

支持2.7 3.6 3.7，会在首页更新 编译说明文档

文档更新预计今晚完成。
感谢

**Comment by jiangchao123** [comment]
好的，谢谢~

**Comment by bjjwwang** [comment]
已修复
