### ISSUE TITLE
paddle serving编译文档支持python3

### ISSUE THREAD

**Issue by bjjwwang** [PaddlePaddle/Serving#559]
https://github.com/PaddlePaddle/Serving/blob/develop/doc/COMPILE.md
https://github.com/PaddlePaddle/Serving/blob/develop/doc/COMPILE_CN.md

**Comment by bjjwwang** [comment]
其实就是添加 
```
    cmake -DPYTHON_INCLUDE_DIR=$PYTHONROOT/include/python3.6m/ \
          -DPYTHON_LIBRARIES=$PYTHONROOT/lib64/libpython3.6.so \
          -DPYTHON_EXECUTABLE=$PYTHONROOT/bin/python3 \
          -DSERVER=ON \
          -DWITH_GPU=ON ..
```
这样的命令就可以了

**Comment by barrierye** [comment]
Python3 在文档中有提到：
> This document will take Python2 as an example to show how to compile Paddle Serving. If you want to compile with Python 3, just adjust the Python options of cmake.
本文档将以Python2为例介绍如何编译Paddle Serving。如果您想用Python3进行编译，只需要调整cmake的Python相关选项即可。
