### ISSUE TITLE
paddle-serving-client源码问题

### ISSUE THREAD

**Issue by omtbreak** [PaddlePaddle/Serving#562]
paddle-serving-client源码中，调用了.serving_client中的PredictorClient
```
    def load_client_config(self, path):
        from .serving_client import PredictorClient
        from .serving_client import PredictorRes
        model_conf = m_config.GeneralModelConfig()
        f = open(path, 'r')
        model_conf = google.protobuf.text_format.Merge(
            str(f.read()), model_conf)
```
但在使用客户端代码报ImportError
```
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/paddle_serving_client/serving_client.so, 2): no suitable image found.  Did find:
```
查找发现，通过pip3安装的paddle-serving-client中，没有serving_client.py文件，只有serving_client.so
![截屏2020-05-1423 30 20](https://user-images.githubusercontent.com/12478872/81954593-9e391780-963b-11ea-8750-bc92152d3c83.png)

**Comment by barrierye** [comment]
您好，`serving_client.so`是由pybind生成的，可以在Python端直接调用。
该文件是在Linux下编译的，与macOS的文件格式不同，建议[在Docker中运行](https://github.com/PaddlePaddle/Serving/blob/develop/doc/RUN_IN_DOCKER_CN.md)

**Comment by bjjwwang** [comment]
是想要在mac os上运行吗

**Comment by omtbreak** [comment]
> 您好，`serving_client.so`是由pybind生成的，可以在Python端直接调用。
> 该文件是在Linux下编译的，与macOS的文件格式不同，建议[在Docker中运行](https://github.com/PaddlePaddle/Serving/blob/develop/doc/RUN_IN_DOCKER_CN.md)

您好，那如果macos或者windows就只能在docker中运行嘛

**Comment by omtbreak** [comment]
> 是想要在mac os上运行吗

我现在是想在macos上测试，但业务部署的客户端是运行在windows

**Comment by barrierye** [comment]
> 那如果macos或者windows就只能在docker中运行嘛

是的，目前只支持Linux。您可以考虑在Windows或macOS上用HTTP模式获取服务

**Comment by omtbreak** [comment]
> > 那如果macos或者windows就只能在docker中运行嘛
> 
> 是的，目前只支持Linux。您可以考虑在Windows或macOS上用HTTP模式获取服务

明白了，那可以提供一个通过HTTP方式调用目标检测服务的例子嘛

**Comment by barrierye** [comment]
> 明白了，那可以提供一个通过HTTP方式调用目标检测服务的例子嘛

可以参考这个例子：[Faster RCNN model on Paddle Serving](https://github.com/PaddlePaddle/Serving/tree/develop/python/examples/faster_rcnn_model)

**Comment by omtbreak** [comment]
> > 明白了，那可以提供一个通过HTTP方式调用目标检测服务的例子嘛
> 
> 可以参考这个例子：[Faster RCNN model on Paddle Serving](https://github.com/PaddlePaddle/Serving/tree/develop/python/examples/faster_rcnn_model)
这个例子我看只有rpc调用的方式呀，http的方式没有

**Comment by barrierye** [comment]
> > > 明白了，那可以提供一个通过HTTP方式调用目标检测服务的例子嘛
> > 
> > 
> > 可以参考这个例子：[Faster RCNN model on Paddle Serving](https://github.com/PaddlePaddle/Serving/tree/develop/python/examples/faster_rcnn_model)
> > 这个例子我看只有rpc调用的方式呀，http的方式没有

暂时没有目标检测服务的HTTP例子，可以参考下图像分类的例子：[Image Classification
](https://github.com/PaddlePaddle/Serving/tree/develop/python/examples/imagenet)

**Comment by omtbreak** [comment]
> > > > 明白了，那可以提供一个通过HTTP方式调用目标检测服务的例子嘛
> > > 
> > > 
> > > 可以参考这个例子：[Faster RCNN model on Paddle Serving](https://github.com/PaddlePaddle/Serving/tree/develop/python/examples/faster_rcnn_model)
> > > 这个例子我看只有rpc调用的方式呀，http的方式没有
> 
> 暂时没有目标检测服务的HTTP例子，可以参考下图像分类的例子：[Image Classification](https://github.com/PaddlePaddle/Serving/tree/develop/python/examples/imagenet)

不好意思，这个图像分类的例子的服务器端代码在ubuntu18上也跑不起来
```
Traceback (most recent call last):
  File "test_server.py", line 6, in <module>
    from paddle_serving_app import ImageReader
ImportError: cannot import name 'ImageReader'
```
容器外安装了paddle_serving_app，版本0.0.2
还是希望可以提供一个HTTP的目标检测的例子

**Comment by omtbreak** [comment]
> > > > 明白了，那可以提供一个通过HTTP方式调用目标检测服务的例子嘛
> > > 
> > > 
> > > 可以参考这个例子：[Faster RCNN model on Paddle Serving](https://github.com/PaddlePaddle/Serving/tree/develop/python/examples/faster_rcnn_model)
> > > 这个例子我看只有rpc调用的方式呀，http的方式没有
> 
> 暂时没有目标检测服务的HTTP例子，可以参考下图像分类的例子：[Image Classification](https://github.com/PaddlePaddle/Serving/tree/develop/python/examples/imagenet)

您好，可以提供一个RPC或者HTTP的目标检测的例子吗，[Faster RCNN on Paddle Serving](https://github.com/PaddlePaddle/Serving/tree/develop/python/examples/faster_rcnn_model)中的例子无法运行
