### ISSUE TITLE
Cant pull serving:0.2.0-gpu

### ISSUE THREAD

**Issue by linux-devil** [PaddlePaddle/Serving#565]
nvidia-docker pull hub.baidubce.com/paddlepaddle/serving:0.2.0-gpu fails to pull all the layer

Tried multiple times , but there is some timeout.

**Comment by guru4elephant** [comment]
服务器上不能访问百度云CCE的dockerhub hub.baidubce.com, 可能是因为没有路由。
加这句试试：
ip r add 100.64.0.0/10 via 10.255.100.1 dev eth0

**Comment by linux-devil** [comment]
sudo ip r add 100.64.0.0/10 via 10.255.100.1 dev wlp112s0 
Error: Nexthop has invalid gateway.

**Comment by barrierye** [comment]
可以访问dockerhub吗？试试这个：docker pull barriery/serving:0.2.0-gpu
不行的话可以考虑在能访问外网的机器上下载镜像，传到内网机器

**Comment by linux-devil** [comment]
Thanks @barrierye  this works
