### ISSUE TITLE
用你们提供的docker源码进行编译gpu版的serving

### ISSUE THREAD

**Issue by miaochunyuan** [PaddlePaddle/Serving#572]
提供的docker是cuda9，从docker编译出来的版本就只能适用于cuda9吗？我想编译出适用于cuda10的版本该如何编译

**Comment by barrierye** [comment]
提供的GPU编译镜像只能编译CUDA9版本的，可以尝试将[Dockerfile](https://github.com/PaddlePaddle/Serving/blob/develop/tools/Dockerfile.gpu.devel)的第一行改为：
```shell
FROM nvidia/cuda:10.1-cudnn7-devel-centos7
```
构建编译镜像（主机的cuda版本要比镜像高）

**Comment by guru4elephant** [comment]
后续会考虑提供cuda10镜像

**Comment by miaochunyuan** [comment]
您好，在自己构建了cuda10版本的镜像后，编译安装后运行会出现cuda not `found的报错：`

```
 GLOG_v=2 python -m paddle_serving_server_gpu.serve --model servingExport/yolov3_darknet_voc/serving_client --port 9293 --gpu_id 5 
mkdir: cannot create directory 'workdir_5': File exists
CUDA not found, please check your environment or use cpu version by "pip install paddle_serving_server"
```

只修改了dockerfile里的第一行：FROM nvidia/cuda:10.0-cudnn7-devel-centos7构建的镜像

**Comment by miaochunyuan** [comment]
您好，在自己构建了cuda10版本的镜像后，编译安装后运行会出现cuda not found的报错：

```
GLOG_v=2 python -m paddle_serving_server_gpu.serve --model servingExport/yolov3_darknet_voc/serving_client --port 9293 --gpu_id 5 
mkdir: cannot create directory 'workdir_5': File exists
CUDA not found, please check your environment or use cpu version by "pip install paddle_serving_server"
```

只修改了dockerfile里的第一行：FROM nvidia/cuda:10.0-cudnn7-devel-centos7构建的镜像

**Comment by barrierye** [comment]
容器是否是用nvidia-docker启动的？

**Comment by miaochunyuan** [comment]
> 容器是否是用nvidia-docker启动的？

是的，容器内可以找到cuda，使用gpu

**Comment by miaochunyuan** [comment]
> 容器是否是用nvidia-docker启动的？

是的，容器内可以找到cuda，使用gpu

**Comment by MRXLT** [comment]
有使用SERVING_BIN指定编译出的serving二进制路径吗

**Comment by miaochunyuan** [comment]
> 有使用SERVING_BIN指定编译出的serving二进制路径吗

使用了

**Comment by MRXLT** [comment]
使用ldd命令查看一下编译出的serving二进制的动态库链接情况

**Comment by miaochunyuan** [comment]
> 使用ldd命令查看一下编译出的serving二进制的动态库链接情况

`linux-vdso.so.1 =>  (0x00007ffc5070f000)
        libpthread.so.0 => /usr/lib64/libpthread.so.0 (0x00007f4e3587c000)
        libcudart.so.10.0 => /usr/local/cuda/lib64/libcudart.so.10.0 (0x00007f4e35602000)
        libiomp5.so => /paddle/Serving/build/third_party/install/Paddle/third_party/install/mklml/lib/libiomp5.so (0x00007f4e35226000)
        libmklml_intel.so => /paddle/Serving/build/third_party/install/Paddle/third_party/install/mklml/lib/libmklml_intel.so (0x00007f4e2d2aa000)
        libdnnl.so.1 => /paddle/Serving/build/third_party/install/Paddle/third_party/install/mkldnn/lib/libdnnl.so.1 (0x00007f4e2bdd1000)
        libcrypto.so.10 => /usr/lib64/libcrypto.so.10 (0x00007f4e2b96e000)
        librt.so.1 => /usr/lib64/librt.so.1 (0x00007f4e2b766000)
        libssl.so.10 => /usr/lib64/libssl.so.10 (0x00007f4e2b4f4000)
        libdl.so.2 => /usr/lib64/libdl.so.2 (0x00007f4e2b2f0000)
        libz.so.1 => /usr/lib64/libz.so.1 (0x00007f4e2b0da000)
        libbz2.so.1 => /usr/lib64/libbz2.so.1 (0x00007f4e2aeca000)
        libm.so.6 => /usr/lib64/libm.so.6 (0x00007f4e2abc8000)
        libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007f4e2a8c1000)
        libgcc_s.so.1 => /usr/lib64/libgcc_s.so.1 (0x00007f4e2a6ab000)
        libc.so.6 => /usr/lib64/libc.so.6 (0x00007f4e2a2dd000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f4e35a98000)
        libgssapi_krb5.so.2 => /usr/lib64/libgssapi_krb5.so.2 (0x00007f4e2a090000)
        libkrb5.so.3 => /usr/lib64/libkrb5.so.3 (0x00007f4e29da7000)
        libcom_err.so.2 => /usr/lib64/libcom_err.so.2 (0x00007f4e29ba3000)
        libk5crypto.so.3 => /usr/lib64/libk5crypto.so.3 (0x00007f4e29970000)
        libkrb5support.so.0 => /usr/lib64/libkrb5support.so.0 (0x00007f4e29760000)
        libkeyutils.so.1 => /usr/lib64/libkeyutils.so.1 (0x00007f4e2955c000)
        libresolv.so.2 => /usr/lib64/libresolv.so.2 (0x00007f4e29342000)
        libselinux.so.1 => /usr/lib64/libselinux.so.1 (0x00007f4e2911b000)
        libpcre.so.1 => /usr/lib64/libpcre.so.1 (0x00007f4e28eb9000)
`
这应该是正常的吧

**Comment by barrierye** [comment]
与 #606 重复
