### ISSUE TITLE
自己训练导出的模型，HTTP Service部署后预测失败

### ISSUE THREAD

**Issue by mcl-stone** [PaddlePaddle/Serving#600]
![image](https://user-images.githubusercontent.com/62418900/82722968-a230fd80-9cfd-11ea-8931-60186bd1ab85.png)
使用上图示例是可以成功的，自己训练完模型后，按照Paddle Serving部署模型导出也是成功的，使用导出的模型按照示例HTTP Service部署成功后，预测时失败。
![image](https://user-images.githubusercontent.com/62418900/82723000-f89e3c00-9cfd-11ea-845b-e13870738e8c.png)
上图左边是自己导出后的serving_server_conf.prototxt，右边是示例中的文件。使用curl -H "Content-Type:application/json" -X POST -d '{"feed":[{"image": "https://paddle-serving.bj.bcebos.com/imagenet-example/daisy.jpg"}], "fetch": ["score"]}' http://127.0.0.1:9696/image/prediction命令预测图片，需要改动哪里？fetch:[]参数里面改了下也不行，还有起服务的脚本需要如何修改。求帮助，谢谢。

**Comment by mcl-stone** [comment]
加了imsize：但还是不行

**Comment by mcl-stone** [comment]
我是使用yolov4训练出的模型，想用HTTP Service部署，使用curlpost包进行预测的方式，希望给个例子。谢了！

**Comment by guru4elephant** [comment]
收到case，我们会尽快提供检测任务的可视化demo

**Comment by mcl-stone** [comment]
> 收到case，我们会尽快提供检测任务的可视化demo

感谢！好了给个连接吧，最近比较急，要使用。

**Comment by bjjwwang** [comment]
> > 收到case，我们会尽快提供检测任务的可视化demo
> 
> 感谢！好了给个连接吧，最近比较急，要使用。

方便给个模型让我测试一下吗，以及还有报的是什么样的错误。

**Comment by mcl-stone** [comment]
> > > 收到case，我们会尽快提供检测任务的可视化demo
> > 
> > 
> > 感谢！好了给个连接吧，最近比较急，要使用。
> 
> 方便给个模型让我测试一下吗，以及还有报的是什么样的错误。

可以的，模型的部署没有报错，就是使用时不知道怎么使用，我模型怎么给你？

**Comment by mcl-stone** [comment]
> > > 收到case，我们会尽快提供检测任务的可视化demo
> > 
> > 
> > 感谢！好了给个连接吧，最近比较急，要使用。
> 
> 方便给个模型让我测试一下吗，以及还有报的是什么样的错误。

这我qq，986548155，可以的话，加qq我给您吧？

**Comment by mcl-stone** [comment]
或者您在飞桨交流3群里吗，我从那跟您说

**Comment by mcl-stone** [comment]
> > > 收到case，我们会尽快提供检测任务的可视化demo
> > 
> > 
> > 感谢！好了给个连接吧，最近比较急，要使用。
> 
> 方便给个模型让我测试一下吗，以及还有报的是什么样的错误。

![image](https://user-images.githubusercontent.com/62418900/82866064-c2112d00-9f5a-11ea-9a82-21612e876764.png)
我使用时，应该时这个参数不知道填什么，我自己yolov4训练的模型和你们提供的yolov3_r50vd_dcn_obj365_pretrained模型，使用tools/export_serving_model.py导出方式后，导出的文件需要都是下图这样，im_size参数填写不知如何写，写上后也报错，导出后模型的部署是没有问题的。帮忙看看吧，谢谢了！
![image](https://user-images.githubusercontent.com/62418900/82866472-904c9600-9f5b-11ea-9915-6710fc467c50.png)

**Comment by bjjwwang** [comment]
> > > > 收到case，我们会尽快提供检测任务的可视化demo
> > > 
> > > 
> > > 感谢！好了给个连接吧，最近比较急，要使用。
> > 
> > 
> > 方便给个模型让我测试一下吗，以及还有报的是什么样的错误。
> 
> 这我qq，986548155，可以的话，加qq我给您吧？

好的

**Comment by JiaoZiLang** [comment]
用yolov3自己训练的模型同样碰到这个问题，麻烦能给个yolov3的demo不？

**Comment by ghfblt** [comment]
我也是使用yolov3训练出的模型，想用HTTP Service部署，使用curlpost包进行预测的方式，希望给个例子

**Comment by Huihuihh** [comment]
> 模型的部署没有报错，就是使用时不知道怎么使用，我模型怎么给

请问有例子了吗

**Comment by Huihuihh** [comment]
> 我也是使用yolov3训练出的模型，想用HTTP Service部署，使用curlpost包进行预测的方式，希望给个例子

请问有对应的例子提供了吗，我也需要使用curl post的方式预测

**Comment by 2018-Summer** [comment]
`加载自己的训练模型，报错，有没有大神给指导一下`
`Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle_serving_server/pipeline/error_catch.py", line 97, in wrapper
    res = func(*args, **kw)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle_serving_server/pipeline/error_catch.py", line 160, in wrapper
    raise CustomException(CustomExceptionCode.INPUT_PARAMS_ERROR, "invalid arg list: {}".format(invalid_argument_list), True)
paddle_serving_server.pipeline.error_catch.CustomException: 
	exception_code: 5000
	exception_type: INPUT_PARAMS_ERROR
	error_msg: invalid arg list: ['feed_batch']
	is_send_to_user: True
Classname: Op.process.<locals>.feed_fetch_list_check_helper
FunctionName: feed_fetch_list_check_helper
Args: ([{'x': array([[[[-1.0904187 , -1.0904187 , -1.0904187 , ..., -0.439678  ,
          -0.439678  , -0.439678  ],
         [-1.0732939 , -1.0732939 , -1.0732939 , ..., -0.439678  ,
          -0.439678  , -0.439678  ],
         [-1.0390444 , -1.0390444 , -1.0390444 , ..., -0.439678  ,
          -0.439678  , -0.42255327],
         ...,
         [-0.35405427, -0.35405427, -0.35405427, ..., -0.19993149,
          -0.11430772, -0.11430772],
         [-0.11430772, -0.11430772, -0.11430772, ..., -0.21705623,
          -0.13143247, -0.13143247],
         [-0.11430772, -0.09718297, -0.09718297, ..., -0.21705623,
          -0.14855723, -0.13143247]],

        [[-1.0903361 , -1.0903361 , -1.0903361 , ..., -0.12745096,
          -0.12745096, -0.12745096],
         [-1.0728291 , -1.0728291 , -1.0728291 , ..., -0.16246496,
          -0.16246496, -0.16246496],
         [-1.0378151 , -1.0378151 , -1.0378151 , ..., -0.19747896,
          -0.21498597, -0.21498597],
         ...,
         [-0.460084  , -0.442577  , -0.442577  , ..., -0.81022406,
          -0.652661  , -0.60014004],
         [-0.21498597, -0.21498597, -0.21498597, ..., -0.827731  ,
          -0.687675  , -0.60014004],
         [-0.24999997, -0.23249297, -0.23249297, ..., -0.827731  ,
          -0.705182  , -0.617647  ]],

        [[-0.8458388 , -0.8458388 , -0.8458388 , ...,  0.26962963,
           0.26962963,  0.26962963],
         [-0.8284096 , -0.8284096 , -0.8284096 , ...,  0.23477125,
           0.23477125,  0.23477125],
         [-0.7935512 , -0.7935512 , -0.7935512 , ...,  0.19991288,
           0.19991288,  0.19991288],
         ...,
         [-0.27067533, -0.27067533, -0.27067533, ..., -0.7064052 ,
          -0.61925924, -0.61925924],
         [-0.02666664, -0.02666664, -0.02666664, ..., -0.72383446,
          -0.61925924, -0.61925924],
         [-0.06152503, -0.04409584, -0.04409584, ..., -0.72383446,
          -0.6366884 , -0.61925924]]]], dtype=float32)}], ['multiclass_nms3_0.tmp_0', 'multiclass_nms3_0.tmp_2'])
ERROR 2023-06-28 10:07:53,042 [operator.py:1079] [det] failed to predict. Log_id: 0  Raise_msg:  invalid arg list  ClassName: Op.process.<locals>.feed_fetch_list_check_helper  FunctionName: feed_fetch_list_check_helper. Please check the input dict and checkout PipelineServingLogs/pipeline.log for more details.
INFO 2023-06-28 10:07:53,042 [operator.py:1454] prometheus inf count +1
ERROR 2023-06-28 10:07:53,044 [dag.py:420] (data_id=0 log_id=0) Failed to predict: [det] failed to predict. Log_id: 0  Raise_msg:  invalid arg list  ClassName: Op.process.<locals>.feed_fetch_list_check_helper  FunctionName: feed_fetch_list_check_helper. Please check the input dict and checkout PipelineServingLogs/pipeline.log for more details.
`
