### ISSUE TITLE
Paddle Serving的inference_model_to_serving接口转换模型文件的时候报错

### ISSUE THREAD

**Issue by hongenge** [PaddlePaddle/Serving#610]
代码：
```
import paddle_serving_client.io as serving_io
serving_io.inference_model_to_serving("/home/aistudio/export", serving_server="serving_server", serving_client="serving_client",  model_filename='__model__', params_filename='__params__')
```

截图：
![image](https://user-images.githubusercontent.com/15665995/82874033-f93a0b00-9f67-11ea-9a54-91228f1f4b08.png)
![abcd](https://user-images.githubusercontent.com/15665995/82874395-79f90700-9f68-11ea-9743-506053d7b3c6.png)

**Comment by MRXLT** [comment]
你好，这个接口需要使用develop的版本
可以先使用以下链接中的安装包
app
https://paddle-serving.bj.bcebos.com/whl/paddle_serving_app-0.1.0-py3-none-any.whl
client
https://paddle-serving.bj.bcebos.com/whl/paddle_serving_client-0.3.0-cp36-none-manylinux1_x86_64.whl
server
https://paddle-serving.bj.bcebos.com/whl/paddle_serving_server_gpu-0.3.0-py3-none-any.whl

**Comment by BeyondYourself** [comment]
@MRXLT 如果不是develop版本，就像上面说到的是0.2.1的版本，此处该怎么用

**Comment by BeyondYourself** [comment]
client
https://paddle-serving.bj.bcebos.com/whl/paddle_serving_client-0.3.0-cp36-none-manylinux1_x86_64.whl
这个版本有window版本的吗

**Comment by BeyondYourself** [comment]
[image](https://user-images.githubusercontent.com/12640462/83111523-50bab100-a0f7-11ea-992e-429ba19ddbcb.png)
![image](https://user-images.githubusercontent.com/12640462/83111645-865f9a00-a0f7-11ea-85c8-9ff962fbd16f.png)

根据上面的develop版本，在引入包的时候没有相关的方法，只有图上的几个函数

**Comment by MRXLT** [comment]
0.2.1可以参考这个文档使用，不过还是建议使用0.3.0的版本
https://github.com/PaddlePaddle/Serving/blob/v0.2.0/doc/SAVE.md
目前serving还不支持windows版本

**Comment by Shixuqing4343** [comment]
![image](https://user-images.githubusercontent.com/41406169/98437981-dc625000-2121-11eb-955c-9ec479af4ccf.png)
请问zhe这个错误该如何解决
