### ISSUE TITLE
在docker上构建服务，是否需要root权限

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/Serving#613]
当前准备在linux环境下Docker内构建Paddle Serving，在构建docker服务中是否需要使用到root权限，

**Comment by guru4elephant** [comment]
启动docker本身就需要root或者sudo

**Comment by hongenge** [comment]
需要root权限，或者sudo docker

**Comment by BeyondYourself** [comment]
好的，谢谢各位，之前直接用的root用户构建的，没有注意是否可以非root
