### ISSUE TITLE
使用Dockerfile.centos6.devel生成的镜像编译cpu server报错

### ISSUE THREAD

**Issue by MRXLT** [PaddlePaddle/Serving#618]
第一次make时失败，再次执行make后编译成功
![image](https://user-images.githubusercontent.com/16594411/83106780-9d9a8980-a0ef-11ea-9831-ae2540b09c77.png)
![image](https://user-images.githubusercontent.com/16594411/83106759-97a4a880-a0ef-11ea-97df-8b64e2a1e2f3.png)

**Comment by barrierye** [comment]
复现了下遇到这个问题：
> ImportError: No module named setuptools

需要先安装setuptools

**Comment by barrierye** [comment]
该镜像的python位置与centos7的镜像不同（重新装的python2.7）
> export PYTHONROOT=/usr/local/python2.7/
