### ISSUE TITLE
hub.baidubce.com/ctr/paddleserving 中 命令 执行 /serving/bin/elastic_serving时，报错Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by HankPeng03** [PaddlePaddle/Serving#622]
在模型库 个性化推荐-DeepCTR 中 镜像 hub.baidubce.com/ctr/paddleserving 中 命令 执行 /serving/bin/elastic_serving时，报错 Illegal instruction (core dumped)，有遇到过类似的问题么，求助

**Comment by HankPeng03** [comment]
![20F7EE3844D5BCD6C4953ED40E4EDE29](https://user-images.githubusercontent.com/22376333/83216341-9b8e0480-a19b-11ea-8f6a-43991cb0c75c.jpg)

**Comment by bjjwwang** [comment]
您好 方便kubectl logs paddleserving看一下嘛

**Comment by HankPeng03** [comment]
![image](https://user-images.githubusercontent.com/22376333/83471526-75c47080-a4b7-11ea-84c1-479be70a0390.png)


报错信息很简单
