### ISSUE TITLE
关于paddle.fluid自训练模型线上部署的问题

### ISSUE THREAD

**Issue by ClassmateXiaoyu** [PaddlePaddle/Serving#625]
我根据AI Studio中的教程在本地电脑用paddle.fluid复写了一个手写数字识别脚本，在本地电脑可以正常保存模型并预测输入图片的结果。之后通过docker运行paddle serving将手写数字识别模型进行线上部署预测，其中通过paddle_serving_client.io.inference_model_to_serving()将fluid.io.save_inference_model()保存的模型进行了转换。随后写了rpc的脚本，通过python -m paddle_serving_server.serve --model 模型server/ --port 9292启动了服务，在client端执行python rpc脚本.py 模型client/serving_client_conf.prototxt时，没有出现在本地环境进行测试预测数来的正确结果。
本地电脑环境：Windows 64、python 3.7、paddle-serving-client 0.2.1、paddle-serving-server 0.2.1、paddlehub 1.6.1、paddlepaddle 1.8.1、Docker version：18.03.0-ce
虚拟环境：使用的镜像hub.baidubce.com/paddlepaddle/serving:latest，内置python 2.7、docker info：Operating System: Boot2Docker 19.03.5 (TCL 10.1)、OSType: linux、Architecture: x86_64。
![QQ图片20200530153355](https://user-images.githubusercontent.com/62195135/83366849-2cefb780-a3e4-11ea-9c32-77e2258810c4.jpg)

**Comment by MRXLT** [comment]
你好，看样子是server端出问题了，请问server端有没有报错信息，在启动server的路径下有log/serving.ERROR文件，如果server端出错会有报错日志

**Comment by ClassmateXiaoyu** [comment]
有serving.INFO和serving.WARNING，没有serving.ERROR，下图是上周六跑后的log信息
![QQ图片20200601104115](https://user-images.githubusercontent.com/62195135/83371285-a5f70b00-a3f4-11ea-9652-0e25dbf8d9ec.png)

**Comment by MRXLT** [comment]
client端发送请求后，server端进程有退出的情况吗

**Comment by ClassmateXiaoyu** [comment]
中午又模拟了一遍，client端发送请求后，client的结果与问题截图一样。server端用ps看了一下，如下图（ps时，已经在client端发送请求了）。
![QQ图片20200601135029](https://user-images.githubusercontent.com/62195135/83379761-e5caec00-a40e-11ea-88cc-bc4ec9fd7da1.png)

**Comment by MRXLT** [comment]
请贴一下log/serving.INFO的尾部日志

**Comment by ClassmateXiaoyu** [comment]
![QQ图片20200601160933](https://user-images.githubusercontent.com/62195135/83389170-562f3880-a422-11ea-8f6b-223f0202b409.png)

**Comment by MRXLT** [comment]
麻烦你按照以下步骤获取以下更详细的日志
1、在server的终端里export GLOG_v=3
2、启动server
3、client端发送请求
然后截一下serving.INFO的尾部日志和client端输出到屏幕的日志

**Comment by ClassmateXiaoyu** [comment]
按照建议的步骤操作后，图一是serving.INFO信息，图二是client端输出到屏幕的信息。
![QQ图片20200601164658](https://user-images.githubusercontent.com/62195135/83392360-8d541880-a427-11ea-9a4a-0bf690042c25.png)
![QQ图片20200601165106](https://user-images.githubusercontent.com/62195135/83392704-1f5c2100-a428-11ea-8bcf-3fb11973dd03.png)

**Comment by MRXLT** [comment]
暂时还找不到出错的原因，建议先更新一下到0.2.3版本看问题是否还存在

**Comment by ClassmateXiaoyu** [comment]
> 暂时还找不到出错的原因，建议先更新一下到0.2.3版本看问题是否还存在

刚更新完，貌似只有server能升级到0.2.3，client用pip install --upgrade 指定0.2.3升级，反馈没有这个版本号。正在用server0.2.3跑脚本，截图稍后贴上。

**Comment by ClassmateXiaoyu** [comment]
> > 暂时还找不到出错的原因，建议先更新一下到0.2.3版本看问题是否还存在
> 
> 刚更新完，貌似只有server能升级到0.2.3，client用pip install --upgrade 指定0.2.3升级，反馈没有这个版本号。正在用server0.2.3跑脚本，截图稍后贴上。

有一点很奇怪，我在docker内升级server和client都可以到0.2.3，本地电脑环境只有server可以到0.2.3

**Comment by ClassmateXiaoyu** [comment]
docker内的版本：
![QQ图片20200602093533](https://user-images.githubusercontent.com/62195135/83470317-74457900-a4b4-11ea-8d24-58c72489d66b.png)
随后在server启动服务，但是0.2.3版本出现了0.2.1没有的Illegal instruction (core dumped)，截图如下：
![QQ图片20200602094159](https://user-images.githubusercontent.com/62195135/83470714-778d3480-a4b5-11ea-95bb-326353899ebf.png)
随后在client端发送请求，截图如下：
![QQ图片20200602094621](https://user-images.githubusercontent.com/62195135/83470932-f7b39a00-a4b5-11ea-8810-8e9927eda244.png)

**Comment by ClassmateXiaoyu** [comment]
你好，请问这个问题下一步该怎么处理，是否需要我提供脚本进行复现？

**Comment by MRXLT** [comment]
嗯嗯，请提供一下可复现的脚本

**Comment by ClassmateXiaoyu** [comment]
好的，通过什么方式提供给你？

**Comment by MRXLT** [comment]
将文件发送给我的邮箱吧 xlt2024@gmail.com

**Comment by ClassmateXiaoyu** [comment]
> xlt2024@gmail.com

邮件已发送。

**Comment by MRXLT** [comment]
你好，代码中有两处错误，
1、从已保存的模型中导出serving可用的配置文件时，server和client端配置文件的目录名称写反了
2、predict接口中fetch变量名错误，应该为fc_2.tmp_2，脚本中用的是save_infer_model/scale_0.tmp_0，fetch变量名应该与serving_client_conf.prototxt文件中的fetch变量的alias_name相同

**Comment by ClassmateXiaoyu** [comment]
> 你好，代码中有两处错误，
> 1、从已保存的模型中导出serving可用的配置文件时，server和client端配置文件的目录名称写反了
> 2、predict接口中fetch变量名错误，应该为fc_2.tmp_2，脚本中用的是save_infer_model/scale_0.tmp_0，fetch变量名应该与serving_client_conf.prototxt文件中的fetch变量的alias_name相同

你好，我上午按照建议对脚本进行了修改，server和client端配置文件的目录名称进行了调换。有个疑问我没弄懂，我这边无论是docker中还是本地Windows训练，2边得到的serving_client_conf.prototxt文件中的fetch变量的alias_name名字都是save_infer_model/scale_0.tmp_0，没有出现建议的fc_2.tmp_2。此外，我用自己写的另一个fluid模型进行了实验，得到的serving_client_conf.prototxt文件中的fetch变量的alias_name名字依旧是save_infer_model/scale_0.tmp_0。感到很奇怪，不同的模型得到的serving_client_conf.prototxt文件中的fetch变量的alias_name名字都是save_infer_model/scale_0.tmp_0。请问，这个怎么处理呀？
![6F7D79F8-4706-4e36-AB28-EAF434862378](https://user-images.githubusercontent.com/62195135/83844834-51c49180-a73a-11ea-9a4d-ae1058a67956.png)

**Comment by MRXLT** [comment]
> > 你好，代码中有两处错误，
> > 1、从已保存的模型中导出serving可用的配置文件时，server和client端配置文件的目录名称写反了
> > 2、predict接口中fetch变量名错误，应该为fc_2.tmp_2，脚本中用的是save_infer_model/scale_0.tmp_0，fetch变量名应该与serving_client_conf.prototxt文件中的fetch变量的alias_name相同
> 
> 你好，我上午按照建议对脚本进行了修改，server和client端配置文件的目录名称进行了调换。有个疑问我没弄懂，我这边无论是docker中还是本地Windows训练，2边得到的serving_client_conf.prototxt文件中的fetch变量的alias_name名字都是save_infer_model/scale_0.tmp_0，没有出现建议的fc_2.tmp_2。此外，我用自己写的另一个fluid模型进行了实验，得到的serving_client_conf.prototxt文件中的fetch变量的alias_name名字依旧是save_infer_model/scale_0.tmp_0。感到很奇怪，不同的模型得到的serving_client_conf.prototxt文件中的fetch变量的alias_name名字都是save_infer_model/scale_0.tmp_0。请问，这个怎么处理呀？
> ![6F7D79F8-4706-4e36-AB28-EAF434862378](https://user-images.githubusercontent.com/62195135/83844834-51c49180-a73a-11ea-9a4d-ae1058a67956.png)

这个可能是我使用的paddle版本和你的不一致，这个不影响serving使用，fetch这里还是以使用的配置文件中的为准，你这里要是用save_infer_model/scale_0.tmp_0

**Comment by ClassmateXiaoyu** [comment]
你好，我从paddle_serving_app.local_predict模块中导入了Debugger类并创建了实例debugger。随后，使用debugger.predict接口，并用serving_client_conf.prototxt文件中的feed和fetch变量的alias_name名字img和save_infer_model/scale_0.tmp_0，结果可以正常打印出每个标签的概率。说明fetch名字没有问题了，接下来是到docker进行线上的测试。
![DDA04097-3B7F-4d5c-BBA3-7A5843E7C236](https://user-images.githubusercontent.com/62195135/83851003-48402700-a744-11ea-881e-686e66e35bda.png)

但是在docker启动server端服务时，出现无法下载的错误。
![IMG_6275](https://user-images.githubusercontent.com/62195135/83851232-9fde9280-a744-11ea-9e34-e14446875c84.PNG)

**Comment by MRXLT** [comment]
直接wget那个tar包的链接能够下载吗

**Comment by ClassmateXiaoyu** [comment]
> 直接wget那个tar包的链接能够下载吗

今天再运行的时候可以下载了，不知道是不是电脑自身的问题。

**Comment by ClassmateXiaoyu** [comment]
你好，昨天用一台i7台式电脑进行手写数字识别模型测试，重新安装了系统以及编程环境，RPC已经可以跑起来并得到结果。但是今天测试HTTP这块，报错比较多。

**Comment by ClassmateXiaoyu** [comment]
> 你好，昨天用一台i7台式电脑进行手写数字识别模型测试，重新安装了系统以及编程环境，RPC已经可以跑起来并得到结果。但是今天测试HTTP这块，报错比较多。

我是用uci房价模型那种默认的HTTP启动server的方式启动服务后，通过curl方式可以得到预测结果。自己写的脚本报错很多。

**Comment by barrierye** [comment]
具体是什么报错呢？curl可以得到结果的话大概率是脚本有点问题

**Comment by ClassmateXiaoyu** [comment]
> 具体是什么报错呢？curl可以得到结果的话大概率是脚本有点问题

我再跑一遍HTTP的脚本，随后把报错贴上来

**Comment by ClassmateXiaoyu** [comment]
你好，昨天curl和py脚本都成功是另一个处理文本数据的模型。报错的是手写数字识别的模型，在server端通过python -m paddle_serving_server.serve --model nbh_model_server --port 9292 --name nbh启动了HTTP服务，随后在client端不管是运行py脚本还是curl命令，都返回这个报错，图片的预处理方式与模型训练之前使用的是同一个处理方式。
server端启动服务没有报错，这是在client运行py脚本后返回的信息：
![QQ截图20200610140944](https://user-images.githubusercontent.com/62195135/84233013-13591900-ab24-11ea-8744-a831f10c6bdc.png)
这个是client端返回的报错：
![QQ截图20200610141044](https://user-images.githubusercontent.com/62195135/84233078-34216e80-ab24-11ea-8e0d-f9a56b1ed188.png)

**Comment by ClassmateXiaoyu** [comment]
> 你好，昨天curl和py脚本都成功是另一个处理文本数据的模型。报错的是手写数字识别的模型，在server端通过python -m paddle_serving_server.serve --model nbh_model_server --port 9292 --name nbh启动了HTTP服务，随后在client端不管是运行py脚本还是curl命令，都返回这个报错，图片的预处理方式与模型训练之前使用的是同一个处理方式。

手写数字识别用PRC服务没有问题，可以预测结果出来。
![QQ截图20200610141535](https://user-images.githubusercontent.com/62195135/84233422-e35e4580-ab24-11ea-8636-1a1c573a9793.png)

**Comment by barrierye** [comment]
> 你好，昨天curl和py脚本都成功是另一个处理文本数据的模型。报错的是手写数字识别的模型，在server端通过python -m paddle_serving_server.serve --model nbh_model_server --port 9292 --name nbh启动了HTTP服务，随后在client端不管是运行py脚本还是curl命令，都返回这个报错，图片的预处理方式与模型训练之前使用的是同一个处理方式。
> server端启动服务没有报错，这是在client运行py脚本后返回的信息：
> ![QQ截图20200610140944](https://user-images.githubusercontent.com/62195135/84233013-13591900-ab24-11ea-8744-a831f10c6bdc.png)
> 这个是client端返回的报错：
> ![QQ截图20200610141044](https://user-images.githubusercontent.com/62195135/84233078-34216e80-ab24-11ea-8e0d-f9a56b1ed188.png)

看起来应该是client端发送的http请求有问题，web service是自己实现的吗？可以贴出来看看吗

**Comment by ClassmateXiaoyu** [comment]
web service：
![QQ截图20200610150412](https://user-images.githubusercontent.com/62195135/84237281-ae092600-ab2b-11ea-8eb9-a746d9d5fc35.png)
client http：
![QQ图片20200610150831](https://user-images.githubusercontent.com/62195135/84237636-4acbc380-ab2c-11ea-80ad-2310b62c4590.png)

**Comment by barrierye** [comment]
fetch的值看起来有点奇怪，可以看下server端的log（在server端会生成log文件夹）看看具体是什么问题

**Comment by ClassmateXiaoyu** [comment]
![QQ截图20200610170919](https://user-images.githubusercontent.com/62195135/84249339-33490680-ab3d-11ea-90c7-bca995706387.png)
cat serving.INFO都是循环显示一样的信息（截图是最后3条）
![QQ截图20200610171103](https://user-images.githubusercontent.com/62195135/84249490-67bcc280-ab3d-11ea-8885-3a5f54b1647f.png)
cat serving.WARNING也都是循环显示一样的信息（截图是最后5条）
![QQ截图20200610171243](https://user-images.githubusercontent.com/62195135/84249645-9e92d880-ab3d-11ea-8788-27852d90a2b4.png)

**Comment by barrierye** [comment]
可以提供一下可复现的脚本吗？邮箱 barriery@qq.com

**Comment by ClassmateXiaoyu** [comment]
> 可以提供一下可复现的脚本吗？邮箱 [barriery@qq.com](mailto:barriery@qq.com)

你好，邮件已发送。

**Comment by barrierye** [comment]
您好，404问题我没能复现，可以再检查下url等网络相关的配置吗？

我发现另一个问题：
目前Serving Client支持list和numpy array两种输入，当输入格式为list时需要将输入矩阵展平成一维（不然无法通过shape检查，这个我们之后会改进）。
而HTTP方式是通过list格式输入的，故需要将输入img.reshape(-1)一下。

**Comment by ClassmateXiaoyu** [comment]
> 您好，404问题我没能复现，可以再检查下url等网络相关的配置吗？
> 
> 我发现另一个问题：
> 目前Serving Client支持list和numpy array两种输入，当输入格式为list时需要将输入矩阵展平成一维（不然无法通过shape检查，这个我们之后会改进）。
> 而HTTP方式是通过list格式输入的，故需要将输入img.reshape(-1)一下。

你好，我按照建议将feed的数据进行了reshape(-1)后，HTTP服务没有报错，成功的打印了每个标签的概率值，这个问题看来还是feed数据的格式问题，URL这块是ok的。目前模型的RPC和HTTP都可以正常部署并预测数据，非常感谢。
