### ISSUE TITLE
Can't find CUDA when I use CUDA10

### ISSUE THREAD

**Issue by gongweibao** [PaddlePaddle/Serving#627]
when I use CUDA10, it reports that serving can't find CUDA and I use CUDA 9 resolve it!

**Comment by barrierye** [comment]
CUDA9 is used by default for Paddle Serving.
If you need CUDA10, you can [compile it from source](https://github.com/PaddlePaddle/Serving/blob/develop/doc/COMPILE.md).

**Comment by gongweibao** [comment]
Why not just release CUDA-9.0,  CUDA-10.0 version's wheel package?

**Comment by barrierye** [comment]
We will consider release CUDA9 and CUDA10 version later.

**Comment by guru4elephant** [comment]
will release in 0.4.0

**Comment by sevenold** [comment]
@guru4elephant 

example: https://github.com/PaddlePaddle/Serving/tree/develop/python/examples/ocr

```bash
paddle-serving-app        0.1.1                    pypi_0    pypi
paddle-serving-client     0.3.1                    pypi_0    pypi
paddle-serving-server     0.3.1                    pypi_0    pypi
paddle-serving-server-gpu 0.3.1                    pypi_0    pypi
paddlepaddle-gpu          1.8.3.post97             pypi_0    pypi
```

![image](https://user-images.githubusercontent.com/41443157/88357509-17708b80-cd9e-11ea-8b5b-e30da5e31429.png)

**Comment by barrierye** [comment]
Please run `ldd <PATH/TO/SERVING_BIN>| grep cudart` to see the output.

By the way, CUDA10 has been supported recently. You can download CUDA10 temporary version binary file(https://paddle-serving.bj.bcebos.com/temporary_files_for_docker/serving-gpu-0.3.1.tar.gz) and use it with the 
 command `export SERVING_BIN=<PATH/TO/CUDA10_SERVING_BIN>`.

**Comment by sevenold** [comment]
- docker image : paddlepaddle/serving:latest-cuda10.0-cudnn7 
- cudart
```
[root@PC models]# ldd $SERVING_BIN | grep cudart
        libcudart.so.10.0 => /usr/local/cuda-10.0/targets/x86_64-linux/lib/libcudart.so.10.0 (0x00007f215c489000)
```
![image](https://user-images.githubusercontent.com/41443157/88641127-5598e280-d0f1-11ea-8f8c-46ae71b24d75.png)

@barrierye

**Comment by barrierye** [comment]
Please check nvidia devices by `ls /dev/ | grep nvidia`

**Comment by iceriver97** [comment]
您好，在AIstudio上运行Serving的相关项目也需要更改CUDA的版本吗？
