### ISSUE TITLE
latest gpu镜像中执行debugger报错

### ISSUE THREAD

**Issue by MRXLT** [PaddlePaddle/Serving#628]
![image](https://user-images.githubusercontent.com/16594411/83391712-73fe9c80-a426-11ea-983a-f360bed71970.png)

原因：环境中缺失 libcupti.so
复现脚本
https://github.com/PaddlePaddle/Serving/tree/develop/python/paddle_serving_app#debug-tools

**Comment by barrierye** [comment]
有更详细的复现步骤吗？

根据[文档](https://github.com/PaddlePaddle/Serving/blob/develop/python/paddle_serving_app/README_CN.md#debug%E5%B7%A5%E5%85%B7)执行下面的脚本：
```python
from paddle_serving_app.local_predict import Debugger
import numpy as np

debugger = Debugger()
debugger.load_model_config("./uci_housing_model", gpu=False)
data = [0.0137, -0.1136, 0.2553, -0.0692, 0.0582, -0.0727,
        -0.1583, -0.0584, 0.6283, 0.4919, 0.1856, 0.0795, -0.0332]
fetch_map = debugger.predict(feed={"x":data}, fetch = ["price"])
```

运行正常（gpu选项改成True同样运行正常）

**Comment by barrierye** [comment]
> 有更详细的复现步骤吗？
> 
> 根据[文档](https://github.com/PaddlePaddle/Serving/blob/develop/python/paddle_serving_app/README_CN.md#debug%E5%B7%A5%E5%85%B7)执行下面的脚本：
> 
> ```python
> from paddle_serving_app.local_predict import Debugger
> import numpy as np
> 
> debugger = Debugger()
> debugger.load_model_config("./uci_housing_model", gpu=False)
> data = [0.0137, -0.1136, 0.2553, -0.0692, 0.0582, -0.0727,
>         -0.1583, -0.0584, 0.6283, 0.4919, 0.1856, 0.0795, -0.0332]
> fetch_map = debugger.predict(feed={"x":data}, fetch = ["price"])
> ```
> 
> 运行正常（gpu选项改成True同样运行正常）

使用paddlepaddle-gpu可以复现
