### ISSUE TITLE
自训练yolov3 rpc部署失败

### ISSUE THREAD

**Issue by JiaoZiLang** [PaddlePaddle/Serving#641]
如题，用PaddleDetection 自训练yolov3模型，参考rcnn的serving写rpc的部署，调用失败。（感觉yolov3很常用，可否给一个yolov3的demo指导）

**Comment by bjjwwang** [comment]
这两天就会支持，。
出错目前原因是serving没有做int32支持，所有类型都是int64。

**Comment by JiaoZiLang** [comment]
请问一下现在支持了么@。@

**Comment by MRXLT** [comment]
> 请问一下现在支持了么@。@

你好，int32的代码已合入develop分支，暂时未发布正式版，请通过以下链接先试用latest版本
https://github.com/PaddlePaddle/Serving/blob/develop/doc/LATEST_PACKAGES.md
