### ISSUE TITLE
paddle-serving-client 最新的安装包和线上源码不一致

### ISSUE THREAD

**Issue by zoe531** [PaddlePaddle/Serving#653]
运行最新的包发现源码 save_model(serving_client, serving_server,）参数反了，发现线上源码已更新，能否及时更新安装源的包？
## 安装包代码
![屏幕快照 2020-06-05 下午6 09 16](https://user-images.githubusercontent.com/10573385/83865777-42a10c00-a759-11ea-9d28-b7157f2de308.png)
## 线上代码
![屏幕快照 2020-06-05 下午6 21 25](https://user-images.githubusercontent.com/10573385/83865884-77ad5e80-a759-11ea-9bca-1d3a7b928250.png)

**Comment by MRXLT** [comment]
请先使用这个链接中的安装包，链接中的安装包编译自develop分支
https://github.com/PaddlePaddle/Serving/blob/develop/doc/LATEST_PACKAGES.md
我们需要对代码进行测试后才能正式发布，所以会与develop分支代码有一些差异，请谅解

**Comment by zoe531** [comment]
macos 不支持 chient 安装

**Comment by barrierye** [comment]
> macos 不支持 chient 安装

目前版本的client不支持macOS使用，可以考虑使用HTTP接口。后续版本我们会推出一个支持多平台多语言的client，感谢支持~
