### ISSUE TITLE
feed_vars and fetch_targets for save_model for blazeface

### ISSUE THREAD

**Issue by kgkzhiwen** [PaddlePaddle/Serving#657]
请问我要用save_model来保存blazeface模型，以便在serving上运行，我应该使用什么作为feed_vars 和fetch_targets?

谢谢！

**Comment by barrierye** [comment]
您好，可以参考[这个脚本](https://github.com/PaddlePaddle/Serving/blob/develop/python/examples/bert/prepare_model.py)

**Comment by kgkzhiwen** [comment]
这个是针对PaddleHub的模型。对于不在Paddle Hub里的模型，比如开发套件里面的，要怎么样获取输入和输出context？ 谢谢！

**Comment by barrierye** [comment]
> 这个是针对PaddleHub的模型。对于不在Paddle Hub里的模型，比如开发套件里面的，要怎么样获取输入和输出context？ 谢谢！

是已经导出模型文件吗？可以参考[这个文档](https://github.com/PaddlePaddle/Serving/blob/develop/doc/SAVE_CN.md)

**Comment by kgkzhiwen** [comment]
是一个用blazeface训练好的模型，已经用fluid.io.save保存下来 产生了三个文件，（final.pdmodel, final.params, final.pdopt), 要怎么样把它转化为serving可以用的模型。

使用inference_model_to_serving出现版本不相容的错误，

因此，我想用python把模型调出来，然后再用save_model转化为serving可以用的模型。我已经找到feed_vars,可是始终弄不到target_vars的结构。请问有什么办法？

**Comment by bjjwwang** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/master/docs/advanced_tutorials/deploy/EXPORT_MODEL.md 参考这个

**Comment by kgkzhiwen** [comment]
谢谢！我现在可以输出模型，也可以运行serving，

可是，当我尝试用RPC client 做预测的时候，产生下面的错误。 要怎么样解决？
W0609 18:58:15.637337  1998 redis_protocol.cpp:69] No corresponding PipelinedInfo in socket
E0609 18:58:15.637379  1998 input_messenger.cpp:113] A message from 127.0.0.1:9292(protocol=esp) is bigger than 536870912 bytes, the connection will be closed. Set max_body_size to allow bigger messages
W0609 18:58:15.637388  1998 input_messenger.cpp:276] Close fd=4 SocketId=1@127.0.0.1:9292@58740: too big data
W0609 18:58:15.637607  1982 predictor.hpp:129] inference call failed, message: [E22]1/1 channels failed, fail_limit=1 [C0][E22]Close fd=4 SocketId=1@127.0.0.1:9292@58740: too big data

**Comment by bjjwwang** [comment]
m

> 谢谢！我现在可以输出模型，也可以运行serving，
> 
> 可是，当我尝试用RPC client 做预测的时候，产生下面的错误。 要怎么样解决？
> W0609 18:58:15.637337 1998 redis_protocol.cpp:69] No corresponding PipelinedInfo in socket
> E0609 18:58:15.637379 1998 input_messenger.cpp:113] A message from 127.0.0.1:9292(protocol=esp) is bigger than 536870912 bytes, the connection will be closed. Set max_body_size to allow bigger messages
> W0609 18:58:15.637388 1998 input_messenger.cpp:276] Close fd=4 SocketId=1@127.0.0.1:9292@58740: too big data
> W0609 18:58:15.637607 1982 predictor.hpp:129] inference call failed, message: [E22]1/1 channels failed, fail_limit=1 [C0][E22]Close fd=4 SocketId=1@127.0.0.1:9292@58740: too big data

抱歉 久等了
您好 Blazeface已经在https://github.com/PaddlePaddle/Serving/pull/711/files  PR中正在评审。
想问下这个错误的图片是有多大，batch size是多少

**Comment by taoqinghua** [comment]
> m
> 
> > 谢谢！我现在可以输出模型，也可以运行serving，
> > 可是，当我尝试用RPC client 做预测的时候，产生下面的错误。 要怎么样解决？
> > W0609 18:58:15.637337 1998 redis_protocol.cpp:69] No corresponding PipelinedInfo in socket
> > E0609 18:58:15.637379 1998 input_messenger.cpp:113] A message from 127.0.0.1:9292(protocol=esp) is bigger than 536870912 bytes, the connection will be closed. Set max_body_size to allow bigger messages
> > W0609 18:58:15.637388 1998 input_messenger.cpp:276] Close fd=4 SocketId=1@127.0.0.1:9292@58740: too big data
> > W0609 18:58:15.637607 1982 predictor.hpp:129] inference call failed, message: [E22]1/1 channels failed, fail_limit=1 [C0][E22]Close fd=4 SocketId=1@127.0.0.1:9292@58740: too big data
> 
> 抱歉 久等了
> 您好 Blazeface已经在https://github.com/PaddlePaddle/Serving/pull/711/files PR中正在评审。
> 想问下这个错误的图片是有多大，batch size是多少

我在使用simnet模型预测时也出现相同的问题，不知道如何解决。

**Comment by madonghui0329** [comment]
> > 米
> > > 谢谢！我可以输出模型，也可以运行服务，是的，当我现在
> > > 尝试用 RPC 客户端做预测的时候，会出现下面的错误。要如何解决？
> > > W0609 18:58:15.637337 1998 redis_protocol.cpp:69] 否socket 
> > > E0609 18:58:15.637379 1998 input_messenger.cpp:113] 来自 127.0.0.1:9292(protocol=esp) 的消息大于 536870912 字节，连接将被关闭。设置 max_body_size 以允许更大的消息
> > > W0609 18:58:15.637388 1998 input_messenger.cpp:276] 关闭 fd=4 SocketId=1@127.0.0.1:9292@58740: 数据太大
> > > W0609 18:58:15.637607 1982 predictor.hpp:129 ] 推理调用失败，消息：[E22]1/1 个通道失败，fail_limit=1 [C0][E22]Close fd=4 SocketId=1@127.0.0.1:9292@58740：数据太大
> > 
> > 
> > 抱歉久等你了好Blazeface
> > 已经在https://github.com/PaddlePaddle/Serving/pull/711/files PR 中正在审查的。
> > 想问下这个错误图片是有多大，batch size 是多少
> 
> 我在使用simnet的时候也出现了相同的问题预测模型，不知道如何解决。

请问这个问题解决了吗？我也遇到了类似的
