### ISSUE TITLE
本地镜像中未成功启动服务端

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/Serving#660]
在服务器的linux系统中（不能连外网），在paddle的镜像中进行服务端的启动，出现以下错误：
![image](https://user-images.githubusercontent.com/12640462/84102029-efbda200-aa41-11ea-94e5-f7317e33987c.png)
，其中镜像中已经安装了paddle-serving-client和server，版本为：
paddle-serving-client 0.2.3
paddle-serving-server 0.2.3
服务器已经安装了，这个是还要重新安装一次？
paddle版本是1.8.1  
python版本3.7.7

**Comment by barrierye** [comment]
您好，paddle-serving-server在第一次使用时，需要访问外网下载一个二进制文件

**Comment by BeyondYourself** [comment]
@barrierye 离线使用的怎么部署，哪里可以下载

**Comment by barrierye** [comment]
> @barrierye 离线使用的怎么部署，哪里可以下载

根据上述log中的链接下载`serving-cpu-noavx-openblas-0.2.3.tar.gz`，将其解压到`<paddle_serving_server安装路径>/serving-cpu-noavx-openblas-0.2.3`

**Comment by BeyondYourself** [comment]
Thanks，已解决
