### ISSUE TITLE
Serving 调用时Out of Memory 

### ISSUE THREAD

**Issue by omtbreak** [PaddlePaddle/Serving#664]
1. 在服务器上使用0号显卡或者1号显卡开启目标检测模型，并且服务器显卡显存充足
![截屏2020-06-0915 51 22](https://user-images.githubusercontent.com/12478872/84120953-16db9a00-aa69-11ea-8be0-34f20b4ca780.png)

2. 使用RPC方式调用时，服务器端报错out of memory
![截屏2020-06-0915 52 28](https://user-images.githubusercontent.com/12478872/84121062-3e326700-aa69-11ea-834d-8c028a89dada.png)

并且按照指示设置
```
export FLAGS_fraction_of_gpu_memory_to_use=0.9
```
同样出现问题，没有解决

**Comment by MRXLT** [comment]
你好，可以在启动server服务时，添加--mem_optim True参数开启显存优化

**Comment by omtbreak** [comment]
> --mem_optim True

解决了谢谢

**Comment by omtbreak** [comment]
> 你好，可以在启动server服务时，添加--mem_optim True参数开启显存优化

您好，在持续调用多张图片的情况下，添加--mem_optim True参数后，仍出现这个问题
![截屏2020-06-1010 33 09](https://user-images.githubusercontent.com/12478872/84220708-0fb69980-ab06-11ea-9d93-e24778c276ba.png)

**Comment by MRXLT** [comment]
你好，请问使用的模型是什么样的，启动服务时显卡上的可用显存是多少

**Comment by omtbreak** [comment]
> 你好，请问使用的模型是什么样的，启动服务时显卡上的可用显存是多少

启动的模型时cascade rcnn，启动服务时显卡情况就如![截屏2020-06-0915 51 22](https://user-images.githubusercontent.com/12478872/84120953-16db9a00-aa69-11ea-8be0-34f20b4ca780.png)所示

**Comment by omtbreak** [comment]
> 你好，请问使用的模型是什么样的，启动服务时显卡上的可用显存是多少

有可能是，服务器端再完成一次图片的检测后，并不释放当前使用的显存，而当下一次调用来时，又去重新申请新的显存。

**Comment by bjjwwang** [comment]
现在暂时是把thread最小限制压缩到2，可以编译一下再试试看显存消耗问题

**Comment by sevenold** [comment]
```bash

export FLAGS_fraction_of_gpu_memory_to_use=0.9

python -m paddle_serving_server_gpu.serve --model server_model/server_rec  --port 9294 --gpu_id 2 --mem_optim --thread 2 --max_body_size 1073741824

```
![image](https://user-images.githubusercontent.com/41443157/94360428-b20f8280-00df-11eb-8d1e-a49516ba3d6e.png)

模型是paddleOCR
- ch_det_r50_vd_db  
- ch_rec_r34_vd_crnn
- 显存11G


一张类似PDF的图片就直接OOM!!

@wangjiawei04
