### ISSUE TITLE
serving什么时候支持int32

### ISSUE THREAD

**Issue by mcl-stone** [PaddlePaddle/Serving#671]
自己训练的模型部署使用时报错，因为不支持int32，请问什么时候支持，求支持

**Comment by guru4elephant** [comment]
@mcl-stone 已经排到todo了

**Comment by mcl-stone** [comment]
> @mcl-stone 已经排到todo了

感谢！

**Comment by mcl-stone** [comment]
> @mcl-stone 已经排到todo了

请问有大概的完成时间点吗？很期待！

**Comment by MRXLT** [comment]
你好，对int32的支持正在PR中
https://github.com/PaddlePaddle/Serving/pull/676

**Comment by MRXLT** [comment]
> 你好，对int32的支持正在PR中
> #676

PR已合入
