### ISSUE TITLE
paddle-serving的RPC和支持多线程调用吗

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/Serving#674]
1 paddle-serving的RPC和支持多线程调用吗
2 服务端在处理的时候支持多线程操作吗，还是只支持多进程
3 服务端部署目前支持分布式部署吗

**Comment by MRXLT** [comment]
你好，serving是支持多线程的，server端可以通过--thread参数或者set_thread_num api来设置线程数，目前0.3.1之前的版本支持的thread最小为4，后续版本最小为2，client端可以多线程调用predict接口。

分布式部署是指的哪种方式呢，可以介绍一下应用场景吗

**Comment by BeyondYourself** [comment]
分布式部署类似于hadoop部署，是否支持多节点服务部署，主要可能是当前的单机资源紧缺，需要通过调用多机资源来实现服务调用

**Comment by TeslaZhao** [comment]
目前不支持分布式部署。单机资源有限，是指模型很大，无法在一个GPU卡上运行吗？

**Comment by BeyondYourself** [comment]
目前可能GPU稀缺，主要还是用CPU
