### ISSUE TITLE
lac服务只支持分词吗？

### ISSUE THREAD

**Issue by zhangzhen8230** [PaddlePaddle/Serving#675]
README中给出了lac服务示例，但是只有分词功能，看paddle下的paddlehub的lac可以分词和命名实体实体等，并且lac现在已经出了2.0. 现在的paddleserving下的lac模型是最新的吗？ 是否支持其它如词性标注、命名实体识别等工程。

**Comment by guru4elephant** [comment]
实际上可以基于serving框架进行自主开发，serving团队也会提供一些最新模型的示例给用户@zhangzhen8230
