### ISSUE TITLE
模型通过paddle serving部署后的使用疑惑

### ISSUE THREAD

**Issue by ClassmateXiaoyu** [PaddlePaddle/Serving#677]
模型已经通过paddle serving部署成功（RPC和HTTP都已实现）。现在有关于一些使用上的疑惑：
现有一台操作系统为Windows 64的电脑A（以下简称为A），A的环境包括docker（内含paddlepaddle，paddlehub、paddle-serving-server、paddle-serving-client、paddle-serving-app）；一台操作系统同为Windows 64的电脑B（以下简称为B），B的环境同样包括docker（内含paddlepaddle，paddlehub、paddle-serving-server、paddle-serving-client）。
情景1：A做为server端，在A docker中成功的启动了HTTP服务，此时在A docker中，无论是通过运行py脚本或是curl命令，都可以正常的预测数据。在B那边输入网址预测时，预测网址无法访问，那么B应该如何访问A的server？
情景2：A做为server端，B做为client端（已安装paddle-serving-client）。在A docker中成功的启动了RPC服务，此时在A docker中，通过运行py脚本可以正常的预测数据。在B运行脚本也无法访问服务进行数据预测。
注：上述2种情景在A docker中都是正常的，可以访问服务并预测数据。

**Comment by MRXLT** [comment]
你好，请问docker是否做了端口映射

**Comment by ClassmateXiaoyu** [comment]
> 你好，请问docker是否做了端口映射

你好，docker run创建容器的时候，添加了-p 9292:9292做了映射的。

**Comment by ClassmateXiaoyu** [comment]
> > 你好，请问docker是否做了端口映射
> 
> 你好，docker run创建容器的时候，添加了-p 9292:9292做了映射的。

容器创建时命令docker run -p 9292:9292 --name test -dit 镜像名

**Comment by MRXLT** [comment]
docker b中有没有设置代理，HTTP预测服务的话，client端如果有代理时会报错

**Comment by ClassmateXiaoyu** [comment]
> docker b中有没有设置代理，HTTP预测服务的话，client端如果有代理时会报错

你好，docker没有设置过相关的代理，server和client都没有设置过。我猜想是否与用作server端的电脑ip是否为固定ip有关呀？

**Comment by omtbreak** [comment]
> > docker b中有没有设置代理，HTTP预测服务的话，client端如果有代理时会报错
> 
> 你好，docker没有设置过相关的代理，server和client都没有设置过。我猜想是否与用作server端的电脑ip是否为固定ip有关呀？

请问您可以使用RPC方式多次调用模型么

**Comment by ClassmateXiaoyu** [comment]
> > > docker b中有没有设置代理，HTTP预测服务的话，client端如果有代理时会报错
> > 
> > 
> > 你好，docker没有设置过相关的代理，server和client都没有设置过。我猜想是否与用作server端的电脑ip是否为固定ip有关呀？
> 
> 请问您可以使用RPC方式多次调用模型么

你好，是这样的。HTTP和RPC这两种服务在同一台电脑上分别开启server和client端，是都可以多次成功调用模型的，我在办公室多台电脑都试过了。现在我是想同不同的电脑做测试，A电脑做server端，B电脑做client端。公司的外网ip为非固定ip，公司内部的电脑都在同一个局域网，通过DHCP自动分配的ip。我在A电脑docker容器中启动server端HTTP货RPC服务后，B电脑（即client端）访问不到A电脑server端的RPC或HTTP服务。

**Comment by ClassmateXiaoyu** [comment]
> > > > docker b中有没有设置代理，HTTP预测服务的话，client端如果有代理时会报错
> > > 
> > > 
> > > 你好，docker没有设置过相关的代理，server和client都没有设置过。我猜想是否与用作server端的电脑ip是否为固定ip有关呀？
> > 
> > 
> > 请问您可以使用RPC方式多次调用模型么
> 
> 你好，是这样的。HTTP和RPC这两种服务在同一台电脑上分别开启server和client端，是都可以多次成功调用模型的，我在办公室多台电脑都试过了。现在我是想同不同的电脑做测试，A电脑做server端，B电脑做client端。公司的外网ip为非固定ip，公司内部的电脑都在同一个局域网，通过DHCP自动分配的ip。我在A电脑docker容器中启动server端HTTP货RPC服务后，B电脑（即client端）访问不到A电脑server端的RPC或HTTP服务。

你好，请问这是docker设置问题还是电脑公网ip问题呢？

**Comment by MRXLT** [comment]
你好，应该是非固定ip导致的，最好能固定server端的ip

**Comment by ClassmateXiaoyu** [comment]
> 你好，应该是非固定ip导致的，最好能固定server端的ip

好的，我在云服务器上也试了一下，在云上安装了docker后，由于无法像本地电脑进BIOS开启VT功能，docker也没办法在云上运行起来，相当尴尬。
![QQ图片20200618153040](https://user-images.githubusercontent.com/62195135/84991251-da9aee80-b178-11ea-9a18-ea80f9e98507.png)

**Comment by andy-zhangtao** [comment]
找一台Linux的VPS，然后创建容器时，通过-p 将http/rpc的端口对外暴露出来就能解决你的问题了

**Comment by ClassmateXiaoyu** [comment]
> 找一台Linux的VPS，然后创建容器时，通过-p 将http/rpc的端口对外暴露出来就能解决你的问题了

好的，谢谢答复。我准备了一个入门级的云服务器，centos7系统，上午正在装python、paddle和其他环境，下午在云上试一下。

**Comment by ClassmateXiaoyu** [comment]
> > 找一台Linux的VPS，然后创建容器时，通过-p 将http/rpc的端口对外暴露出来就能解决你的问题了
> 
> 好的，谢谢答复。我准备了一个入门级的云服务器，centos7系统，上午正在装python、paddle和其他环境，下午在云上试一下。

下午在云服务器开启了server服务，其中HTTP和RPC模式都分别进行了启动。随后，在另一台笔记本client通过分别通过curl命令和py脚本访问服务，结果都成功的打印了结果，server端没有报错。
