### ISSUE TITLE
paddle-serving启动成功后，相关的日志在哪里设置

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/Serving#684]
1 服务启动成功，客户端调用成功后，有如下警告：`WARNING: Logging before InitGoogleLogging() is written to STDERR`，这个该怎么解决
2 服务端相关启动日志可以从哪里设置，目前没有找到相关配置

**Comment by TeslaZhao** [comment]
1.警告是glog组件打印的，告知glog初始化之前日志打印在STDERR
2.一般采用GLOG_v方式启动服务同时设置日志级别。
例如：GLOG_v=2 python -m paddle_serving_server.serve --model xxx_conf/ --port 9999

**Comment by BeyondYourself** [comment]
明白，谢谢解惑
