### ISSUE TITLE
RPC模式下，windows客户端下启动报错

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/Serving#686]
RPC模式下，linux客户端调用服务正常，但是在windows客户端下，直接调用报错，window的paddle-serving-client为0.2版本，paddle为1.8.1  CPU模式下的调用，具体错误如下：
![image](https://user-images.githubusercontent.com/12640462/84846147-b9ef6d80-b080-11ea-8afc-3b2683674114.png)
看了看源码，关于paddle_serving_client.serving_client这部分是so文件，是C的实现方式，这个调用可以改进一下吗，
![image](https://user-images.githubusercontent.com/12640462/84846439-66c9ea80-b081-11ea-8c08-526eec78e6f2.png)

======================================================
windows下的paddle-serving-client应该是dll文件编译吧，当前的0.2版本的client是so文件是不是有问题？？

**Comment by guru4elephant** [comment]
您好，windows下的使用我们会给出官方方法，当前pip发布的client无法在win上直接使用

**Comment by barrierye** [comment]
在下一个版本中会加入多平台的支持。

windows可以暂时考虑：
1. 当前版本使用HTTP方式获取服务
2. 使用临时版本的包：[传送门](https://github.com/PaddlePaddle/Serving/blob/develop/doc/LATEST_PACKAGES.md) 
  （但是目前最新client包只支持linux安装，我们会在这个issue中修复 #687 ）

临时版本的多平台服务端和客户端的使用方法：
- [server端](https://github.com/PaddlePaddle/Serving/blob/develop/python/examples/fit_a_line/test_multilang_server.py)
- [client端](https://github.com/PaddlePaddle/Serving/blob/develop/python/examples/fit_a_line/test_multilang_client.py)

**Comment by barrierye** [comment]
临时版本的包的地址已经更新：https://github.com/PaddlePaddle/Serving/blob/1a7db667259f3610492a29e2b462f307d2b3881f/doc/LATEST_PACKAGES.md

**Comment by BeyondYourself** [comment]
好的，多谢解答 @barrierye @guru4elephant
