### ISSUE TITLE
windows环境下rpc客户端报错No module named 'paddle_serving_client.serving_client'

### ISSUE THREAD

**Issue by chengxurensheng666** [PaddlePaddle/Serving#693]
![image](https://user-images.githubusercontent.com/48110081/85199496-a06d5080-b322-11ea-963d-5958030cb133.png)

**Comment by chengxurensheng666** [comment]
users' first issue？

**Comment by guru4elephant** [comment]
您好，支持多平台的client，最近刚刚merge还没有release，我们会尽快提供release版本，耽误您时间了

**Comment by barrierye** [comment]
您好，可以参考这个issue #686
多平台支持还在完善中，预计在这两天合入，详见https://github.com/PaddlePaddle/Serving/issues/683

**Comment by chengxurensheng666** [comment]
好的，请尽快发布，对了还有一个问题请你们提供一个http请求demo演示fasterrcnn嘛，padddleserving的案例还比较少

**Comment by guru4elephant** [comment]
好的，放到计划中

**Comment by barrierye** [comment]
您好，多平台的服务端/客户端已经支持，用法参考：https://github.com/PaddlePaddle/Serving/tree/develop/python/examples/grpc_impl_example/fit_a_line
