### ISSUE TITLE
Paddle Serving 、Paddle Inference、PaddleHub Serving三者的区别是什么？有什么样的包含关系？

### ISSUE THREAD

**Issue by zhuyingjun-zyj** [PaddlePaddle/Serving#706]
问题一：
想用paddles erving做模型的部署，发现文档上有paddle inference也可以部署模型，想知道这两者有什么区别？分别针对什么样的业务场景
  问题二：
我想实现在web端一键控制模型的开始训练、停止训练、预测服务、上传自定义数据集、在web端展示模型训练的实时状态信息，paddleserving、paddleinference、paddlehub serving三个中的哪个框架可以和web端交互实现这种业务场景么？如果可以，能说一下具体的实现方式么？
还希望老师们解答一下，多谢！！

**Comment by guru4elephant** [comment]
paddle serving是远程服务，即发起预测的设备（手机、浏览器、客户端等）与实际预测的硬件不在一起。paddle inference是一个library，适合嵌入到一个大系统中保证预测效率，paddle serving调用了paddle inference做远程服务。paddlehub serving可以认为是一个demo，后面都会使用paddle serving作为统一预测服务入口。如果在web端交互，一般是调用远程服务的形式，可以使用paddle serving的web service搭建。@zhuyingjun-zyj

**Comment by zhuyingjun-zyj** [comment]
在上面的解答中你有说道：
paddle serving调用了paddle inference做远程服务

那么paddle serving和paddle inference是如何交互的呢？也就是说使用了paddle inference做预测，paddle serving如何调起paddle inference的预测接口？
希望老师帮忙解答一下。

**Comment by BeyondYourself** [comment]
serving和inference交互通过百度的RPC框架，这个可以看看serving的设计文档，里面有说明

> paddle serving和paddle inference是如何交互的呢？

**Comment by minghua-123** [comment]
PaddleHub Serving和Paddle Serving区别和联系呢

**Comment by minghua-123** [comment]
@guru4elephant
