### ISSUE TITLE
python -m paddle_serving_app.package --get_model yolov4

### ISSUE THREAD

**Issue by mcl-stone** [PaddlePaddle/Serving#713]
python -m paddle_serving_app.package --get_model yolov4
![image](https://user-images.githubusercontent.com/62418900/86236953-7a229d00-bbcd-11ea-93ba-3dba4d7c1c45.png)
找不到model

**Comment by bjjwwang** [comment]
wget https://paddle-serving.bj.bcebos.com/paddle_hub_models/image/ObjectDetection/yolov4.tar.gz --no-check-certificate 试试看这样好不好下载

**Comment by MRXLT** [comment]
你好，使用yolov4示例需要安装develop版本的paddle_serving，可以从这个页面下载安装
https://github.com/PaddlePaddle/Serving/blob/develop/doc/LATEST_PACKAGES.md

**Comment by mcl-stone** [comment]
ok！谢了！
