### ISSUE TITLE
pipeline 优化 profile 日志

### ISSUE THREAD

**Issue by barrierye** [PaddlePaddle/Serving#721]
> 人去看这个日志很费劲

![image](https://user-images.githubusercontent.com/28446721/86562513-61cbcd00-bf95-11ea-9c78-490e02ca625e.png)

可以考虑在channel中存日志，传到client端（server端由于dag跨请求，不方便传到client）

**Comment by cg82616424** [comment]
嗯，设计下日志，方便人阅读，也方便监控系统做数据采集

**Comment by barrierye** [comment]
现在支持从 client 端获取profile了：https://github.com/PaddlePaddle/Serving/pull/714 ，通过在调用预测函数时设置 profile=True
