### ISSUE TITLE
NEW WEB SERVICE文档外链404

### ISSUE THREAD

**Issue by bjjwwang** [PaddlePaddle/Serving#726]
https://github.com/PaddlePaddle/Serving/blob/develop/doc/NEW_WEB_SERVICE.md

第一段
This document will take the image classification service based on the Imagenet data set as an example to introduce how to develop a new web service. The complete code can be visited at [here](https://github.com/PaddlePaddle/Serving/blob/develop/python/examples/imagenet/image_classification_service.py).

**Comment by MRXLT** [comment]
fixed in https://github.com/PaddlePaddle/Serving/pull/732
