### ISSUE TITLE
import paddle_serving_client 时报错，TypeError: __new__() got an unexpected keyword argument 'serialized_options'

### ISSUE THREAD

**Issue by qjing666** [PaddlePaddle/Serving#728]
<img width="1440" alt="截屏2020-07-08下午7 43 19" src="https://user-images.githubusercontent.com/19721227/86914678-48707f80-c153-11ea-97d9-c4ddef806386.png">

**Comment by qjing666** [comment]
protobuf版本没对上，安装3.11.3版本的protobuf后解决

**Comment by MRXLT** [comment]
fixed in https://github.com/PaddlePaddle/Serving/pull/732
