### ISSUE TITLE
如何优雅的关闭服务

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/Serving#739]
在启动paddle-serving后，如果要停止服务，目前我这边只能执行：`kill -9 进程ID`
但是在查看后台后，发现会有defunct进程出现。该如何恰当的停止服务，有这方面的建议吗，谢谢

**Comment by MRXLT** [comment]
你好，如果是直接启动的话，关闭服务时使用ctrl-c中断即可，如果是后台启动，关闭服务时需要将主进程以及子进程都kill掉，例如下图中的12099和12163进程
![image](https://user-images.githubusercontent.com/16594411/87496576-6fb0da80-c686-11ea-95e0-498b193ba0af.png)

**Comment by BeyondYourself** [comment]
这两种方式都用过，kill的时候会不会有产生僵尸进程，因为之前好多服务遇到过这样的情况

**Comment by MRXLT** [comment]
子进程都kill掉的话是不会有僵尸进程的

**Comment by 60999** [comment]
没个关闭的命令，方法吗？

**Comment by MRXLT** [comment]
> 没个关闭的命令，方法吗？

目前都是通过ctrl+c或者kill进程的方式来关闭的，请问你希望的是使用什么样的方法来关闭呢

**Comment by 60999** [comment]
命令行方式，关闭服务
