### ISSUE TITLE
 paddle_serving_server 报错

### ISSUE THREAD

**Issue by xiaomujiang** [PaddlePaddle/Serving#754]
在servering 启动服务的时候，出现了cuda找不到
PaddleDetection/serving_model# 
 export CUDA_VISIBLE_DEVICES=0
python -m paddle_serving_server_gpu.serve --model serving_model/ --thread 10 --port 9292 --gpu_ids 0
CUDA not found, please check your environment or use cpu version by "pip install paddle_serving_server"

版本如下
paddle-serving-app        0.1.1
paddle-serving-client     0.3.1
paddle-serving-server     0.3.1
paddle-serving-server-gpu 0.3.1
paddlehub                 1.6.2
paddlepaddle-gpu          1.8.1.post107
python 3.7
查看显卡如下
 nvidia-smi
Wed Jul 22 17:14:09 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.82       Driver Version: 440.82       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro RTX 4000     Off  | 00000000:5E:00.0  On |                  N/A |
| 30%   36C    P8     2W / 125W |    603MiB /  7979MiB |      2%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     27371      G   /usr/lib/xorg/Xorg                           169MiB |
|    0     28318      G   /usr/bin/gnome-shell                         199MiB |
|    0     33752      G   ...AAAAAAAAAAAACAAAAAAAAAA= --shared-files   209MiB |
|    0     36758      G   ...AAAAAAAAAAAACAAAAAAAAAA= --shared-files    22MiB |
+-----------------------------------------------------------------------------+

**Comment by barrierye** [comment]
您好 是在Serving提供的gpu镜像中启动server的吗？

**Comment by xiaomujiang** [comment]
我是参考这个https://aistudio.baidu.com/aistudio/projectdetail/643597做的，没有在GPU镜像中启动server， 是想将paddledetection产生的模型，用serving 进行启动， 但是没有启动起来，需要怎么做？

**Comment by xiaomujiang** [comment]
> 您好 是在Serving提供的gpu镜像中启动server的吗？
我是参考这个https://aistudio.baidu.com/aistudio/projectdetail/643597做的，没有在GPU镜像中启动server， 是想将paddledetection产生的模型，用serving 进行启动， 但是没有启动起来，需要怎么做？

**Comment by barrierye** [comment]
可以根据这个[文档](https://github.com/PaddlePaddle/Serving/blob/develop/doc/SAVE.md)导出Serving模型后，根据这个[文档](https://github.com/PaddlePaddle/Serving/blob/develop/doc/RUN_IN_DOCKER.md)获取Docker镜像启动服务
