### ISSUE TITLE
能有一个yolov3的demo么？？？

### ISSUE THREAD

**Issue by JiaoZiLang** [PaddlePaddle/Serving#756]
如题，yolov3用的应该还挺多的吧，求各位大大给个yolov3的demo

**Comment by JiaoZiLang** [comment]
自己参考yolov4的写预测，部署起来效果差异巨大，也没法排查调整

**Comment by guru4elephant** [comment]
https://github.com/PaddlePaddle/Serving/tree/develop/python/examples/yolov4 @JiaoZiLang

**Comment by bjjwwang** [comment]
> 自己参考yolov4的写预测，部署起来效果差异巨大，也没法排查调整

想问下现在您用的模型是从哪里来的，从PaddleDetection导出的吗
