### ISSUE TITLE
ubuntu18.04下无法执行推断报错

### ISSUE THREAD

**Issue by coder-sun** [PaddlePaddle/Serving#763]
![image](https://user-images.githubusercontent.com/25734125/88608107-8d813500-d0b3-11ea-9cfc-15ff56f0f48e.png)

环境为虚拟机ubuntu18.04，检测模块单独可以正常使用，一起使用时就会报这个错误。

**Comment by Steffy-zxf** [comment]
@coder-sun 你好！可以参考issue解决方法： https://github.com/PaddlePaddle/PaddleOCR/issues/440

**Comment by coder-sun** [comment]
> @coder-sun 你好！可以参考issue解决方法： [PaddlePaddle/PaddleOCR#440](https://github.com/PaddlePaddle/PaddleOCR/issues/440)

谢谢，已经解决，版本问题
