### ISSUE TITLE
显卡显存不释放？

### ISSUE THREAD

**Issue by sevenold** [PaddlePaddle/Serving#767]
随着调用次数的增多， 显存占用率不断增加！！！！
![image](https://user-images.githubusercontent.com/41443157/88653247-62700300-d0fe-11ea-99bf-2268781aaabf.png)
![image](https://user-images.githubusercontent.com/41443157/88653421-a105bd80-d0fe-11ea-9060-ef311752aea0.png)
显存满了后 ，就会报错
![image](https://user-images.githubusercontent.com/41443157/88653539-cdb9d500-d0fe-11ea-8f9c-afa7fccf37e8.png)
然后显存会恢复到最初的占用率
![image](https://user-images.githubusercontent.com/41443157/88653593-e0340e80-d0fe-11ea-9752-a5dcf4e33f8a.png)
需要重启服务，才可以重新开始预测！
不断反复
![image](https://user-images.githubusercontent.com/41443157/88653816-22f5e680-d0ff-11ea-8f41-27b1a0a398de.png)
使用的模型为:https://github.com/PaddlePaddle/PaddleOCR/tree/develop/deploy/pdserving

**Comment by TeslaZhao** [comment]
显存的使用量，和模型、线程数量、显存优化参数有关系。请问，服务启动命令设置了几个线程？

**Comment by sevenold** [comment]
启动命令：
```bash

 python -m paddle_serving_server_gpu.serve --model server_model/server_det/ --port 9293 --gpu_id 0
 python ocr_web_server.py

```
就是按照这个教程走的：https://github.com/PaddlePaddle/PaddleOCR/tree/develop/deploy/pdserving

模型是使用paddle_serving_app提供的模型，执行下列命令
```bash

python -m paddle_serving_app.package --get_model ocr_rec
tar -xzvf ocr_rec.tar.gz
python -m paddle_serving_app.package --get_model ocr_det
tar -xzvf ocr_det.tar.gz 

```

客户端
```python

import requests
import json
import cv2
import base64
import os, sys
import time


def cv2_to_base64(image):
    #data = cv2.imencode('.jpg', image)[1]
    return base64.b64encode(image).decode(
        'utf8')  #data.tostring()).decode('utf8')


headers = {"Content-type": "application/json"}
url = "http://127.0.0.1:9292/ocr/prediction"


test_img_dir = "imgs"
for img_file in os.listdir(test_img_dir):
    with open(os.path.join(test_img_dir, img_file), 'rb') as file:
        image_data1 = file.read()
    image = cv2_to_base64(image_data1)
    data = {"feed": [{"image": image}], "fetch": ["res"]}
    r = requests.post(url=url, headers=headers, data=json.dumps(data))
    print(r.json())


```

运行一次客户端，第一次正常，但是显存增加了不释放，第二次再运行，显存再增加，再运行就是out of memory

**Comment by MRXLT** [comment]
你好，请在server端启动的时候设置--thread 4限制server端的线程数，设置--mem_optim参数开启显存优化，应该可以解决显存不足的问题

**Comment by sevenold** [comment]
```bash
 python -m paddle_serving_server_gpu.serve --model ocr_det_model --port 9293 --gpu_id 0 --thread 4 --mem_optim
```
改成这样，效果确实比刚刚好，但是还是会报显存不足的问题，这次的显存不足应该是代码

https://github.com/PaddlePaddle/PaddleOCR/blob/develop/deploy/pdserving/ocr_web_server.py

但是我在这个代码里，设置了

```python 

ocr_service.default_rpc_service(thread_num=4)

```
但是没有找到设置--mem_optim的接口

这样设置后，还是会有显存不足的错误

@MRXLT

**Comment by MRXLT** [comment]
不好意思，目前web_service的使用方式中还未暴露mem_optim接口，我们会尽快添加

**Comment by sevenold** [comment]
启动命令
```bash
# text detection
$  python -m paddle_serving_server_gpu.serve --model server_model/server_det --port 9293 --gpu_id 0 --mem_optim --thread 4 --max_body_size 1073741824
# text recognition
$ python -m paddle_serving_server_gpu.serve --model server_model/server_rec  --port 9294 --gpu_id 0 --mem_optim --thread 4 --max_body_size 1073741824

```

部署完成后初始显存占用率
![image](https://user-images.githubusercontent.com/41443157/88782113-c7d7f880-d1bf-11ea-9ed3-8c124b1c81b7.png)
运行测试的显存占用率
![image](https://user-images.githubusercontent.com/41443157/88782726-8136ce00-d1c0-11ea-81e0-328f73c56c64.png)
闲置时显存占用率
![image](https://user-images.githubusercontent.com/41443157/88782889-b17e6c80-d1c0-11ea-8044-030aabb9330d.png)
显存还是没有释放！！！
@MRXLT

**Comment by MRXLT** [comment]
serving目前不能自动释放内存，只有关闭服务后才会释放

**Comment by EtachGu** [comment]
0.6 仍然存在显存无法释放的问题

**Comment by Juruobudong** [comment]
请问这个问题解决了嘛，是否需要升级到0.7以上

**Comment by hq0749a** [comment]
请问这个问题解决了么，serving0.9好像还是不行

**Comment by Juruobudong** [comment]
https://www.ab62.cn/article/2683.html
请问我有办法像这样对WebService当成个子进程来管理嘛，还是用https://www.ngui.cc/el/1266036.html?action=onClick，这几个对训练有用的参数？
from paddle_serving_server.web_service import WebService
