### ISSUE TITLE
请问自己在client端继承web_service类，实现自己的类去进行前置和后置处理，这样的话，serving的执行命令是什么？

### ISSUE THREAD

**Issue by jiangchao123** [PaddlePaddle/Serving#771]
如题：使用serving默认的http的服务的命令是这个：python3 -m paddle_serving_server.serve --model fm_serving_model --thread 10 --port 8696 --name fm &>std.log 2>err.log &

那么，如果我自己实现前置和后置处理，然后执行自己的web_service的命令，应该如何去写？命令里面也能指定线程数吗？

**Comment by MRXLT** [comment]
你好，可以参考这个文档来实现web_service
https://github.com/PaddlePaddle/Serving/blob/develop/doc/NEW_WEB_SERVICE.md
可以配合uwsgi来配置线程数
https://github.com/PaddlePaddle/Serving/blob/develop/doc/UWSGI_DEPLOY.md
