### ISSUE TITLE
cuda10-devel 镜像中用paddle detection导出serving可部署的模型报错

### ISSUE THREAD

**Issue by barrierye** [PaddlePaddle/Serving#772]
来自微信 @海洋
latest-cuda10-cudnn7-devel 镜像中用paddle detection导出serving可部署的模型报错
![image](https://user-images.githubusercontent.com/28446721/88753267-592e7700-d18e-11ea-8192-eb56c7c4076b.png)

**Comment by mcl-stone** [comment]
感谢，已解决，使用自己编译的docker镜像，然后使用最新的代码编译出最新版本安装，再安装paddledetection进行导出，就可以了

**Comment by barrierye** [comment]
> 感谢，已解决，使用自己编译的docker镜像，然后使用最新的代码编译出最新版本安装，再安装paddledetection进行导出，就可以了

方便说下自己编译的docker镜像是什么样的吗（dockerfile）？

**Comment by mcl-stone** [comment]
https://github.com/PaddlePaddle/Serving/blob/217e7b63de5a02bce2843f29920374afab6be0c3/tools/Dockerfile.gpu.devel
nvidia/cuda:10.1-cudnn7-devel-centos7
没记错的话是使用这个dockerfile，然后把第一行的镜像换成下面这个

**Comment by barrierye** [comment]
感谢您的回复~
