### ISSUE TITLE
文档中有一些死链

### ISSUE THREAD

**Issue by barrierye** [PaddlePaddle/Serving#774]
from 厂内 @ liyangokay
[死链.xlsx](https://github.com/PaddlePaddle/Serving/files/5001585/default.xlsx)

id | status_code | link | link_name | page | page_name | version
-- | -- | -- | -- | -- | -- | --
127389 | 404 | https://github.com/PaddlePaddle/Serving/blob/default/python/examples/grpc_impl_example/criteo_ctr_with_cube/../../../doc/CUBE_LOCAL_CN.md | 稀疏参数索引服务Cube单机版使用指南 | /home/work/paddle_repo/Serving/python/examples/grpc_impl_example/criteo_ctr_with_cube/README_CN.md | Serving | default
127397 | 404 | https://github.com/PaddlePaddle/Serving/blob/default/doc/deprecated/DESIGN.md | Design | /home/work/paddle_repo/Serving/doc/deprecated/INDEX.md | Serving | default
127398 | 404 | https://github.com/PaddlePaddle/Serving/blob/default/doc/deprecated/INSTALL.md | Installation | /home/work/paddle_repo/Serving/doc/deprecated/INDEX.md | Serving | default
127405 | 404 | https://github.com/PaddlePaddle/Serving/blob/default/doc/deprecated/BENCHMARKING.md | Benchmarking | /home/work/paddle_repo/Serving/doc/deprecated/INDEX.md | Serving | default
127406 | 404 | https://github.com/PaddlePaddle/Serving/blob/default/doc/deprecated/GPU_BENCHMARKING.md | GPU Benchmarking | /home/work/paddle_repo/Serving/doc/deprecated/INDEX.md | Serving | default
127409 | 404 | https://github.com/PaddlePaddle/Serving/blob/default/doc/deprecated/../tools/Dockerfile | CPU版本Dockerfile | /home/work/paddle_repo/Serving/doc/deprecated/DOCKER_CN.md | Serving | default
127410 | 404 | https://github.com/PaddlePaddle/Serving/blob/default/doc/deprecated/../tools/Dockerfile.gpu | GPU版本Dockerfile | /home/work/paddle_repo/Serving/doc/deprecated/DOCKER_CN.md | Serving | default
127414 | 404 | https://github.com/PaddlePaddle/Serving/blob/default/doc/deprecated/pruned-ctr-network.png | Pruned CTR prediction   network | /home/work/paddle_repo/Serving/doc/deprecated/CTR_PREDICTION.md | Serving | default
127420 | 404 | https://github.com/PaddlePaddle/Serving/blob/default/doc/deprecated/DESIGN.md | 设计文档 | /home/work/paddle_repo/Serving/doc/deprecated/CREATING.md | Serving | default
127423 | 404 | https://github.com/PaddlePaddle/Serving/blob/default/doc/deprecated/../tools/Dockerfile | CPU Version   Dockerfile | /home/work/paddle_repo/Serving/doc/deprecated/DOCKER.md | Serving | default
127424 | 404 | https://github.com/PaddlePaddle/Serving/blob/default/doc/deprecated/../tools/Dockerfile.gpu | GPU Version   Dockerfile | /home/work/paddle_repo/Serving/doc/deprecated/DOCKER.md | Serving | default
127425 | 404 | https://github.com/PaddlePaddle/Serving/blob/default/doc/deprecated/INSTALL.md | 编译安装说明 | /home/work/paddle_repo/Serving/doc/deprecated/GETTING_STARTED.md | Serving | default
127426 | 404 | https://github.com/PaddlePaddle/Serving/blob/default/doc/deprecated/../demo-client/python/text_classification.py | text_classification.py | /home/work/paddle_repo/Serving/doc/deprecated/HTTP_INTERFACE.md | Serving | default
127427 | 404 | https://github.com/PaddlePaddle/Serving/blob/default/doc/deprecated/../demo-client/php/text_classification.php | text_classification.php | /home/work/paddle_repo/Serving/doc/deprecated/HTTP_INTERFACE.md | Serving | default
127454 | 404 | https://github.com/PaddlePaddle/Serving/blob/default/doc/total:   {} | {} | /home/work/paddle_repo/Serving/doc/ABTEST_IN_PADDLE_SERVING.md | Serving | default
127455 | 404 | https://github.com/PaddlePaddle/Serving/blob/default/doc/total:   1867 | lstm | /home/work/paddle_repo/Serving/doc/ABTEST_IN_PADDLE_SERVING.md | Serving | default
127456 | 404 | https://github.com/PaddlePaddle/Serving/blob/default/doc/total:   217 | bow | /home/work/paddle_repo/Serving/doc/ABTEST_IN_PADDLE_SERVING.md | Serving | default
127465 | 404 | https://github.com/PaddlePaddle/Serving/blob/default/doc/./Distributed_Cube | Distributed Cube User   Guide | /home/work/paddle_repo/Serving/doc/CUBE_LOCAL.md | Serving | default
127511 | 404 | https://github.com/PaddlePaddle/Serving/blob/default/doc/total:   {} | {} | /home/work/paddle_repo/Serving/doc/ABTEST_IN_PADDLE_SERVING_CN.md | Serving | default
127512 | 404 | https://github.com/PaddlePaddle/Serving/blob/default/doc/total:   1867 | lstm | /home/work/paddle_repo/Serving/doc/ABTEST_IN_PADDLE_SERVING_CN.md | Serving | default
127513 | 404 | https://github.com/PaddlePaddle/Serving/blob/default/doc/total:   217 | bow | /home/work/paddle_repo/Serving/doc/ABTEST_IN_PADDLE_SERVING_CN.md | Serving | default
127519 | 404 | https://github.com/PaddlePaddle/Serving/blob/default/doc/CREATING.md | 从零开始写一个预测服务 | /home/work/paddle_repo/Serving/doc/DESIGN_CN.md | Serving | default
127530 | 404 | https://github.com/PaddlePaddle/Serving/blob/default/doc/doc/INSTALL.md | BUILD steps | /home/work/paddle_repo/Serving/doc/CONTRIBUTE.md | Serving | default
127595 | 404 | https://github.com/PaddlePaddle/Serving/blob/default/doc/分布式Cube | 稀疏参数索引服务Cube使用指南 | /home/work/paddle_repo/Serving/doc/CUBE_LOCAL_CN.md | Serving | default

**Comment by MRXLT** [comment]
fixed in https://github.com/PaddlePaddle/Serving/pull/779
