### ISSUE TITLE
No module named 'paddle_serving_client.serving_client'

### ISSUE THREAD

**Issue by chengxurensheng666** [PaddlePaddle/Serving#780]
五月份我提出过相同的issue，当时版本是0.22，现在更新成0.31后，win平台还是报这个错误
![image](https://user-images.githubusercontent.com/48110081/89420355-29223d80-d765-11ea-957a-f72eb69766e3.png)
![image](https://user-images.githubusercontent.com/48110081/89420376-32aba580-d765-11ea-9b4e-8b82a4fb4281.png)
![image](https://user-images.githubusercontent.com/48110081/89420487-5969dc00-d765-11ea-8811-4b2125ff63f7.png)

**Comment by barrierye** [comment]
您好，win平台不能使用Client。

可以换用MultiLangServer和MultiLangClient解决，参考[例子](https://github.com/PaddlePaddle/Serving/tree/develop/python/examples/grpc_impl_example/fit_a_line)

**Comment by chengxurensheng666** [comment]
我看了这个例子
![image](https://user-images.githubusercontent.com/48110081/89487840-18131400-d7d9-11ea-9c59-3dca59cb3ce6.png)
![image](https://user-images.githubusercontent.com/48110081/89487871-2a8d4d80-d7d9-11ea-8a18-8b0bab10f587.png)
我做的是rcnn目标检测 ，需要预读取一些配置文件MultiLangClient缺少load_client_config的api

**Comment by barrierye** [comment]
MultiLangClient 删除了 load_client_config 的 API，可以直接把这行删去。

**Comment by chengxurensheng666** [comment]
![image](https://user-images.githubusercontent.com/48110081/89488467-b5227c80-d7da-11ea-85a8-fe3b0cca049a.png)
那这个我从paddledetection导出的文件应该怎样读取呢

**Comment by barrierye** [comment]
> 那这个我从paddledetection导出的文件应该怎样读取呢

这个模型应该在 MultiLangServer 端读取，MultiLangClient 通过RPC方式从 MultiLangServer 获取模型文件。

MultiLangServer 的 load_model_config 接口如下所示：
```python
def load_model_config(self, server_config_paths, client_config_path=None)
```
通常情况下 `serving_server/serving_server_conf.prototxt` 与 `serving_client/serving_client_conf.prototxt` 两个文件内容是一致的，`client_config_path` 不需要设置。

**Comment by yybestw** [comment]
在windows下部署客户端需要使用multilangclient，但0.7.0版本不支持该方法，我测试后发现paddle_serving_client 0.5.0可以使用该方法，服务器端同样使用0.5.0版本的paddle_serving_server和paddle_serving_client，启动服务器端的命令为 python3 -m paddle_serving_server.serve --model serving_server --thread 10 --port 9292 --use_multilang
