### ISSUE TITLE
可以开多个线程并行的推理么？小模型在单卡上gpu显存占用比较小，gpu利用率比较低

### ISSUE THREAD

**Issue by jeshxxx** [PaddlePaddle/Serving#782]
现在是一个gpu卡部署了一个serving服务，但是gpu利用率不到30%，如果压测的话感觉就积压了，能在一个模型起多个推理线程并行跑么？

**Comment by TeslaZhao** [comment]
单个Serving进程内，所有预测任务共用同一个GPU stream，多个并发请求的GPU操作会被串行到stream内，因此不是完全并行；这样当多个请求到达时，预期会出现较为严重的排队情况。Serving支持在单张显卡上部署多个预测服务，建议的解决方案是服务端启动多个预测服务来提高资源利用率。

单卡多模型部署方法：
https://github.com/PaddlePaddle/Serving/blob/develop/doc/MULTI_SERVICE_ON_ONE_GPU_CN.md
GPU BENCHMARK：
https://github.com/PaddlePaddle/Serving/commit/7af42c0a7762f70492a77d49a92f62630e59d22f

**Comment by jeshxxx** [comment]
> 单个Serving进程内，所有预测任务共用同一个GPU stream，多个并发请求的GPU操作会被串行到stream内，因此不是完全并行；这样当多个请求到达时，预期会出现较为严重的排队情况。Serving支持在单张显卡上部署多个预测服务，建议的解决方案是服务端启动多个预测服务来提高资源利用率。
> 
> 单卡多模型部署方法：
> https://github.com/PaddlePaddle/Serving/blob/develop/doc/MULTI_SERVICE_ON_ONE_GPU_CN.md
> GPU BENCHMARK：
> [7af42c0](https://github.com/PaddlePaddle/Serving/commit/7af42c0a7762f70492a77d49a92f62630e59d22f)

单卡多模型，每个模型之间也是串行执行的吧？有办法做到每个模型服务创建一个GPU stream么？

**Comment by TeslaZhao** [comment]
单卡多模型，每个模型之间是串行执行的，目前Serving不支持每个模型服务创建一个GPU stream。底层预测库PaddlePredictor已经支持多线程独立GPU流，不再共用。后续Serving版本可以支持该需求。

**Comment by jeshxxx** [comment]
好的，多谢，PaddlePredictor支持多线程独立GPU流的情况，有文档介绍么？如果我直接依赖PaddlePredictor起个服务

**Comment by TeslaZhao** [comment]
目前没有文档，在paddle devlop版本中，还未正式发布。

**Comment by jeshxxx** [comment]
方便帮忙看一下是哪个commit的修改么？我可以直接拉develop的代码编译一个inference lib来用么？

**Comment by TeslaZhao** [comment]
https://github.com/PaddlePaddle/Paddle/pull/24046

**Comment by jeshxxx** [comment]
多谢多谢
