### ISSUE TITLE
使用PaddleHub Fine-tune 的模型部署问题

### ISSUE THREAD

**Issue by iceriver97** [PaddlePaddle/Serving#792]
使用PaddleHub Fine-tune 的模型应该如何部署呢？HubServing 好像不支持这种模型

**Comment by Steffy-zxf** [comment]
@iceriver97 你好，可以参考issue https://github.com/PaddlePaddle/PaddleHub/issues/816

关于PaddleHub的issue可以在PaddleHub 提issue：https://github.com/PaddlePaddle/PaddleHub/issues
