### ISSUE TITLE
强烈建议增加用PaddleHub作精调的模型部署的例子。

### ISSUE THREAD

**Issue by fisher030712** [PaddlePaddle/Serving#800]
被PaddleServing难倒了！
不知道该如何确定自己的模型的输入和输出参数，细节都被Paddlehub隐藏了。
大佬们是如何知道模型的输入输出的呢？还是说，PaddleHub公开的那几个模型，都是固定的输入输出？在哪能查到呢？

**Comment by fisher030712** [comment]
盼大佬们尽快上来指导一下，研究2天了，没有思路。

**Comment by fisher030712** [comment]
每个模型，根本就没有一个明确的输入输出说明，训练的时候，就是给一个reader，也不涉及到模型的输入啊。

**Comment by bjjwwang** [comment]
> 大佬们是如何知道模型的输入输出的呢？还是说，PaddleHub公开的那几个模型，都是固定的输入输出？在哪能查到呢？

想问下您是要部署什么样的例子，我们也fine-tune做一下试验
