### ISSUE TITLE
【疑似bug】框架内部会自动给用户输入升维？

### ISSUE THREAD

**Issue by xixiaoyao** [PaddlePaddle/Serving#803]
如图，client端的feed dict为如下元素和形状：
![image](https://user-images.githubusercontent.com/24541791/90550473-9486f900-e1c2-11ea-8232-56e6bca5bf2c.png)

即包含两个样本的bert输入。

但是如图所示，

![image](https://user-images.githubusercontent.com/24541791/90550737-ea5ba100-e1c2-11ea-90b1-3f66df7836a3.png)

server端收到输入并经过fluid.embedding之后，本应该得到[2,9,1024]（经过了1024维度的embedding），结果莫名其妙的变成了[1,2,9,1024]，前面不知道从哪里多了一个size为1的维度。这是paddle serving框架内部自动添加的维度吗？

**Comment by xixiaoyao** [comment]
我发现仅仅是将feed中的元素从numpy array变成python list，报错都变了。。。tolist之后变成这样的报错了

![image](https://user-images.githubusercontent.com/24541791/90553099-67d4e080-e1c6-11ea-8b3f-9a6daa4d6b32.png)

client对feed输入的处理策略到底是怎样的呢？

**Comment by bjjwwang** [comment]
目前一个batch需要做成list [dict]的形式，每个dict是一条样本。否则做成一条样本目前会自动加batch维度，这部分接口在修改，预计下周提测。
