### ISSUE TITLE
pyreader 读入数据,并未使用dataset，如何发布服务

### ISSUE THREAD

**Issue by iceriver97** [PaddlePaddle/Serving#805]
我该如何将自定义的 Variable：test 绑定到模型中？我看示例是采用的dataset.set_use_var(),但我并未使用dataset，而是使用的pyreader 读入的数据；下面代码不做绑定，直接这样保存模型是不是错误的做法？
```
test = fluid.layers.data(name="test", shape=[1], dtype="int64", lod_level=1)
prediction = predict_wrapper_serving(reader, exe, test_prog, test_pyreader, graph_vars,'final', 'final')
serving_io.save_model("RE_model","RE_client_conf", {"text": test}, {"prediction": prediction},fluid.default_main_program())
```
我如果将自定义的test变量传入网络，应该怎样修改呢？网络之前是使用pyreader读入数据的；代码如下：
```
(src_ids, sent_ids, pos_ids, task_ids, input_mask, labels, seq_lens,
     example_index, tok_to_orig_start_index,
     tok_to_orig_end_index) = fluid.layers.read_file(pyreader)
```
@wangjiawei04  使用 pyreader  异步读取数据的模型是否不能发布serving？有没有类似的例子？

**Comment by iceriver97** [comment]
@wangjiawei04

**Comment by iceriver97** [comment]
@wangjiawei04 我是能将read_file返回的变量列表作为Serving模型的输入变量列表，然后修改 decorate_tensor_provider() 接收客户端发送的 http 请求中的 json 数据来保存推理模型？我该怎样接收json的数据呢？谢谢

**Comment by iceriver97** [comment]
@wangjiawei04  我能否将 Seving 得到的输入先存到文件中，然后再调用模型进行预测？

**Comment by iceriver97** [comment]
@TeslaZhao

**Comment by bjjwwang** [comment]
> 我该如何将自定义的 Variable：test 绑定到模型中？我看示例是采用的dataset.set_use_var(),但我并未使用dataset，而是使用的pyreader 读入的数据；下面代码不做绑定，直接这样保存模型是不是错误的做法？
> 
> ```
> test = fluid.layers.data(name="test", shape=[1], dtype="int64", lod_level=1)
> prediction = predict_wrapper_serving(reader, exe, test_prog, test_pyreader, graph_vars,'final', 'final')
> serving_io.save_model("RE_model","RE_client_conf", {"text": test}, {"prediction": prediction},fluid.default_main_program())
> ```
> 
> 我如果将自定义的test变量传入网络，应该怎样修改呢？网络之前是使用pyreader读入数据的；代码如下：
> 
> ```
> (src_ids, sent_ids, pos_ids, task_ids, input_mask, labels, seq_lens,
>      example_index, tok_to_orig_start_index,
>      tok_to_orig_end_index) = fluid.layers.read_file(pyreader)
> ```
> 
> @wangjiawei04 使用 pyreader 异步读取数据的模型是否不能发布serving？有没有类似的例子？

这个操作试验过吗 有报什么错误吗

**Comment by bjjwwang** [comment]
> @wangjiawei04 我是能将read_file返回的变量列表作为Serving模型的输入变量列表，然后修改 decorate_tensor_provider() 接收客户端发送的 http 请求中的 json 数据来保存推理模型？我该怎样接收json的数据呢？谢谢

如果是json的话 推荐用web service的方法，但感觉这个需求没看很明白 方便多贴一些代码解释一下吗

**Comment by bjjwwang** [comment]
> @wangjiawei04 我能否将 Seving 得到的输入先存到文件中，然后再调用模型进行预测？

为什么需要先保存成文件。 
还是因为pyreader吗？
pyreader op及输入var是不能放进serving模型的。保存应从pyreader的输出开始。

**Comment by iceriver97** [comment]
@wangjiawei04  谢谢。我能否这样写？在模型的定义中，我首先定义pyreader，然后定义一个变量从客户端接收数据，并将该数据存入文件中，之后再用pyreader读取，代码如下：
```
def create_model(args, pyreader_name, ernie_config):
    pyreader = fluid.layers.py_reader(
        capacity=50,
        shapes=[[-1, args.max_seq_len, 1], [-1, args.max_seq_len, 1],
                [-1, args.max_seq_len, 1], [-1, args.max_seq_len, 1],
                [-1, args.max_seq_len, 1],
                [-1, args.max_seq_len, args.num_labels], [-1, 1], [-1, 1],
                [-1, args.max_seq_len, 1], [-1, args.max_seq_len, 1]],
        dtypes=[
            'int64', 'int64', 'int64', 'int64', 'float32', 'float32', 'int64',
            'int64', 'int64', 'int64'
        ],
        lod_levels=[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        name=pyreader_name,
        use_double_buffer=True)
    str_text  = fluid.layers.data(name="text", shape=[1], dtype="int64", lod_level=1)
    res = fluid.layers.is_empty(str_text)
    if  res is False:
         recoveredbytes = str_text.to_string(True, True)
         recoveredstring = recoveredbytes.decode('utf-8')
         files = open('pre_save.json', 'w')
         files.write(recoveredstring+'\n')
         files.close
    
```
我有个疑问，PP该如何判断变量是否已经被赋值呢？按照上面的写法，得到的res是个变量而不是布尔值，我该怎么获取res的布尔值；
我在模型中做这些操作能实现我使用 str_text接收数据的目的吗？如果我把这些代码放在模型外，我是不是只能将接收到的变量存入文件才能使用pyreader?
我在交流群中得知：Serving模型保存时指定的输入变量只能直接传给模型，我这样间接的方式是不是不可行？
因为以上疑惑，我不清楚使用pyreader的话还能否使用serving，所以想看一下例子；
非常感谢您的解答！

**Comment by iceriver97** [comment]
@wangjiawei04
