### ISSUE TITLE
CUDA10 镜像无法按Run in docker文档跑pypi上GPU版本的例子

### ISSUE THREAD

**Issue by barrierye** [PaddlePaddle/Serving#809]
from 微信用户 @ Duncan

**Comment by barrierye** [comment]
cuda10.0镜像是最近开发的，对应python whl还没有发布（pypi上的python whl是cuda9.0），您可以用LATEST_PACKAGES页面的0.3.2版本的whl包运行：https://github.com/PaddlePaddle/Serving/blob/develop/doc/LATEST_PACKAGES.md#gpu-server

0.3.2版本发布后，需要对Run in docker文档进行更新。

**Comment by TeslaZhao** [comment]
已更新
