### ISSUE TITLE
windows下部署serving问题

### ISSUE THREAD

**Issue by liangruofei** [PaddlePaddle/Serving#815]
### 我是在win10用anaconda安装了虚拟的paddle环境，然后把相应的包都安装了；在linux服务器端跑都没问题，运行程序如下：
`from paddle_serving_client import Client
from paddle_serving_app.reader import *
import numpy as np

preprocess = Sequential([
    File2Image(), BGR2RGB(), Div(255.0),
    Normalize([0.385, 0.386, 0.375], [0.162, 0.159, 0.159], False),
    Resize(1000, 1500), Transpose((2, 0, 1)), PadStride(32)
])
client = Client()
client.load_client_config("/home/aistudio/PaddleDetection-0.4/output/serving_model/cascade_rcnn_dcn_r50_vd_fpn_3x_server_side/serving_client/serving_client_conf.prototxt")
client.connect(['127.0.0.1:9292'])
im = preprocess('/home/aistudio/work/A/test014.jpg')
fetch_map = client.predict(feed={"image": im, "im_info": np.array(list(im.shape[1:]) + [1.0]),
                                 "im_shape": np.array(list(im.shape[1:]) + [1.0])}, fetch=["multiclass_nms_0.tmp_0"])
fetch_map["image"] = '/home/aistudio/work/test.jpg'
print (fetch_map)`
### ，但是在window下运行提示如下：
(paddlepaddle) D:\Desktop\serving>python test2.py
Traceback (most recent call last):
  File "test2.py", line 10, in <module>
    client = Client()
  File "D:\Anaconda3\envs\paddlepaddle\lib\site-packages\paddle_serving_client\__init__.py", line 136, in __init__
    from .serving_client import PredictorRes
ModuleNotFoundError: No module named 'paddle_serving_client.serving_client'
### 然后，我根据你们提供的新平台支持修改了程序如下：
`from paddle_serving_client import MultiLangClient as Client
from paddle_serving_app.reader import *
import numpy as np

preprocess = Sequential([
    File2Image(), BGR2RGB(), Div(255.0),
    Normalize([0.385, 0.386, 0.375], [0.162, 0.159, 0.159], False),
    Resize(1000, 1500), Transpose((2, 0, 1)), PadStride(32)
])
client = Client()
client.load_client_config("serving_client/serving_client_conf.prototxt")
client.connect(['127.0.0.1:9292'])
im = preprocess('/home/aistudio/work/A/test001.jpg')
fetch_map = client.predict(feed={"image": im, "im_info": np.array(list(im.shape[1:]) + [1.0]),
                                 "im_shape": np.array(list(im.shape[1:]) + [1.0])}, fetch=["multiclass_nms_0.tmp_0"])
fetch_map["image"] = '/home/aistudio/work/test001.jpg'
print (fetch_map)`
### 报错如下：
`(paddlepaddle) D:\Desktop\serving>python test3.py
Traceback (most recent call last):
  File "test3.py", line 12, in <module>
    client.load_client_config("serving_client/serving_client_conf.prototxt")
AttributeError: 'MultiLangClient' object has no attribute 'load_client_config'`

**Comment by barrierye** [comment]
MultiLangClient 去除了 load_client_config，删去该条语句即可（同时Server端要使用MultiLangServer）

**Comment by liangruofei** [comment]
好的，我试下，另外有没有server端的这块语法使用说明啊，不知道具体API是啥意思，咋用的
在2020年8月27日 18:20，barriery<notifications@github.com> 写道：

MultiLangClient 去除了 load_client_config，删去该条语句即可（同时Server端要使用MultiLangServer）

**Comment by barrierye** [comment]
> 好的，我试下，另外有没有server端的这块语法使用说明啊，不知道具体API是啥意思

server 端API与原来的一致（把Server替换成MultiLangServer），参考这个例子：https://github.com/PaddlePaddle/Serving/blob/develop/python/examples/grpc_impl_example/fit_a_line/README_CN.md

**Comment by liangruofei** [comment]
根据您给的方法修改后，报错： 😅        

(paddlepaddle) D:\Desktop\serving>python test3.py
Traceback (most recent call last):
  File "test3.py", line 13, in <module>
    client.connect(['127.0.0.1:9292'])
  File "D:\Anaconda3\envs\paddlepaddle\lib\site-packages\paddle_serving_client\__init__.py", line 432, in connect
    resp = self.stub_.GetClientConfig(get_client_config_req)
  File "D:\Anaconda3\envs\paddlepaddle\lib\site-packages\grpc\_channel.py", line 826, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "D:\Anaconda3\envs\paddlepaddle\lib\site-packages\grpc\_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "connections to all backends failing"
        debug_error_string = "{"created":"@1598578864.166000000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":4090,"referenced_errors":[{"created":"@1598578864.166000000","description":"connections to all backends failing","file":"src/core/ext/filters/client_channel/lb_policy/round_robin/round_robin.cc","file_line":335,"grpc_status":14}]}"



在2020年8月27日 18:57，barriery<notifications@github.com> 写道：

好的，我试下，另外有没有server端的这块语法使用说明啊，不知道具体API是啥意思

server 端API与原来的一致（把Server替换成MultiLangServer），参考这个例子：https://github.com/PaddlePaddle/Serving/blob/develop/python/examples/grpc_impl_example/fit_a_line/README_CN.md

**Comment by barrierye** [comment]
看下对应端口有没有问题，另外如果有网络代理的话可能需要先关掉代理

**Comment by liangruofei** [comment]
检查了端口，关了代理，关了杀毒软件还是报错😅


(paddlepaddle) D:\Desktop\serving>python test3.py
Traceback (most recent call last):
  File "test3.py", line 13, in <module>
    client.connect(['127.0.0.1:9898'])
  File "D:\Anaconda3\envs\paddlepaddle\lib\site-packages\paddle_serving_client\__init__.py", line 432, in connect
    resp = self.stub_.GetClientConfig(get_client_config_req)
  File "D:\Anaconda3\envs\paddlepaddle\lib\site-packages\grpc\_channel.py", line 826, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "D:\Anaconda3\envs\paddlepaddle\lib\site-packages\grpc\_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "connections to all backends failing"
        debug_error_string = "{"created":"@1598583685.695000000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":4090,"referenced_errors":[{"created":"@1598583685.695000000","description":"connections to all backends failing","file":"src/core/ext/filters/client_channel/lb_policy/round_robin/round_robin.cc","file_line":335,"grpc_status":14}]}"
>


在2020年8月28日 10:23，barriery<notifications@github.com> 写道：

看下对应端口有没有问题，另外如果有网络代理的话可能需要先关掉代理

**Comment by barrierye** [comment]
可以描述下具体如何运行的吗？（运行步骤、文件等）

参考步骤：
```shell
python -m paddle_serving_server.serve --model <MODEL> --port <PORT> --use_multilang # multilang-server
python <client.py> # multilang-client
```

**Comment by liangruofei** [comment]
我写了个文档，还麻烦给看下


在2020年8月28日 11:12，barriery<notifications@github.com> 写道：

可以描述下具体如何运行的吗？（运行步骤、文件等）

参考步骤：

python -m paddle_serving_server.serve --model <MODEL> --port <PORT> --use_multilang # multilang-server

python <client.py># multilang-client

**Comment by barrierye** [comment]
> 我写了个文档，还麻烦给看下

我这边好像没收到您的文档，可以重发下吗

**Comment by liangruofei** [comment]
重发了


在2020年8月28日 12:29，barriery<notifications@github.com> 写道：

我写了个文档，还麻烦给看下

我这边好像没收到您的文档，可以重发下吗

**Comment by barrierye** [comment]
还是没收到...您可能发到notifications@github.com 了。
方便直接放在issue上吗

**Comment by liangruofei** [comment]
## 一、Linux-rpc连接-linux成功：

`1、pip install -U paddle_serving_app-0.1.0-py3-none-any.whl  paddle_serving_client-0.3.0-cp37-none-manylinux1_x86_64.whl  paddle_serving_server_gpu-0.3.0-py3-none-any.whl`
### 2、启动客户端

`LD_LIBRARY_PATH=/home/aistudio/work/serving/env/cuda-9.0/lib64:$LD_LIBRARY_PATH && python -m paddle_serving_server_gpu.serve --thread 10 --model serving_server --port 9292 --gpu_id 0`
### 3、服务的连接
`from paddle_serving_client import Client
from paddle_serving_app.reader import *
import numpy as np

preprocess = Sequential([
    File2Image(), BGR2RGB(), Div(255.0),
    Normalize([0.385, 0.386, 0.375], [0.162, 0.159, 0.159], False),
    Resize(1000, 1500), Transpose((2, 0, 1)), PadStride(32)
])
client = Client()
client.load_client_config("/home/aistudio/PaddleDetection-0.4/output/serving_model/cascade_rcnn_dcn_r50_vd_fpn_3x_server_side/serving_client/serving_client_conf.prototxt")
client.connect(['127.0.0.1:9292'])
im = preprocess('/home/aistudio/work/A/test014.jpg')
fetch_map = client.predict(feed={"image": im, "im_info": np.array(list(im.shape[1:]) + [1.0]),
                                 "im_shape": np.array(list(im.shape[1:]) + [1.0])}, fetch=["multiclass_nms_0.tmp_0"])
fetch_map["image"] = '/home/aistudio/test.jpg'
print (fetch_map)
以上是没有问题的：输出：
{'multiclass_nms_0.tmp_0': array([[  1.       ,   0.9599179, 695.74994  , 253.60997  , 755.7464   ,276.15915  ]], dtype=float32), 'image': '/home/aistudio/test.jpg'}
`
## 二、windows-rpc连接-linux失败：
Linux还是上面的安装，
在windows下进行了
Anaconda安装paddle，paddle_serving_app-0.1.0-py3-none-any.whl，paddle_serving_client-0.3.1-cp37-none-any.whl，paddle_serving_server_gpu-0.3.0-py3-none-any.whl。
然后python test.py

`#from paddle_serving_client import Client
from paddle_serving_client import MultiLangClient as Client
from paddle_serving_app.reader import *
import numpy as np

preprocess = Sequential([
    File2Image(), BGR2RGB(), Div(255.0),
    Normalize([0.385, 0.386, 0.375], [0.162, 0.159, 0.159], False),
    Resize(1000, 1500), Transpose((2, 0, 1)), PadStride(32)
])
client = Client()
#client.load_client_config("serving_client/serving_client_conf.prototxt")
#client.connect(['127.0.0.1'])
client.connect(['169.254.220.108'])

im = preprocess('D:\Desktop\serving\pic\1.jpg')
fetch_map = client.predict(feed={"image": im, "im_info": np.array(list(im.shape[1:]) + [1.0]),
                                 "im_shape": np.array(list(im.shape[1:]) + [1.0])}, fetch=["multiclass_nms_0.tmp_0"])
fetch_map["image"] = 'D:\Desktop\serving\pic\test.jpg'
print (fetch_map)`
出现问题

`(paddlepaddle) D:\Desktop\serving>python test3.py
E0828 12:22:14.866000000 10500 src/core/ext/filters/client_channel/parse_address.cc:97] no port given for ipv4 scheme
E0828 12:22:14.870000000 10500 src/core/lib/surface/channel.cc:77] channel stack builder failed: {"created":"@1598588534.870000000","description":"the target uri is not valid.","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":1683}
Traceback (most recent call last):
  File "test3.py", line 14, in <module>
    client.connect(['169.254.220.108'])
  File "D:\Anaconda3\envs\paddlepaddle\lib\site-packages\paddle_serving_client\__init__.py", line 432, in connect
    resp = self.stub_.GetClientConfig(get_client_config_req)
  File "D:\Anaconda3\envs\paddlepaddle\lib\site-packages\grpc\_channel.py", line 826, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "D:\Anaconda3\envs\paddlepaddle\lib\site-packages\grpc\_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "lame client channel"
        debug_error_string = "{"created":"@1598588534.879000000","description":"lame client channel","file":"src/core/lib/surface/lame_client.cc","file_line":93}"
>`

**Comment by barrierye** [comment]
启动Server的命令行需要调整下，您用的
```
python -m paddle_serving_server_gpu.serve --thread 10 --model serving_server --port 9292 --gpu_id 0
```
是基于Server class启动的，而使用MultiLangServer class需要再加上`--use_multilang`参数：
```
python -m paddle_serving_server_gpu.serve --thread 10 --model serving_server --port 9292 --gpu_id 0 --use_multilang
```

**Comment by barrierye** [comment]
> client.connect(['169.254.220.108'])

同时，您的endpoint不正确，需要添加相应的端口号

**Comment by liangruofei** [comment]
收到，马上修改试下，谢谢




| |
梁若飞
邮箱：liangruofeinuc@163.com
|

签名由 网易邮箱大师 定制

在2020年08月28日 12:50，barriery 写道：

client.connect(['169.254.220.108'])

同时，您的endpoint不正确，需要添加相应的端口号

**Comment by liangruofei** [comment]
还是不对，
##1 、服务端
按你说的报错如下
`aistudio@jupyter-282556-682889:~/PaddleDetection-0.4/output/serving_model/cascade_rcnn_dcn_r50_vd_fpn_3x_server_side$ python -m paddle_serving_server_gpu.serve --thread 10 --model serving_server --port 9292 --gpu_id 0 --use_multilang
usage: serve [-h] [--thread THREAD] [--model MODEL] [--port PORT] [--workdir WORKDIR] [--device DEVICE] [--gpu_ids GPU_IDS] [--name NAME] [--mem_optim] [--ir_optim]
             [--max_body_size MAX_BODY_SIZE]
serve: error: unrecognized arguments: --use_multilang`

## 我本地的ip如下：
`以太网适配器 VMware Network Adapter VMnet1:

   连接特定的 DNS 后缀 . . . . . . . :
   本地链接 IPv6 地址. . . . . . . . : fe80::1c95:19cd:4368:d077%14
   自动配置 IPv4 地址  . . . . . . . : 169.254.208.119
   子网掩码  . . . . . . . . . . . . : 255.255.0.0
   默认网关. . . . . . . . . . . . . :

以太网适配器 VMware Network Adapter VMnet8:

   连接特定的 DNS 后缀 . . . . . . . :
   本地链接 IPv6 地址. . . . . . . . : fe80::b801:a56b:2550:dc6c%20
   自动配置 IPv4 地址  . . . . . . . : 169.254.220.108
   子网掩码  . . . . . . . . . . . . : 255.255.0.0
   默认网关. . . . . . . . . . . . . :

无线局域网适配器 WLAN:

   连接特定的 DNS 后缀 . . . . . . . :
   本地链接 IPv6 地址. . . . . . . . : fe80::f828:9593:adb6:7468%2
   IPv4 地址 . . . . . . . . . . . . : 10.0.2.10
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   默认网关. . . . . . . . . . . . . : 10.0.2.2`

我更改程序中的
`client.connect(['10.0.2.10:9292'])`，
仍然报错如下：
`Traceback (most recent call last):
  File "test3.py", line 15, in <module>
    client.connect(['10.0.2.10:9292'])
  File "D:\Anaconda3\envs\paddlepaddle\lib\site-packages\paddle_serving_client\__init__.py", line 432, in connect
    resp = self.stub_.GetClientConfig(get_client_config_req)
  File "D:\Anaconda3\envs\paddlepaddle\lib\site-packages\grpc\_channel.py", line 826, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "D:\Anaconda3\envs\paddlepaddle\lib\site-packages\grpc\_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "connections to all backends failing"
        debug_error_string = "{"created":"@1598593429.272000000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":4090,"referenced_errors":[{"created":"@1598593429.272000000","description":"connections to all backends failing","file":"src/core/ext/filters/client_channel/lb_policy/round_robin/round_robin.cc","file_line":335,"grpc_status":14}]}"
>`

**Comment by barrierye** [comment]
应该是包的版本不对，0.3.0好像还没加入MultiLangServer/MultiLangClient，建议从这个[文档](https://github.com/PaddlePaddle/Serving/blob/develop/doc/LATEST_PACKAGES.md)中下载最新的包更新下paddle-sering-server-gpu 和 paddle-serving-client

**Comment by liangruofei** [comment]
还是报错，我本地window10 ，cuda10，paddle1.8
### 1、我安装  paddle_serving_app-0.1.0-py3-none-any.whl  报错如下
`(paddlepaddle) D:\Desktop\serving>python test3.py
Traceback (most recent call last):
  File "test3.py", line 15, in <module>
    client.connect(['172.20.10.4:9292'])
  File "D:\Anaconda3\envs\paddlepaddle\lib\site-packages\paddle_serving_client\__init__.py", line 433, in connect
    resp = self.stub_.GetClientConfig(get_client_config_req)
  File "D:\Anaconda3\envs\paddlepaddle\lib\site-packages\grpc\_channel.py", line 826, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "D:\Anaconda3\envs\paddlepaddle\lib\site-packages\grpc\_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "connections to all backends failing"
        debug_error_string = "{"created":"@1598597828.159000000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":4090,"referenced_errors":[{"created":"@1598597828.159000000","description":"connections to all backends failing","file":"src/core/ext/filters/client_channel/lb_policy/round_robin/round_robin.cc","file_line":335,"grpc_status":14}]}"
>`

### 当我 安装 paddle_serving_app-0.1.2-py3-none-any.whl 报错如下
`(paddlepaddle) D:\Desktop\serving>python test3.py
Traceback (most recent call last):
  File "test3.py", line 3, in <module>
    from paddle_serving_app.reader import *
  File "D:\Anaconda3\envs\paddlepaddle\lib\site-packages\paddle_serving_app\reader\__init__.py", line 15, in <module>
    from .image_reader import ImageReader, File2Image, URL2Image, Sequential, Normalize
  File "D:\Anaconda3\envs\paddlepaddle\lib\site-packages\paddle_serving_app\reader\image_reader.py", line 24, in <module>
    from shapely.geometry import Polygon
  File "D:\Anaconda3\envs\paddlepaddle\lib\site-packages\shapely\geometry\__init__.py", line 4, in <module>
    from .base import CAP_STYLE, JOIN_STYLE
  File "D:\Anaconda3\envs\paddlepaddle\lib\site-packages\shapely\geometry\base.py", line 19, in <module>
    from shapely.coords import CoordinateSequence
  File "D:\Anaconda3\envs\paddlepaddle\lib\site-packages\shapely\coords.py", line 8, in <module>
    from shapely.geos import lgeos
  File "D:\Anaconda3\envs\paddlepaddle\lib\site-packages\shapely\geos.py", line 154, in <module>
    _lgeos = CDLL(os.path.join(sys.prefix, 'Library', 'bin', 'geos_c.dll'))
  File "D:\Anaconda3\envs\paddlepaddle\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] 找不到指定的模块。`

### 另外对于ip ，我用的无线
本地ip 
`以太网适配器 VMware Network Adapter VMnet1:

   连接特定的 DNS 后缀 . . . . . . . :
   本地链接 IPv6 地址. . . . . . . . : fe80::1c95:19cd:4368:d077%14
   自动配置 IPv4 地址  . . . . . . . : 169.254.208.119
   子网掩码  . . . . . . . . . . . . : 255.255.0.0
   默认网关. . . . . . . . . . . . . :

以太网适配器 VMware Network Adapter VMnet8:

   连接特定的 DNS 后缀 . . . . . . . :
   本地链接 IPv6 地址. . . . . . . . : fe80::b801:a56b:2550:dc6c%20
   自动配置 IPv4 地址  . . . . . . . : 169.254.220.108
   子网掩码  . . . . . . . . . . . . : 255.255.0.0
   默认网关. . . . . . . . . . . . . :

无线局域网适配器 WLAN:

   连接特定的 DNS 后缀 . . . . . . . :
   IPv6 地址 . . . . . . . . . . . . : 2409:8900:1a41:993b:f828:9593:adb6:7468
   临时 IPv6 地址. . . . . . . . . . : 2409:8900:1a41:993b:f86e:3996:bd05:b91
   本地链接 IPv6 地址. . . . . . . . : fe80::f828:9593:adb6:7468%2
   IPv4 地址 . . . . . . . . . . . . : 172.20.10.4
   子网掩码  . . . . . . . . . . . . : 255.255.255.240
   默认网关. . . . . . . . . . . . . : fe80::e5:18bd:583f:39b4%2
                                       172.20.10.1`

我的程序写成这样 没问题把
`from paddle_serving_client import MultiLangClient as Client
from paddle_serving_app.reader import *
import numpy as np

preprocess = Sequential([
    File2Image(), BGR2RGB(), Div(255.0),
    Normalize([0.385, 0.386, 0.375], [0.162, 0.159, 0.159], False),
    Resize(1000, 1500), Transpose((2, 0, 1)), PadStride(32)
])
client = Client()

client.connect(['172.20.10.4:9292'])

im = preprocess('D:\Desktop\serving\pic\1.jpg')
fetch_map = client.predict(feed={"image": im, "im_info": np.array(list(im.shape[1:]) + [1.0]),
                                 "im_shape": np.array(list(im.shape[1:]) + [1.0])}, fetch=["multiclass_nms_0.tmp_0"])
fetch_map["image"] = 'D:\Desktop\serving\pic\test.jpg'
print (fetch_map)`

**Comment by barrierye** [comment]
> 当我 安装 paddle_serving_app-0.1.2-py3-none-any.whl 报错如下
(paddlepaddle) D:\Desktop\serving>python test3.py Traceback (most recent call last): File "test3.py", line 3, in <module> from paddle_serving_app.reader import * File "D:\Anaconda3\envs\paddlepaddle\lib\site-packages\paddle_serving_app\reader\__init__.py", line 15, in <module> from .image_reader import ImageReader, File2Image, URL2Image, Sequential, Normalize File "D:\Anaconda3\envs\paddlepaddle\lib\site-packages\paddle_serving_app\reader\image_reader.py", line 24, in <module> from shapely.geometry import Polygon File "D:\Anaconda3\envs\paddlepaddle\lib\site-packages\shapely\geometry\__init__.py", line 4, in <module> from .base import CAP_STYLE, JOIN_STYLE File "D:\Anaconda3\envs\paddlepaddle\lib\site-packages\shapely\geometry\base.py", line 19, in <module> from shapely.coords import CoordinateSequence File "D:\Anaconda3\envs\paddlepaddle\lib\site-packages\shapely\coords.py", line 8, in <module> from shapely.geos import lgeos File "D:\Anaconda3\envs\paddlepaddle\lib\site-packages\shapely\geos.py", line 154, in <module> _lgeos = CDLL(os.path.join(sys.prefix, 'Library', 'bin', 'geos_c.dll')) File "D:\Anaconda3\envs\paddlepaddle\lib\ctypes\__init__.py", line 364, in __init__ self._handle = _dlopen(self._name, mode) OSError: [WinError 126] 找不到指定的模块。

这个是第三方库shapely不兼容更新，需要重装下shapely：
```shell
pip install shapely==1.7.0 -U # 确保装到对应的python版本中
```

另外，Server端有什么报错信息吗？

**Comment by liangruofei** [comment]
版本没问题了，linux端没问题。windows10调用还是不对
(paddlepaddle) D:\Desktop\serving>python test3.py
Traceback (most recent call last):
  File "test3.py", line 15, in <module>
    client.connect(['172.20.10.4:9292'])
  File "D:\Anaconda3\envs\paddlepaddle\lib\site-packages\paddle_serving_client\__init__.py", line 433, in connect
    resp = self.stub_.GetClientConfig(get_client_config_req)
  File "D:\Anaconda3\envs\paddlepaddle\lib\site-packages\grpc\_channel.py", line 826, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "D:\Anaconda3\envs\paddlepaddle\lib\site-packages\grpc\_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "connections to all backends failing"
        debug_error_string = "{"created":"@1598599777.446000000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":4090,"referenced_errors":[{"created":"@1598599777.446000000","description":"connections to all backends failing","file":"src/core/ext/filters/client_channel/lb_policy/round_robin/round_robin.cc","file_line":335,"grpc_status":14}]}"
>
在2020年8月28日 15:12，barriery<notifications@github.com> 写道：

当我 安装 paddle_serving_app-0.1.2-py3-none-any.whl 报错如下
(paddlepaddle) D:\Desktop\serving>python test3.py Traceback (most recent call last): File "test3.py", line 3, in from paddle_serving_app.reader import * File "D:\Anaconda3\envs\paddlepaddle\lib\site-packages\paddle_serving_app\reader_init_.py", line 15, in from .image_reader import ImageReader, File2Image, URL2Image, Sequential, Normalize File "D:\Anaconda3\envs\paddlepaddle\lib\site-packages\paddle_serving_app\reader\image_reader.py", line 24, in from shapely.geometry import Polygon File "D:\Anaconda3\envs\paddlepaddle\lib\site-packages\shapely\geometry_init_.py", line 4, in from .base import CAP_STYLE, JOIN_STYLE File "D:\Anaconda3\envs\paddlepaddle\lib\site-packages\shapely\geometry\base.py", line 19, in from shapely.coords import CoordinateSequence File "D:\Anaconda3\envs\paddlepaddle\lib\site-packages\shapely\coords.py", line 8, in from shapely.geos import lgeos File "D:\Anaconda3\envs\paddlepaddle\lib\site-packages\shapely\geos.py", line 154, in lgeos = CDLL(os.path.join(sys.prefix, 'Library', 'bin', 'geos_c.dll')) File "D:\Anaconda3\envs\paddlepaddle\lib\ctypes_init.py", line 364, in init self._handle = _dlopen(self._name, mode) OSError: [WinError 126] 找不到指定的模块。

这个是第三方库shapely不兼容更新，需要重装下shapely：

pip install shapely==1.7.0 -U # 确保装到对应的python版本中

另外，Server端有什么报错信息吗？

**Comment by TeslaZhao** [comment]
status = StatusCode.UNAVAILABLE
details = "connections to all backends failing"

是IP/Port设置不正确，linux是server，windows是client，请重新确认下server端的出口IP/Port
