### ISSUE TITLE
centos中利用pip安装后，出现启动项目cuda找不到的情况。

### ISSUE THREAD

**Issue by natureLanguageQing** [PaddlePaddle/Serving#822]
![image](https://user-images.githubusercontent.com/37429336/92207778-642aa480-eebc-11ea-967e-9fabe9d64778.png)

**Comment by TeslaZhao** [comment]
本地环境CUDA是什么版本？

**Comment by natureLanguageQing** [comment]
Traceback (most recent call last):
  File "ocr_web_server.py", line 24, in <module>
    from paddle_serving_app.reader import DBPostProcess, FilterBoxes, GetRotateCropImage, SortedBoxes
ImportError: cannot import name 'GetRotateCropImage' from 'paddle_serving_app.reader' (/ml/home/yanguangqing/.conda/envs/PaddleOcr/lib/python3.7/site-packages/paddle_serving_app/reader/__init__.py)

**Comment by natureLanguageQing** [comment]
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130

**Comment by natureLanguageQing** [comment]
安装的版本和代码的版本不是很一致啊
现在是独立的吗

**Comment by natureLanguageQing** [comment]
Traceback (most recent call last):
  File "ocr/ocr_web_server.py", line 7, in <module>
    from paddle_serving_app.reader import DBPostProcess, FilterBoxes, GetRotateCropImage, SortedBoxes
ImportError: cannot import name 'GetRotateCropImage' from 'paddle_serving_app.reader' (/ml/home/yanguangqing/.conda/envs/PaddleOcr/lib/python3.7/site-packages/paddle_serving_app/reader/__init__.py)

**Comment by natureLanguageQing** [comment]
so sorry
我今天怎么会有这么多的幼稚的问题啊。

**Comment by natureLanguageQing** [comment]
pip install paddle-serving-server-gpu==0.2 是我的错 我不应该安装最新版本的
