### ISSUE TITLE
有没有PaddleSeg到PaddleServing的示例呢？

### ISSUE THREAD

**Issue by iceriver97** [PaddlePaddle/Serving#834]
我在使用Seg套件后想使用Serving套件进行部署，但是碰到了很多问题，所以想看看有没有完整的教程？谢谢

**Comment by TeslaZhao** [comment]
您好，目前没有PaddleSeg使用paddle serving的完整教程。您的建议我们会转给产品同学与paddleSeg沟通后，再确定相关的开发计划

**Comment by iceriver97** [comment]
@TeslaZhao 谢谢

**Comment by TeslaZhao** [comment]
相关的PR已经开发完成，等待合入。 https://github.com/PaddlePaddle/PaddleSeg/pull/409

**Comment by iceriver97** [comment]
image_reader 中的SegPostprocess（） 中还是有reshpe 到 （512，512，1）的操作啊？我按照这个教程依旧卡在这里，不能work
