### ISSUE TITLE
example ocr 服务端启动案例 运行OCR部署代码找不到 对象

### ISSUE THREAD

**Issue by natureLanguageQing** [PaddlePaddle/Serving#838]
在paddle serving app的 0.1.1版本 python example OCR 项目中的reader 找不到GetRotateCropImage, SortedBoxes类。

**Comment by natureLanguageQing** [comment]
换了centos环境进行GPU服务部署，发生not found cuda 的情况。本地cuda 切换了 9.0的环境 以及 10.0.130的版本，都没办法正常启动服务。

**Comment by MRXLT** [comment]
你好，可以更新到serving 0.3.2版本试一下，app的新版本是0.1.2

**Comment by natureLanguageQing** [comment]
好的我这边会更新一下版本进行尝试。
