### ISSUE TITLE
有没有类似于websocket这种实时推流的部署方案

### ISSUE THREAD

**Issue by Sunyingbin** [PaddlePaddle/Serving#846]
我想请教一下，我目前在做车辆检测的部署，场景就是添加一个rtsp之后，对视频流实时的检测车辆，用websocket或socketio这种来返回具体坐标信息，有没有docker这种简单方便的部署方案可以参考。具体应该如何做，新手请多指教，谢谢。

**Comment by MRXLT** [comment]
你好，PaddleServing是支持HTTP服务的，可以在这个接口上再进一步开发websocket的方式
docker部署可以参考这个链接 https://github.com/PaddlePaddle/Serving/blob/develop/doc/RUN_IN_DOCKER.md
