### ISSUE TITLE
重新安装wheel包时，可能会遇到Couldn't build proto file into descriptor pool!

### ISSUE THREAD

**Issue by barrierye** [PaddlePaddle/Serving#849]
![311600947824_ pic_hd](https://user-images.githubusercontent.com/28446721/94151481-0c74cd00-fead-11ea-8544-3076f3c1e7f3.jpg)

**Comment by MRXLT** [comment]
paddle serving在使用时需要保证server端和client端的版本号一致，不同版本中的proto协议可能会有不同，这时候便会导致这个问题
