### ISSUE TITLE
serving  OOM

### ISSUE THREAD

**Issue by sevenold** [PaddlePaddle/Serving#851]
```bash

export FLAGS_fraction_of_gpu_memory_to_use=0.9

python -m paddle_serving_server_gpu.serve --model server_model/server_rec  --port 9294 --gpu_id 2 --mem_optim --thread 2 --max_body_size 1073741824

```
![image](https://user-images.githubusercontent.com/41443157/94407427-011feb00-01a6-11eb-8860-84df23381d25.png)

模型是paddleOCR
- ch_ppocr_server_v1.1_det
- ch_ppocr_server_v1.1_rec

显存11G

![image](https://user-images.githubusercontent.com/41443157/94407563-2e6c9900-01a6-11eb-8b8c-88bf452bcdf6.png)

访问多了后，显存就OOM了

**Comment by MRXLT** [comment]
你好，请问是使用的哪个版本的serving

**Comment by sevenold** [comment]
paddle-serving-server-gpu 0.3.2.post10

@MRXLT

**Comment by TeslaZhao** [comment]
从错误信息看，GPU 1 可用显存不足。显存的截图是运行Serving期间的显存截图吗？

**Comment by sevenold** [comment]
显存是11G，模型最开始运行的时候，占用3G左右,随着测试的数据,一张一张测试,显存会增加，最后出现这个错误,有没有什么办法,不报OOM ，单张处理是没有问题的，这样跑着跑着就挂了，很难受。

**Comment by MRXLT** [comment]
把--mem_optim去掉试一下
0.3.2版本默认是打开显存优化的，--mem_optim参数已废弃，新增了--mem_optim_off参数用来在特定情况下关闭显存优化，这里的--mem_optim参数由于python argparse模块会采用前缀匹配，被识别成了--mem_optim_off

**Comment by sevenold** [comment]
谢谢 ，我试下， 有反馈我再回复
@MRXLT
