### ISSUE TITLE
no module named paddle_serving_client.convert

### ISSUE THREAD

**Issue by iceriver97** [PaddlePaddle/Serving#860]
使用官方帮助文档中保存serving模型的方法，但是提示不存在这个module啊，是不是文档写错了？

**Comment by MRXLT** [comment]
你好，这个方法目前是develop版本的功能，0.3.2版本中没有发布

**Comment by iceriver97** [comment]
> 你好，这个方法目前是develop版本的功能，0.3.2版本中没有发布


好的谢谢
