### ISSUE TITLE
关于日志保留时间设置

### ISSUE THREAD

**Issue by JiaoZiLang** [PaddlePaddle/Serving#864]
请教下如何设置日志保留最多天数时间，长时间运行下来日志占用空间太大了

**Comment by TeslaZhao** [comment]
您好，目前不支持Serving过期日志时间删除。过期日志删除一般有2种处理方式，第一种是运维同学写一个logrotate.py，配置好log路径和文件名称，脚本定期检查和删除过期文件。第二种方式在Serving中实现过期文件配置和删除，目前不支持，我可以提供一个方法：

1.C++端：在InitGoogleLogging同时，设置自动cleaner，需要重新编译C++代码
    google::EnableLogCleaner(3); // keep your logs for 3 days
2.python端：pipeline，在pipeline/logger.py中增加
        maxBytes: 1024
        backupCount: 3
3.业务层：
    继承TimedRotatingFileHandler或RotatingFileHandler 实现

**Comment by TeslaZhao** [comment]
下个版本增加这个功能

**Comment by JiaoZiLang** [comment]
多谢🙏
