### ISSUE TITLE
OCR 两个模型运行在一张卡的时候 其中一个进程会卡住

### ISSUE THREAD

**Issue by bjjwwang** [PaddlePaddle/Serving#868]
日志
![image](https://user-images.githubusercontent.com/23625746/97947055-113f7180-1dc7-11eb-8f54-f1224c3fcad9.png)

运行脚本
![image](https://user-images.githubusercontent.com/23625746/97947061-18ff1600-1dc7-11eb-9774-6689a39692c7.png)

环境 nvidia-docker
 hub.baidubce.com/paddlepaddle/serving:latest-cuda10.0-cudnn7

**Comment by TeslaZhao** [comment]
提一个疑问：是不是在同一张卡上运行任何2个相同的模型都会 卡住？
