### ISSUE TITLE
批量分析时，服务中断；如何关闭predict

### ISSUE THREAD

**Issue by TIan-z** [PaddlePaddle/Serving#874]
serving镜像版本：hub.baidubce.com/paddlepaddle/paddle latest-cuda10.0-cudnn7-devel
显卡 2080TI

server：
 centOS 7.7
 cuda 10.0
 cudnn 7.6.5

client:
 Ubuntu 16.04

问题描述:
E1110 08:51:55.873919   718 factory.h:149] RAW: Insert duplicate with tag: WeightedRandomRender
I1110 08:51:55.873919   718 abtest.h:67] RAW: Factory has been registed: WeightedRandomRender->EndpointRouterBase.
F1110 08:51:57.535298   718 doubly_buffered_data.h:283] Fail to pthread_key_create: Resource temporarily unavailable
*** Check failure stack trace: ***
W1110 08:51:57.535545   718 init.cc:226] Warning: PaddlePaddle catches a failure signal, it may not work properly
W1110 08:51:57.535591   718 init.cc:228] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W1110 08:51:57.535596   718 init.cc:231] The detail failure signal is:

W1110 08:51:57.535603   718 init.cc:234] *** Aborted at 1604969517 (unix time) try "date -d @1604969517" if you are using GNU date ***
W1110 08:51:57.538965   718 init.cc:234] PC: @                0x0 (unknown)
W1110 08:51:57.540107   718 init.cc:234] *** SIGABRT (@0x17e) received by PID 382 (TID 0x7f1798df3700) from PID 382; stack trace: ***
W1110 08:51:57.543048   718 init.cc:234]     @     0x7f1a94537390 (unknown)
W1110 08:51:57.545758   718 init.cc:234]     @     0x7f1a9363e428 gsignal
W1110 08:51:57.548385   718 init.cc:234]     @     0x7f1a9364002a abort
W1110 08:51:57.549118   718 init.cc:234]     @     0x7f1935981bb9 google::logging_fail()
W1110 08:51:57.550195   718 init.cc:234]     @     0x7f193598386d google::LogMessage::Fail()
W1110 08:51:57.551098   718 init.cc:234]     @     0x7f193598731c google::LogMessage::SendToLog()
W1110 08:51:57.552357   718 init.cc:234]     @     0x7f1935983393 google::LogMessage::Flush()
W1110 08:51:57.553185   718 init.cc:234]     @     0x7f193598882e google::LogMessageFatal::~LogMessageFatal()
W1110 08:51:57.554028   718 init.cc:234]     @     0x7f1935afe75a butil::DoublyBufferedData<>::DoublyBufferedData()
W1110 08:51:57.554955   718 init.cc:234]     @     0x7f1935afb3de brpc::policy::LocalityAwareLoadBalancer::LocalityAwareLoadBalancer()
W1110 08:51:57.555816   718 init.cc:234]     @     0x7f1935afb5e8 brpc::policy::LocalityAwareLoadBalancer::New()
W1110 08:51:57.556735   718 init.cc:234]     @     0x7f1935aba122 brpc::SharedLoadBalancer::Init()
W1110 08:51:57.557924   718 init.cc:234]     @     0x7f1935aa7c43 brpc::LoadBalancerWithNaming::Init()
W1110 08:51:57.558842   718 init.cc:234]     @     0x7f1935a8beb4 brpc::Channel::Init()
W1110 08:51:57.560153   718 init.cc:234]     @     0x7f1935a472f9 baidu::paddle_serving::sdk_cpp::StubImpl<>::init_channel()
W1110 08:51:57.561209   718 init.cc:234]     @     0x7f1935a4a779 baidu::paddle_serving::sdk_cpp::StubImpl<>::initialize()
W1110 08:51:57.562448   718 init.cc:234]     @     0x7f19359ab708 baidu::paddle_serving::sdk_cpp::Variant::initialize()
W1110 08:51:57.563263   718 init.cc:234]     @     0x7f19359aa817 baidu::paddle_serving::sdk_cpp::Endpoint::initialize()
W1110 08:51:57.564047   718 init.cc:234]     @     0x7f19359b14bd baidu::paddle_serving::sdk_cpp::PredictorApi::create()
W1110 08:51:57.564837   718 init.cc:234]     @     0x7f1935977534 _ZZN8pybind1112cpp_function10initializeIZN5baidu14paddle_serving13general_modelL28pybind11_init_serving_clientERNS_6moduleEEUlRNS4_15PredictorClientERKSsE8_vIS8_SA_EINS_4nameENS_9is_methodENS_7siblingEEEEvOT_PFT0_DpT1_EDpRKT2_ENUlRNS_6detail13function_callEE1_4_FUNESS_.49864
W1110 08:51:57.565630   718 init.cc:234]     @     0x7f1935957db2 pybind11::cpp_function::dispatcher()
W1110 08:51:57.565790   718 init.cc:234]     @           0x5243cb _PyCFunction_FastCallKeywords
W1110 08:51:57.565940   718 init.cc:234]     @           0x57e965 (unknown)
W1110 08:51:57.566080   718 init.cc:234]     @           0x576f9f _PyEval_EvalFrameDefault
W1110 08:51:57.566221   718 init.cc:234]     @           0x57609f (unknown)
W1110 08:51:57.566361   718 init.cc:234]     @           0x57f96b (unknown)
W1110 08:51:57.566501   718 init.cc:234]     @           0x57e8bc (unknown)
W1110 08:51:57.566637   718 init.cc:234]     @           0x576f9f _PyEval_EvalFrameDefault
W1110 08:51:57.566777   718 init.cc:234]     @           0x57f8ad (unknown)
W1110 08:51:57.566916   718 init.cc:234]     @           0x57e8bc (unknown)
W1110 08:51:57.567050   718 init.cc:234]     @           0x576f9f _PyEval_EvalFrameDefault
W1110 08:51:57.567189   718 init.cc:234]     @           0x576736 (unknown)

paddle serving最大连接数多少；如何关闭predict； 有没有Ubuntu系统的paddleserving镜像；’谢谢

**Comment by TeslaZhao** [comment]
Fail to pthread_key_create: Resource temporarily unavailable

出现这个错误是系统无法分配进程了，请检查下系统资源是不是有限制，另外检查一下client使用是否正确，例如循环生成client会导致资源耗尽。

Paddle Serving支持的系统镜像：https://github.com/PaddlePaddle/Serving/blob/develop/doc/DOCKER_IMAGES_CN.md
CPU 开发镜像 (用于编译 Ubuntu 包)
GPU (cuda9.0-cudnn7) 开发镜像 (用于编译 Ubuntu 包)
编译出的Ubuntu包

**Comment by TIan-z** [comment]
好的，谢谢------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;TeslaZhao&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年11月13日(星期五) 中午12:23
收件人:&nbsp;&quot;PaddlePaddle/Serving&quot;<Serving@noreply.github.com&gt;;
抄送:&nbsp;&quot;TIan-z&quot;<958463384@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/Serving] 批量分析时，服务中断；如何关闭predict (#874)
