### ISSUE TITLE
怎么关闭paddle client的链接

### ISSUE THREAD

**Issue by 631961895** [PaddlePaddle/Serving#876]
from paddle_serving_client import Client
client = Client()
client.load_client_config(client_config)
client.connect([])
链接成功使用完毕之后怎么把链接关闭？这里面并没有close()的方法

**Comment by bjjwwang** [comment]
> from paddle_serving_client import Client
> client = Client()
> client.load_client_config(client_config)
> client.connect([])
> 链接成功使用完毕之后怎么把链接关闭？这里面并没有close()的方法

底层是BRPC的接口，之前没有这样设计，我看看是不是应该去设计一个。

**Comment by TeslaZhao** [comment]
您好，client.connect()像是网络连接接口，并不是直接使用socket连接。Paddle Serving底层使用brpc网络库，并使用butil::get_object做内存管理，在程序退出时会析构资源。因此，在使用client使用过程中无需close关注接口。
