### ISSUE TITLE
paddleserving有做websocket这种服务吗

### ISSUE THREAD

**Issue by Sunyingbin** [PaddlePaddle/Serving#878]
我现在有一个场景，就是通过接入rtsp视频流，启动一个websocket服务，然后paddle用来识别，将结果实时返回

**Comment by TeslaZhao** [comment]
你好，PaddleServing支持HTTP服务，您可以在HTTP上再进一步开发websocket的方式
docker部署可以参考这个链接 https://github.com/PaddlePaddle/Serving/blob/develop/doc/RUN_IN_DOCKER.md
