### ISSUE TITLE
serving进行预测时，不将结果保存需要如何操作

### ISSUE THREAD

**Issue by liangruofei** [PaddlePaddle/Serving#879]
**不要output输出内容

from paddle_serving_client import Client
from paddle_serving_app.reader import *
import sys
import numpy as np

preprocess = Sequential([
    File2Image(), BGR2RGB(), Div(255.0),
    Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225], False),
    Resize(640, 640), Transpose((2, 0, 1))
])

postprocess = RCNNPostprocess("label_list.txt", "output")
client = Client()

client.load_client_config(sys.argv[1])
client.connect(['127.0.0.1:9494'])

im = preprocess(sys.argv[3])
fetch_map = client.predict(
    feed={
        "image": im,
        "im_info": np.array(list(im.shape[1:]) + [1.0]),
        "im_shape": np.array(list(im.shape[1:]) + [1.0])
    },
    fetch=["multiclass_nms"])
fetch_map["image"] = sys.argv[3]
postprocess(fetch_map)

**Comment by TeslaZhao** [comment]
您好，目前不支持output不输出的定制，想了解下您不想输出output的原因是？

**Comment by liangruofei** [comment]
因为我的检测结果后面还要对接应用，数据会给其他处理。这里加上保存会增加我的延时




| |
梁若飞
邮箱：liangruofeinuc@163.com
|

签名由 网易邮箱大师 定制

在2020年11月13日 12:28，TeslaZhao 写道：

您好，目前不支持output不输出的定制，想了解下您不想输出output的原因是？

**Comment by TeslaZhao** [comment]
了解，你先自行在代码里改一下（./paddle_serving_app/reader/image_reader.py）。我们会增加一个新需求是否保存结果的选项。您也可以给我们提PR和code。

**Comment by liangruofei** [comment]
👌




| |
梁若飞
邮箱：liangruofeinuc@163.com
|

签名由 网易邮箱大师 定制

在2020年11月13日 13:58，TeslaZhao 写道：

了解，你先自行在代码里改一下（./paddle_serving_app/reader/image_reader.py）。我们会增加一个新需求是否保存结果的选项。您也可以给我们提PR和code。
