### ISSUE TITLE
如何在arm平台部署paddle_serving_client

### ISSUE THREAD

**Issue by TongHengcheng** [PaddlePaddle/Serving#885]
我在jetson tx2上使用pip 安装 paddle_serving_client 后，初始化Client时显示
![image](https://user-images.githubusercontent.com/35362026/99612809-45669380-2a51-11eb-9663-eace61d340ed.png)
使用file serving_client.so发现该文件是x86下编译的，如果需要重新编译paddle_serving_client的话，我需要怎么做？望解答。

**Comment by TeslaZhao** [comment]
您好，目前没有在arm平台上编译过serving。如果您想试一下编译，可以参考linux平台编译文档。https://github.com/PaddlePaddle/Serving/blob/develop/doc/COMPILE_CN.md

**Comment by TongHengcheng** [comment]
好的，我尝试下



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "TeslaZhao"<notifications@github.com&gt;; 
发送时间: 2020年11月19日(星期四) 下午2:04
收件人: "PaddlePaddle/Serving"<Serving@noreply.github.com&gt;; 
抄送: "2841799783"<2841799783@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [PaddlePaddle/Serving] 如何在arm平台部署paddle_serving_client (#885)





 
您好，目前没有在arm平台上编译过serving。如果您想试一下编译，可以参考linux平台编译文档。https://github.com/PaddlePaddle/Serving/blob/develop/doc/COMPILE_CN.md

**Comment by bjjwwang** [comment]
> 好的，我尝试下
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "TeslaZhao"<notifications@github.com&gt;; 发送时间: 2020年11月19日(星期四) 下午2:04 收件人: "PaddlePaddle/Serving"<Serving@noreply.github.com&gt;; 抄送: "2841799783"<2841799783@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [PaddlePaddle/Serving] 如何在arm平台部署paddle_serving_client (#885) 您好，目前没有在arm平台上编译过serving。如果您想试一下编译，可以参考linux平台编译文档。https://github.com/PaddlePaddle/Serving/blob/develop/doc/COMPILE_CN.md — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

是有什么样的需求要Arm的serving

**Comment by TongHengcheng** [comment]
需求是这样的：我们在服务器上使用了paddle_serving_server开启了服务，arm上只是建立一个客户端能够访问服务器上的服务。





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jiawei Wang"<notifications@github.com&gt;; 
发送时间: 2020年11月19日(星期四) 晚上10:03
收件人: "PaddlePaddle/Serving"<Serving@noreply.github.com&gt;; 
抄送: "2841799783"<2841799783@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [PaddlePaddle/Serving] 如何在arm平台部署paddle_serving_client (#885)





  
好的，我尝试下
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "TeslaZhao"<notifications@github.com&gt;; 发送时间: 2020年11月19日(星期四) 下午2:04 收件人: "PaddlePaddle/Serving"<Serving@noreply.github.com&gt;; 抄送: "2841799783"<2841799783@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [PaddlePaddle/Serving] 如何在arm平台部署paddle_serving_client (#885) 您好，目前没有在arm平台上编译过serving。如果您想试一下编译，可以参考linux平台编译文档。https://github.com/PaddlePaddle/Serving/blob/develop/doc/COMPILE_CN.md — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
是有什么样的需求要Arm的serving

**Comment by Chambers1994** [comment]
[ 56%] Built target pdcodegen
[  0%] Building CXX object CMakeFiles/PROTO_LIB.dir/idl_options.pb.cc.o
c++: error: unrecognized command line option ‘-msse4’
c++: error: unrecognized command line option ‘-msse4.2’
CMakeFiles/PROTO_LIB.dir/build.make:198: recipe for target 'CMakeFiles/PROTO_LIB.dir/idl_options.pb.cc.o' failed
make[5]: *** [CMakeFiles/PROTO_LIB.dir/idl_options.pb.cc.o] Error 1
make[5]: *** Waiting for unfinished jobs....
[  0%] Building CXX object CMakeFiles/PROTO_LIB.dir/brpc/rtmp.pb.cc.o
c++: error: unrecognized command line option ‘-msse4’
c++: error: unrecognized command line option ‘-msse4.2’

我是在jetson arm64平台编译client，这个错误大概是由于jetson不支持sse指令集，我不知道如何修改关掉对sse指令集进行编译，请帮忙解答，谢谢！

**Comment by 60999** [comment]
有后续吗，同样的问题
