### ISSUE TITLE
yolov3检测模型，批量分析时中间报错

### ISSUE THREAD

**Issue by Jakel21** [PaddlePaddle/Serving#891]
容器内起了yolov3的检测模型服务，在批量请求时固定卡在第500哥请求的时候报错（不是图的问题，检查过图没有问题）。
如果一次请求少于500，则没有问题。
----------------------------------------------------
报错信息如下：
![image](https://user-images.githubusercontent.com/20606275/100037547-52162d80-2e3d-11eb-97f7-90a6057d5b56.png)

检查过容器是否有内存限制等，貌似没有问题
![image](https://user-images.githubusercontent.com/20606275/100037272-bd133480-2e3c-11eb-8143-0b278878f53b.png)
目前请求是这样写的
![image](https://user-images.githubusercontent.com/20606275/100037965-192a8880-2e3e-11eb-9721-aa77c27de30c.png)

请问如果想批量请求处理的话该怎么修改呢？
500这个限制是固定限制，查找也没找到是哪里做了限制，这个之前有遇到过嘛？

**Comment by T8T9** [comment]
看起来像OS创建线程数达到限制了，麻烦确认一下每个进程可创建的线程数是否收到限制。

**Comment by TeslaZhao** [comment]
您好，您遇到的问题是OS创建线程数达到限制了，建议您使用QueueObject模式，创建N个Client对象，初始化后放入QueueObject，在Service处理函数层从QueueObject中获取Client对象predict。我们下一版本示例中增加QueueObject的使用，希望能帮助到您
