### ISSUE TITLE
Local deployment debug, package incompatibility

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/Serving#892]
platform : win10
server-version: 0.3.2

When I run the local prediction(debug)，there seems a lib  incompatible with environment,
The error message is as follows：
![image](https://user-images.githubusercontent.com/12640462/100174424-60c91700-2f07-11eb-9da7-896f2de7f58c.png)

I found the lib fcntl was  not compatible with  windows system
![image](https://user-images.githubusercontent.com/12640462/100174674-d3d28d80-2f07-11eb-8a96-c4aca505d6c4.png)

**Comment by TeslaZhao** [comment]
您好，windows环境我们正在适配中，感谢您的issue.

**Comment by BeyondYourself** [comment]
好的，期待ing
