### ISSUE TITLE
可否出个docker镜像，源码编译了一天，老是中途错误

### ISSUE THREAD

**Issue by 3050311118** [PaddlePaddle/Serving#90]
os  ubuntu 18.04
go 1.12
cmake 3.10
g++ 7.4.0

最好出个镜像，学习测试下，不用卡在编译上

**Comment by wangjiawei04** [comment]
目前官方镜像还没有出来，如果需要编译环境，目前需要一个GCC4.8.2
可以 pull hub.baidubce.com/ctr/paddleserving:latest 这个镜像

**Comment by guru4elephant** [comment]
https://github.com/PaddlePaddle/Serving/blob/develop/doc/RUN_IN_DOCKER.md
