### ISSUE TITLE
serving-cpu-noavx-openblas-0.3.2/serving: cannot execute binary file

### ISSUE THREAD

**Issue by turbodblabs** [PaddlePaddle/Serving#906]
启动服务一直报这个错
![image](https://user-images.githubusercontent.com/26930834/101286935-676d5d80-3828-11eb-9970-fab484c64328.png)

端口有启动成功，执行
`curl -H "Content-Type:application/json" -X POST -d '{"x": [0.0137, -0.1136, 0.2553, -0.0692, 0.0582, -0.0727, -0.1583, -0.0584, 0.6283, 0.4919, 0.1856, 0.0795, -0.0332], "fetch":["price"]}' http://127.0.0.1:9292/uci/prediction
`
报500 错误

![image](https://user-images.githubusercontent.com/26930834/101287001-b9ae7e80-3828-11eb-8193-1c162241d6e3.png)

**Comment by TeslaZhao** [comment]
您好，0.3.2版本不支持mac部署。v0.4.0/develop 分支上支持在mac上使用local predict方式的部署。

**Comment by turbodblabs** [comment]
>感谢
