### ISSUE TITLE
提示安装成功后使用paddle出错

### ISSUE THREAD

**Issue by yuope** [PaddlePaddle/Serving#940]
Python 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:59:51) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle.fluid as fluid
 ** On entry to DGEBAL parameter number  3 had an illegal value
 ** On entry to DGEHRD  parameter number  2 had an illegal value
 ** On entry to DORGHR DORGQR parameter number  2 had an illegal value
 ** On entry to DHSEQR parameter number  4 had an illegal value
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Program\tools\python3.8\lib\site-packages\paddle\__init__.py", line 18, in <module>
    check_import_scipy(os.name)
  File "D:\Program\tools\python3.8\lib\site-packages\paddle\check_import_scipy.py", line 20, in check_import_scipy
    import scipy.io as scio
  File "D:\Program\tools\python3.8\lib\site-packages\scipy\__init__.py", line 61, in <module>
    from numpy import show_config as show_numpy_config
  File "D:\Program\tools\python3.8\lib\site-packages\numpy\__init__.py", line 305, in <module>
    _win_os_check()
  File "D:\Program\tools\python3.8\lib\site-packages\numpy\__init__.py", line 302, in _win_os_check
    raise RuntimeError(msg.format(__file__)) from None
RuntimeError: The current Numpy installation ('D:\\Program\\tools\\python3.8\\lib\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86

**Comment by TeslaZhao** [comment]
你好，是Windows系统吗，安装哪个版本Serving?

**Comment by yuope** [comment]
是win10 用pip install&nbsp;paddlepaddle==1.8.5 -i https://mirror.baidu.com/pypi/simple 下载的1.8.5 版本




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Serving"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月23日(星期三) 下午3:57
收件人:&nbsp;"PaddlePaddle/Serving"<Serving@noreply.github.com&gt;;
抄送:&nbsp;"帕芭"<1582724427@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/Serving] 提示安装成功后使用paddle出错 (#940)





 
你好，是Windows系统吗，安装哪个版本Serving?
