### ISSUE TITLE
请求服务出现{"result":"not enough values to unpack (expected 3, got 2)"}

### ISSUE THREAD

**Issue by Kokoing123** [PaddlePaddle/Serving#949]
使用paddleserving的图像分类历程，使用curl H请求远程服务curl -H "Content-Type:application/json" -X POST -d '{"feed":[{"image": "https://paddle-serving.bj.bcebos.com/imagenet-example/daisy.jpg"}], "fetch": ["score"]}' http://127.0.0.1:9292/image/prediction，完全例子的写法，出现以上{"result":"not enough values to unpack (expected 3, got 2)"}返回问题。
paddleserving 0.4.0 cuda10 cudnn7

**Comment by TeslaZhao** [comment]
你好，我测试了v0.4.0版本的imagenet示例，可以正常运行。结果如下：
{"result":{"label":["daisy"],"prob":[0.9341403245925903]}}

根据您提供的错误原因，请重新安装一下server、client、app安装包版本不正确。运行下面命令，将安装包更新到v0.4.0版本：
pip install -U paddle-serving-client==0.4.0
pip install -U paddle-serving-server==0.4.0
pip install -U paddle-serving-app==0.2.0

**Comment by meishitouzhele** [comment]
我也遇到了这个问题，安装的是4.0  然后使用内置分词模型调用 
[root@9776ba5ea3b6 /]# curl -H "Content-Type:application/json" -X POST -d '{"feed":[{"words": "我爱北京天安门"}], "fetch":["word_seg"]}' http://127.0.0.1:9393/lac/prediction
{"result":"need more than 2 values to unpack"}
请问是官网文档里的json错误吗

**Comment by meishitouzhele** [comment]
![image](https://user-images.githubusercontent.com/11419081/103597609-a3850280-4f3b-11eb-8b61-b4bd8c6afc1c.png)

**Comment by meishitouzhele** [comment]
请问 环境里，除了这三个版本要求
paddle-serving-app    0.2.0   
paddle-serving-client 0.4.0   
paddle-serving-server 0.4.0  还有其他要求吗？docker安装的serving

**Comment by TeslaZhao** [comment]
如果是cpu的docker没有要求，如果使用GPU预测的话docker要和cuda相匹配。刚刚试一下examples/lac是没有问题的

curl -H "Content-Type:application/json" -X POST -d '{"feed":[{"words": "我爱北京天安门"}], "fetch":["word_seg"]}' http://127.0.0.1:9292/lac/prediction

{'crf_decode': array([[30],
       [38],
       [50],
       [51],
       [50],
       [51],
       [51],
       [30],
       [38],
       [50],
       [51],
       [50],
       [51],
       [51]]), 'crf_decode.lod': array([ 0,  7, 14], dtype=int32)}
word_seg: 我|爱|北京|天安门

使用pip list | grep serving 看看版本是否OK
paddle-serving-app            0.2.0
paddle-serving-client         0.4.0
paddle-serving-server         0.4.0

**Comment by TeslaZhao** [comment]
还有你的examples代码是否更新到最新？

**Comment by meishitouzhele** [comment]
感谢  目前使用的是cpu的，查询安装的版本的确是这三种
 paddle-serving-app 0.2.0
paddle-serving-client 0.4.0
paddle-serving-server 0.4.0
启动内置的分词http api是可以启动  就是调用的时候 返回这提示{"result":"need more than 2 values to unpack"}

**Comment by meishitouzhele** [comment]
examples 更新指的是？ 我刚安装后serving的docker后，就直接根据文档下载的model 然后启动  然后调用api，下载后还需要特殊更新吗？

**Comment by TeslaZhao** [comment]
examples是 代码库python/examples目录示例代码。表示你的代码是否为最新v0.4.0版本。v0.4.0版本除了更新server、client、app。同时也更新了部分示例代码。

**Comment by meishitouzhele** [comment]
嗯嗯 使用pip list | grep serving 看看版本结果是最新，怎么才能确认examples是否最新？
paddle-serving-app 0.2.0
paddle-serving-client 0.4.0
paddle-serving-server 0.4.0

**Comment by TeslaZhao** [comment]
如果你的环境下有git，可以git pull最新代码。如果没有git，download最新的zip包
![image](https://user-images.githubusercontent.com/6309021/103598898-bd741480-4f3e-11eb-8394-ace87b58dbf2.png)

**Comment by meishitouzhele** [comment]
好的  感谢  我去对比下lac_web_service.py文件

**Comment by meishitouzhele** [comment]
我刚对比了lac_web_service.py文件，发现docker里的样例下的model应该不是最新的，我下载源码后只覆盖了lac_web_service.py文件，请问怎么才能下载最新的model？

**Comment by TeslaZhao** [comment]
model没有变化，按README.md中步骤操作即可

**Comment by meishitouzhele** [comment]
额 按照readme中操作，下载解压后的lac_web_service.py还是老的 跟git上的lac_web_service.py源码不一致啊

**Comment by meishitouzhele** [comment]
最新的def preprocess(self, feed={}, fetch=[]):
        feed_batch = []
        fetch = ["crf_decode"]
        lod_info = [0]
        is_batch = True
        for ins in feed:
根据文档下载解压后：
 def preprocess(self, feed={}, fetch=[]):
        feed_batch = []
        for ins in feed:
            if "words" not in ins:
                raise ("feed data error!")
            feed_data = self.reader.process(ins["words"])
            feed_batch.append({"words": feed_data})
        fetch = ["crf_decode"]
        return feed_batch, fetch

**Comment by TeslaZhao** [comment]
收到反馈，压缩包里的lac_web_service.py我们删除掉，用最新的文件可以运行起来吗？

**Comment by meishitouzhele** [comment]
用最新的lac_web_service.py也返回一样的结果{"result":"need more than 2 values to unpack"}，使用下面自带的图像分类测试是正常的，就分词这个有点障碍
> python -m paddle_serving_app.package --get_model resnet_v2_50_imagenet
> tar -xzf resnet_v2_50_imagenet.tar.gz
> python resnet50_imagenet_classify.py resnet50_serving_model &
> curl -H "Content-Type:application/json" -X POST -d '{"feed":[{"image": "https://paddle-serving.bj.bcebos.com/imagenet-example/daisy.jpg"}], "fetch": ["score"]}' http://127.0.0.1:9292/image/prediction
{"result":{"label":["daisy"],"prob":[0.9341403245925903]}}

**Comment by meishitouzhele** [comment]
补充一下：一开始文档图像分类的也不行，使用git上最新的是成功的。

**Comment by meishitouzhele** [comment]
能不能像图像分类那样，能个最新的下来.gz得地址？
图像的sh文件内容如下：
wget --no-check-certificate https://paddle-serving.bj.bcebos.com/imagenet-example/ResNet50_vd.tar.gz
tar -xzvf ResNet50_vd.tar.gz
wget --no-check-certificate https://paddle-serving.bj.bcebos.com/imagenet-example/ResNet101_vd.tar.gz
tar -xzvf ResNet101_vd.tar.gz

wget --no-check-certificate https://paddle-serving.bj.bcebos.com/imagenet-example/image_data.tar.gz
tar -xzvf image_data.tar.gz

**Comment by TeslaZhao** [comment]
最新的压缩包里已经删除了lac_web_service.py，不会被旧文件覆盖了。

用最新的lac_web_service.py也返回一样的结果{"result":"need more than 2 values to unpack"}有点奇怪。我本地没有复现这个问题，换个端口试一下？

**Comment by meishitouzhele** [comment]
好的  谢谢 辛苦了

**Comment by meishitouzhele** [comment]
这次好了，居然好了  不过返回信息不是汉字  是Unicode编码  内容如下：
{"result":[{"word_seg":"\u6211|\u7231|\u5317\u4eac|\u5929\u5b89\u95e8"}]}
翻译过来是对的：
{"result":[{"word_seg":"我|爱|北京|天安门"}]}
