### ISSUE TITLE
这里提示这些API将要抛弃，那我用什么办法提供HTTP请求呢？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Serving#951]
这里提示这些API将要抛弃，那我用什么办法提供HTTP请求呢？

https://github.com/PaddlePaddle/Serving/blob/7ea59bda3f25bccacfbff0cccac79390f0a86017/python/paddle_serving_server_gpu/web_service.py#L262-L271

**Comment by TeslaZhao** [comment]
参考Pipeline的用法 https://github.com/PaddlePaddle/Serving/blob/develop/python/examples/pipeline/simple_web_service/web_service.py

Pipeline的文档
https://github.com/PaddlePaddle/Serving/blob/develop/doc/PIPELINE_SERVING_CN.md
