### ISSUE TITLE
win10的docker中 cpu模式运行正常，gpu提示下面描述，

### ISSUE THREAD

**Issue by meishitouzhele** [PaddlePaddle/Serving#960]
服务器环境：配了一个cuda10.2.141的gpu
http://172.17.0.2:9292/image/prediction
This API will be deprecated later. Please do not use it
 * Serving Flask app "paddle_serving_server_gpu.web_service" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
GPU not found, please check your environment or use cpu version by "pip install paddle_serving_server"

**Comment by TeslaZhao** [comment]
cuda10.2我们没测试过，你的环境下，能预测吗？

**Comment by meishitouzhele** [comment]
我测试了如下几个环境：
1、win10 直接安装使用paddlehub 可以使用gpu预测
2、centos 上使用cpu可以预测
3、win10上安装paddle serving docker 镜像后，cpu模式可以预测，gpu模式目前无法预测（提示找不到gpu，是驱动的问题吗）。

**Comment by TeslaZhao** [comment]
你好，你的机器上有cuda10.1驱动吗，试试cuda10.1驱动下能否正常启动？
