### ISSUE TITLE
在云服务器发布serving格式模型后，调用服务发生报错。

### ISSUE THREAD

**Issue by ClassmateXiaoyu** [PaddlePaddle/Serving#961]
问题描述：在云服务器（CentOS 7.5 64位）上使用RPC模式发布了一个自己的模型（用paddlex训练的分类模型，发布的模型已经转换为了serving格式的）。随后在客户端调用的时候，发生报错ModuleNotFoundError: No module named 'paddle_serving_client.serving_client'。

云服务器命令：python -m paddle_serving_server.serve --model serving_server --port 9696
客户端命令：python rpc_client.py ./serving_client/serving_client_conf.prototxt
![4148E263-4FF2-452a-92DD-412BBA5D665D](https://user-images.githubusercontent.com/62195135/103998389-ef070d00-51d6-11eb-80fa-a17dd43dd9c4.png)
服务器端服务启动无异常

**Comment by TeslaZhao** [comment]
你好，需要安装paddle-serving-client
pip install paddle-serving-client==版本号

例如：
pip install paddle-serving-client==0.4.0

**Comment by ClassmateXiaoyu** [comment]
> 你好，需要安装paddle-serving-client
> pip install paddle-serving-client==版本号
> 
> 例如：
> pip install paddle-serving-client==0.4.0

你好，发布这条issue的时候，做为客户端的PC有安装0.4.0版本的paddle-serving-client，出现的这个问题。
![QQ截图20210114115825](https://user-images.githubusercontent.com/62195135/104543155-dfb51300-565f-11eb-83ac-05fd3ceb622b.png)
