### ISSUE TITLE
基于pd开发的模型是否能加密部署？

### ISSUE THREAD

**Issue by grapefruitL** [PaddlePaddle/Serving#964]
你好！我有两个问题：
1、本项目和paddlehub里的[部署方案](https://github.com/PaddlePaddle/PaddleHub/blob/release/v2.0.0-rc/docs/docs_en/tutorial/serving_en.md)有什么区别？如果我使用pd自己开发的模型需要部署，应该使用哪种方案？
2、基于serving的部署方案（无论本项目还是paddlehub），是否支持模型加密？我搜索到[类似问题](https://github.com/PaddlePaddle/Serving/pull/689)，不知是否表明已经具备加密部署能力，如果具备是否能提供使用说明文档？

**Comment by TeslaZhao** [comment]
您好！

1. paddlehub是单模型部署的服务框架，便于获取Paddle生态的预训练模型。paddle serving是paddle生态的服务化推理框架，支持大规模、工业级对标Tensorflow Serving的产品。对于自己开发模型，主要看你的使用场景是否有其他需求，如果没有特殊需求，用2种方式部署都可以。

2.是的，您已经找到了我们开发的关于模型加解密的PR，文档也在同步撰写中，该功能会随着v0.4.1版本（1月底）发布。敬请期待！

**Comment by TeslaZhao** [comment]
Paddle Serving v0.5.0版本已发布，模型加解密请参考文档：https://github.com/PaddlePaddle/Serving/blob/develop/doc/ENCRYPTION_CN.md
