### ISSUE TITLE
确定高性能、生产可用？官方Benchmark显示性能比较低

### ISSUE THREAD

**Issue by readthecodes** [PaddlePaddle/Serving#965]
Repo简介里写着高性能，可是Benchmark数据显示性能不太能接受：https://github.com/PaddlePaddle/Serving/blob/v0.4.0/doc/BENCHMARKING.md

**Comment by TeslaZhao** [comment]
您好，非常抱歉，BENCHMARK文档是旧的，没有更新。最新数据月底在下一个版本开发结束后更新。
