### ISSUE TITLE
Paddle Serving 是否支持单进程中的多线程执行预测

### ISSUE THREAD

**Issue by zhfkt** [PaddlePaddle/Serving#968]
Hi,

感谢作者开发Paddle Serving，我打算使用Paddle Serving去部署model。不过这里有一个疑问：Paddle Serving 是否支持单进程中的多线程执行预测？

有这个疑问的原因是，做Python Web application开发的时候，一般是通过多进程的方式去部署从而增加服务端的性能（比如Django/Flask，因为python 有GIL所以单进程没有办法利用CPU所有的核）。但是由于有的时候Model模型文件会很大，所以多进程会导致内存占用翻个好几倍。那Paddle Serving也是通过多进程（像Django或者Flask）的方式去增加服务端的性能的吗？Paddle Serving 是否支持单进程中的多线程执行预测 ？或者说Paddle Serving是否支持单进程中利用CPU所有核（绕开Pythond的GIL）去执行预测 ？

Thank you !

**Comment by xiao4er** [comment]
Flask测试发现，当threaded=False, processes>1时， API实现中使用paddle_serving_client.Client.predict方法进行预测时，将一直阻塞；
使用单独的测试脚本进行预测表现正常；

**Comment by TeslaZhao** [comment]
您好，如您所说，因为python 有GIL所以单进程没有办法利用CPU所有的核，在webserver + rpc多线程模式下，在pybind代码中加入 py::call_guard<py::gil_scoped_release>());绕开Pythond的GIL。由于有1次WebServer + 1次RPC访问，多线程模式的性能仍然不好。Paddle Serving v0.4.0版本新开发Pipeline Serving特性有效提升吞吐和并发性，支持多线程和多进程2种模式，支持grpc/webserver访问。推荐您使用 Pipeline + Local predictor方式，吞吐有大幅提升的效果。

示例：https://github.com/PaddlePaddle/Serving/tree/v0.4.0/python/examples/pipeline/simple_web_service
文档：https://github.com/PaddlePaddle/Serving/blob/v0.4.0/doc/PIPELINE_SERVING_CN.md

**Comment by HexToString** [comment]
回答的真好~

**Comment by zhfkt** [comment]
Thank you. Let me check
