### ISSUE TITLE
Serving pipeline的ocr例子只能返回一个识别字符串

### ISSUE THREAD

**Issue by zhfkt** [PaddlePaddle/Serving#975]
直接按照官方的这个例子跑Serving pipeline的OCR，永远只能返回一个识别字符串

https://github.com/PaddlePaddle/Serving/blob/v0.4.0/python/examples/pipeline/ocr/README_CN.md

启动 - 

python web_service.py

请求requests - 

python pipeline_http_client.py

输出 - 

{'err_no': 0, 'err_msg': '', 'key': ['res'], 'value': ["['没有吃饱只有一个']"]}
{'err_no': 0, 'err_msg': '', 'key': ['res'], 'value': ["['管理员的认证--使用JT']"]}
{'err_no': 0, 'err_msg': '', 'key': ['res'], 'value': ["['当mybatis-plus所提供的接口不能满足业务需要的时候']"]}

测试图片：

--------------------------

图片1：
![7](https://user-images.githubusercontent.com/4969804/105021349-69f7df80-5a83-11eb-8b23-cc92d9b99a5d.jpg)

图片2：
![test](https://user-images.githubusercontent.com/4969804/105021369-6ebc9380-5a83-11eb-95ef-f7eb6813ca6f.png)

图片3：
![3](https://user-images.githubusercontent.com/4969804/105021710-d1ae2a80-5a83-11eb-9430-f859d4dd2b55.png)

--------------------------

稍微调试了一下，发现DetOp https://github.com/PaddlePaddle/Serving/blob/54999920b674cd3f370ede4bea43fff1dbd9ca10/python/examples/pipeline/ocr/web_service.py#L30 可以识别多个文本框boxes，但是在 RecOp 阶段https://github.com/PaddlePaddle/Serving/blob/54999920b674cd3f370ede4bea43fff1dbd9ca10/python/examples/pipeline/ocr/web_service.py#L69 只能输出一个文本，而不是多个文本。不知道是否是Pipeline框架的bug，或者是本身web_service.py有问题。请看一下这个bug，谢谢！

**Comment by zhfkt** [comment]
@wangjiawei04 可能是这个修改导致的 https://github.com/PaddlePaddle/Serving/commit/ce97387f9cc659c6b8118b6cedda97452ebb7cc1#r46105380 

但是如果把web_service.py改回上面的老版本，运行又会报错。

**Comment by zhfkt** [comment]
debug了一下，提供更多的线索在这里，问题可能是出在 ：

https://github.com/PaddlePaddle/Serving/blob/54999920b674cd3f370ede4bea43fff1dbd9ca10/python/pipeline/operator.py#L802

RecOP（识别模块）中，对于输出的名字含有lod的情况（lodtensor），对midped_data_dict 做了一个特殊的处理，只取出了第一个结果 （data_ids只有一个值的时候），后面的值全部放弃了。导致了只有第一个字符串被保留了下来，后面的都字符串都没添加进来。

如果是DetOP（检测模块）的Normal tensor，就没有这种情况，结果会被全部添加进来

https://github.com/PaddlePaddle/Serving/blob/54999920b674cd3f370ede4bea43fff1dbd9ca10/python/pipeline/operator.py#L816

这个应该是一个由新的Pipeline模式导致的bug。在不用Pipeline模式的情况下，没有这个bug。

**Comment by TeslaZhao** [comment]
您好，我们复现一下看看

**Comment by zengqi0730** [comment]
是的，我也遇到这种情况，改了好几天，代码好复杂，还是没改好。求更新

**Comment by TeslaZhao** [comment]
你好，问题基本定位了。周末改一版

**Comment by TeslaZhao** [comment]
已经修复，提交PR:https://github.com/PaddlePaddle/Serving/pull/1008

**Comment by zengqi0730** [comment]
> 你好，问题基本定位了。周末改一版

你好，怎么才能返回文本框在原图的坐标呢？preprocess和postprocess好像变量不能共享

**Comment by zengqi0730** [comment]
> 已经修复，提交PR:#1008

请问什么时候发布更新后的版本呢？或者哪里可以下载修复后的whl文件呢？

**Comment by TeslaZhao** [comment]
v0.5.0版本已经于2月23日正式发布，欢迎您使用
