### ISSUE TITLE
pipleline模式下 ，在存在local_service_conf的情况下，config.yml中的concurrency无法设定线程数

### ISSUE THREAD

**Issue by zhfkt** [PaddlePaddle/Serving#978]
pipleline模式下 ，在存在local_service_conf的情况下，config.yml中的concurrency无法设定线程数

对于这个下面的这个例子：

https://github.com/PaddlePaddle/Serving/blob/v0.4.0/python/examples/pipeline/ocr/config.yml

改变 concurrency 无法改变并发的线程数，线程数一直为2。

原因在于 存在local_service_conf的情况下，需要同时设置 thread_num 才行，否则就一直是2。可能出问题的代码在这里。

https://github.com/PaddlePaddle/Serving/blob/54999920b674cd3f370ede4bea43fff1dbd9ca10/python/pipeline/operator.py#L155  

thread_num 覆盖了上面的 concurrency 的值。如果没有设置 thread_num 的情况下，默认thread_num = 2，也会 覆盖了上面的 concurrency的值。

应该变成 在没有设定 thread_num  的情况下， 不要覆盖 concurrency 的值。

Please check this bug

Thank you !

**Comment by TeslaZhao** [comment]
谢谢您的建议！concurrency和thread_num 是2个不同层次的概念。
concurrency是OP并发数量。 根据线程、进程模式，会启动多进程或多线程。
local_service_conf.get("thread_num") 是Local predictor模式下，设置 CPU Blas 库计算线程数量，当CPU资源足够时，有较高的性能提升

**Comment by zhfkt** [comment]
ok. Thank you. 追问 @TeslaZhao : 

我试了下thread_num设置成了10，但是似乎只用到了4个核（观察一个长时间的predict任务发现只有4个cpu核会跑到100%），是否对thread_num的上限有做了什么设置？

**Comment by zhfkt** [comment]
> 谢谢您的建议！concurrency和thread_num 是2个不同层次的概念。
> concurrency是OP并发数量。 根据线程、进程模式，会启动多进程或多线程。
> local_service_conf.get("thread_num") 是Local predictor模式下，设置 CPU Blas 库计算线程数量，当CPU资源足够时，有较高的性能提升

另外 如果 concurrency和thread_num 是2个不同层次的概念， 下面的代码建议不应该让  concurrency和thread_num 建立联系，两个变量应该保持独立互不影响。

https://github.com/PaddlePaddle/Serving/blob/54999920b674cd3f370ede4bea43fff1dbd9ca10/python/pipeline/operator.py#L136

**Comment by TeslaZhao** [comment]
thread_num 在brpc 和 local_predictor模式下，公用这个变量。在brpc模式下，thread_num表示c++ serving中线程数量，thread_num和concurrency是相同概念的，因此，默认值就是self.thread_num = self.concurrency ；在local_predictor模式下设置 CPU Blas 库计算线程数量，thread_num从配置conf中赋值。这两个功能均在local_service_handler.py中用到，因此公用一个变量。

**Comment by TeslaZhao** [comment]
> 我试了下thread_num设置成了10，但是似乎只用到了4个核（观察一个长时间的predict任务发现只有4个cpu核会跑到100%），是否对thread_num的上限有做了什么设置？

您好，我们看一下，尽快回复您

**Comment by TeslaZhao** [comment]
您的机器配置有几个CPU核？

**Comment by zhfkt** [comment]
CPU共8个核（我用自己的笔记本测试的）
