### ISSUE TITLE
readme文档中有一处小错误

### ISSUE THREAD

**Issue by ponycloud235** [PaddlePaddle/Serving#982]
![image](https://user-images.githubusercontent.com/2733701/105269702-6d987d00-5bcf-11eb-9afd-7b701ab1757c.png)

这里在头部漏了一句
`import numpy as np`

不引入，执行
`fetch_map = client.predict(feed={"x": np.array(data).reshape(1,13,1)}, fetch=["price"])` 
报错
`NameError: name 'np' is not defined`

**Comment by TeslaZhao** [comment]
好的，感谢您的建议。我们加上
