### ISSUE TITLE
gpu模型部署不成功，无报错，如何排除？

### ISSUE THREAD

**Issue by ponycloud235** [PaddlePaddle/Serving#984]
运行
![image](https://user-images.githubusercontent.com/2733701/105324614-99832500-5c06-11eb-9bc0-2d5d127f4378.png)
相关命令，后一直卡着，然后就没了？ 可以有什么办法排除吗
`python -m paddle_serving_server_gpu.serve --model yolov3_server --port 9292 --gpu_ids 0`

相关环境：
![image](https://user-images.githubusercontent.com/2733701/105324594-94be7100-5c06-11eb-8aa4-031f7d0a4e2f.png)
python3.6.8版本 
centos7.6
cuda9.0
依赖包版本信息
![image](https://user-images.githubusercontent.com/2733701/105324873-ee26a000-5c06-11eb-9b1a-c97d3a8d3e3b.png)

**Comment by ponycloud235** [comment]
刚试了在docker中运行，也是一样的问题。。 
![image](https://user-images.githubusercontent.com/2733701/105454031-3784f700-5cbc-11eb-9eca-88c9d0ab293e.png)

**Comment by ponycloud235** [comment]
找到问题了，执行命令时，会自动下载包serving-gpu-cuda10-0.4.0.tar.gz ，当这个操作没下载完，或者被中断，或者包不完整，就会出现什么都不报错的问题。。
希望官方能够完善提供离线下载的方式，所需要的依赖都在文档中体现，避免别人采坑，搞了1天

**Comment by TeslaZhao** [comment]
感谢您的提问和回复~
