### ISSUE TITLE
Pipeline模式下 ，设置local_service_conf中的参数thread_num无论多大，都只能利用CPU的4个核心。

### ISSUE THREAD

**Issue by zhfkt** [PaddlePaddle/Serving#986]
pipleline模式下 ，设置local_service_conf中的参数thread_num无论多大，都只能利用CPU的4个核心。

我试了下thread_num设置成了10，但是似乎只用到了4个核（观察一个长时间的predict任务发现只有4个cpu核会跑到100%），是否对thread_num的上限有做了什么设置？(BLAS相关？)

**Comment by TeslaZhao** [comment]
收到您的反馈，我们查一下

**Comment by TeslaZhao** [comment]
您的机器上，有多少个CPU物理核？

**Comment by zhfkt** [comment]
CPU共8个核（我用自己的笔记本测试的）

**Comment by huaxiangsiyi** [comment]
1个物理CPU，4个核数，8个线程数：
client_type：设置 brpc时，CPU的利用率为98%左右；设置成local_predictor时，CPU的利用率提高到798%左右，充分利用；其他参数不变，但是，QPS，只提高了1倍，请教工程师帮忙解释下呗，谢谢！撒花……

**Comment by huaxiangsiyi** [comment]
补充上述问题：
1、in：4000+
2、out：0.09
3、midp：900左右
请教改是否还有优化空间？感谢！！！
@zhfkt @TeslaZhao
