### ISSUE TITLE
Paddle Serving 启动lac服务的tags词性分析需要什么参数

### ISSUE THREAD

**Issue by suntao2015005848** [PaddlePaddle/Serving#989]
lac模型的 tags分析如何启用啊

**Comment by TeslaZhao** [comment]
您说的是Serving/python/examples/lac/的例子吗?

**Comment by weixiu00** [comment]
同问，目前Serving/python/examples/lac/的例子，返回结果只有分词，没有词性结果

**Comment by bjjwwang** [comment]
> 同问，目前Serving/python/examples/lac/的例子，返回结果只有分词，没有词性结果

这个模型应该有些老，我们会着手更新一下。可以利用现有的老lac作为例子，然后搬运新的模型用serving启动。
