### ISSUE TITLE
文档有处小错误

### ISSUE THREAD

**Issue by ponycloud235** [PaddlePaddle/Serving#990]
https://github.com/PaddlePaddle/Serving/blob/v0.4.0/doc/SAVE_CN.md
![image](https://user-images.githubusercontent.com/2733701/105667423-30f1bc00-5f16-11eb-9ef3-6757dcc1616f.png)
少了m，应该是params_filename

**Comment by TeslaZhao** [comment]
收到，谢谢您的反馈

**Comment by TeslaZhao** [comment]
v0.4.0，develop，v0.5版本均已修改，谢谢您的反馈
